### ISSUE TITLE
Lex sample requires CognitoAuth SDK

### ISSUE THREAD

**Issue by palpatim** [aws-amplify/aws-sdk-android#1018]
**Describe the bug**
Following the instructions on the [Lex Sample App](https://github.com/awslabs/aws-sdk-android-samples/tree/master/LexSample) in the Android Sample Repo, I ran into two problems attempting to initialize AWSMobileClient:

1. The AWS CLI injected an "Auth" section into the generated `awsconfiguration.json` file, despite my not using Hosted UI
1. The SDK would not properly intialize AWSMobileClient without me adding `aws-android-sdk-cognitoauth` to my build.gradle

I've not been able to investigate this deeply to see if this is a bug due to a recent change, or a problem in my local setup.

**To Reproduce**

1. Follow the instructions on the LexSample to spin up a new Lex sample app
  1. It may be necessary to perform an additional setup step not documented in the LexSample instructions: The CLI does not create any aliases, and I don't think it publishes the newly-created bot. That might need to be done before running the sample, but I haven't investigated closely
1. Attempt to build and run the app

**Expected behavior**

The app builds, runs, and is able to do a "book trip" transaction via TextActivity.

**Actual Behavior**

1. The app fails to initialize AWSMobileClient during the TextActivity, failing to find `AuthProvider`. Relevant stack trace:

```
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.amazonaws.mobileconnectors.cognitoauth.handlers.AuthHandler" on path: DexPathList[[zip file "/data/app/com.amazonaws.sample.lex-JMOmFkHzt2PylpxsL9CcQA==/base.apk", zip file "/data/app/com.amazonaws.sample.lex-JMOmFkHzt2PylpxsL9CcQA==/split_lib_dependencies_apk.apk", zip file "/data/app/com.amazonaws.sample.lex-JMOmFkHzt2PylpxsL9CcQA==/split_lib_resources_apk.apk", zip file "/data/app/com.amazonaws.sample.lex-JMOmFkHzt2PylpxsL9CcQA==/split_lib_slice_0_apk.apk", zip file "/data/app/com.amazonaws.sample.lex-JMOmFkHzt2PylpxsL9CcQA==/split_lib_slice_1_apk.apk", zip file "/data/app/com.amazonaws.sample.lex-JMOmFkHzt2PylpxsL9CcQA==/split_lib_slice_2_apk.apk", zip file "/data/app/com.amazonaws.sample.lex-JMOmFkHzt2PylpxsL9CcQA==/split_lib_slice_3_apk.apk", zip file "/data/app/com.amazonaws.sample.lex-JMOmFkHzt2PylpxsL9CcQA==/split_lib_slice_4_apk.apk", zip file "/data/app/com.amazonaws.sample.lex-JMOmFkHzt2PylpxsL9CcQA==/split_lib_slice_5_apk.apk", 
        at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:125)
        at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
        at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
        at com.amazonaws.mobile.client.AWSMobileClient com.amazonaws.mobile.client.AWSMobileClient.getInstance() (AWSMobileClient.java:-1)
        at void com.amazonaws.sample.lex.TextActivity.initializeLexSDK() (TextActivity.java:150)
        at void com.amazonaws.sample.lex.TextActivity.init() (TextActivity.java:139)
        at void com.amazonaws.sample.lex.TextActivity.onCreate(android.os.Bundle) (TextActivity.java:109)
        at void android.app.Activity.performCreate(android.os.Bundle, android.os.PersistableBundle) (Activity.java:7009)
        at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:7000)
        at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1214)
        at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2731)
        at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2856)
        at void android.app.ActivityThread.-wrap11(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
        at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1589)
        at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
        at void android.os.Looper.loop() (Looper.java:164)
        at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6494)
        at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
        at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
        at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:807)
```

1. After working around the above (see below), the app also logs an error and fails to initialize the AWSMobileClient (but does not crash because of it):

```
E/TextActivity: initialize.onError: 
    java.lang.RuntimeException: Failed to initialize OAuth, please check your awsconfiguration.json
        at com.amazonaws.mobile.client.AWSMobileClient$2.run(AWSMobileClient.java:579)
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: org.json.JSONException: No value for Scopes
        at org.json.JSONObject.get(JSONObject.java:392)
        at org.json.JSONObject.getJSONArray(JSONObject.java:587)
        at com.amazonaws.mobile.client.AWSMobileClient._initializeHostedUI(AWSMobileClient.java:602)
        at com.amazonaws.mobile.client.AWSMobileClient.access$400(AWSMobileClient.java:164)
        at com.amazonaws.mobile.client.AWSMobileClient$2.run(AWSMobileClient.java:576)
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101) 
        at java.lang.Thread.run(Thread.java:764) 
```

**Workarounds**

1. Add to `dependencies` section of `build.gradle`:

```gradle
implementation ("com.amazonaws:aws-android-sdk-cognitoauth:$aws_version@aar") { transitive=true }
```

1. Remove the `OAuth` section from `awsconfiguration.json`

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.13.6
 - Emulator
 - API 23
 - Specific to simulators: No

**Comment by psyrenpark** [comment]
thanks~ ^^
your nice

**Comment by alan0987270275** [comment]
Thank you so much!!!!

**Comment by bryannevega** [comment]
Wondering why is this still open and it hasn't been revised. It's March 1st 2020 and nothing yet.
