### ISSUE TITLE
Federation from the Hosted UI failed

### ISSUE THREAD

**Issue by hoangtran-agilityio** [aws-amplify/aws-sdk-android#1066]
**Describe the bug**
Trying to use Hosted UI for Authentication Follow this [link](https://aws-amplify.github.io/docs/android/authentication#manual-setup-1)

But it throws this
```
E/AWSMobileClient: onError: Federation from the Hosted UI failed
    java.lang.RuntimeException: Error in federating the token.
        at com.amazonaws.mobile.client.AWSMobileClient$8.run(AWSMobileClient.java:1484)
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: com.amazonaws.AmazonServiceException: 1 validation error detected: Value '{=eyJraWQiOiJTU1RiNkVLYlh5S1RoSitrNHNEaE13dUZQeXR4enltengxMkNFV2pFbXdJPSIsImFsZyI6IlJTMjU2In0.eyJhdF9oYXNoIjoicjZDYVRhZ3V0Y2QxWFE0Q2Jqd2g0USIsInN1YiI6ImM2MzU5MGMzLTc2OWYtNGVjMS04YzI5LTIwOTcxMWJlNDhjNiIsImNvZ25pdG86Z3JvdXBzIjpbInVzLWVhc3QtMV9NNzhBeWUzMjZfRmFjZWJvb2siXSwiaXNzIjoiaHR0cHM6XC9cL2NvZ25pdG8taWRwLnVzLWVhc3QtMS5hbWF6b25hd3MuY29tXC91cy1lYXN0LTFfTTc4QXllMzI2IiwiY29nbml0bzp1c2VybmFtZSI6IkZhY2Vib29rXzI2MjE1OTU2MDc4NTI3NDAiLCJub25jZSI6Inp6R3hmSFZSc0NCLUNzaERmQktJbUdOVVJQMXlwaWJCUW5OZnQ4R3JqYVduVTZZZmljSW8yRnlxTXFnWjhwNEhVajlZd0pwUzhUMnpKODFCQTRVbnJTS0tFSGpWa0FYYk15dWhkMC10MUxmbXNZZlJ5SURRWk96eF9DSDVqTC1WQk53Qng1N1RoaGRweUhBdmd4dEM0WHBIUWx1RkpWUkxQV1pBQ3o0cGFwOCIsImF1ZCI6IjRuM2ZxMTE1am90YWh0NnZ2MGE2Y2RnZnVwIiwiaWRlbnRpdGllcyI6W3sidXNlcklkIjoiMjYyMTU5NTYwNzg1Mjc0MCIsInByb3ZpZGVyTmFtZSI6IkZhY2Vib29rIiwicHJvdmlkZXJUeXBlIjoiRmFjZWJvb2siLCJpc3N1ZXIiOm51bGwsInByaW1hcnkiOiJ0cnVlIiwiZGF0ZUNyZWF0ZWQiOiIxNTYyMzIyMjEyMzcyIn1dLCJ0b2tlbl91c2UiOiJpZCIsImF1dGhfdGltZSI6MTU2MjY0Nzg1MywiZXhwIjoxNTYyNjUxNDUzLCJpYXQiOjE1NjI2NDc4NTMsImVtYWlsIjoidnVuZ3V5ZW5pdEB5YWhvby5jb20ifQ.ZgJ_o8WFibFX7vhHlvYC_VedVBnr2YektGql2giwODdyRpOVUstP9Gh4tWqhTzdvzGQSMCCz2ZJaMxtnmzYyhamCRopXbrbRiHfz9c8is6jOdk30W4hT7T0pqnc6-CG0ziLhn77ulLcuRmeSwDCZViYd9pdpiUQLemB8UwcyhLMg8YuBmJ23kPlGQhotqK4e7rijpv-jb2lBVoQcCZRW1opwnzk06x9e5C-OXWGRL2nBCa6IWy83tHy6L4l4vL9ycGvJF0K6RQcdzvgHMAYDVI9IuOEJqktg1eNuu17Q_2ppbvLMlTqHlCqypTvRNFLmovIgDhlFqGD78-a5MOVQ5w}' at 'logins' failed to satisfy constraint: Map keys must satisfy constraint: [Member must have length less than or equal to 128, Member must have length greater than or equal to 1] (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: ValidationException; Request ID: 220834a4-a205-11e9-b557-696bbdf3dd71)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:730)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:405)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
        at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:1734)
        at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getId(AmazonCognitoIdentityClient.java:815)
        at com.amazonaws.auth.AWSAbstractCognitoIdentityProvider.getIdentityId(AWSAbstractCognitoIdentityProvider.java:172)
        at com.amazonaws.mobile.client.AWSMobileClientCognitoIdentityProvider.refresh(AWSMobileClient.java:3600)
        at com.amazonaws.auth.CognitoCredentialsProvider.retryRefresh(CognitoCredentialsProvider.java:714)
        at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:686)
```
- It created an user in the user pool. But throw error above

**To Reproduce**
```
 @Override
protected void onResume() {
     super.onResume();
     Intent activityIntent = getIntent();
     if (activityIntent.getData() != null &&
             "myapp".equals(activityIntent.getData().getScheme())) {
         AWSMobileClient.getInstance().handleAuthResponse(activityIntent);
     }
 }
```

**Expected behavior**
Create an user in user pool and able to login

**Environment Information (please complete the following information):**

```
- AWS Android SDK Version: 2.13.6
 - Device: Pixel XL 2
- Android version: 8.1.0
```

**Comment by woanversace** [comment]
@royjit Any update on this issue?

**Comment by willhappenio** [comment]
Stuck in same issue. Any Idea? 
Trying to working around with Cognito > Auth0 > Social Accounts

**Comment by desokroshan** [comment]
@hoangtran-agilityio @willhappenio Thanks for reaching out. I will try to reproduce the issue and get back to you.

**Comment by doc-rj-celltrak** [comment]
@hoangtran-agilityio Did you find any solution for this? We're thinking of using the same flow. Are you using a Cognito Identity Pool in addition to your User Pool?  Maybe this flow requires an Identity Pool to be setup?

**Comment by doc-rj-celltrak** [comment]
@willhappenio Any luck with Auth0?  Did you have an Identity Pool setup, or only User Pool?

**Comment by gpanshu** [comment]
From the error message it appears that your token was invalid. Have you had any luck trying it recently?
