### ISSUE TITLE
idToken not retrieved from stored cache without an artificial delay

### ISSUE THREAD

**Issue by saltedpotatos** [aws-amplify/aws-sdk-android#1078]
**Describe the bug**
We use a Cognito id token to make an authenticated request to API Gateway.

When using the apigateway library, I ran into issues referenced in  #767 and parsed everything manually. So I decided to drop apigateway and make the requests in retrofit.

To obtain the id token, I call 
` val idToken = AWSMobileClient.getInstance().tokens.idToken.tokenString`

If I open the app in a signed out state/clear app data, everything works as expected. However, if I am signed in, close the app/swipe away the app card, and relaunch, the app crashes with 

`java.lang.Exception: getTokens does not support retrieving tokens for federated sign-in`

If I attach a debugger and break on that line, the id token is always there, which implied to me that its a race between the token being decrypted/available, and me trying to retrieve them.

As a temporary fix, it seems as if adding a 50ms sleep is enough time for AWSMobileClient to figure itself out and let me obtain the id token.

```
fun retrofitAPI() {
        Timber.d("RetrofitAPI Called")
        sleep(50)
        val idToken = AWSMobileClient.getInstance().tokens.idToken.tokenString
        //The rest of the network request, etc.
```

**Which AWS service(s) are affected?**
AWSMobileClient

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.13.7, 2.14.0
 - Device: Simulator
 - Android Version: API 28
 - Specific to simulators: Unknown

**Additional context**
AWSMobileClient is initialized in MainActivity onCreate, and retrofit calls are completed in a viewmodel.

Full crash log

```
2019-07-19 14:32:28.066 I/puting.app: Not late-enabling -Xcheck:jni (already on)
2019-07-19 14:32:28.363 W/puting.app: Unexpected CPU variant for X86 using defaults: x86
2019-07-19 14:32:30.041 W/puting.app: Accessing hidden method Landroid/graphics/drawable/Drawable;->getOpticalInsets()Landroid/graphics/Insets; (light greylist, linking)
2019-07-19 14:32:30.043 W/puting.app: Accessing hidden field Landroid/graphics/Insets;->left:I (light greylist, linking)
2019-07-19 14:32:30.043 W/puting.app: Accessing hidden field Landroid/graphics/Insets;->right:I (light greylist, linking)
2019-07-19 14:32:30.044 W/puting.app: Accessing hidden field Landroid/graphics/Insets;->top:I (light greylist, linking)
2019-07-19 14:32:30.044 W/puting.app: Accessing hidden field Landroid/graphics/Insets;->bottom:I (light greylist, linking)
2019-07-19 14:32:30.119 W/puting.app: Accessing hidden method Landroid/view/View;->getAccessibilityDelegate()Landroid/view/View$AccessibilityDelegate; (light greylist, linking)
2019-07-19 14:32:30.154 W/puting.app: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (light greylist, reflection)
2019-07-19 14:32:30.155 W/puting.app: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (light greylist, reflection)
2019-07-19 14:32:30.430 I/puting.app: Rejecting re-init on previously-failed class java.lang.Class<com.amazonaws.mobile.client.AWSMobileClient$10>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/amazonaws/mobileconnectors/cognitoauth/handlers/AuthHandler;
2019-07-19 14:32:30.430 I/puting.app:     at com.amazonaws.mobile.client.AWSMobileClient com.amazonaws.mobile.client.AWSMobileClient.getInstance() (AWSMobileClient.java:-1)
2019-07-19 14:32:30.430 I/puting.app:     at void com.example.app.MainActivity.onCreate(android.os.Bundle) (MainActivity.kt:41)
2019-07-19 14:32:30.430 I/puting.app:     at void android.app.Activity.performCreate(android.os.Bundle, android.os.PersistableBundle) (Activity.java:7136)
2019-07-19 14:32:30.430 I/puting.app:     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:7127)
2019-07-19 14:32:30.430 I/puting.app:     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1271)
2019-07-19 14:32:30.430 I/puting.app:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2893)
2019-07-19 14:32:30.431 I/puting.app:     at android.app.Activity android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.app.servertransaction.PendingTransactionActions, android.content.Intent) (ActivityThread.java:3048)
2019-07-19 14:32:30.431 I/puting.app:     at void android.app.servertransaction.LaunchActivityItem.execute(android.app.ClientTransactionHandler, android.os.IBinder, android.app.servertransaction.PendingTransactionActions) (LaunchActivityItem.java:78)
2019-07-19 14:32:30.431 I/puting.app:     at void android.app.servertransaction.TransactionExecutor.executeCallbacks(android.app.servertransaction.ClientTransaction) (TransactionExecutor.java:108)
2019-07-19 14:32:30.431 I/puting.app:     at void android.app.servertransaction.TransactionExecutor.execute(android.app.servertransaction.ClientTransaction) (TransactionExecutor.java:68)
2019-07-19 14:32:30.431 I/puting.app:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1808)
2019-07-19 14:32:30.431 I/puting.app:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
2019-07-19 14:32:30.431 I/puting.app:     at void android.os.Looper.loop() (Looper.java:193)
2019-07-19 14:32:30.431 I/puting.app:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6669)
2019-07-19 14:32:30.431 I/puting.app:     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
2019-07-19 14:32:30.431 I/puting.app:     at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:493)
2019-07-19 14:32:30.431 I/puting.app:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:858)
2019-07-19 14:32:30.431 I/puting.app: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.amazonaws.mobileconnectors.cognitoauth.handlers.AuthHandler" on path: DexPathList[[zip file "/data/app/com.example.app-Pa294Su5fcbKHrk96VuYig==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.app-Pa294Su5fcbKHrk96VuYig==/lib/x86, /system/lib]]
2019-07-19 14:32:30.431 I/puting.app:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:134)
2019-07-19 14:32:30.431 I/puting.app:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
2019-07-19 14:32:30.431 I/puting.app:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
2019-07-19 14:32:30.431 I/puting.app:     at com.amazonaws.mobile.client.AWSMobileClient com.amazonaws.mobile.client.AWSMobileClient.getInstance() (AWSMobileClient.java:-1)
2019-07-19 14:32:30.431 I/puting.app:     at void com.example.app.MainActivity.onCreate(android.os.Bundle) (MainActivity.kt:41)
2019-07-19 14:32:30.431 I/puting.app:     at void android.app.Activity.performCreate(android.os.Bundle, android.os.PersistableBundle) (Activity.java:7136)
2019-07-19 14:32:30.431 I/puting.app:     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:7127)
2019-07-19 14:32:30.431 I/puting.app:     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1271)
2019-07-19 14:32:30.431 I/puting.app:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2893)
2019-07-19 14:32:30.431 I/puting.app:     at android.app.Activity android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.app.servertransaction.PendingTransactionActions, android.content.Intent) (ActivityThread.java:3048)
2019-07-19 14:32:30.431 I/puting.app:     at void android.app.servertransaction.LaunchActivityItem.execute(android.app.ClientTransactionHandler, android.os.IBinder, android.app.servertransaction.PendingTransactionActions) (LaunchActivityItem.java:78)
2019-07-19 14:32:30.431 I/puting.app:     at void android.app.servertransaction.TransactionExecutor.executeCallbacks(android.app.servertransaction.ClientTransaction) (TransactionExecutor.java:108)
2019-07-19 14:32:30.431 I/puting.app:     at void android.app.servertransaction.TransactionExecutor.execute(android.app.servertransaction.ClientTransaction) (TransactionExecutor.java:68)
2019-07-19 14:32:30.431 I/puting.app:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1808)
2019-07-19 14:32:30.431 I/puting.app:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
2019-07-19 14:32:30.431 I/puting.app:     at void android.os.Looper.loop() (Looper.java:193)
2019-07-19 14:32:30.431 I/puting.app:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6669)
2019-07-19 14:32:30.431 I/puting.app:     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
2019-07-19 14:32:30.431 I/puting.app:     at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:493)
2019-07-19 14:32:30.431 I/puting.app:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:858)
2019-07-19 14:32:30.432 I/puting.app: Rejecting re-init on previously-failed class java.lang.Class<com.amazonaws.mobile.client.AWSMobileClient$10>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/amazonaws/mobileconnectors/cognitoauth/handlers/AuthHandler;
2019-07-19 14:32:30.432 I/puting.app:     at com.amazonaws.mobile.client.AWSMobileClient com.amazonaws.mobile.client.AWSMobileClient.getInstance() (AWSMobileClient.java:-1)
2019-07-19 14:32:30.432 I/puting.app:     at void com.example.app.MainActivity.onCreate(android.os.Bundle) (MainActivity.kt:41)
2019-07-19 14:32:30.432 I/puting.app:     at void android.app.Activity.performCreate(android.os.Bundle, android.os.PersistableBundle) (Activity.java:7136)
2019-07-19 14:32:30.432 I/puting.app:     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:7127)
2019-07-19 14:32:30.432 I/puting.app:     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1271)
2019-07-19 14:32:30.432 I/puting.app:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2893)
2019-07-19 14:32:30.432 I/puting.app:     at android.app.Activity android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.app.servertransaction.PendingTransactionActions, android.content.Intent) (ActivityThread.java:3048)
2019-07-19 14:32:30.432 I/puting.app:     at void android.app.servertransaction.LaunchActivityItem.execute(android.app.ClientTransactionHandler, android.os.IBinder, android.app.servertransaction.PendingTransactionActions) (LaunchActivityItem.java:78)
2019-07-19 14:32:30.432 I/puting.app:     at void android.app.servertransaction.TransactionExecutor.executeCallbacks(android.app.servertransaction.ClientTransaction) (TransactionExecutor.java:108)
2019-07-19 14:32:30.432 I/puting.app:     at void android.app.servertransaction.TransactionExecutor.execute(android.app.servertransaction.ClientTransaction) (TransactionExecutor.java:68)
2019-07-19 14:32:30.432 I/puting.app:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1808)
2019-07-19 14:32:30.432 I/puting.app:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
2019-07-19 14:32:30.433 I/puting.app:     at void android.os.Looper.loop() (Looper.java:193)
2019-07-19 14:32:30.433 I/puting.app:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6669)
2019-07-19 14:32:30.433 I/puting.app:     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
2019-07-19 14:32:30.433 I/puting.app:     at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:493)
2019-07-19 14:32:30.433 I/puting.app:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:858)
2019-07-19 14:32:30.433 I/puting.app: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.amazonaws.mobileconnectors.cognitoauth.handlers.AuthHandler" on path: DexPathList[[zip file "/data/app/com.example.app-Pa294Su5fcbKHrk96VuYig==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.app-Pa294Su5fcbKHrk96VuYig==/lib/x86, /system/lib]]
2019-07-19 14:32:30.433 I/puting.app:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:134)
2019-07-19 14:32:30.433 I/puting.app:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
2019-07-19 14:32:30.433 I/puting.app:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
2019-07-19 14:32:30.433 I/puting.app:     at com.amazonaws.mobile.client.AWSMobileClient com.amazonaws.mobile.client.AWSMobileClient.getInstance() (AWSMobileClient.java:-1)
2019-07-19 14:32:30.433 I/puting.app:     at void com.example.app.MainActivity.onCreate(android.os.Bundle) (MainActivity.kt:41)
2019-07-19 14:32:30.433 I/puting.app:     at void android.app.Activity.performCreate(android.os.Bundle, android.os.PersistableBundle) (Activity.java:7136)
2019-07-19 14:32:30.433 I/puting.app:     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:7127)
2019-07-19 14:32:30.433 I/puting.app:     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1271)
2019-07-19 14:32:30.433 I/puting.app:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2893)
2019-07-19 14:32:30.433 I/puting.app:     at android.app.Activity android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.app.servertransaction.PendingTransactionActions, android.content.Intent) (ActivityThread.java:3048)
2019-07-19 14:32:30.433 I/puting.app:     at void android.app.servertransaction.LaunchActivityItem.execute(android.app.ClientTransactionHandler, android.os.IBinder, android.app.servertransaction.PendingTransactionActions) (LaunchActivityItem.java:78)
2019-07-19 14:32:30.433 I/puting.app:     at void android.app.servertransaction.TransactionExecutor.executeCallbacks(android.app.servertransaction.ClientTransaction) (TransactionExecutor.java:108)
2019-07-19 14:32:30.433 I/puting.app:     at void android.app.servertransaction.TransactionExecutor.execute(android.app.servertransaction.ClientTransaction) (TransactionExecutor.java:68)
2019-07-19 14:32:30.433 I/puting.app:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1808)
2019-07-19 14:32:30.433 I/puting.app:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
2019-07-19 14:32:30.433 I/puting.app:     at void android.os.Looper.loop() (Looper.java:193)
2019-07-19 14:32:30.433 I/puting.app:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6669)
2019-07-19 14:32:30.433 I/puting.app:     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
2019-07-19 14:32:30.433 I/puting.app:     at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:493)
2019-07-19 14:32:30.433 I/puting.app:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:858)
2019-07-19 14:32:30.482 I/AWSKeyValueStore: Detected Android API Level = 28
2019-07-19 14:32:30.482 I/AWSKeyValueStore: Using keyAlias = com.amazonaws.mobile.client.aesKeyStoreAlias
2019-07-19 14:32:30.486 D/KeyProvider23: AndroidKeyStore contains keyAlias com.amazonaws.mobile.client.aesKeyStoreAlias
2019-07-19 14:32:30.486 D/KeyProvider23: Loading the encryption key from Android KeyStore.
2019-07-19 14:32:30.508 I/AWSKeyValueStore: Creating the AWSKeyValueStore with key for sharedPreferences = com.amazonaws.mobile.client
2019-07-19 14:32:30.527 I/AWSKeyValueStore: Detected Android API Level = 28
2019-07-19 14:32:30.527 I/AWSKeyValueStore: Using keyAlias = com.amazonaws.android.auth.aesKeyStoreAlias
2019-07-19 14:32:30.529 I/puting.app: Background concurrent copying GC freed 5262(2MB) AllocSpace objects, 0(0B) LOS objects, 50% free, 2023KB/3MB, paused 1.368ms total 162.761ms
2019-07-19 14:32:30.534 D/KeyProvider23: AndroidKeyStore contains keyAlias com.amazonaws.android.auth.aesKeyStoreAlias
2019-07-19 14:32:30.534 D/KeyProvider23: Loading the encryption key from Android KeyStore.
2019-07-19 14:32:30.535 I/AWSKeyValueStore: Creating the AWSKeyValueStore with key for sharedPreferences = com.amazonaws.android.auth
2019-07-19 14:32:30.706 D/AWSMobileClient: Inspecting user state details
2019-07-19 14:32:30.722 I/AWSKeyValueStore: Detected Android API Level = 28
2019-07-19 14:32:30.722 I/AWSKeyValueStore: Using keyAlias = com.amazonaws.android.auth.aesKeyStoreAlias
2019-07-19 14:32:30.724 D/KeyProvider23: AndroidKeyStore contains keyAlias com.amazonaws.android.auth.aesKeyStoreAlias
2019-07-19 14:32:30.724 D/KeyProvider23: Loading the encryption key from Android KeyStore.
2019-07-19 14:32:30.743 I/AWSKeyValueStore: Creating the AWSKeyValueStore with key for sharedPreferences = com.amazonaws.android.auth
2019-07-19 14:32:30.762 D/CognitoCachingCredentialsProvider: Loading credentials from SharedPreferences
2019-07-19 14:32:30.777 I/HomeScreenFragment$onCreateView: LoginViewModel says we are signed in
2019-07-19 14:32:30.777 D/HomeScreenViewModel: RetrofitAPI Called
2019-07-19 14:32:30.834 D/AndroidRuntime: Shutting down VM
2019-07-19 14:32:30.835 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.app, PID: 15616
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: java.lang.Exception: getTokens does not support retrieving tokens for federated sign-in
        at com.amazonaws.mobile.client.AWSMobileClient$9.run(AWSMobileClient.java:1561)
        at com.amazonaws.mobile.client.internal.InternalCallback.await(InternalCallback.java:115)
        at com.amazonaws.mobile.client.AWSMobileClient.getTokens(AWSMobileClient.java:1532)
        at com.example.app.homescreen.HomeScreenViewModel.retrofitAPI(HomeScreenViewModel.kt:46)
        at com.example.app.homescreen.HomeScreenFragment$onCreateView$2.onChanged(HomeScreenFragment.kt:66)
        at com.example.app.homescreen.HomeScreenFragment$onCreateView$2.onChanged(HomeScreenFragment.kt:21)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:144)
        at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:443)
        at androidx.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:395)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:361)
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:300)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:339)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:145)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:131)
        at androidx.fragment.app.FragmentViewLifecycleOwner.handleLifecycleEvent(FragmentViewLifecycleOwner.java:51)
        at androidx.fragment.app.Fragment.performStart(Fragment.java:2644)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:917)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1240)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1305)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2658)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStart(FragmentManagerImpl.java:2618)
        at androidx.fragment.app.Fragment.performStart(Fragment.java:2646)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:917)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1240)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1305)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2658)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStart(FragmentManagerImpl.java:2618)
        at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:257)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:551)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
        at android.app.Activity.performStart(Activity.java:7157)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2937)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
2019-07-19 14:32:30.835 E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        	... 3 more
2019-07-19 14:32:30.858 I/Process: Sending signal. PID: 15616 SIG: 9
```

**Comment by palpatim** [comment]
@saltedpotatos 

Are you initializing the AWSMobileClient before making the call to `AWSMobileClient.getInstance().tokens.idToken.tokenString`? If so, recall that [`initialize`](https://aws-amplify.github.io/docs/android/authentication#initialization) is an asynchronous method; are you waiting for it to complete before attempting to retrieve the tokens?

**Comment by saltedpotatos** [comment]
Sorry for the delay, was on vacation. 

I guess I mistakenly assumed that it was initialized since I was seeing AWSMobileclient doing things in the log prior to the crash. I will look into waiting on initialize to complete before attempting to read the token string and report back.

Thanks!
