### ISSUE TITLE
TransferUtility does not wait for network connectivity

### ISSUE THREAD

**Issue by gitnarqt** [aws-amplify/aws-sdk-android#1088]
**Describe the bug**
TransferUtility does not wait for network connectivity and fails the upload instead. In other words, the state of TransferObserver will be FAILED instead of WAITING_FOR_NETWORK

`2019-07-25 16:03:48.133 22847-22847/ai.nar.ravenai E/AWSS3Service: onError: Error uploading image.
    com.amazonaws.AmazonClientException: Unable to execute HTTP request: Network is unreachable
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:441)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4908)
        at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1959)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:277)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:115)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:60)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:776)
     Caused by: java.net.ConnectException: Network is unreachable
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
        at java.net.Socket.connect(Socket.java:592)
        at com.android.okhttp.internal.Platform.connectSocket(Platform.java:113)
        at com.android.okhttp.Connection.connectSocket(Connection.java:196)
        at com.android.okhttp.Connection.connect(Connection.java:172)
        at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
        at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:329)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:246)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:126)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:257)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java)
        at com.amazonaws.http.UrlHttpClient.writeContentToConnection(UrlHttpClient.java:162)
        at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:75)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:371)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212) 
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4908) 
        at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1959) 
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:277) 
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:115) 
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:60) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:776) `

**To Reproduce**
A code sample or steps:
- Upload 10 images of small sizes (500KB each)
- Turn off internet connectivity on the device. All uploads will fail.

**Which AWS service(s) are affected?**
- S3

**Expected behavior**
If there is no internet, WAIT_FOR_NETWORK should be the state of the TransferObserver

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.14.0
 - Device: Huwawei Media Pad T3
 - Android Version: 7
 - Specific to simulators: [e.g. Yes/No] No

**Comment by kvasukib** [comment]
@gitnarqt Sorry for the inconvenience caused.

Have you registered the `TransferService` in `AndroidManifest.xml` and start the service manually from the app? This is required since the `2.7.0` version of the SDK.

Does this happen for single-part uploads? 
Do you experience the same behavior for multi-part uploads and downloads?
Are you seeing this error in other devices/emulators?
What Android versions are you seeing this error?

**Comment by gitnarqt** [comment]
@kvasukib thank you for getting back to me.

I did register the TransferService in AndroidManifest.xml without starting the service manually. Is there any sample code to spin up the service manually I can use?

- It does happen for single part uploads. Is this a normal behavior?
- Will try for multi-part uploads and downloads tomorrow
- Didn't try on other devices, will try it tomorrow
- Android 7.0

**Comment by kvasukib** [comment]
@gitnarqt There is an example of starting the service here:

https://github.com/awslabs/aws-sdk-android-samples/blob/master/S3TransferUtilitySample/src/com/amazonaws/demo/s3transferutility/MyApplication.java#L16

**Comment by gitnarqt** [comment]
@kvasukib it worked perfectly! I just had to start the TransferService like you said.

One more question, if the upload was successful, TransferUtility removes the TransferRecord. Is that correct behavior as it wasn't like this in the previous versions?

**Comment by kvasukib** [comment]
@gitnarqt Thank you for the confirmation. Glad it worked. Yes, TransferUtility removes the TransferRecord if the upload was successful.
