### ISSUE TITLE
NumberFormatException thrown in TransferRecord.updateFromDB

### ISSUE THREAD

**Issue by GerardoRobledo** [aws-amplify/aws-sdk-android#1093]
**Describe the bug**

Fatal Exception: c.f.c.t: java.lang.NumberFormatException: For input string: "ANY"
       at com.google.gson.internal.bind.TypeAdapters$7.read + 228(TypeAdapters.java:228)
       at com.google.gson.internal.bind.TypeAdapters$7.read + 218(TypeAdapters.java:218)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read + 131(ReflectiveTypeAdapterFactory.java:131)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read + 222(ReflectiveTypeAdapterFactory.java:222)
       at com.google.gson.Gson.fromJson + 927(Gson.java:927)
       at com.google.gson.Gson.fromJson + 892(Gson.java:892)
       at com.google.gson.Gson.fromJson + 841(Gson.java:841)
       at com.google.gson.Gson.fromJson + 813(Gson.java:813)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferRecord.updateFromDB + 159(TransferRecord.java:159)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferNetworkLossHandler.resumeAllTransfersOnNetworkAvailability + 176(TransferNetworkLossHandler.java:176)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferNetworkLossHandler.access$000 + 37(TransferNetworkLossHandler.java:37)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferNetworkLossHandler$1.run + 123(TransferNetworkLossHandler.java:123)

**To Reproduce**
 Updated sdk from version 2.12.0

**Which AWS service(s) are affected?**
S3

**Expected behavior**
Not to

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: [2.13.5]
 - Device: Note 9 
 - Android Version: 9 
 - Specific to simulators: No

**Comment by raphkim** [comment]
Hello @GerardoRobledo,

I'm sorry that you had trouble with this bug. It appears that there's an issue with serializing/deserializing transfer utility option in our loss handler, which we are currently investigating. Meanwhile, would you be able to provide more details regarding reproducing this bug? 

Thank you!

**Comment by GerardoRobledo** [comment]
Hello @raphkim,

Sure, the issue started to happen after updating our app dependency from 2.12.0 to 2.13.5.
Whenever resumeAllTransfersOnNetworkAvailability() method was called the app crashed.
For the end user this was after entering the app after a while or after switching airplane mode off.

 The workaround that helped me: 
 Inside onCreate() method from my Application class delete ""awss3transfertable.db" file
crash stopped from happening so maybe, I'm assuming it was an old record in the db.

Hope my description helps.

**Comment by raphkim** [comment]
Hi @GerardoRobledo,

Thank you for providing more details. I believe that the core issue was with the old record in your database if deleting it helped fix the issue, but I added a small change to make sure that deserialization is completed properly. Would you be able to incorporate the changes in your app to test if this PR helped with your issue?

But first of all, would you be able to check if the db needs to be deleted each time (as you currently do by invoking it inside onCreate), or if deleting it once permanently fixed the issue?

**Comment by GerardoRobledo** [comment]
deleting it once permanently fixed the issue.

**Comment by raphkim** [comment]
Okay. That seems to confirm that the issue was with database migration rather than with data serialization. We will be closing this issue for now, but please feel free to contact us with an update if this issue arises again. Thank you.

**Comment by PruthvirajSoftvan** [comment]
I have faced an issue after updating aws SDK from 2.28.0 to 2.58.0

```
Fatal Exception: com.google.gson.n: java.lang.NumberFormatException: For input string: "ANY"
       at com.google.gson.internal.bind.TypeAdapters$7.b(TypeAdapters.java:25)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:2)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:47)
       at com.google.gson.Gson.fromJson(Gson.java:31)
       at com.google.gson.Gson.b(Gson.java:1)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferRecord.updateFromDB(TransferRecord.java:422)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferNetworkLossHandler.resumeAllTransfersOnNetworkAvailability(TransferNetworkLossHandler.java:73)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferNetworkLossHandler$1.run(TransferNetworkLossHandler.java:73)
       at java.lang.Thread.run(Thread.java:1012)
```

**Update Aws SDK from 2.28.0 to 2.58.0**
**This crash show in firebase.**
**Not Reproduce**
