### ISSUE TITLE
Unable to execute HTTP request: socket failed: EPERM on attempt to upload an image to s3 bucket

### ISSUE THREAD

**Issue by yuri2o1o** [aws-amplify/aws-sdk-android#1118]
Im getting this error: "com.amazonaws.AmazonClientException: Unable to execute HTTP request: socket failed: EPERM (Operation not permitted)" when trying to upload an image (jpeg) file to an s3 bucket. The bucket is set up, public, and i managed to upload to it using javascript... i also checked and i have all the required permissions, here they are:
uses-permission android:name="android.permission.INTERNET" /
    uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" /
    uses-permission android:name="android.permission.ACCESS_WIFI_STATE" /
    uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/
    uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" /
    uses-permission android:name="android.permission.CAMERA"/
    uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" /
    uses-permission android:name="android.permission.VIBRATE" /
(some of these are for other things)

Here is the code:

public void UploadImage(String imgUri)
    {
        File file = new File(imgUri.substring(6)); //this removes some junk, the uri is just a path (that i checked is correct and works)

        CognitoCachingCredentialsProvider credentialsProvider;
        credentialsProvider = new CognitoCachingCredentialsProvider(
                getApplicationContext(),
                "CENSORED", // Identity Pool ID
                Regions.EU_WEST_2 // Region
        );

        AmazonS3 s3 = new AmazonS3Client(credentialsProvider);

        TransferUtility transferUtility = new TransferUtility(s3, getApplicationContext());
        TransferObserver observer = transferUtility.upload(
                "icuimages",  //this is the bucket name on S3
                file.getName(),
                file,
                CannedAccessControlList.PublicRead //to make the file public
        );

        observer.setTransferListener(new TransferListener() {
            @Override
            public void onStateChanged(int id, TransferState state) {
                if (state.equals(TransferState.COMPLETED)) {
                    Toast.makeText(getApplicationContext(),"Upload Successful",Toast.LENGTH_LONG).show();
                } else if (state.equals(TransferState.FAILED)) {
                    Toast.makeText(getApplicationContext(),"Failed to upload",Toast.LENGTH_LONG).show();
                }
            }

            @Override
            public void onProgressChanged(int id, long bytesCurrent, long bytesTotal) { }

            @Override
            public void onError(int id, Exception ex) { }
        });
    }

it was made according to [this](https://www.therightmatter.com/blog/how-to-upload-file-to-s3-bucket-from-android) 

here is the full error log:

2019-08-06 12:40:44.790 5220-5877/ysb.softwere.icu D/UploadTask: Failed to upload: 3 due to Unable to execute HTTP request: socket failed: EPERM (Operation not permitted)
    com.amazonaws.AmazonClientException: Unable to execute HTTP request: socket failed: EPERM (Operation not permitted)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:441)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
        at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:566)
        at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getId(AmazonCognitoIdentityClient.java:448)
        at com.amazonaws.auth.AWSAbstractCognitoIdentityProvider.getIdentityId(AWSAbstractCognitoIdentityProvider.java:172)
        at com.amazonaws.auth.AWSEnhancedCognitoIdentityProvider.refresh(AWSEnhancedCognitoIdentityProvider.java:76)
        at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:678)
        at com.amazonaws.auth.CognitoCredentialsProvider.getCredentials(CognitoCredentialsProvider.java:465)
        at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:485)
        at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:77)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4653)
        at com.amazonaws.services.s3.AmazonS3Client.getBucketRegionViaHeadRequest(AmazonS3Client.java:5430)
        at com.amazonaws.services.s3.AmazonS3Client.fetchRegionFromCache(AmazonS3Client.java:5405)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4650)
        at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1752)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:219)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:93)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:49)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.net.SocketException: socket failed: EPERM (Operation not permitted)
        at java.net.Socket.createImpl(Socket.java:492)
        at java.net.Socket.getImpl(Socket.java:552)
        at java.net.Socket.setSoTimeout(Socket.java:1180)
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:143)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:219)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:30)
        at com.amazonaws.http.UrlHttpClient.writeContentToConnection(UrlHttpClient.java:162)
        at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:75)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:371)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212) 
        at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:566) 
        at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getId(AmazonCognitoIdentityClient.java:448) 
        at com.amazonaws.auth.AWSAbstractCognitoIdentityProvider.getIdentityId(AWSAbstractCognitoIdentityProvider.java:172) 
        at com.amazonaws.auth.AWSEnhancedCognitoIdentityProvider.refresh(AWSEnhancedCognitoIdentityProvider.java:76) 
        at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:678) 
        at com.amazonaws.auth.CognitoCredentialsProvider.getCredentials(CognitoCredentialsProvider.java:465) 
        at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:485) 
        at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:77) 
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4653) 
        at com.amazonaws.services.s3.AmazonS3Client.getBucketRegionViaHeadRequest(AmazonS3Client.java:5430) 
        at com.amazonaws.services.s3.AmazonS3Client.fetchRegionFromCache(AmazonS3Client.java:5405) 
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4650) 
        at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1752) 
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:219) 
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:93) 
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:49) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 

Why am i getting this error? (please help i cant find any solution to this online)

**Comment by royjit** [comment]
Hi @yuri2o1o Sorry for the inconvenience caused. Could you please provide the following details:

1. AWS SDK version
2. Android version
3. Size of file you are uploading
4. Does this issue occur all the time?
5. Are you getting any callback on `onProgressChanged` or `onError` methods?

**Comment by yuri2o1o** [comment]
> Hi @yuri2o1o Sorry for the inconvenience caused. Could you please provide the following details:
> 
> 1. AWS SDK version
> 2. Android version
> 3. Size of file you are uploading
> 4. Does this issue occur all the time?
> 5. Are you getting any callback on `onProgressChanged` or `onError` methods?

1. im using version 2.6.+ (and 2.6.7) here are my dependencies:
implementation ('com.amazonaws:aws-android-sdk-mobile-client:2.6.7@aar') { transitive = true }
    implementation 'com.amazonaws:aws-android-sdk-s3:2.6.+'
    implementation 'com.amazonaws:aws-android-sdk-cognito:2.6.+'

2. im using min API level 21 and testing on a nexus emulator running android version 10
3. about 50kb (and as i said, i successfully uploaded the same file using javascript in browser (on pc))
4. im only using this function, and when i do, yes, it occurs all the time.
5. i do, but its defiantly not the correct ones... here is the output:
E/MainActivity: onProgressChanged - id: 5, bytesCurrent: 0, bytesTotal: 9813
E/MainActivity: onError - id: 5, Exception: Unable to execute HTTP request: socket failed: EPERM (Operation not permitted) (as you can see this is the same error im getting...)

**Comment by TrekSoft** [comment]
Hey Yuri,

I reproduced the steps in that article and it's missing one key step - you need to go to your IAM service, select roles, find the role you created in Incognito for unauth users (should look like Cognito_<your role title>Unauth_Role), click Attach Policies, check AmazonS3FullAccess, and then AttachPolicy.

Let me know if that fixes your issue.
