### ISSUE TITLE
Getting timeout in TransferUtility on unstable connection

### ISSUE THREAD

**Issue by gitnarqt** [aws-amplify/aws-sdk-android#1190]
**Describe the bug**
I'm trying to upload 20 images of 30MB each to my S3 bucket using the Amazon android SDK and TransferUtility. It starts off well until I get this error for some of the uploads:

`java.util.concurrent.ExecutionException: com.amazonaws.AmazonClientException: Unable to execute HTTP request: timeout
        at java.util.concurrent.FutureTask.report(FutureTask.java:123)
        at java.util.concurrent.FutureTask.get(FutureTask.java:193)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadMultipartAndWaitForCompletion(UploadTask.java:178)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:110)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:60)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: com.amazonaws.AmazonClientException: Unable to execute HTTP request: timeout
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:441)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4908)
        at com.amazonaws.services.s3.AmazonS3Client.uploadPart(AmazonS3Client.java:3884)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadPartTask.call(UploadPartTask.java:60)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadPartTask.call(UploadPartTask.java:30)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: java.net.SocketTimeoutException: timeout
        at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:221)
        at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:261)
        at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
        at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:316)
        at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:310)
        at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:206)
        at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:395)
        at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:144)
        at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:887)
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:759)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:480)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:416)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseMessage(HttpURLConnectionImpl.java:543)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseMessage(DelegatingHttpsURLConnection.java:109)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseMessage(HttpsURLConnectionImpl.java:26)
        at com.amazonaws.http.UrlHttpClient.createHttpResponse(UrlHttpClient.java:92)
        at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:85)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:371)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212) 
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4908) 
        at com.amazonaws.services.s3.AmazonS3Client.uploadPart(AmazonS3Client.java:3884) 
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadPartTask.call(UploadPartTask.java:60) 
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadPartTask.call(UploadPartTask.java:30) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: java.net.SocketException: socket is closed
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:584)
        at com.android.okhttp.okio.Okio$2.read(Okio.java:141)
        at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
        at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:316) 
        at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:310) 
        at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:206) 
        at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:395) 
        at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:144) 
        at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:887) 
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:759) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:480) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:416) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseMessage(HttpURLConnectionImpl.java:543) 
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseMessage(DelegatingHttpsURLConnection.java:109) 
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseMessage(HttpsURLConnectionImpl.java:26) 
        at com.amazonaws.http.UrlHttpClient.createHttpResponse(UrlHttpClient.java:92) 
        at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:85) 
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:371) 
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212) 
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4908) 
        at com.amazonaws.services.s3.AmazonS3Client.uploadPart(AmazonS3Client.java:3884) 
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadPartTask.call(UploadPartTask.java:60) 
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadPartTask.call(UploadPartTask.java:30) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) `

**Which AWS service(s) are affected?**
S3 & TransferUtility

**Expected behavior**
The upload should retry automatically until the user tells him to stop.
I've tried to capture the error in my TransferListener onError method. Since I'm uploading a large file (30MB) and the upload failed, I would have to re-upload the file again from scratch. It would be great if we can resume the upload from where it left of.

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.14.0
 - Device: Samsung Galaxy Note 8
 - Android Version: 8

**Comment by TrekSoft** [comment]
Hey Nicolas,

Looks like this is probably the same issue as #1006 so I'll close this one out and you can track that one which we'll be actively working on. If, though, it looks like the solution over there or problem is not the same as yours, feel free to reopen this.
