### ISSUE TITLE
AndroidPubSUb example not working.(Failed to initialize Cognito Identity;)

### ISSUE THREAD

**Issue by mihirmendapara** [aws-amplify/aws-sdk-android#1198]
**Describe the bug**
After following the step's provided in
 https://github.com/awslabs/aws-sdk-android-samples/blob/master/AndroidPubSub/README.md

able to launch application on my android device but button of "connect" is not active.so not able to connect my device to AWS.

after this i download old sample from 

https://github.com/awslabs/aws-sdk-android-samples/tree/03488248f78cc3654b2486cc86ec0d37c985d10a/AndroidPubSub

and followed the step .luckily this works perfectly.

difference i noticed in this two is that  older one does not have awsconfiguration.json and it accepts pool id on same page.i don't know how this make difference.

p.s  one threat with same issue is closed before but it is still not resolved.

**To Reproduce**
A code sample or steps:
```
Your code
```

**Which AWS service(s) are affected?**
Androidpubsub sample application
**Expected behavior**

**Screenshots**
![WhatsApp Image 2019-09-16 at 2 34 21 AM](https://user-images.githubusercontent.com/15989247/64927626-d547f680-d82a-11e9-98f4-70854b53626a.jpeg)

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: [latest as on 16-09-19  ver. dont know]
 - Device: [Xiaomi Redmi Note 4]
 - Android Version: [ Nougat 7.1.2]
 - Specific to simulators: [no]

**Additional context**
logcat error log :- 

2019-09-16 02:47:34.332 17042-17042/com.amazonaws.demo.androidpubsub E/HAL: PATH3 /odm/lib64/hw/gralloc.qcom.so
2019-09-16 02:47:34.332 17042-17042/com.amazonaws.demo.androidpubsub E/HAL: PATH2 /vendor/lib64/hw/gralloc.qcom.so
2019-09-16 02:47:34.332 17042-17042/com.amazonaws.demo.androidpubsub E/HAL: PATH1 /system/lib64/hw/gralloc.qcom.so
2019-09-16 02:47:34.332 17042-17042/com.amazonaws.demo.androidpubsub E/HAL: PATH3 /odm/lib64/hw/gralloc.msm8953.so
2019-09-16 02:47:34.332 17042-17042/com.amazonaws.demo.androidpubsub E/HAL: PATH2 /vendor/lib64/hw/gralloc.msm8953.so
2019-09-16 02:47:34.332 17042-17042/com.amazonaws.demo.androidpubsub E/HAL: PATH1 /system/lib64/hw/gralloc.msm8953.so
2019-09-16 02:47:34.412 17042-17166/com.amazonaws.demo.androidpubsub E/com.amazonaws.demo.androidpubsub.PubSubActivity: onError: 
    **java.lang.RuntimeException: Failed to initialize Cognito Identity; please check your awsconfiguration.json**
        at com.amazonaws.mobile.client.AWSMobileClient$2.run(AWSMobileClient.java:533)
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
        at java.lang.Thread.run(Thread.java:760)
     Caused by: java.lang.IllegalArgumentException: No region provided
        at com.amazonaws.AmazonWebServiceClient.setRegion(AmazonWebServiceClient.java:450)
        at com.amazonaws.mobile.client.AWSMobileClient$2.run(AWSMobileClient.java:526)
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101) 
        at java.lang.Thread.run(Thread.java:760)

**Comment by desokroshan** [comment]
@mihirmendapara Can you please share your awsconfiguration.json. The above error usually is result of identity pool not being setup correctly. I am able to work perfectly with the sample app as is following the instructions. Can you please make sure you followed the identity pool setup perfectly. Thanks!

**Comment by mihirmendapara** [comment]
Hi Roshan,

here is my awsconfigration.json

{
  "Version": "1.0",
  "IdentityManager": {
    "Default": {}
  },
  "CredentialsProvider": {
    "CognitoIdentity": {
      "Default": {
        "PoolId": "ap-south-1:3bf4XXXX-XXXX-XXXX-9d8e-6cXXXd0daf43",
        "Region": "Regions.AP_SOUTH_1"
      }
    }
  }
}

**Comment by kvasukib** [comment]
@mihirmendapara The region value should be ```"Region": "ap-south-1"```
