### ISSUE TITLE
ConcurrentModificationException in pauseAllTransfersDueToNetworkInterruption, aws-android-sdk-core:2.16.0

### ISSUE THREAD

**Issue by HashimAli09** [aws-amplify/aws-sdk-android#1231]
**Describe the bug**
I see that this issue was already opened before https://github.com/aws-amplify/aws-sdk-android/issues/777

But we are still rarely encountering a ConcurrentModificationException at 
pauseAllTransfersDueToNetworkInterruption in aws-android-sdk-core:2.16.0

`java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
        at java.util.HashMap$ValueIterator.next(HashMap.java:1470)
        at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1084)
        at com.amazonaws.mobileconnectors.s3.transferutility.TransferNetworkLossHandler.pauseAllTransfersDueToNetworkInterruption(TransferNetworkLossHandler.java:212)
        at com.amazonaws.mobileconnectors.s3.transferutility.TransferNetworkLossHandler.access$100(TransferNetworkLossHandler.java:37)
        at com.amazonaws.mobileconnectors.s3.transferutility.TransferNetworkLossHandler$1.run(TransferNetworkLossHandler.java:125)
        at java.lang.Thread.run(Thread.java:784)`

**To Reproduce**
The exception occurs when the network is disconnected while a new upload task is submitting at the same time.  Here is my code which adds the upload task:
` try {
            TransferObserver transferObserver = mTransferUtility.upload(getFileUploadPath(file), file);
            transferObserver.setTransferListener(...);
        } catch (Exception e) {
            e.printStackTrace();
        }
`
Aws gradle dependencies:
`   
implementation 'com.amazonaws:aws-android-sdk-core:2.16.0'    
implementation 'com.amazonaws:aws-android-sdk-s3:2.13.5'    
implementation('com.amazonaws:aws-android-sdk-mobile-client:2.16.0@aar') { transitive = true }    
implementation('com.amazonaws:aws-android-sdk-auth-userpools:2.16.0@aar') { transitive = true }`

**Which AWS service(s) are affected?**
Amazon S3

**Expected behavior**
The exception should not occur.

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.16.0
 - Device: Actual Devices
 - Android Version: All versions
 - Specific to simulators: No

**Comment by raphkim** [comment]
Hi @HashimAli09 

I see that you are using s3 version 2.13.5, but this bug was fixed in 2.13.7. Would you be able to let us know if this behavior still happens when you update the dependencies? Thank you!

**Comment by HashimAli09** [comment]
Yes! after updating the dependencies, I am not getting the exception.

thank you soo much for your quick help.
