### ISSUE TITLE
S3 GetObject request failing with "More data read(78279) than expected" error. 

### ISSUE THREAD

**Issue by chandusam2002** [aws-amplify/aws-sdk-android#1232]
**Describe the bug**
AmazonS3Client's getObject call to retrieve a s3 object is failing with an error com.amazonaws.AmazonClientException: More data read (78279) than expected (76839). The s3 object that is being retrieved has Content-Encoding of gzip and i verified that the actual content length is 76839 (used aws cli to confirm). 

Not sure it matters but the s3 object is using kms server encryption.

**To Reproduce**

-  Create a s3 object is a bucket with content encoding as gzip and content type as binary/octet-stream
- Set the server side encryption as kms 
- Retrieve the object using the code below

Your code
```
val s3Client = AmazonS3Client(credentials)
val request = GetObjectRequest("testbucket", "testkey")
s3Object = s3Client.getObject(request)
val bytes = IOUtils.toByteArray(s3Object.objectContent)
```
**Which AWS service(s) are affected?**
S3

**Expected behavior**
Able to retrieve the s3 object with out any exception.

**Screenshots**
Exception stack trace
```
com.amazonaws.AmazonClientException: More data read (78279) than expected (76839)
        at com.amazonaws.util.LengthCheckInputStream.checkLength(LengthCheckInputStream.java:135)
        at com.amazonaws.util.LengthCheckInputStream.read(LengthCheckInputStream.java:101)
        at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:73)
        at com.amazonaws.services.s3.model.S3ObjectInputStream.read(S3ObjectInputStream.java:167)
        at com.amazonaws.services.s3.model.S3ObjectInputStream.read(S3ObjectInputStream.java:159)
        at com.amazonaws.util.IOUtils.toByteArray(IOUtils.java:48)
```

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.8.x
 - Device: Moto 5
 - Specific to simulators: No

**Additional context**
I have setup break points in com.amazonaws.http.HttpResponse class and can see that the rawContent has a length that matches the response metadata. It is possible that wrapping GzipInputStream around the rawContent is causing the total size to go up. 

But the LengthCheckInputStream wrapper in AmazonS3Client is verifying against the length specified in the response object metadata instead of the uncompressed  data from the GzipInputStream.

**Comment by raphkim** [comment]
Thank you for reporting this issue. I was able to reproduce that error, and I'll look into correcting this.

**Comment by varunbharill** [comment]
Hi,
I am getting a very similar exception. I am getting a gzip object -> getting its stream -> passing it into GZIPInputStream.

```
GetObjectRequest getObjectRequest = new GetObjectRequest(getBucketName(), etDownloadFilePattern());
S3Object object = s3Client.getObject(getObjectRequest);
return ((new GZIPInputStream(object.getObjectContent())));
```

The exception I get is below:
```
Caused by: com.amazonaws.AmazonClientException: More data read than expected: dataLength=1; expectedLength=0; includeSkipped=true; in.getClass()=class com.amazonaws.services.s3.AmazonS3Client$2; markedSupported=false; marked=0; resetSinceLastMarked=false; markCount=0; resetCount=0
	at com.amazonaws.util.LengthCheckInputStream.checkLength(LengthCheckInputStream.java:155)
	at com.amazonaws.util.LengthCheckInputStream.read(LengthCheckInputStream.java:94)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:66)
	at com.amazonaws.services.s3.model.S3ObjectInputStream.read(S3ObjectInputStream.java:135)
	at java.util.zip.CheckedInputStream.read(CheckedInputStream.java:59)
	at java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:266)
	at java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:258)
	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
```

Any though on the workaround?
@drochetti

**Comment by chandusam2002** [comment]
@drochetti you may this option. You would be overriding the content type encoding  header.

```
                getObjectRequest.responseHeaders =
                    new ResponseHeaderOverrides().withContentEncoding("identity")
                S3Object object = s3Client.getObject(request)
                return GZIPInputStream(s3Result.objectContent)
```

**Comment by gwicks56** [comment]
I also got this error, I will check to see if it re-occurs. I think maybe it happened because the file was written to during the upload, making it slightly bigger. Is it possible that could cause the error?

**Comment by hackaprende** [comment]
Same error here, it happens when doing 
`amazonS3Client.putObject(myRequest)`

**Comment by sdhuka** [comment]
@hackaprende @gwicks56 @chandusam2002 

I am not able to repro this issue with v2.44.0. I tried with [this file](http://www.sbeams.org/sample_data/Proteomics/yeast_orfs.new.20040422.gz) and kms encryption enabled. Could you please retry with latest version and update here.

```
val s3Client = storagePlugin.escapeHatch as AmazonS3Client
            val request =
                GetObjectRequest("bucket", key)
            val s3Object = s3Client.getObject(request)
            val bytes = IOUtils.toByteArray(s3Object.objectContent)
```
