### ISSUE TITLE
Using AWSIotMqttManager on Android 21

### ISSUE THREAD

**Issue by seristomXOZ** [aws-amplify/aws-sdk-android#1250]
**Question**
Hi there! 
So I am using this sdk for subscribing to a PubSub Server on Android SDK 21+. Apparently it doesnt work on devices lower than SDK 27 (or maybe I'm doing something wrong).
I was just wondering if there is another way to make it work or if there is a plan to use another lib than the underlying lib creating this problem? 
https://github.com/eclipse/paho.mqtt.java/issues/633

**Which AWS Services are you utilizing?**
AWSIotMqttManager:
'com.amazonaws:aws-android-sdk-iot:2.6.16@aar',
'com.amazonaws:aws-android-sdk-mobile-client:2.6.16@aar',

**Provide code snippets (if applicable)**
```
AWSIotMqttManager = AWSIotMqttManager(randomUid, endpoint)
  .connect( CognitoCachingCredentialsProvider(
                ContextHelper.getContext(),
                identityPoolId,
                Regions.EU_CENTRAL_1
          )
```

An underlying lib of AWSIotMqttManager is returning this Error:
```10-12 21:40:18.753 E/AndroidRuntime: FATAL EXCEPTION: MQTT Con: c0bf0d33-e15f-4caa-8291-d2431b1b2515
    java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/net/ssl/SNIHostName;
        at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:139)
        at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketSecureNetworkModule.start(WebSocketSecureNetworkModule.java:63)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:722)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "javax.net.ssl.SNIHostName" on path: DexPathList[[zip file "/data/app/com.[...]-1/base.apk"],nativeLibraryDirectories=[/data/app/com.[...]-1/lib/x86, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:139) 
        at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketSecureNetworkModule.start(WebSocketSecureNetworkModule.java:63) 
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:722) 
        at java.lang.Thread.run(Thread.java:818) 
    	Suppressed: java.lang.ClassNotFoundException: javax.net.ssl.SNIHostName
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 5 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

**Environment(please complete the following information):**
 - SDK Version: tried almost every version from 2.2.

**Device Information (please complete the following information):**
 - Device: [Simulator]
 - Android Version: [Lollipop 5.1.]
 - Specific to simulators:  Size 40", 1920x1080 xhdpi, Android 5.1 x86, Android TV

**Comment by seristomXOZ** [comment]
I had a problem with the update of the dependencies. 2.16.0 seems to work now. 
Sorry for the inconvenience. 🤦‍♂
