### ISSUE TITLE
I get "No cached session error" after calling getToken()  when user state is SIGNED_IN 

### ISSUE THREAD

**Issue by mohsenk** [aws-amplify/aws-sdk-android#1262]
**Describe the bug**
At first when i login with Google HosteUI everything is good. but after close and open app. my userStateListener  says that user is "SIGNED_IN" and i'm going to get call getTokens() method but it returns error "No Cached Session".

```
2019-10-19 14:38:49.108 12558-12660/hu.avicenna.android E/ApiClient: error in get token
    java.lang.Exception: No cached session.
        at com.amazonaws.mobile.client.AWSMobileClient$10.onFailure(AWSMobileClient.java:1648)
        at com.amazonaws.mobileconnectors.cognitoauth.AuthClient.getSession(AuthClient.java:182)
        at com.amazonaws.mobileconnectors.cognitoauth.Auth.getSession(Auth.java:674)
        at com.amazonaws.mobile.client.AWSMobileClient._getHostedUITokens(AWSMobileClient.java:1651)
        at com.amazonaws.mobile.client.AWSMobileClient.access$800(AWSMobileClient.java:163)
        at com.amazonaws.mobile.client.AWSMobileClient$9.run(AWSMobileClient.java:1573)
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.Exception: No cached session
        at com.amazonaws.mobileconnectors.cognitoauth.AuthClient.getSession(AuthClient.java:182) 
        at com.amazonaws.mobileconnectors.cognitoauth.Auth.getSession(Auth.java:674) 
        at com.amazonaws.mobile.client.AWSMobileClient._getHostedUITokens(AWSMobileClient.java:1651) 
        at com.amazonaws.mobile.client.AWSMobileClient.access$800(AWSMobileClient.java:163) 
        at com.amazonaws.mobile.client.AWSMobileClient$9.run(AWSMobileClient.java:1573) 
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101) 
        at java.lang.Thread.run(Thread.java:764) 
```

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.15.1
 - Device: OnePlus 5T
 - Android Version: 8.1
 - Specific to simulators: No

**Comment by kvasukib** [comment]
@mohsenk We did some bug fixes to AWSMobileClient for Hosted UI in the versions later than `2.15.1`. Can you upgrade to the latest, verify and let us know?

**Comment by mohsenk** [comment]
No i tried with 2.16.1 but i still get same error.

**Comment by truongnguyen-agilityio** [comment]
I tried with 2.16.3 but still get error

**Comment by truongnguyen-agilityio** [comment]
any new ? @kvasukib @mohsenk

**Comment by developer--** [comment]
I got same problem

**Comment by TobiS97** [comment]
I also get the same error: AWSMobileClient: Tokens are invalid, please sign-in again. java.lang.Exception: No cached session. Are there any news about this topic?
I am using my own UI and the user state of my user is also: signedIn.
 For the signIn i am using this method:  AWSMobileClient.getInstance().signIn
Afterwards when calling:
Log.d("JWT: ", AWSMobileClient.getInstance().getTokens().getIdToken().getTokenString());
I get the exception.

**Comment by TrekSoft** [comment]
Hi all,

It seems this issue is caused by running the non-async getTokens() method on the main UI thread. You can either run it on a background thread or run the version of getTokens that takes a callback:

`AWSMobileClient.getInstance().getTokens(Callback)`

**Comment by TrekSoft** [comment]
Hi all, just wanted to let you know I happened to come across this issue in my own testing and found this is the result of a bug on our end where once a user has signed in with Hosted UI, it permanently caches that which messes up getting tokens if you sign in with the regular sign in method. 

The workaround is to clear data for the app but we will be fixing this so it doesn't happen again.
