### ISSUE TITLE
If credentials cannot be retrieved by CognitoCachingCredentialsProvider when AWSIotMqttManager is attempting to reconnect, AWSIotMqttManager starts making multiple, rapid, overlapping connection attempts. This sometimes lastingly affects reconnection.

### ISSUE THREAD

**Issue by yesitsdave** [aws-amplify/aws-sdk-android#1274]
**Describe the bug**
If credentials cannot be retrieved by CognitoCachingCredentialsProvider when AWSIotMqttManager is attempting to reconnect - for example, if there is no data connection available on the device - AWSIotMqttManager starts making multiple, rapid, overlapping connection attempts, some of which have the same reconnection attempt number. If the data connection to the device is then restored, the fact that there are now multiple connection attempts seems to leave AWSIotMqttManager in a strange state - occasionally, it reconnects again after some time. Sometimes, it seems it does not reconnect at all (not 100% confirmed but have seen this).

**To Reproduce**
[I've created a repo that can be used to demonstrate this here](https://github.com/Nona-Creative/iot-test).
You will need the details of a Cognito User Pool linked to an Identity Pool, with policies to connect to IoT.
Start the app, then disable internet connectivity for the app or device to trigger the keepalive timeout and reconnection attempts. When the credentials expire (after about an hour) you will see the issue.

**Which AWS service(s) are affected?**
IoT

**Expected behavior**
Reconnection attempts should continue normally, with normal timing, if credentials cannot be retrieved, and once they can be retrieved reconnection should happen normally.

**Logs**

Logs showing the example app attempting to reconnect normally:

```java
019-10-23 19:04:02.384 29466-29526/digital.nona.iottest W/AWSIotMqttManager: connection is Lost
2019-10-23 19:04:02.385 29466-29526/digital.nona.iottest I/AWSIotMqttManager: resetting reconnect attempt and retry time
2019-10-23 19:04:02.385 29466-29526/digital.nona.iottest I/AWSIotMqttManager: schedule Reconnect attempt 0 of -1 in 60 seconds.
2019-10-23 19:04:02.386 29466-29526/digital.nona.iottest I/IOTManager: IoT Status: Reconnecting
2019-10-23 19:05:02.420 29466-29534/digital.nona.iottest D/AWSIotMqttManager: TID: 29534 trying to reconnect to session
2019-10-23 19:05:02.420 29466-29534/digital.nona.iottest I/AWSIotMqttManager: attempting to reconnect to mqtt broker
2019-10-23 19:05:02.427 29466-29534/digital.nona.iottest D/AWSIotMqttManager: Reconnect to mqtt broker: ao3x258cc22q2-ats.iot.eu-west-1.amazonaws.com mqttWebSocketURL: 
2019-10-23 19:05:02.427 29466-29534/digital.nona.iottest D/AWSIotMqttManager: Setting up Callback for MqttClient
2019-10-23 19:05:02.427 29466-29534/digital.nona.iottest D/AWSIotMqttManager: mqtt reconnecting attempt 1
2019-10-23 19:05:42.513 29466-29552/digital.nona.iottest W/AWSIotMqttManager: Reconnect failed 
2019-10-23 19:05:42.513 29466-29552/digital.nona.iottest I/AWSIotMqttManager: schedule Reconnect attempt 1 of -1 in 60 seconds.
2019-10-23 19:05:42.514 29466-29552/digital.nona.iottest I/IOTManager: IoT Status: Reconnecting
2019-10-23 19:06:42.527 29466-29553/digital.nona.iottest D/AWSIotMqttManager: TID: 29553 trying to reconnect to session
2019-10-23 19:06:42.528 29466-29553/digital.nona.iottest I/AWSIotMqttManager: attempting to reconnect to mqtt broker
2019-10-23 19:06:42.533 29466-29553/digital.nona.iottest D/AWSIotMqttManager: Reconnect to mqtt broker: ao3x258cc22q2-ats.iot.eu-west-1.amazonaws.com mqttWebSocketURL: 
2019-10-23 19:06:42.534 29466-29553/digital.nona.iottest D/AWSIotMqttManager: Setting up Callback for MqttClient
2019-10-23 19:06:42.534 29466-29553/digital.nona.iottest D/AWSIotMqttManager: mqtt reconnecting attempt 2
2019-10-23 19:07:22.618 29466-29572/digital.nona.iottest W/AWSIotMqttManager: Reconnect failed 
2019-10-23 19:07:22.618 29466-29572/digital.nona.iottest I/AWSIotMqttManager: schedule Reconnect attempt 2 of -1 in 60 seconds.
2019-10-23 19:07:22.620 29466-29572/digital.nona.iottest I/IOTManager: IoT Status: Reconnecting
2019-10-23 19:08:22.681 29466-29573/digital.nona.iottest D/AWSIotMqttManager: TID: 29573 trying to reconnect to session
2019-10-23 19:08:22.681 29466-29573/digital.nona.iottest I/AWSIotMqttManager: attempting to reconnect to mqtt broker
2019-10-23 19:08:22.686 29466-29573/digital.nona.iottest D/AWSIotMqttManager: Reconnect to mqtt broker: ao3x258cc22q2-ats.iot.eu-west-1.amazonaws.com mqttWebSocketURL: 
2019-10-23 19:08:22.687 29466-29573/digital.nona.iottest D/AWSIotMqttManager: Setting up Callback for MqttClient
2019-10-23 19:08:22.687 29466-29573/digital.nona.iottest D/AWSIotMqttManager: mqtt reconnecting attempt 3
2019-10-23 19:09:02.772 29466-29591/digital.nona.iottest W/AWSIotMqttManager: Reconnect failed`

Logs showing behaviour once credentials have expired and cannot be retrieved:

`019-10-23 19:59:07.482 29466-30200/digital.nona.iottest I/IOTManager: IoT Status: Reconnecting
2019-10-23 19:59:07.482 29466-30209/digital.nona.iottest D/KeyProvider23: Loading the encryption key from Android KeyStore.
2019-10-23 19:59:07.482 29466-30200/digital.nona.iottest D/AWSIotMqttManager: Setting up Callback for MqttClient
2019-10-23 19:59:07.482 29466-30200/digital.nona.iottest D/AWSIotMqttManager: mqtt reconnecting attempt 33
2019-10-23 19:59:07.698 29466-30209/digital.nona.iottest E/AWSIotMqttManager: Failed to get credentials. AmazonClientException: 
2019-10-23 19:59:07.698 29466-30209/digital.nona.iottest I/AWSIotMqttManager: schedule Reconnect attempt 33 of -1 in 60 seconds.
2019-10-23 19:59:07.700 29466-30209/digital.nona.iottest I/IOTManager: IoT Status: Reconnecting
2019-10-23 19:59:07.700 29466-30209/digital.nona.iottest D/AWSIotMqttManager: Setting up Callback for MqttClient
2019-10-23 19:59:07.700 29466-30209/digital.nona.iottest D/AWSIotMqttManager: mqtt reconnecting attempt 34
2019-10-23 19:59:07.712 29466-30209/digital.nona.iottest E/AWSIotMqttManager: Exception during reconnect, exception: 
    Connect already in progress (32110)
        at org.eclipse.paho.client.mqttv3.MqttAsyncClient.connect(MqttAsyncClient.java:602)
        at com.amazonaws.mobileconnectors.iot.AWSIotMqttManager.reconnectToSession(AWSIotMqttManager.java:1092)
        at com.amazonaws.mobileconnectors.iot.AWSIotMqttManager$4.run(AWSIotMqttManager.java:1156)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2019-10-23 19:59:07.712 29466-30209/digital.nona.iottest I/AWSIotMqttManager: schedule Reconnect attempt 34 of -1 in 60 seconds.
2019-10-23 19:59:07.715 29466-30209/digital.nona.iottest I/IOTManager: IoT Status: Reconnecting
2019-10-23 19:59:47.563 29466-30240/digital.nona.iottest W/AWSIotMqttManager: Reconnect failed 
2019-10-23 19:59:47.563 29466-30240/digital.nona.iottest I/AWSIotMqttManager: schedule Reconnect attempt 34 of -1 in 60 seconds.
2019-10-23 19:59:47.564 29466-30240/digital.nona.iottest I/IOTManager: IoT Status: Reconnecting
2019-10-23 20:00:07.543 29466-30224/digital.nona.iottest D/AWSIotMqttManager: TID: 30224 trying to reconnect to session
2019-10-23 20:00:07.543 29466-30224/digital.nona.iottest I/AWSIotMqttManager: attempting to reconnect to mqtt broker
2019-10-23 20:00:07.544 29466-30224/digital.nona.iottest D/CognitoCachingCredentialsProvider: Making a network call to fetch credentials.
2019-10-23 20:00:07.545 29466-30224/digital.nona.iottest D/KeyProvider23: AndroidKeyStore contains keyAlias com.amazonaws.android.auth.aesKeyStoreAlias
2019-10-23 20:00:07.545 29466-30224/digital.nona.iottest D/KeyProvider23: Loading the encryption key from Android KeyStore.
2019-10-23 20:00:07.733 29466-30232/digital.nona.iottest D/AWSIotMqttManager: TID: 30232 trying to reconnect to session
2019-10-23 20:00:07.733 29466-30232/digital.nona.iottest I/AWSIotMqttManager: attempting to reconnect to mqtt broker
2019-10-23 20:00:07.770 29466-30233/digital.nona.iottest D/AWSIotMqttManager: TID: 30233 trying to reconnect to session
2019-10-23 20:00:07.770 29466-30233/digital.nona.iottest I/AWSIotMqttManager: attempting to reconnect to mqtt broker
2019-10-23 20:00:47.622 29466-30241/digital.nona.iottest D/AWSIotMqttManager: TID: 30241 trying to reconnect to session
2019-10-23 20:00:47.622 29466-30241/digital.nona.iottest I/AWSIotMqttManager: attempting to reconnect to mqtt broker
2019-10-23 20:00:47.961 29466-30224/digital.nona.iottest E/AWSIotMqttManager: Failed to get credentials. AmazonClientException: 
2019-10-23 20:00:47.961 29466-30224/digital.nona.iottest I/AWSIotMqttManager: schedule Reconnect attempt 34 of -1 in 60 seconds.
2019-10-23 20:00:47.961 29466-30232/digital.nona.iottest D/CognitoCachingCredentialsProvider: Making a network call to fetch credentials.
2019-10-23 20:00:47.964 29466-30232/digital.nona.iottest D/KeyProvider23: AndroidKeyStore contains keyAlias com.amazonaws.android.auth.aesKeyStoreAlias
2019-10-23 20:00:47.964 29466-30232/digital.nona.iottest D/KeyProvider23: Loading the encryption key from Android KeyStore.`

This gets worse as time goes on:

`2019-10-23 20:05:34.050 29466-30372/digital.nona.iottest I/IOTManager: IoT Status: Reconnecting
2019-10-23 20:05:34.051 29466-30371/digital.nona.iottest D/KeyProvider23: Loading the encryption key from Android KeyStore.
2019-10-23 20:05:34.051 29466-30372/digital.nona.iottest D/AWSIotMqttManager: Setting up Callback for MqttClient
2019-10-23 20:05:34.051 29466-30372/digital.nona.iottest D/AWSIotMqttManager: mqtt reconnecting attempt 64
2019-10-23 20:05:34.051 29466-30372/digital.nona.iottest E/AWSIotMqttManager: Exception during reconnect, exception: 
    Connect already in progress (32110)
        at org.eclipse.paho.client.mqttv3.MqttAsyncClient.connect(MqttAsyncClient.java:602)
        at com.amazonaws.mobileconnectors.iot.AWSIotMqttManager.reconnectToSession(AWSIotMqttManager.java:1092)
        at com.amazonaws.mobileconnectors.iot.AWSIotMqttManager$4.run(AWSIotMqttManager.java:1156)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2019-10-23 20:05:34.051 29466-30372/digital.nona.iottest I/AWSIotMqttManager: schedule Reconnect attempt 64 of -1 in 60 seconds.
2019-10-23 20:05:34.052 29466-30372/digital.nona.iottest I/IOTManager: IoT Status: Reconnecting
2019-10-23 20:05:48.777 29466-30393/digital.nona.iottest D/AWSIotMqttManager: TID: 30393 trying to reconnect to session
2019-10-23 20:05:48.777 29466-30393/digital.nona.iottest I/AWSIotMqttManager: attempting to reconnect to mqtt broker
2019-10-23 20:05:50.419 29466-30394/digital.nona.iottest D/AWSIotMqttManager: TID: 30394 trying to reconnect to session
2019-10-23 20:05:50.419 29466-30397/digital.nona.iottest D/AWSIotMqttManager: TID: 30397 trying to reconnect to session
2019-10-23 20:05:50.419 29466-30394/digital.nona.iottest I/AWSIotMqttManager: attempting to reconnect to mqtt broker
2019-10-23 20:05:50.419 29466-30397/digital.nona.iottest I/AWSIotMqttManager: attempting to reconnect to mqtt broker
2019-10-23 20:05:50.623 29466-30403/digital.nona.iottest D/AWSIotMqttManager: TID: 30403 trying to reconnect to session
2019-10-23 20:05:50.624 29466-30403/digital.nona.iottest I/AWSIotMqttManager: attempting to reconnect to mqtt broker
2019-10-23 20:05:50.685 29466-30407/digital.nona.iottest D/AWSIotMqttManager: TID: 30407 trying to reconnect to session
2019-10-23 20:05:50.685 29466-30407/digital.nona.iottest I/AWSIotMqttManager: attempting to reconnect to mqtt broker
2019-10-23 20:05:50.856 29466-30408/digital.nona.iottest D/AWSIotMqttManager: TID: 30408 trying to reconnect to session
2019-10-23 20:05:50.856 29466-30408/digital.nona.iottest I/AWSIotMqttManager: attempting to reconnect to mqtt broker
2019-10-23 20:05:51.162 29466-30413/digital.nona.iottest D/AWSIotMqttManager: TID: 30413 trying to reconnect to session
2019-10-23 20:05:51.162 29466-30412/digital.nona.iottest D/AWSIotMqttManager: TID: 30412 trying to reconnect to session
2019-10-23 20:05:51.162 29466-30413/digital.nona.iottest I/AWSIotMqttManager: attempting to reconnect to mqtt broker
2019-10-23 20:05:51.162 29466-30412/digital.nona.iottest I/AWSIotMqttManager: attempting to reconnect to mqtt broker
2019-10-23 20:05:51.520 29466-30416/digital.nona.iottest D/AWSIotMqttManager: TID: 30416 trying to reconnect to session
2019-10-23 20:05:51.521 29466-30415/digital.nona.iottest D/AWSIotMqttManager: TID: 30415 trying to reconnect to session
2019-10-23 20:05:51.521 29466-30416/digital.nona.iottest I/AWSIotMqttManager: attempting to reconnect to mqtt broker
2019-10-23 20:05:51.521 29466-30415/digital.nona.iottest I/AWSIotMqttManager: attempting to reconnect to mqtt broker
2019-10-23 20:05:51.895 29466-30418/digital.nona.iottest D/AWSIotMqttManager: TID: 30418 trying to reconnect to session
2019-10-23 20:05:51.895 29466-30419/digital.nona.iottest D/AWSIotMqttManager: TID: 30419 trying to reconnect to session
2019-10-23 20:05:51.895 29466-30419/digital.nona.iottest I/AWSIotMqttManager: attempting to reconnect to mqtt broker
2019-10-23 20:05:51.895 29466-30418/digital.nona.iottest I/AWSIotMqttManager: attempting to reconnect to mqtt broker
2019-10-23 20:05:52.265 29466-30422/digital.nona.iottest D/AWSIotMqttManager: TID: 30422 trying to reconnect to session
2019-10-23 20:05:52.265 29466-30421/digital.nona.iottest D/AWSIotMqttManager: TID: 30421 trying to reconnect to session
2019-10-23 20:05:52.265 29466-30422/digital.nona.iottest I/AWSIotMqttManager: attempting to reconnect to mqtt broker
2019-10-23 20:05:52.265 29466-30421/digital.nona.iottest I/AWSIotMqttManager: attempting to reconnect to mqtt broker
2019-10-23 20:06:12.991 29466-30465/digital.nona.iottest W/AWSIotMqttManager: Reconnect failed 
2019-10-23 20:06:12.992 29466-30465/digital.nona.iottest I/AWSIotMqttManager: schedule Reconnect attempt 64 of -1 in 60 seconds.
2019-10-23 20:06:12.993 29466-30465/digital.nona.iottest I/IOTManager: IoT Status: Reconnecting
2019-10-23 20:06:14.673 29466-30371/digital.nona.iottest E/AWSIotMqttManager: Failed to get credentials. AmazonClientException: 
2019-10-23 20:06:14.673 29466-30371/digital.nona.iottest I/AWSIotMqttManager: schedule Reconnect attempt 64 of -1 in 60 seconds.
2019-10-23 20:06:14.674 29466-30374/digital.nona.iottest D/CognitoCachingCredentialsProvider: Making a network call to fetch credentials.
```

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.16.1
 - Device: Nexus 5X API 28 x86 simulator / Samsung Galaxy S7
 - Android Version: 28
 - Specific to simulators: No

**Additional context**
None

**Comment by yesitsdave** [comment]
@desokroshan Thanks for the response. I don't know if this happens on older versions - I've only tried 2.16.1.

**Comment by eeatonaws** [comment]
Hi, I apologize this was not looked into sooner. Since this is an old issue, before we investigate, could you please let us know if you are still facing the issue with the latest version of the SDK?

**Comment by poojamat** [comment]
https://github.com/aws-amplify/aws-sdk-android/issues/1470
