### ISSUE TITLE
Crash of AWS IoT SDK v2.16.1 on Android 5.1

### ISSUE THREAD

**Issue by rynkowsg** [aws-amplify/aws-sdk-android#1275]
**Describe the bug**
```
AndroidRuntime  E  FATAL EXCEPTION: MQTT Con: 200853
                E  Process: com.chargedup.largestation.dev.debug, PID: 10664
                E  java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/net/ssl/SNIHostName;
                E      at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:139)
                E      at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:722)
                E      at java.lang.Thread.run(Thread.java:818)
                E  Caused by: java.lang.ClassNotFoundException: Didn't find class "javax.net.ssl.SNIHostName" on path: DexPathList[[
                zip file "/data/app/com.chargedup.largestation.dev.debug-1/base.apk"],nativeLibraryDirectories=[/data/app/com.cha
                                                                                                                rgedup.largestation.dev.debug-1/lib/arm, /vendor/lib, /system/lib]]
                E      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                E      at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                E      at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                E      ... 3 more
                E      Suppressed: java.lang.ClassNotFoundException: javax.net.ssl.SNIHostName
                E          at java.lang.Class.classForName(Native Method)
                E          at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                E          at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                E          at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                E          ... 4 more
                E      Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```
**To Reproduce**
A code sample or steps:
```
provided AWS sample code
```

**Which AWS service(s) are affected?**
IoT

**Expected behavior**
No crashes on launch.

**Screenshots**
No screenshots.

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.16.1
 - Device: Custom Device
 - Android Version: 5.1
 - Specific to simulators: No

**Additional context**
Happens in 2.16.1, when you introduced "org.eclipse.paho:org.eclipse.paho.client.mqttv3".
2.16.0 works fine.

**Comment by desokroshan** [comment]
This is being tracked here https://github.com/aws-amplify/aws-sdk-android/issues/1259 
Closing as duplicate.
