### ISSUE TITLE
Using v2.16.4 causes FileInputStream crash on Android 5.1

### ISSUE THREAD

**Issue by rynkowsg** [aws-amplify/aws-sdk-android#1336]
**Describe the bug**
I was using v2.16.0 on Android 5.1 and it worked fine.
Today I tried to update it to v2.16.4 and I got an issue with reading files in my app:
```
FATAL EXCEPTION: main
Process: com.chargedup.largestation.dev, PID: 9701
java.lang.RuntimeException: Unable to create application com.chargedup.largestation.App: java.io.FileNotFoundException: /mnt/internal_sd/Android/data/com.chargedup.largestation.dev/files/options.json: open failed: EACCES (Permission denied)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4582)
    at android.app.ActivityThread.access$1500(ActivityThread.java:151)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1380)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5280)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)
Caused by: java.io.FileNotFoundException: /mnt/internal_sd/Android/data/com.chargedup.largestation.dev/files/options.json: open failed: EACCES (Permission denied)
    at libcore.io.IoBridge.open(IoBridge.java:456)
    at java.io.FileInputStream.<init>(FileInputStream.java:76)
    at com.chargedup.largestation.data.options.DataOptionsModule.provideOptions(DataOptionsModule.kt:30)
    at com.chargedup.largestation.data.options.DataOptionsModule_ProvideOptionsFactory.provideOptions(DataOptionsModule_ProvideOptionsFactory.java:39)
    at com.chargedup.largestation.data.options.DataOptionsModule_ProvideOptionsFactory.get(DataOptionsModule_ProvideOptionsFactory.java:29)
    at com.chargedup.largestation.data.options.DataOptionsModule_ProvideOptionsFactory.get(DataOptionsModule_ProvideOptionsFactory.java:9)
    at com.chargedup.largestation.data.DataAndroidModule_ProvidesStationIdFactory.get(DataAndroidModule_ProvidesStationIdFactory.java:26)
    at com.chargedup.largestation.data.DataAndroidModule_ProvidesStationIdFactory.get(DataAndroidModule_ProvidesStationIdFactory.java:9)
    at com.chargedup.largestation.data.iot.AwsModule_ProvidesStationInputTopicFactory.get(AwsModule_ProvidesStationInputTopicFactory.java:28)
    at com.chargedup.largestation.data.iot.AwsModule_ProvidesStationInputTopicFactory.get(AwsModule_ProvidesStationInputTopicFactory.java:8)
    at com.chargedup.largestation.data.iot.IotClient_Factory.get(IotClient_Factory.java:66)
    at com.chargedup.largestation.data.iot.IotClient_Factory.get(IotClient_Factory.java:12)
    at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
    at com.chargedup.largestation.appinitializers.SystemInitializer_Factory.get(SystemInitializer_Factory.java:35)
    at com.chargedup.largestation.appinitializers.SystemInitializer_Factory.get(SystemInitializer_Factory.java:11)
    at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
    at dagger.internal.SetFactory.get(SetFactory.java:126)
    at dagger.internal.SetFactory.get(SetFactory.java:37)
    at com.chargedup.common.appinitializers.AppInitializers_Factory.get(AppInitializers_Factory.java:22)
    at com.chargedup.common.appinitializers.AppInitializers_Factory.get(AppInitializers_Factory.java:9)
    at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
    at com.chargedup.largestation.di.DaggerAppComponent.injectApp(DaggerAppComponent.java:462)
    at com.chargedup.largestation.di.DaggerAppComponent.inject(DaggerAppComponent.java:458)
    at com.chargedup.largestation.di.DaggerAppComponent.inject(DaggerAppComponent.java:168)
    at dagger.android.DaggerApplication.injectIfNecessary(DaggerApplication.java:63)
    at dagger.android.DaggerApplication.onCreate(DaggerApplication.java:38)
    at com.chargedup.largestation.App.onCreate(App.kt:13)
    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4579)
    ... 9 more
Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
    at libcore.io.Posix.open(Native Method)
    at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
    at libcore.io.IoBridge.open(IoBridge.java:442)
```

**To Reproduce**
```
@Provides
    fun provideOptions(
        @Named(OPTIONS_PATH) optionsPath: String,
        adapter: JsonAdapter<Options>
    ): Options {
        val file = File(optionsPath)
        val inputStream = FileInputStream(file)
        val bytes = inputStream.readBytes()
        val str = bytes.toString(Charsets.UTF_8)
        return adapter.fromJson(str)!!
    }
```
It seems that `FileInputStream(file)` throws an exception.
To be honest I don't know how to explain that, yet. This file is not read by AWS SDK, I'm reading a file in my own code, but still, I got this issue only when I update AWS IOT SDK to v2.16.4. I tested also v2.16.2, v2.16.3. Same problem. 
_(Tested as well v2.16.1, but using this one I'm facing the issue reported in #1259 & #1275)_.

**Which AWS service(s) are affected?**
AWS IOT

**Expected behaviour**
No exception.

**Screenshots**
-

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.16.2, 2.16.3, 2.16.4
 - Device: Custom device
 - Android Version: 5.1 (API 21)
 - Specific to simulators: No

**Additional context**
-

**Comment by TrekSoft** [comment]
Hey, have you tried downgrading back to 2.16.0 to see if it goes back to working?

**Comment by TrekSoft** [comment]
Also, do you have the WRITE_EXTERNAL_STORAGE permission in the proper location in your manifest per this SO question?

https://stackoverflow.com/questions/8854359/exception-open-failed-eacces-permission-denied-on-android

**Comment by rynkowsg** [comment]
@TrekSoft 

Yes, 2.16.0 is working fine. The problem starts with 2.16.1.

Yes, I use WRITE_EXTERNAL_STORAGE permission in my manifest.

If you have a look at the stacktrace, this issue seemed to be a bit odd. It comes from `libcore.io.IoBridge.open(IoBridge.java:456)`. How that is possible that upgrade of your library affects reading file in the code not related to the library?

**Comment by rynkowsg** [comment]
I'm developing an IoT app, and I'm not able to update the system.

Any updates on this one? I don't want to stack with 2.16.0 forever when the lib is moving forward. You have to either cut the support for older platforms officially or fix the issue.

**Comment by rjuliano** [comment]
I'm working on trying to reproduce this error, but haven't been able to. How's the `options.json` file getting to `/mnt/internal_sd/Android/data/com.chargedup.largestation.dev/files/options.json`? Is it part of the app's resources?

As you mentioned, it's really odd that the upgrade to the SDK would be causing a permission denied error on a file that's read completely outside of the context of our SDK. 

I'll keep on trying to troubleshoot this, but figured I'd reach out to understand some more specifics about what's going on.

**Comment by rynkowsg** [comment]
@rjuliano 
It placed there half-automatically - it is a part of IoT thing setup, but it is irrelevant here.

This bug is weird. `FileInputStream(file)` throws the exception, but only in the newer version. Does your library do any bytecode manipulation within Java Standard Library?

**Comment by rjuliano** [comment]
Not that I'm aware of, but I'll do some more digging. I was just curious about the file because I noticed the `Permission denied` exception. I was able to read a file from that location without encountering the problem in an environment similar to the one your outlined.

Like I said, I'll do some more investigating on my side.

**Comment by rjuliano** [comment]
I spent some time this weekend trying to reproduce this to no avail. Are you running this on physical devices, simulators or both? My only thought at this point is that my testing setup somehow differs from yours. If you can share any additional info about your environment, that may help
