### ISSUE TITLE
java.lang.NoClassDefFoundError: AmazonS3Client;

### ISSUE THREAD

**Issue by nir-ilumisolutions** [aws-amplify/aws-sdk-android#1373]
I am using Amazon AWS S3 for downloading a file. When I try to initialize it shows below error.

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/amazonaws/services/s3/AmazonS3Client;
        at com.ilumi.data.serviceagents.ilumiServiceAgent.getFirmwareWithAccessTokens(ServiceAgent.java:2580)
        at com.ilumi.data.managers.ILAssetManager.fetchFirmwares(AssetManager.java:219)
        at com.ilumi.data.managers.ILAssetManager.access$300(AssetManager.java:24)
        at com.ilumi.data.managers.ILAssetManager$4.onSuccess(AssetManager.java:189)
        at com.ilumi.data.serviceagents.ilumiServiceAgent$55.onSuccess(ServiceAgent.java:2521)
        at com.ilumi.data.serviceagents.ServiceAgentBase$3.onResponse(ServiceAgentBase.java:400)
        at com.ilumi.data.serviceagents.CustomRequest.deliverResponse(CustomRequest.java:101)
        at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.amazonaws.services.s3.AmazonS3Client" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.myapp-lY3fjdvYXUhj7idTXW4v4Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.meshtekbeta.meshtek-lY3fjdvYXUhj7idTXW4v4Q==/lib/arm64, /data/app/com.myapp-lY3fjdvYXUhj7idTXW4v4Q==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
```

Here is my code : 
```
AmazonS3 s3 = new AmazonS3Client(new StaticCredentialsProvider(new BasicSessionCredentials("my_access_key", "my_secret_key", "my_session_token")));
       
        s3.setRegion(Region.getRegion(Regions.US_EAST_2));
        TransferUtility transferUtility = new TransferUtility(s3, context);

```
I am using it with SDK Version : 
 - implementation 'com.amazonaws:aws-android-sdk-s3:2.3.3'

I am using Google Pixel Android 9.0 device.

**Comment by kvasukib** [comment]
@nir-ilumisolutions I would recommend to upgrade to `implementation 'com.amazonaws:aws-android-sdk-s3:2.16.+'` and perform a gradle sync and see the behavior.
