### ISSUE TITLE
Amplify.API.mutate error: Java.Lang.NoSuchMethodError

### ISSUE THREAD

**Issue by Tachyon97** [aws-amplify/aws-sdk-android#1386]
**Describe the bug**
So I am following the tutorial at the website and I get this weird error

> 2019-12-20 04:30:12.284 9922-9982/com.sum.idgaf D/MainActivity: API QuickStart ready
2019-12-20 04:30:12.325 9922-9982/com.sum.idgaf E/AndroidRuntime: FATAL EXCEPTION: Thread-4
    Process: com.sum.idgaf, PID: 9922
    java.lang.NoSuchMethodError: No static method metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; in class Ljava/lang/invoke/LambdaMetafactory; or its super classes (declaration of 'java.lang.invoke.LambdaMetafactory' appears in /apex/com.android.runtime/javalib/core-oj.jar)
        at com.amplifyframework.util.FieldFinder.findFieldsIn(FieldFinder.java:59)
        at com.amplifyframework.core.model.ModelSchema.fromModelClass(ModelSchema.java:105)
        at com.amplifyframework.api.aws.AppSyncGraphQLRequestFactory.buildMutation(AppSyncGraphQLRequestFactory.java:155)
        at com.amplifyframework.api.aws.AWSApiPlugin.mutate(AWSApiPlugin.java:341)
        at com.amplifyframework.api.aws.AWSApiPlugin.mutate(AWSApiPlugin.java:322)
        at com.amplifyframework.api.aws.AWSApiPlugin.mutate(AWSApiPlugin.java:277)
        at com.amplifyframework.api.ApiCategory.mutate(ApiCategory.java:135)
        at com.sum.idgaf.MainActivity.createBlog(MainActivity.java:51)
        at com.sum.idgaf.MainActivity.access$100(MainActivity.java:19)
        at com.sum.idgaf.MainActivity$1.onResult(MainActivity.java:35)
        at com.sum.idgaf.MainActivity$1.onResult(MainActivity.java:28)
        at com.amazonaws.mobile.client.internal.InternalCallback.call(InternalCallback.java:75)
        at com.amazonaws.mobile.client.internal.InternalCallback.onResult(InternalCallback.java:62)
        at com.amazonaws.mobile.client.AWSMobileClient$2.run(AWSMobileClient.java:452)
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
        at java.lang.Thread.run(Thread.java:919)

**To Reproduce**
https://aws-amplify.github.io/docs/android/api 

upto createBlog()
```
    private void createBlog() {
        Blog blog = Blog.builder().name("My first blog").build();

        Amplify.API.mutate(
                blog,
                MutationType.CREATE,
                new ResultListener<GraphQLResponse<Blog>>() {
                    @Override
                    public void onResult(GraphQLResponse<Blog> response) {
                        Log.i("ApiQuickStart", "Added Blog with id: " + response.getData().getId());
                    }

                    @Override
                    public void onError(Throwable throwable) {
                        Log.e("ApiQuickStart", throwable.getMessage());
                    }
                }
        );
    }
```

**Which AWS service(s) are affected?**
Amplify API

**Expected behavior**
It is supposed to create an entry in the database

**Screenshots**

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: [2.7.+]
 - Device: [Nexus 6]
 - Android Version: [API 29]
 - Specific to simulators: [No]

**Additional context**

**Comment by TrekSoft** [comment]
Hey, did you follow the part of the documentation adding the compileOptions to your app build.gradle?

```
android {
  compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }
}
```
