### ISSUE TITLE
Refresh token expired earlier than it should on android.

### ISSUE THREAD

**Issue by mrinalTASKER** [aws-amplify/aws-sdk-android#1401]
Aws SignIn Token Is getting invalid within 1hr in low network. 
AWS SDK Version - 2.16

2019-12-30 18:17:36.500 20152-20152/com.prydo.driver E/SignInStatus :: Sign-in done.
2019-12-30 18:17:36.511 20152-20152/com.prydo.driver D/ViewRootImpl@6d5146c[VerifyUserIdActivity]: MSG_WINDOW_FOCUS_CHANGED 1
2019-12-30 18:17:36.512 20152-20152/com.prydo.driver D/ViewRootImpl@6d5146c[VerifyUserIdActivity]: mHardwareRenderer.initializeIfNeeded()#2 mSurface={isValid=true 2087864320}
2019-12-30 18:17:36.519 20152-20152/com.prydo.driver E/ViewRootImpl: sendUserActionEvent() returned.
2019-12-30 18:17:36.537 20152-22446/com.prydo.driver D/AWSMobileClient: Inspecting user state details
2019-12-30 18:17:36.678 20152-22446/com.prydo.driver W/CognitoUserSession: CognitoUserSession is not valid because idToken is null.
2019-12-30 18:17:36.678 20152-22446/com.prydo.driver W/AWSMobileClient: signalTokensNotAvailable
2019-12-30 18:17:36.679 20152-22446/com.prydo.driver W/AWSMobileClient: Tokens are invalid, please sign-in again.
    java.lang.Exception: No cached session.
        at com.amazonaws.mobile.client.AWSMobileClient$11$1.a(AWSMobileClient.java:1789)
        at com.amazonaws.mobile.client.AWSMobileClient$11$1.a(AWSMobileClient.java:1769)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.a(CognitoUser.java:778)
        at com.amazonaws.mobile.client.AWSMobileClient$11.run(AWSMobileClient.java:1751)
        at com.amazonaws.mobile.client.internal.InternalCallback.b(InternalCallback.java:115)
        at com.amazonaws.mobile.client.AWSMobileClient.a(AWSMobileClient.java:1717)
        at com.amazonaws.mobile.client.AWSMobileClient.b(AWSMobileClient.java:1024)
        at com.amazonaws.mobile.client.AWSMobileClient.n(AWSMobileClient.java:921)
        at com.amazonaws.mobile.client.AWSMobileClient$11.run(AWSMobileClient.java:1733)
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
        at java.lang.Thread.run(Thread.java:762)
2019-12-30 18:17:36.680 20152-22446/com.prydo.driver W/System.err: java.lang.Exception: getTokens does not support retrieving tokens while signed-out
2019-12-30 18:17:36.680 20152-22446/com.prydo.driver W/System.err:     at com.amazonaws.mobile.client.AWSMobileClient$11.run(AWSMobileClient.java:1734)
2019-12-30 18:17:36.680 20152-22446/com.prydo.driver W/System.err:     at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
2019-12-30 18:17:36.680 20152-22446/com.prydo.driver W/System.err:     at java.lang.Thread.run(Thread.java:762)
2019-12-30 18:17:36.716 20152-22480/com.prydo.driver D/AWSMobileClient: Inspecting user state details
2019-12-30 18:17:36.751 20152-22480/com.prydo.driver W/CognitoUserSession: CognitoUserSession is not valid because idToken is null.
2019-12-30 18:17:36.752 20152-22480/com.prydo.driver W/AWSMobileClient: signalTokensNotAvailable
2019-12-30 18:17:36.752 20152-22480/com.prydo.driver W/AWSMobileClient: Tokens are invalid, please sign-in again.
    java.lang.Exception: No cached session.
        at com.amazonaws.mobile.client.AWSMobileClient$11$1.a(AWSMobileClient.java:1789)
        at com.amazonaws.mobile.client.AWSMobileClient$11$1.a(AWSMobileClient.java:1769)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.a(CognitoUser.java:778)
        at com.amazonaws.mobile.client.AWSMobileClient$11.run(AWSMobileClient.java:1751)
        at com.amazonaws.mobile.client.internal.InternalCallback.b(InternalCallback.java:115)
        at com.amazonaws.mobile.client.AWSMobileClient.a(AWSMobileClient.java:1717)
        at com.amazonaws.mobile.client.AWSMobileClient.b(AWSMobileClient.java:1024)
        at com.amazonaws.mobile.client.AWSMobileClient.n(AWSMobileClient.java:903)
        at com.amazonaws.mobile.client.AWSMobileClient$11.run(AWSMobileClient.java:1733)
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
        at java.lang.Thread.run(Thread.java:762)
2019-12-30 18:17:36.752 20152-22480/com.prydo.driver D/AWSMobileClient: waitForSignIn: userState:SIGNED_OUT_USER_POOLS_TOKENS_INVALID

**Comment by zubairzahoor** [comment]
Make sure you are making the getTokens call from an async block. If you call it from uiThread, it returns the token that is in the cache so it will never refresh.

**Comment by raphkim** [comment]
@zubairzahoor is correct. 

Network call cannot be made from the UI thread, so the asynchronous call would be appropriate in this situation. Please see the [following discussion](https://github.com/aws-amplify/aws-sdk-android/issues/679#issuecomment-479688704) for more information.
