### ISSUE TITLE
confirmSignIn - Invalid attributes given, <attribute> is missing. 

### ISSUE THREAD

**Issue by zubairzahoor** [aws-amplify/aws-sdk-android#1402]
On gettting the NEW_PASSWORD_REQUIRED challange, when confirmSignIn is called with new password it shows 'Invalid attributes given, name is missing'.
'name' here is a required user attribute. 
Is there a way to pass the name (or other attributes) while submitting the new password?
In js there is a way. What about Android? 

 ` com.amazonaws.services.cognitoidentityprovider.model.InvalidParameterException: Invalid attributes given, name is missing (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: InvalidParameterException; Request ID: a2afe9e6-6382-44cd-ae53-2c4c7c25a8e6)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:730)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:405)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
        at com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.invoke(AmazonCognitoIdentityProviderClient.java:6292)
        at com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.respondToAuthChallenge(AmazonCognitoIdentityProviderClient.java:4953)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.respondToChallenge(CognitoUser.java:2408)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.continuations.ChallengeContinuation.continueTask(ChallengeContinuation.java:165)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.continuations.NewPasswordContinuation.continueTask(NewPasswordContinuation.java:147)
        at com.amazonaws.mobile.client.AWSMobileClient$7.run(AWSMobileClient.java:1274)
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
        at java.lang.Thread.run(Thread.java:764) `

**Comment by raphkim** [comment]
Closing in favor of duplicate issue #1403
