### ISSUE TITLE
BadRequestException thrown when updating endpoint due to limit being exceeded 

### ISSUE THREAD

**Issue by itViratSingh** [aws-amplify/aws-sdk-android#1470]
When i call updateEndpointProfile i get this error.

 ```
com.amazonaws.services.pinpoint.model.BadRequestException: Exceeded maximum endpoint per user count: 10 (Service: AmazonPinpoint; Status Code: 400; Error Code: BadRequestException; Request ID: 6c660ecb-93ca-448b-9b30-0f6a835fceb4)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:730)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:405)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
        at com.amazonaws.services.pinpoint.AmazonPinpointClient.invoke(AmazonPinpointClient.java:4081)
        at com.amazonaws.services.pinpoint.AmazonPinpointClient.updateEndpoint(AmazonPinpointClient.java:3775)
        at com.matchpointgps.app.utils.MPGPSPinpointAnalyticsManager.lambda$assignUserIdToEndpoint$0(MPGPSPinpointAnalyticsManager.java:132)
        at com.matchpointgps.app.utils.-$$Lambda$MPGPSPinpointAnalyticsManager$ShVbjan5mTWCeNoNA70y2DLTTjo.run(lambda)
        at java.lang.Thread.run(Thread.java:761)
```

I tried to call `getUserEndpoint` to get endpoint list but i am getting `GetUserEndpointsResult.getEndpointsResponse()`  as null.

```java
GetUserEndpointsRequest userEndpointRequest = new GetUserEndpointsRequest();
userEndpointRequest.setUserId("*****");
userEndpointRequest.setApplicationId("*************************");
GetUserEndpointsResult userEndpointResult = mPinpointManager.getPinpointContext().getPinpointServiceClient().getUserEndpoints(userEndpointRequest);
```

AWS Pinpoint Sdk Version: 2.15.2
Device Name: Moto G(4)
Android API Level : 24(Nougat) 
@kvasukib Please help.

**Comment by eeatonaws** [comment]
Hi, I apologize this was not looked into sooner. Since this is an old issue, before we investigate, could you please let us know if you are still facing the issue with the latest version of the SDK?

**Comment by poojamat** [comment]
Closing the issue due to lack of response, please reopen it if its still as issue.
