### ISSUE TITLE
NotAuthorizedException: Invalid login token. Issuer doesn't match providerName using federated sign in

### ISSUE THREAD

**Issue by scdplzop** [aws-amplify/aws-sdk-android#1484]
**Describe the bug**
Once Android app with current implementation launches the chrome tab social IDP page, then the user gets authorized and redirects back to our app, the exception thrown. 
The login process will fail and the user state call through 
`AWSMobileClient.getInstance().currentUserState().userState.name`
will be SIGNED_OUT_FEDERATED_TOKENS_INVALID.

**To Reproduce**
A code sample or steps:

Basically I follow the [CognitoAuthDemo](https://github.com/awslabs/aws-sdk-android-samples/tree/master/AmazonCognitoAuthDemo)

```
googleAuthBuilder = Auth.Builder()
                .setAppCognitoWebDomain("OUR_DOMAIN")
                .setAppClientId("OUR_ANDROID_CLIENT")
                .setAppClientSecret("OUR_ANDROID_CLIENT_SECRET")
                .setAuthHandler(FederatedHandler())
                .setUserPoolId("OUR_POOL_ID")
                .setIdpIdentifier("Google")
                .setApplicationContext(applicationContext)
                .setIdentityProvider("Google")
                .setSignInRedirect("SIGN_IN_URL")
                .setSignOutRedirect("SIGN_OUT_URL")
```

2. build different types of auth provider then getSession, the chrome tab will be launched at this stage
```
override fun onButtonPressed(idp: String) {
        val federatedAuth = buildProviderAuthOnChosen(idp)

        if ((mobileClient.currentUserState().userState != UserState.SIGNED_IN)) {
            federatedAuth?.getSession()
        }
    }
```

3. then call get token method on which provider user just choose in Android lifecycle onResume() 
```
    override fun onPostResume() {
        super.onPostResume()

        val appRedirect = Uri.parse("giant://onboarding")
//          -- Call Auth.getTokens() to get Cognito JWT --
        if (intent.data != null && appRedirect.host == intent.data.host) {
            getCognitoJWT()
        }
    }
```

```
    private fun getCognitoJWT() {
        preferenceStore.identityProvider.takeIf { it.isNotBlank() }?.let {
            Timber.d("Federated provider: $it")
            buildProviderAuthOnChosen(it)?.getTokens(intent.data)
        } ?: kotlin.run {
            Timber.d("Identity is blank.")
        }
    }
```
4. Call AWSMobileClient.getInstance().federatedSignIn() in call back onSuccess get called
```
inner class FederatedHandler : AuthHandler {
        override fun onSuccess(session: AuthUserSession?) {
            Timber.d("Id token from session: ${session?.idToken?.jwtToken}")
            Timber.d("Access token from session: ${session?.accessToken?.jwtToken}")
            Timber.d("Refresh token from session: ${session?.refreshToken?.token}")

            Timber.d("User sign in: ${AWSMobileClient.getInstance().isSignedIn}")

            preferenceStore.identityProvider.takeIf { it.isNotBlank() }?.let {
                AWSMobileClient.getInstance().federatedSignIn(
                    IdentityProvider.GOOGLE.toString(),
                    session?.idToken?.jwtToken,
                    ResultCallback<UserStateDetails>().apply {
                        result {
                            it.details.forEach {
                                Timber.d("key:${it.key}, value:${it.value}")
                            }
                        }

                        error { error ->
                            Bugsnag.addToTab("federated", preferenceStore.identityProvider, session?.idToken?.jwtToken ?: "")
                            Bugsnag.notify(error)
                            Timber.d(error)
                        }
                    })
```

Exceptions & error: 

```
D/OnbordingActivity$FederatedHandler$onSuccess$$inlined$let$lambda: java.lang.RuntimeException: Error in federating the token.
        at com.amazonaws.mobile.client.AWSMobileClient$10.run(AWSMobileClient.java:1650)
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: com.amazonaws.services.cognitoidentity.model.NotAuthorizedException: Invalid login token. Issuer doesn't match providerName (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: NotAuthorizedException; Request ID: b0cb0a57-8d74-41a6-9a65-f1c7600dfce4)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:730)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:405)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
        at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:1728)
        at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getId(AmazonCognitoIdentityClient.java:809)
        at com.amazonaws.auth.AWSAbstractCognitoIdentityProvider.getIdentityId(AWSAbstractCognitoIdentityProvider.java:172)
        at com.amazonaws.mobile.client.AWSMobileClientCognitoIdentityProvider.refresh(AWSMobileClient.java:3556)
        at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:679)
        at com.amazonaws.auth.CognitoCredentialsProvider.refresh(CognitoCredentialsProvider.java:632)
        at com.amazonaws.auth.CognitoCachingCredentialsProvider.refresh(CognitoCachingCredentialsProvider.java:510)
        at com.amazonaws.mobile.client.AWSMobileClient.federateWithCognitoIdentity(AWSMobileClient.java:1681)
        at com.amazonaws.mobile.client.AWSMobileClient$10.run(AWSMobileClient.java:1637)
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101) 
        at java.lang.Thread.run(Thread.java:764) 
```

**Which AWS service(s) are affected?**
Cognito federated sign in

**Expected behavior**
We expect to use the cognito federated sign in to create user in cognito user pool and authenticate through identity pool in order to let user from social idp to use AWS service in the future.

**Screenshots**

<img width="1440" alt="螢幕快照 2020-02-21 下午5 18 05" src="https://user-images.githubusercontent.com/40878006/75023203-5f7b4180-54d2-11ea-9fc6-c720a68c52b7.png">

<img width="1440" alt="螢幕快照 2020-02-21 下午5 19 32" src="https://user-images.githubusercontent.com/40878006/75023227-6904a980-54d2-11ea-95f6-ea52bfb0b265.png">

Exception is thrown after call setLogins() method 

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.16.8
 - Device: From several virtual emulators to Samsung note 4
 - Android Version: 6,7,8,9 have tested
 - Specific to simulators: N

**Additional context**

**Comment by scdplzop** [comment]
Further information before getting the token from Google(User login successfully).

```
-IyRKXamDtko5vmA3NPR6f9H733iSF_k2Z8mbeV7Bdox06CJI67W24bI2i4rj7RjIwAvwtcZ2YL2UArHAkAJGh2VIgoxpQDnRJfDV09tYYIWuYN9XWTHuIrL0qeHllQH6z5yBqg7FTT_TDUm2LW8CwLAdwutTQyD1WKkcqfbJxWbGoIF-ooJhnCh_ifyuVjHof1MO3Ut58u_79jXXE7efKyoBHU2--nTv9NN9Vib9ZroFv5KP-e9sDUONlB8WevqF4USrtb7xWEDuqKZWX59BO9qjfRyR6R-Zq3RsGg5IgavfxPotw4yaIlOFaaHtLeD1v26m2A7L-2Q96X1Atg2HY1ClLVWd5JoTCFnHWzF_nz9yC9Sdd9ms5b0wCHGzTx3F4uIQe8OOd9FX4mZh0xehmYR0mdPeMBeVc5O8uet_OvvSNM_uPVIHOh2WBEonv4X7D3PQDXX3WNoWnzv8nXELUXrUZO2sQ0cMB0r1s4mgEvyEg8JYJmnIk16Xxj4yDObJX2Od0stLDZeoVrL3FMsvOUQyQEKlViYeH23zqcymmbZGmuYWssb5XWSoBEqyQjJhiIhz4bqM56mQFOrELfYUGtP41RGiadhHOJFVjrHeETp0RI6plgBTvCxo7zLfZxQu9axSMwg7gwFceVhUB4Jen0Px-TCU2xeQG3R3A4VVUBaz9b9yDcN8InU3YXNpGQVNgUt1St8G9uc_xpeo7fhhKOcDYdybL0fbwL0zI3K_DyruAv4zqRyGjoCkSN0AXdnDZHave0Yel9SpjjWKqJrMv1UhOt_ajvrScRbibbUBSWsB_szVxNP3e4_ypAysBwUlZd0WPJAhIfJpDk5_-IC4WE8IHexBQozKSOKQ8PWz-puKYqI5VKrxX8UWPHw00xFanYkZjDwLz4kj6uf6qJ3k.yQd3zkM6IzJmAMuv-dVzPg
------------token got here
D/AWSMobileClient: Inspecting user state details
D/OnbordingActivity$FederatedHandler: User sign in: false
D/AWSMobileClient: _federatedSignIn: Putting provider and token in store
D/AWSMobileClient: Inspecting user state details
V/FA: Recording user engagement, ms: 1168
V/FA: Activity paused, time: 39051451
V/FA: onActivityCreated
D/AWSMobileClient: Inspecting user state details
    hasFederatedToken: false provider: accounts.google.com
I/AWSKeyValueStore: Detected Android API Level = 27
    Creating the AWSKeyValueStore with key for sharedPreferencesForData = CognitoIdentityProviderCache
D/AWSMobileClient: Inspecting user state details
D/SignInManager: Providers: [{}]
D/AWSMobileClient: hasFederatedToken: false provider: accounts.google.com
W/zygote: Long monitor contention with owner Thread-14 (20783) at void com.amazonaws.mobile.client.AWSMobileClient.federateWithCognitoIdentity(java.lang.String, java.lang.String)(AWSMobileClient.java:1665) waiters=0 in void com.amazonaws.mobile.client.AWSMobileClient.federateWithCognitoIdentity(java.lang.String, java.lang.String) for 3.212s
D/AWSMobileClient: hasFederatedToken: false provider: accounts.google.com
D/OnbordingActivity$FederatedHandler$onSuccess$$inlined$let$lambda: java.lang.RuntimeException: Error in federating the token.
        at com.amazonaws.mobile.client.AWSMobileClient$10.run(AWSMobileClient.java:1650)
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by scdplzop** [comment]
Update:
The user identities in the user pool
```
[{"userId":"109351911949433023750","providerName":"Google","providerType":"Google","issuer":null,"primary":true,"dateCreated":1582265070984}]
```

**Comment by TrekSoft** [comment]
Hey,

Currently the only way to have a user created in Cognito User Pools using a third party federated sign in is through Hosted UI. After that, it can be integrated with an Identity Pool through the raw Cognito SDK - https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-integrating-user-pools-with-identity-pools.html

However, only Hosted UI can create the user in the user pool to begin with for a 3rd party identity provider.
