### ISSUE TITLE
Error in federating the token and get Login status is SIGNED_OUT via MobileClient using third party login host UI

### ISSUE THREAD

**Issue by scdplzop** [aws-amplify/aws-sdk-android#1485]
**State your question**
Hi 
this question is based on issue #1484. I followed the instruction by 
[integrated with an Identity Pool through the raw Cognito SDK
](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-integrating-user-pools-with-identity-pools.html) and also updated my implementation.

My goal is to manage the user's login state via AWSMobileClient if someone uses the third party Host-UI, I expect the behavior is the same with user create and login via AWSMobileClient plain Cognito user pool just like the official documents, but this feature seems not supported.

So this situation cause those user's sign-in the state is not valid, they cannot update any attributes or relate operation.

Please have a look if there's something I misuse and give me some advice.

what ```AWSMobileClient.getInstance().federatedSignIn()``` doing is the same as following from my understanding:

```
cognitoUser.getSessionInBackground(new AuthenticationHandler() {
	@Override
	public void onSuccess(CognitoUserSession session) {
		String idToken = session.getIdToken().getJWTToken();

		Map<String, String> logins = new HashMap<String, String>();
		logins.put("cognito-idp.<region>.amazonaws.com/<YOUR_USER_POOL_ID>", session.getIdToken().getJWTToken());
		credentialsProvider.setLogins(logins);
	}

});
```
and this is my implementation after getting the token method once the user is authenticated through hosted-UI:

```
override fun onSuccess(session: AuthUserSession?) {
            Timber.d("Id token from session: ${session?.idToken?.jwtToken}")
            Timber.d("Access token from session: ${session?.accessToken?.jwtToken}")
            Timber.d("Refresh token from session: ${session?.refreshToken?.token}")

            Timber.d("User ${session?.username} sign in: ${AWSMobileClient.getInstance().isSignedIn}")
            Timber.d("User ${session?.username} sign in: ${AWSMobileClient.getInstance().currentUserState().userState.name}")
            
                launch {
                    withContext(Dispatchers.IO) {
                        AWSMobileClient.getInstance().federatedSignIn(
                            IdentityProvider.DEVELOPER.toString(), 
                            session?.idToken?.jwtToken,
                            ResultCallback<UserStateDetails>().apply {
                                result {
                                    it.details.forEach {
                                        Timber.d("key:${it.key}, value:${it.value}")
                                    }
                                }

                                error { error ->
                                    Bugsnag.addToTab("federated", preferenceStore.identityProvider, session?.idToken?.jwtToken ?: "")
                                    Bugsnag.notify(error)
                                    Timber.d(error)
                                }
                            })
                    }
                }
```
The exception will be thrown, but an EXTERNAL_PROVIDER acount user will be created in user pool as well.

```
2020-02-23 14:05:22.384 419-592/com.giant.hpb.debug D/OnbordingActivity$FederatedHandler$onSuccess$$inlined$let$lambda: java.lang.RuntimeException: Error in federating the token.
        at com.amazonaws.mobile.client.AWSMobileClient$10.run(AWSMobileClient.java:1650)
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: com.amazonaws.services.cognitoidentity.model.NotAuthorizedException: Invalid login token. Issuer doesn't match providerName (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: NotAuthorizedException; Request ID: bd40c7cc-fd66-4ca1-ba7f-0248dcf7bd1b)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:730)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:405)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
        at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:1728)
        at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getId(AmazonCognitoIdentityClient.java:809)
        at com.amazonaws.auth.AWSAbstractCognitoIdentityProvider.getIdentityId(AWSAbstractCognitoIdentityProvider.java:172)
        at com.amazonaws.auth.CognitoCredentialsProvider.getIdentityId(CognitoCredentialsProvider.java:423)
        at com.amazonaws.auth.CognitoCachingCredentialsProvider.getIdentityId(CognitoCachingCredentialsProvider.java:460)
        at com.amazonaws.auth.CognitoCredentialsProvider.retryGetCredentialsForIdentity(CognitoCredentialsProvider.java:753)
        at com.amazonaws.auth.CognitoCredentialsProvider.populateCredentialsWithCognito(CognitoCredentialsProvider.java:787)
        at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:695)
        at com.amazonaws.auth.CognitoCredentialsProvider.refresh(CognitoCredentialsProvider.java:632)
        at com.amazonaws.auth.CognitoCachingCredentialsProvider.refresh(CognitoCachingCredentialsProvider.java:510)
        at com.amazonaws.auth.CognitoCachingCredentialsProvider.getIdentityId(CognitoCachingCredentialsProvider.java:452)
        at com.amazonaws.auth.CognitoCredentialsProvider.populateCredentialsWithCognito(CognitoCredentialsProvider.java:777)
        at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:695)
        at com.amazonaws.auth.CognitoCredentialsProvider.refresh(CognitoCredentialsProvider.java:632)
        at com.amazonaws.auth.CognitoCachingCredentialsProvider.refresh(CognitoCachingCredentialsProvider.java:510)
        at com.amazonaws.mobile.client.AWSMobileClient.federateWithCognitoIdentity(AWSMobileClient.java:1681)
        at com.amazonaws.mobile.client.AWSMobileClient$10.run(AWSMobileClient.java:1637)
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101) 
        at java.lang.Thread.run(Thread.java:764) 

```

The identities in user pool and the issuer is null.
```
[{"userId":"107583087937907297421","providerName":"Google","providerType":"Google","issuer":null,"primary":true,"dateCreated":1582190709343}]
```

**Which AWS Services are you utilizing?**
AWS Cognito 
**Provide code snippets (if applicable)**

I also tried to use lower-level implementation, but this time will tell  'Invalid Access Token'

```
 launch {
                withContext(Dispatchers.IO) {
                    val credentialsProvider = CognitoCachingCredentialsProvider(
                        applicationContext,
                        AWSConfiguration(applicationContext, R.raw.awsconfiguration)
                    )
                    val loginMap = mapOf("ap-northeast-1:995ab855-a99c-47ee-9255-9454eb71e60b" to session?.idToken?.jwtToken)
                    credentialsProvider.setPersistenceEnabled(true)
                    credentialsProvider.logins = loginMap

                    val pool = CognitoUserPool(
                        applicationContext,
                        AWSConfiguration(applicationContext, R.raw.awsconfiguration))

                    val clientConfig = ClientConfiguration()
                    val client = AmazonCognitoIdentityProviderClient(AnonymousAWSCredentials(), clientConfig)
                    val cognitoUser = FederatedUser(pool, "Google_103624813389736260433", pool.clientId, "", null, client, applicationContext);

                    Timber.d("User clint id ${pool.clientId},user id ${pool.user.userId}}")
                    cognitoUser.getSessionInBackground(object : AuthenticationHandler {
                        override fun onSuccess(
                            userSession: CognitoUserSession?,
                            newDevice: CognitoDevice?
                        ) {
                            Timber.d("Id token from session: ${userSession?.idToken?.jwtToken}")
                            Timber.d("Access token from session: ${userSession?.accessToken?.jwtToken}")
                            Timber.d("Refresh token from session: ${userSession?.refreshToken?.token}")

                            Timber.d("User ${session?.username} sign in: ${AWSMobileClient.getInstance().isSignedIn}")
                            Timber.d("User ${session?.username} sign in: ${AWSMobileClient.getInstance().currentUserState().userState.name}")

                            cognitoUser.getDetails(object : GetDetailsHandler {
                                override fun onSuccess(cognitoUserDetails: CognitoUserDetails?) {
                                    cognitoUserDetails?.attributes?.attributes?.entries?.forEach {
                                        Timber.d("key:${it.key}, value:${it.value}")
                                    }
                                }

                                override fun onFailure(exception: Exception?) {
                                    Timber.d(exception)
                                }
                            })
                        }

                        override fun onFailure(exception: Exception?) {
                            Timber.d("Error in cognito get session error $exception")
                        }

                        override fun getAuthenticationDetails(
                            authenticationContinuation: AuthenticationContinuation?,
                            userId: String?
                        ) {

                        }

                        override fun authenticationChallenge(continuation: ChallengeContinuation?) {

                        }

                        override fun getMFACode(continuation: MultiFactorAuthenticationContinuation?) {

                        }
                    })
                }
            }


```

And the results is the same. And now it tells the access token is invalid to get user's attributes,
outputs:
```
-vEafU3yUnjgRo-BpXWmZLgyxezjUUkXNllj_KsUJ9g90-j6vb6zEhVXPfKZqgMh36Am0NCc6tU-fSa6TePBYh-sQoMJqEfRWBt-sov-LaEF79Y9tTDWpYYW_FB4naMixtuQbhDvBRrNQvnl6dmjnMZ4T2gPwceIRJ8D2Gc4rptJQCF2cGqtiETLgETv2FyOAQP_m-HrvNpy8MoH7zbJQjsv5wVlmxXP-SYKJGgqmQC6ZiyxREsTtcakR-Z4U7yoHDIWTFm5LyWDc.HgRn30UEQjkKlIvVY9CcYA

---------------------token got via constructing a Cognito user manually, that is getSessionInBackground

2020-02-23 15:42:53.549 5039-5039/com.giant.hpb.debug D/AWSMobileClient: Inspecting user state details
2020-02-23 15:42:53.549 5039-5039/com.giant.hpb.debug D/OnbordingActivity$FederatedHandler$onSuccess: User Google_103624813389736260433 sign in: false
2020-02-23 15:42:53.570 5039-5039/com.giant.hpb.debug D/AWSMobileClient: Inspecting user state details
2020-02-23 15:42:53.571 5039-5039/com.giant.hpb.debug D/OnbordingActivity$FederatedHandler$onSuccess: User Google_103624813389736260433 sign in: SIGNED_OUT
2020-02-23 15:42:55.240 5039-5130/com.giant.hpb.debug W/OkHttpClient: A connection to https://sessions.bugsnag.com/ was leaked. Did you forget to close a response body?
2020-02-23 15:42:55.245 5039-5039/com.giant.hpb.debug D/OnbordingActivity$FederatedHandler$onSuccess$2$1$1$onSuccess: com.amazonaws.services.cognitoidentityprovider.model.NotAuthorizedException: Invalid Access Token (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: NotAuthorizedException; Request ID: cc9ccb4a-7b14-4a23-91eb-186ec8598c88)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:730)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:405)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
        at com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.invoke(AmazonCognitoIdentityProviderClient.java:6319)
        at com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.getUser(AmazonCognitoIdentityProviderClient.java:4045)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getUserDetailsInternal(CognitoUser.java:1166)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.access$700(CognitoUser.java:132)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser$10.run(CognitoUser.java:1112)
        at java.lang.Thread.run(Thread.java:764)
```

The SDK doc says:
```
1) Read the tokens (Id, Access and Refresh) that are cached on the device.
     *      1.1) If the Id and Access tokens are present and they are valid, the
     *          {@link AuthenticationHandler#onSuccess(CognitoUserSession, CognitoDevice)}.
     *          will be called with a {@link CognitoUserSession} that has references to the valid tokens.
     *          This means that the user is **signed-in**.
     *      1.2) If the Id and Access tokens are expired, and if there is a valid refresh token,
     *          a network call is made to get new Id and Access tokens.
     *          If valid Id and Access tokens are retrieved, they are cached on the device
     *          and {@link AuthenticationHandler#onSuccess(CognitoUserSession, CognitoDevice)}
     *          will be called with a {@link CognitoUserSession} that has references to the valid
     *          tokens. This means that the user is **signed-in**.
```
The user is NOT in signed-in if they come from third-party identity provider, even they get recognized by the Cognito identity pool.

**Environment(please complete the following information):**
 - SDK Version: 2.16.8

**Comment by bryannevega** [comment]
If you're logging in with google, shouldn't you do:

logins.put("accounts.google.com", token); ?

**Comment by scdplzop** [comment]
Sorry for the late response, try to update some information:

The snippet above mostly uses the samples from [AmazonCognitoAuthDemo](https://github.com/awslabs/aws-sdk-android-samples/tree/master/AmazonCognitoAuthDemo).

After getting advice from AWS support center,  we follow the doc on the official Amplify and re-implement again.

The result is better than the first time.

Both platform we use AWSMobileClient.showSignIn method, the above exception no longer exists. So I will close this issue. However, again Android side faces some issue but iOS side doesn't after social Idp users logged in. Maybe I'll create another issue
