### ISSUE TITLE
Logged out after changing permission

### ISSUE THREAD

**Issue by Nikooos** [aws-amplify/aws-sdk-android#1507]
**Describe the bug**
After changing permission on app level, like cancelling the location permission, the keystore isn't accessible. This causes the app to log out and sometimes I can't even log in anymore. 

**To Reproduce**
- Log in
- Close app or bring to background
- Go to 'settings' -> 'Apps and notifications' -> [my app] -> change permission
- Go back to the app
- See that you're logged out and find error message in logcat. (see output below)

**Expected behavior**
Not being logged out after changing permission.

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.16.7
 - Device: multiple
 - Android Version: multiple
 - Specific to simulators: No

**Additional context**
logs
```
2020-03-05 09:29:00.935 30861-31015/com.myapp.android.acc.debug E/KeyStore: GetKeyCharacteristics completed with exception
    java.lang.InterruptedException
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:351)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1923)
        at android.security.KeyStore.getKeyCharacteristics(KeyStore.java:630)
        at android.security.keystore.AndroidKeyStoreProvider.getKeyCharacteristics(AndroidKeyStoreProvider.java:233)
        at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyFromKeystore(AndroidKeyStoreProvider.java:364)
        at android.security.keystore.AndroidKeyStoreSpi.engineGetKey(AndroidKeyStoreSpi.java:105)
        at java.security.KeyStore.getKey(KeyStore.java:1062)
        at com.amazonaws.internal.keyvaluestore.KeyProvider23.retrieveKey(KeyProvider23.java:58)
        at com.amazonaws.internal.keyvaluestore.AWSKeyValueStore.retrieveEncryptionKey(AWSKeyValueStore.java:483)
        at com.amazonaws.internal.keyvaluestore.AWSKeyValueStore.get(AWSKeyValueStore.java:226)
        at com.amazonaws.mobile.client.AWSMobileClientStore.get(AWSMobileClient.java:3428)
        at com.amazonaws.mobile.client.AWSMobileClient.getSignInDetailsMap(AWSMobileClient.java:937)
        at com.amazonaws.mobile.client.AWSMobileClient$11.run(AWSMobileClient.java:1725)
        at com.amazonaws.mobile.client.internal.InternalCallback.await(InternalCallback.java:115)
        at com.amazonaws.mobile.client.AWSMobileClient.getTokens(AWSMobileClient.java:1699)
        at com.myapp.android.domains.identity.service.IdentityService.requestAccessToken(IdentityService.kt:222)
```
```
2020-03-05 09:29:00.935 30861-31015/com.myapp.android.acc.debug E/AWSKeyValueStore: com.amazonaws.internal.keyvaluestore.KeyNotFoundException: Error occurred while accessing AndroidKeyStore to retrieve the key for keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias
2020-03-05 09:29:00.936 30861-31015/com.myapp.android.acc.debug I/AWSKeyValueStore: Deleting the encryption key identified by the keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias
2020-03-05 09:29:00.936 1012-1012/? I/keystore: del USRPKEY_com.amazonaws.mobile.client.aesKeyStoreAlias 10260
2020-03-05 09:29:00.937 1012-1012/? I/keystore: del USRCERT_com.amazonaws.mobile.client.aesKeyStoreAlias 10260
2020-03-05 09:29:00.937 1012-1012/? I/keystore: del CACERT_com.amazonaws.mobile.client.aesKeyStoreAlias 10260
```

**Comment by mathijsvds** [comment]
I'm encountering the same problem, can we get some feedback on this?

**Comment by patrickkempff** [comment]
This is a frustrating issue, because changing permissions can change really easily, it seems all pixel devices with Android 10 are affected. Are there any known workarounds?

**Comment by AdrianLxM** [comment]
I do have the exact same issue/stacktrace on a Nokia 7.2 (Android 10) even without changing permissions.

**Comment by birsi** [comment]
Any update on this? Thank you!

**Comment by jpignata** [comment]
Thanks, all. No updates yet, but it's on our triage list for this week. We'll post our analysis when we have it.

**Comment by desokroshan** [comment]
Quick update - I was trying to ascertain if the issue happens in Android 10 or if it device specific. I followed the OP's repro steps on android studio emulators and an acer device both running Android 10. I was not logged out after changing app permission in the settings.
I think this issue is specific to the devices mentioned above (Google pixel and Nokia 7.2) running Android 10. I will try to run it on the one of the above devices and post an update.

**Comment by adrian-hidothealth** [comment]
Is there an update? Thanks.

**Comment by birsi** [comment]
Hi there! Could we please get an update on this. Thanks a lot!

**Comment by patrickkempff** [comment]
@jpignata how did the triage work out last month? any updates?

**Comment by jpignata** [comment]
Hey all - we're still working on a reproduction case but so far @desokroshan has had no luck. He will provide an update. Thanks for your patience!

**Comment by patrickkempff** [comment]
When is this update expected? This is a real issue. We are using the AWSMobileClient with no customisation or fancy configuration and this issue is quite frustrating, the lack of communication does not really motivate working with AWS services. 

If there is a lack in information to reproduce this issue please let us know but please don't just ignore it because it less straight forward.

**Comment by jpignata** [comment]
Thanks for the nudge, @patrickkempff. Thus far we've been unable to reproduce.  Please feel free to give us more information, and we'd encourage users experiencing this to +1 the issue so we can properly prioritize it.

**Comment by marcosalis** [comment]
This could be related:
https://issuetracker.google.com/issues/147384380

**Comment by TrekSoft** [comment]
Very interesting - thanks for that

**Comment by rjuliano** [comment]
The [Android issue](https://issuetracker.google.com/issues/147384380) potentially causing this has been fixed in the OS. Let us know if this problem still exists.

**Comment by AdrianLxM** [comment]
> The [Android issue](https://issuetracker.google.com/issues/147384380) potentially causing this has been fixed in the OS. Let us know if this problem still exists.

If it is fixed in the OS - wouldn't that mean that mean that it would still happen until all customers update their phones?
Wouldn't it still be better to properly handle the exception?

**Comment by raphkim** [comment]
Hi @AdrianLxM ,

You bring up a good point. We will add a more permanent fix to this issue to our backlog, but it will likely not be prioritized since a fix is readily available via an OS update. If there is still a considerable number of reports from customer experiencing this issue, then we will adjust its priority accordingly.
