### ISSUE TITLE
Getting Error "Unable to store object contents to disk:" when downloading objects from S3 bucket to internal storage

### ISSUE THREAD

**Issue by abhidaa1233** [aws-amplify/aws-sdk-android#1513]
**Describe the bug**
I'm getting an error while trying to download all objects in my Amazon S3 bucket to Android 's internal storage.

I'm getting the following error:

```
W/System.err: com.amazonaws.AmazonClientException: Unable to store object contents to disk: /data/user/0/com.example.myawsapp/files/appData/public/S2/test_folder (Is a directory)
2020-03-13 20:00:02.771 11683-11683/com.example.myawsapp W/System.err:     at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.saveToFile(DownloadTask.java:198)
2020-03-13 20:00:02.771 11683-11683/com.example.myawsapp W/System.err:     at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.call(DownloadTask.java:111)
2020-03-13 20:00:02.771 11683-11683/com.example.myawsapp W/System.err:     at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.call(DownloadTask.java:42)
2020-03-13 20:00:02.772 11683-11683/com.example.myawsapp W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-03-13 20:00:02.772 11683-11683/com.example.myawsapp W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
2020-03-13 20:00:02.772 11683-11683/com.example.myawsapp W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
2020-03-13 20:00:02.772 11683-11683/com.example.myawsapp W/System.err:     at java.lang.Thread.run(Thread.java:764)
2020-03-13 20:00:02.773 11683-11683/com.example.myawsapp W/System.err: Caused by: java.io.FileNotFoundException: /data/user/0/com.example.myawsapp/files/appData/public/S2/test_folder (Is a directory)
2020-03-13 20:00:02.773 11683-11683/com.example.myawsapp W/System.err:     at java.io.FileOutputStream.open0(Native Method)
2020-03-13 20:00:02.773 11683-11683/com.example.myawsapp W/System.err:     at java.io.FileOutputStream.open(FileOutputStream.java:287)
2020-03-13 20:00:02.773 11683-11683/com.example.myawsapp W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:223)
2020-03-13 20:00:02.774 11683-11683/com.example.myawsapp W/System.err:     at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.saveToFile(DownloadTask.java:186)
2020-03-13 20:00:02.774 11683-11683/com.example.myawsapp W/System.err: 	... 6 more
```

To create a `File` I have used:
```
File file = new File(getApplicationContext().getFilesDir() + "/appData/" , key);
```

**Comment by jamesonwilliams** [comment]
Hi @abhidaa1233, thanks for the report.

The root cause of this error is found in the second portion of the stack trace:
```
Caused by: java.io.FileNotFoundException: /data/user/0/com.example.myawsapp/files/appData/public/S2/test_folder (Is a directory)
```

You are using the [`File(File, String)`](https://developer.android.com/reference/java/io/File#File(java.io.File,%20java.lang.String)) constructor, but supply a path as the second argument.

So, I guess you've provided `public/S2/test_folder` as the `key` value? But the path apparently doesn't exist.

You can probably fix this by simply doing:
```
file.mkdirs();
```

Feel free to re-open if you have further questions.

**Comment by abhidaa1233** [comment]
Thankx Jameson, that was a bit dumb from me, overlooked it.
