### ISSUE TITLE
Failed to perform store operation

### ISSUE THREAD

**Issue by sandipgh19** [aws-amplify/aws-sdk-android#1689]
**Describe the bug**
When store the data into local cache through appSyncClient,  sometimes I got the ```android.database.sqlite.SQLiteBlobTooBigException```

**To Reproduce**
It's happens rarely. When I saved the data into local Cache.

```
try {
    mAWSAppSyncClient.getStore().write(profileQuery, data).execute();
} catch (ApolloException e) {}
```

I have faced the following exception:

```02:59:57.351 E/AWSRepository(24976): com.apollographql.apollo.exception.ApolloException: Failed to perform store operation
02:59:57.351 E/AWSRepository(24976): 	at com.apollographql.apollo.cache.normalized.GraphQLStoreOperation.execute(GraphQLStoreOperation.java:67)
02:59:57.351 E/AWSRepository(24976): 	at com.example.AWSRepository$15.onResponse(AWSRepository.java:857)
02:59:57.351 E/AWSRepository(24976): 	at com.apollographql.apollo.internal.RealAppSyncCall$1.onResponse(RealAppSyncCall.java:268)
02:59:57.351 E/AWSRepository(24976): 	at com.apollographql.apollo.internal.fetcher.CacheOnlyFetcher$CacheOnlyInterceptor$1.onFailure(CacheOnlyFetcher.java:47)
02:59:57.351 E/AWSRepository(24976): 	at com.apollographql.apollo.internal.interceptor.ApolloCacheInterceptor$1.run(ApolloCacheInterceptor.java:72)
02:59:57.351 E/AWSRepository(24976): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
02:59:57.351 E/AWSRepository(24976): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
02:59:57.351 E/AWSRepository(24976): 	at java.lang.Thread.run(Thread.java:764)
02:59:57.351 E/AWSRepository(24976): Caused by: android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=0, totalRows=1
02:59:57.351 E/AWSRepository(24976): 	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
02:59:57.351 E/AWSRepository(24976): 	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:859)
02:59:57.351 E/AWSRepository(24976): 	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
02:59:57.351 E/AWSRepository(24976): 	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
02:59:57.351 E/AWSRepository(24976): 	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:149)
02:59:57.351 E/AWSRepository(24976): 	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:137)
02:59:57.351 E/AWSRepository(24976): 	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:220)
02:59:57.351 E/AWSRepository(24976): 	at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:259)
02:59:57.351 E/AWSRepository(24976): 	at com.apollographql.apollo.cache.normalized.sql.SqlNormalizedCache.selectRecordForKey(SqlNormalizedCache.java:208)
02:59:57.351 E/AWSRepository(24976): 	at com.apollographql.apollo.cache.normalized.sql.SqlNormalizedCache.merge(SqlNormalizedCache.java:108)
02:59:57.351 E/AWSRepository(24976): 	at com.apollographql.apollo.cache.normalized.OptimisticNormalizedCache$3.apply(OptimisticNormalizedCache.java:68)
02:59:57.351 E/AWSRepository(24976): 	at com.apollographql.apollo.cache.normalized.OptimisticNormalizedCache$3.apply(OptimisticNormalizedCache.java:66)
02:59:57.351 E/AWSRepository(24976): 	at com.apollographql.apollo.api.internal.Present.map(Present.java:70)
02:59:57.351 E/AWSRepository(24976): 	at com.apollographql.apollo.cache.normalized.OptimisticNormalizedCache.merge(OptimisticNormalizedCache.java:66)
02:59:57.351 E/AWSRepository(24976): 	at com.apollographql.apollo.cache.normalized.NormalizedCache.merge(NormalizedCache.java:88)
02:59:57.351 E/AWSRepository(24976): 	at com.apollographql.apollo.internal.cache.normalized.RealAppSyncStore$20.execute(RealAppSyncStore.java:436)
02:59:57.351 E/AWSRepository(24976): 	at com.apollographql.apollo.internal.cache.normalized.RealAppSyncStore$20.execute(RealAppSyncStore.java:421)
02:59:57.351 E/AWSRepository(24976): 	at com.apollographql.apollo.internal.cache.normalized.RealAppSyncStore.writeTransaction(RealAppSyncStore.java:178)
02:59:57.351 E/AWSRepository(24976): 	at com.apollographql.apollo.internal.cache.normalized.RealAppSyncStore.doWrite(RealAppSyncStore.java:421)
02:59:57.351 E/AWSRepository(24976): 	at com.apollographql.apollo.internal.cache.normalized.RealAppSyncStore.access$600(RealAppSyncStore.java:46)
02:59:57.351 E/AWSRepository(24976): 	at com.apollographql.apollo.internal.cache.normalized.RealAppSyncStore$9.perform(RealAppSyncStore.java:250)
02:59:57.351 E/AWSRepository(24976): 	at com.apollographql.apollo.internal.cache.normalized.RealAppSyncStore$9.perform(RealAppSyncStore.java:248)
02:59:57.351 E/AWSRepository(24976): 	at com.apollographql.apollo.cache.normalized.GraphQLStoreOperation.execute(GraphQLStoreOperation.java:65)
02:59:57.351 E/AWSRepository(24976): 	... 7 more
```

**Which AWS service(s) are affected?**
AWSAppSyncClient

**Expected behavior**
Saved the data into local cache.

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.10.1
 - Specific to simulators: NO

**Additional context**

**Comment by jpignata** [comment]
Heya @sandipgh19 -- are you using the [AppSync SDK](https://github.com/awslabs/aws-mobile-appsync-sdk-android)? You should open your issue in that repo if so.
