### ISSUE TITLE
AWS Cognito user: Device confirmation failed

### ISSUE THREAD

**Issue by alexei-frolo** [aws-amplify/aws-sdk-android#1690]
**Describe the bug**
I am not able to properly sign in using `CognitoUser` object after the refresh
token gets expired. In the logs, I am getting the following exception
stacktrace: 

```console
Device confirmation failed: 
com.amazonaws.mobileconnectors.cognitoidentityprovider.exceptions.CognitoNotAuthorizedException: User is not authenticated
    at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getCachedSession(CognitoUser.java:981)
    at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.confirmDevice(CognitoUser.java:3287)
    at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.handleChallenge(CognitoUser.java:2607)
    at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.respondToChallenge(CognitoUser.java:2409)
    at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser$24.run(CognitoUser.java:2480)
    at com.amazonaws.mobileconnectors.cognitoidentityprovider.continuations.AuthenticationContinuation.continueTask(AuthenticationContinuation.java:124)
    at com.amazonaws.mobile.client.AWSMobileClient$6$1.getAuthenticationDetails(AWSMobileClient.java:1177)
    at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getSession(CognitoUser.java:778)
    at com.amazonaws.mobile.client.AWSMobileClient$6.run(AWSMobileClient.java:1137)
    at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
    at java.lang.Thread.run(Thread.java:764)
 Caused by: com.amazonaws.services.cognitoidentityprovider.model.NotAuthorizedException: Invalid Refresh Token. (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: NotAuthorizedException; Request ID: ed2f2501-7a36-447f-ac29-c4ab4741958e)
    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:730)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:405)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
    at com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.invoke(AmazonCognitoIdentityProviderClient.java:6292)
    at com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.initiateAuth(AmazonCognitoIdentityProviderClient.java:4277)
    at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.refreshSession(CognitoUser.java:2378)
    at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getCachedSession(CognitoUser.java:976)
    at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.confirmDevice(CognitoUser.java:3287) 
    at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.handleChallenge(CognitoUser.java:2607) 
    at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.respondToChallenge(CognitoUser.java:2409) 
    at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser$24.run(CognitoUser.java:2480) 
    at com.amazonaws.mobileconnectors.cognitoidentityprovider.continuations.AuthenticationContinuation.continueTask(AuthenticationContinuation.java:124) 
    at com.amazonaws.mobile.client.AWSMobileClient$6$1.getAuthenticationDetails(AWSMobileClient.java:1177) 
    at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getSession(CognitoUser.java:778) 
    at com.amazonaws.mobile.client.AWSMobileClient$6.run(AWSMobileClient.java:1137) 
    at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101) 
    at java.lang.Thread.run(Thread.java:764)
```

I know it's related to the "remember user's device" option in the AWS console.
Actually, this option is enabled.

Then I dug into the source code and debugged step by step the sign in flow.
Turned out, on the very first sign-in (after I uninstalled and installed the
app again) I am not getting any CognitoDevice info in the
`AuthenticationHandler`'s onSuccess callback method (see `newDevice` param in
the code below):

```kotlin
val userPool = getUserPool()
userPool.currentUser.signOut()
userPool
    .getUser(login)
    .getSession(LoginHandler(password,
        {
            semaphore.release()
        },
        {
            semaphore.release()
        })
    )
semaphore.acquire()

...

private class LoginHandler(
        val password: String,
        val onSuccess: () -> Unit,
        val onError: () -> Unit): AuthenticationHandler {

    override fun onSuccess(userSession: CognitoUserSession?, newDevice: CognitoDevice?) {
        // newDevice is always null
        onSuccess()
    }

    override fun onFailure(exception: Exception?) {
        onError()
    }

    override fun getAuthenticationDetails(authenticationContinuation: AuthenticationContinuation?, userId: String?) {
        with(AuthenticationDetails(userId, password, null))
        {
            authenticationType = CognitoServiceConstants.CHLG_TYPE_USER_PASSWORD

            authenticationContinuation?.setAuthenticationDetails(this)
            authenticationContinuation?.continueTask()
        }
    }

    override fun authenticationChallenge(continuation: ChallengeContinuation?) {
        continuation?.continueTask()
    }

    override fun getMFACode(continuation: MultiFactorAuthenticationContinuation?) {
        continuation?.continueTask()
    }
}
```

Hence, the device info including the device key is not cached. So that when I
try to sign in again after the refresh token is expired the library tries to
get the cached device key (which is always null) and then it fails the sign-in
request with the exception mentioned above.

**Expected behavior**
I am expecting that the device key is retrieved and cached properly so I always
can sign in with no exception.

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.15.0
 - Device: Xiaomi Redmi S2
 - Android Version: 8.1

**Comment by mangeshsambare** [comment]
I have same issues on following environment:

**Environment Information (please complete the following information):**

- AWS Android SDK Version: 2.19.0

- Device: Samsung Galaxy A50

- Android Version: 10

Any updates on this?

**Comment by gpanshu** [comment]
Its been a while since this issue was opened. Can you please confirm that this still happens on the latest SDK before we do a deep dive to find a solution?
