### ISSUE TITLE
URGENT E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #3

### ISSUE THREAD

**Issue by belaldaboul** [aws-amplify/aws-sdk-android#1699]
**crash at runtime on payfort lib when I import amplify / proguard enabled**

**logcat:**
```
java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:353)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: **java.lang.VerifyError: Verifier rejected class com.payfort.sdk.android.dependancies.security.aes.AESCipher: java.lang.String com.payfort.sdk.android.dependancies.security.aes.AESCipher.getDecryptedMessage(java.lang.String) failed to verify: java.lang.String com.payfort.sdk.android.dependancies.security.aes.AESCipher.getDecryptedMessage(java.lang.String)**: [0x10] 'this' argument 'Precise Reference: org.apache.commons.codec.binary.Base64' not instance of 'Reference: org.apache.commons.codec.binary.BaseNCodec' (declaration of 'com.payfort.sdk.android.dependancies.security.aes.AESCipher' appears in /data/app/-xLeTPVH9ZKVCDB3vLbGFbg==/base.apk!classes3.dex)
        at com.payfort.sdk.android.dependancies.security.aes.AESCipherManager.encryptData(AESCipherManager.java:22)
        at com.payfort.sdk.android.dependancies.security.DataSecurityService.encryptRequestData(DataSecurityService.java:57)
        at com.payfort.fort.android.sdk.activities.InitSecureConnectionActivity$Handshake.doInBackground(InitSecureConnectionActivity.java:138)
        at com.payfort.fort.android.sdk.activities.InitSecureConnectionActivity$Handshake.doInBackground(InitSecureConnectionActivity.java:105)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
```

**Comment by jamesonwilliams** [comment]
Hi @belaldaboul. Please provide a bit of context about how this error gets triggered. Any sample code to replicate the issue would be appreciated. As of right now, it is not actionable.
