### ISSUE TITLE
Invalid refresh token after MFA challenge success

### ISSUE THREAD

**Issue by ThatJimInAicure** [aws-amplify/aws-sdk-android#1714]
**Describe the bug**
We have a Cognito user pool set up as MFA required and have the remember device set up as always. But the device is not remembered, every time the device will be recorded as a new device remembered on user pool. 

After a little bit further looking into the SDK, I found that:
once MFA challenge is completed, in [`CognitoUser`](https://github.com/aws-amplify/aws-sdk-android/blob/master/aws-android-sdk-cognitoidentityprovider/src/main/java/com/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser.java#L123-L132) class, [line 3287](https://github.com/aws-amplify/aws-sdk-android/blob/master/aws-android-sdk-cognitoidentityprovider/src/main/java/com/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser.java#L3287), it is trying to cache the `deviceKey` by using the `cachedSession`. When fetching the cached session, it is refreshing the session regardless of if it is expired or not, and the refresh call returns the message saying the refresh token is not valid, and therefore, `CognitoNotAuthorizedException("User is not authenticated", nae)` is thrown, and at the same time, all the cached token get removed. The interesting thing is, even the refreshing session failed, the `AuthenticationHandler`'s on `success(...)` is get called with valid tokens.

**To Reproduce**
A code sample or steps:

    public static void SignIn(Context context, String username, String password, SSOSigninHandler signinHandler) {
        CognitoUserPool userPoolSSO;
        userPoolSSO = new CognitoUserPool(context, "XXXXXXX", "XXXXXXXX", null, Regions.US_WEST_2);
        userSSO = userPoolSSO.getUser(username);
        userSSO.getSessionInBackground(new AuthenticationHandler() {
            @Override
            public void onSuccess(CognitoUserSession userSession, CognitoDevice newDevice) {
                signinHandler.onSigninSuccess(userSession.getIdToken().getJWTToken(), userSession.getAccessToken().getJWTToken());
            }

            @Override
            public void getAuthenticationDetails(AuthenticationContinuation authenticationContinuation, String userId) {
                // The API needs user sign-in credentials to continue
                AuthenticationDetails authenticationDetails = new AuthenticationDetails(userId, password, null);

                // Pass the user sign-in credentials to the continuation
                authenticationContinuation.setAuthenticationDetails(authenticationDetails);

                // Allow the sign-in to continue
                authenticationContinuation.continueTask();
            }

            @Override
            public void getMFACode(MultiFactorAuthenticationContinuation continuation) {
                // Multi-factor authentication is required; get the verification code from user
                String phone_number = continuation.getParameters().getDestination();

                signinHandler.onMFAVerification(phone_number);
                MFAContinuation = continuation;
            }

            @Override
            public void authenticationChallenge(ChallengeContinuation continuation) {

            }

            @Override
            public void onFailure(Exception exception) {
                Logger.e(exception.getMessage());
                signinHandler.onSigninFailure(exception);
            }
        });
    }

    public static void continueMFAWithMFAMessage(String MFAMessage){
        MFAContinuation.setMfaCode(MFAMessage);
        MFAContinuation.continueTask();
    }

**Which AWS service(s) are affected?**
aws andoid sdk / Cognito user pool

**Expected behavior**
The refresh call should make it through, and the device keys get cached on device.

**Screenshots**
error log below:
```
2020-05-09 01:38:51.468 24947-25425/com.aicure.aiview.clinical.master.mobile E/CognitoUser: Device confirmation failed:
    com.amazonaws.mobileconnectors.cognitoidentityprovider.exceptions.CognitoNotAuthorizedException: User is not authenticated
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getCachedSession(CognitoUser.java:981)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.confirmDevice(CognitoUser.java:3287)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.handleChallenge(CognitoUser.java:2607)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.respondToChallenge(CognitoUser.java:2409)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.respondToMfaChallenge(CognitoUser.java:946)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.continuations.MultiFactorAuthenticationContinuation$1.run(MultiFactorAuthenticationContinuation.java:107)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: com.amazonaws.services.cognitoidentityprovider.model.NotAuthorizedException: Invalid Refresh Token. (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: NotAuthorizedException; Request ID: ede7b09e-af8b-4c86-95a8-0b160752fafa)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:730)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:405)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
        at com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.invoke(AmazonCognitoIdentityProviderClient.java:6319)
        at com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.initiateAuth(AmazonCognitoIdentityProviderClient.java:4283)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.refreshSession(CognitoUser.java:2378)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getCachedSession(CognitoUser.java:976)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.confirmDevice(CognitoUser.java:3287) 
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.handleChallenge(CognitoUser.java:2607) 
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.respondToChallenge(CognitoUser.java:2409) 
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.respondToMfaChallenge(CognitoUser.java:946) 
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.continuations.MultiFactorAuthenticationContinuation$1.run(MultiFactorAuthenticationContinuation.java:107) 
        at java.lang.Thread.run(Thread.java:764)
```

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.16.8
 - Device:  GALAXY S6
 - Android Version: Android 7.0
 - Specific to simulators: No

**Additional context**
This happens sporadically, and it is blocking the flow of our production environment.

**Comment by ThatJimInAicure** [comment]
Updated: Target user pool id is: us-west-2_WMdSaoPwD

**Comment by desokroshan** [comment]
@ThatJimInAicure Thanks for reaching out. I feel what you are seeing is expected behavior. Following are my observation : 

1. You are right, it does use cached session to confirm the device but it does not always refresh the session. It first [tries to use the current session](https://github.com/aws-amplify/aws-sdk-android/blob/master/aws-android-sdk-cognitoidentityprovider/src/main/java/com/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser.java#L961) and if the current session is not valid it tries to read from [cached token from device](https://github.com/aws-amplify/aws-sdk-android/blob/master/aws-android-sdk-cognitoidentityprovider/src/main/java/com/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser.java#L967). It refreshes the token only if none of the cached tokens are valid.

1. The refresh will succeed only if refresh token is valid. If the refresh token has expired you will get [`CognitoNotAuthorizedException`](https://github.com/aws-amplify/aws-sdk-android/blob/master/aws-android-sdk-cognitoidentityprovider/src/main/java/com/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser.java#L989) as you have noted above. This is the behavior by design and I feel this is the case for you since you see this sporadically. Are you able to confirm that you have valid refresh token when you see this exception?

> But the device is not remembered, every time the device will be recorded as a new device remembered on user pool.

How did you go about verifying this? For me, in trying to reproduce this I disabled subsequent MFA on a remembered device after the first sign-in as in the screenshot below and it seemed to work well for me.
<img width="1127" alt="Screen Shot 2020-05-19 at 10 44 14 AM" src="https://user-images.githubusercontent.com/4340938/82360320-1007bd00-99be-11ea-870a-ef44fb27f485.png">

**Comment by rjuliano** [comment]
Possibly related #1690

**Comment by gpanshu** [comment]
I apologize for the delay in responding to this. 
Please reply back if this is still an issue with the latest versions of the library and we can investigate further.
