### ISSUE TITLE
 Failed to publish a local change = PendingMutation{mutatedItem=

### ISSUE THREAD

**Issue by sunithapremjee** [aws-amplify/aws-sdk-android#1921]
**Describe the bug**
A clear and concise description of what the bug is
Deleted an item from android app and added new item.App front end shows newly added item,but cloud syncing is not happening and AWS dynamo db has still old data.

**Which AWS service(s) are affected?**
AWS appsync, Dynamo DB

**Environment Information 
 - AWS Android SDK Version: 2.15+
 - Device: [Samsung galaxy S10+
 - Android Version: Android 10

W/amplify:aws-datastore: Failed to sync down cloud state for model type = smartwatchdata
    AmplifyException {message=Failure performing sync query to AppSync: [GraphQLResponse.Error{message='Validation error of type FieldUndefined: Field 'syncSmartwatchdatas' in type 'Query' is undefined @ 'syncSmartwatchdatas'', locations='[GraphQLLocation{line='2', column='3'}]', path='null', extensions='null'}], cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}
        at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$sync$0$AppSyncClient(AppSyncClient.java:3)
        at com.amplifyframework.datastore.appsync.-$$Lambda$AppSyncClient$DAlM2A4r8A_52MV-BaSjc1SYWao.accept(Unknown Source:10)
        at com.amplifyframework.api.aws.AppSyncGraphQLOperation$OkHttpCallback.onResponse(AppSyncGraphQLOperation.java:16)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
    Initial cloud sync failed.
    AmplifyException {message=Failure performing sync query to AppSync: [GraphQLResponse.Error{message='Validation error of type FieldUndefined: Field 'syncSmartwatchdatas' in type 'Query' is undefined @ 'syncSmartwatchdatas'', locations='[GraphQLLocation{line='2', column='3'}]', path='null', extensions='null'}], cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}
        at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$sync$0$AppSyncClient(AppSyncClient.java:3)
        at com.amplifyframework.datastore.appsync.-$$Lambda$AppSyncClient$DAlM2A4r8A_52MV-BaSjc1SYWao.accept(Unknown Source:10)
        at com.amplifyframework.api.aws.AppSyncGraphQLOperation$OkHttpCallback.onResponse(AppSyncGraphQLOperation.java:16)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
I/amplify:aws-datastore: Starting processing subscription data buffer.
I/amplify:aws-datastore: Started processing the mutation outbox. Pending mutations will be published to the cloud.
W/amplify:aws-datastore: Failed to publish a local change = PendingMutation{mutatedItem=smartwatchdata {id=cb351616-8f16-4c6c-bd32-2fb1f6f8880f, title=test, description=null, audiopath=https://prodigysmartwatch1f80792be2fc47fba82bae965d2225174703-dev.s3.amazonaws.com/public/public/test, sensitivityvalues=NORMAL, timervalues=fifteen}, classOfMutatedItem=class com.amplifyframework.datastore.generated.model.smartwatchdata, mutationType=DELETE, mutationId=478a7707-b43e-11ea-9593-eb820afec3d1, predicate=null}
    AmplifyException {message=Wanted 1 metadata for item with id = cb351616-8f16-4c6c-bd32-2fb1f6f8880f, but had 0., cause=null, recoverySuggestion=This is likely a bug. please report to AWS.}
        at com.amplifyframework.datastore.syncengine.VersionRepository.extractVersion(VersionRepository.java:25)
        at com.amplifyframework.datastore.syncengine.VersionRepository.lambda$null$0$VersionRepository(VersionRepository.java:1)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$VersionRepository$R5kiVnQCzDy1jTk4Odil1m_dDtM.accept(Unknown Source:8)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$query$4$SQLiteStorageAdapter(SQLiteStorageAdapter.java:42)
        at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$rGner20-W7t2tJu4yCrrZwlquWE.run(Unknown Source:10)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
W/amplify:aws-datastore: Error ended observation of mutation outbox: 
    java.lang.RuntimeException: AmplifyException {message=Wanted 1 metadata for item with id = cb351616-8f16-4c6c-bd32-2fb1f6f8880f, but had 0., cause=null, recoverySuggestion=This is likely a bug. please report to AWS.}
        at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
        at io.reactivex.internal.observers.BlockingMultiObserver.blockingAwait(BlockingMultiObserver.java:185)
        at io.reactivex.Completable.blockingAwait(Completable.java:1256)
        at com.amplifyframework.datastore.syncengine.MutationProcessor.lambda$startDrainingMutationOutbox$1$MutationProcessor(MutationProcessor.java:6)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$MutationProcessor$iu5hAaGgWV8-jjRjPW1wTtFQOwM.apply(Unknown Source:4)
        at io.reactivex.internal.operators.observable.ObservableFlatMapCompletableCompletable$FlatMapCompletableMainObserver.onNext(ObservableFlatMapCompletableCompletable.java:97)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: AmplifyException {message=Wanted 1 metadata for item with id = cb351616-8f16-4c6c-bd32-2fb1f6f8880f, but had 0., cause=null, recoverySuggestion=This is likely a bug. please report to AWS.}
        at com.amplifyframework.datastore.syncengine.VersionRepository.extractVersion(VersionRepository.java:25)
        at com.amplifyframework.datastore.syncengine.VersionRepository.lambda$null$0$VersionRepository(VersionRepository.java:1)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$VersionRepository$R5kiVnQCzDy1jTk4Odil1m_dDtM.accept(Unknown Source:8)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$query$4$SQLiteStorageAdapter(SQLiteStorageAdapter.java:42)
        at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$rGner20-W7t2tJu4yCrrZwlquWE.run(Unknown Source:10)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919)

**Comment by raphkim** [comment]
This seems to be an issue regarding Amplify DataStore. Opened [issue](https://github.com/aws-amplify/amplify-android/issues/602) to track in appropriate repo.
