### ISSUE TITLE
v2.0.5 ExceptionInInitializerError

### ISSUE THREAD

**Issue by niqo01** [aws-amplify/aws-sdk-android#2]
Version 2.0.5
I am having the following exception while creating a new TransferManager.

```
Caused by: java.lang.ExceptionInInitializerError
            at com.amazonaws.ServiceNameFactory.getServiceName(Unknown Source)
            at com.amazonaws.AmazonWebServiceClient.computeServiceName(Unknown Source)
            at com.amazonaws.AmazonWebServiceClient.getServiceNameIntern(Unknown Source)
            at com.amazonaws.AmazonWebServiceClient.computeSignerByURI(Unknown Source)
            at com.amazonaws.AmazonWebServiceClient.setEndpoint(Unknown Source)
            at com.amazonaws.services.s3.AmazonS3Client.setEndpoint(Unknown Source)
            at com.amazonaws.services.s3.AmazonS3Client.init(Unknown Source)
            at com.amazonaws.services.s3.AmazonS3Client.<init>(Unknown Source)
            at com.amazonaws.services.s3.AmazonS3Client.<init>(Unknown Source)
            at com.amazonaws.services.s3.transfer.TransferManager.<init>(Unknown Source)
```

I don't know if its related but there some Dex warning while building the application

```
warning: Ignoring InnerClasses attribute for an anonymous inner class
(org.apache.commons.logging.LogFactory$2) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(org.apache.commons.logging.LogFactory$1) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(org.apache.commons.logging.LogFactory$3) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(org.apache.commons.logging.LogFactory$4) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(org.apache.commons.logging.LogFactory$5) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(org.apache.commons.logging.LogFactory$6) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
```

**Comment by miketrewartha** [comment]
We actually still get this error in a native Android app, even when ProGuard is disabled, using 2.1.7. Have you guys seen any more issues crop up with this?
