### ISSUE TITLE
Cognito: SIGNED_OUT_USER_POOLS_TOKENS_INVALID after a few hours

### ISSUE THREAD

**Issue by RandomEngy** [aws-amplify/aws-sdk-android#2059]
I have a user pool set up with Hosted UI sign in. I can sign in just fine normally but some time less than a day later, calling `AWSMobileClient.currentUserState().userState` returns SIGNED_OUT_USER_POOLS_TOKENS_INVALID . I can see that the access token is valid for one hour. Sometimes the token gets refreshed, but sometimes it does not. I get this exception:

    java.lang.RuntimeException: Cognito Userpools is not signed-in
        at com.amazonaws.mobileconnectors.appsync.sigv4.BasicCognitoUserPoolsAuthProvider.fetchToken(BasicCognitoUserPoolsAuthProvider.java:80)
        at com.amazonaws.mobileconnectors.appsync.sigv4.BasicCognitoUserPoolsAuthProvider.getLatestAuthToken(BasicCognitoUserPoolsAuthProvider.java:86)
        at com.amazonaws.mobileconnectors.appsync.SubscriptionAuthorizer.getAuthorizationDetailsForUserpools(SubscriptionAuthorizer.java:158)
        at com.amazonaws.mobileconnectors.appsync.SubscriptionAuthorizer.getAuthorizationDetails(SubscriptionAuthorizer.java:82)
        at com.amazonaws.mobileconnectors.appsync.SubscriptionAuthorizer.getConnectionAuthorizationDetails(SubscriptionAuthorizer.java:59)
        at com.amazonaws.mobileconnectors.appsync.WebSocketConnectionManager.getConnectionRequestUrl(WebSocketConnectionManager.java:254)
        at com.amazonaws.mobileconnectors.appsync.WebSocketConnectionManager.createWebSocket(WebSocketConnectionManager.java:109)
        at com.amazonaws.mobileconnectors.appsync.WebSocketConnectionManager.requestSubscription(WebSocketConnectionManager.java:78)
        at com.amazonaws.mobileconnectors.appsync.AppSyncWebSocketSubscriptionCall.execute(AppSyncWebSocketSubscriptionCall.java:48)
        at us.engy.focaltodo.services.TodoSyncRepositoryImpl$1.invokeSuspend(TodoSyncRepositoryImpl.kt:60)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)

Oddly, the mobileClient.initialize() callback returns a state of SIGNED_IN. That doesn't make a lot of sense to me.

I am trying to kick start the token refresh by calling AWSMobileClient.getTokens, but it tells me that I cannot get tokens when signed out.

I thought the API should be refreshing the token for me. How can I tell why the token refresh is failing? Is there a way to get out of this state?

**Which AWS service(s) are affected?**
Cognito

**Expected behavior**
AWSMobileClient handles token refresh successfully

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.17.0
 - Device: Pixel XL
 - Android Version: 10
 - Specific to simulators: No

**Comment by RandomEngy** [comment]
@palpatim This issue is still happening: https://github.com/aws-amplify/aws-sdk-android/issues/873 . Also @RafaRuiz @TobiS97 @camtittle @mrinalTASKER @evans-github @rbarbish as  they also said they are still having the issue after the fix, but commented on a closed thread which is not monitored by the AWS team.

**Comment by RandomEngy** [comment]
https://docs.amplify.aws/sdk/auth/how-it-works/q/platform/android#state-tracking

I ended up working around by launching the hosted UI again via `mobileClient.showSignIn()` when currentUserState().userState is not SIGNED_IN, and adding a user state tracker. I still haven't figured out an approach to prevent any UI flashes. The hosted UI always comes back to the app with the myapp:// protocol, which is always going to be the same activity. So it might jump you out of whatever you were on before.

**Comment by RandomEngy** [comment]
https://docs.amplify.aws/sdk/auth/how-it-works/q/platform/android#state-tracking

I ended up working around by launching the hosted UI again via `mobileClient.showSignIn()` when currentUserState().userState is not SIGNED_IN, and adding a user state tracker. I still haven't figured out an approach to prevent any UI flashes. The hosted UI always comes back to the app with the myapp:// protocol, which is always going to be the same activity. So it might jump you out of whatever you were on before.

**Comment by gpanshu** [comment]
Closing this as there is a workaround and there has been no activity since 1.5 years. If you are still experiencing issues please feel free to open a new issue.
