### ISSUE TITLE
Amplify - Android SDK Amplify is using identity pools when signing in with username/password. 

### ISSUE THREAD

**Issue by SamiKh94** [aws-amplify/aws-sdk-android#2064]
**Amplify is using identity pools when signing in with username/password. **
When trying to sign in the signed-up users using `Amplify.Auth.signIn(username, password, {}, {})` Amplify throws an exception that says: 

```
W/AWSMobileClient: Failed to federate tokens during sign-in
    java.lang.Exception: Federation is not enabled, please check if you have CognitoIdentity configured.
        at com.amazonaws.mobile.client.AWSMobileClient$10.run(AWSMobileClient.java:1691)
        at com.amazonaws.mobile.client.internal.InternalCallback.await(InternalCallback.java:115)
        at com.amazonaws.mobile.client.AWSMobileClient.federatedSignInWithoutAssigningState(AWSMobileClient.java:1644)
        at com.amazonaws.mobile.client.AWSMobileClient$6$1.onSuccess(AWSMobileClient.java:1191)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser$6.onSuccess(CognitoUser.java:1099)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser$27.run(CognitoUser.java:3098)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser$24.run(CognitoUser.java:2965)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.continuations.AuthenticationContinuation.continueTask(AuthenticationContinuation.java:147)
        at com.amazonaws.mobile.client.AWSMobileClient$6$1.getAuthenticationDetails(AWSMobileClient.java:1222)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getSession(CognitoUser.java:1032)
        at com.amazonaws.mobile.client.AWSMobileClient$6.run(AWSMobileClient.java:1176)
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
        at java.lang.Thread.run(Thread.java:919)
```

I had `CredentialsProvider {...}`  in the `amplifyconfigration.json` then removed it since I don't want to use the `IdentityPools` 

My `amplifyconfigration.json` file: 
```
{
  "UserAgent": "aws-amplify-cli/2.0",
  "Version": "1.0",
  "auth": {
    "plugins": {
      "awsCognitoAuthPlugin": {
        "CognitoUserPool": {
          "Default": {
            "PoolId": "us-east-1_XXXXXX",
            "AppClientId": "XXXXXX",
            "Region": "us-east-1"
          }
        }
      }
    }
  },
  "CognitoUserPool": {
    "Default": {
      "PoolId": "us-east-1_XXXXXX",
      "AppClientId": "XXXXXX",
      "Region": "us-east-1"
    }
  },
  "Auth": {
    "Default": {
      "OAuth": {
        "WebDomain": "XXXXXXX",
        "AppClientId": "XXXXXX",
        "SignInRedirectURI": "XXXXXX",
        "SignOutRedirectURI": "XXXX",
        "Scopes": [
          "phone",
          "email",
          "openid",
          "profile",
          "aws.cognito.signin.user.admin"
        ]
      },
      "authenticationFlowType": "USER_PASSWORD_AUTH"
    }
  }
}
```

**Comment by rjuliano** [comment]
The current implementation of the Auth plugin relies on both user and identity pool.

**Comment by akalineskou** [comment]
Could you please let us know where is this documented.

We are using both JS and iOS SDKs and they work without federated login.
Can you let us know how we can disable the federated login?
