### ISSUE TITLE
Failed to upload file to S3 with AmazonS3Exception

### ISSUE THREAD

**Issue by kenmasumitsu** [aws-amplify/aws-sdk-android#2088]
**Describe the bug**
Failed to upload data to S3.

**To Reproduce**
A code sample or steps:

putObject throws AmazonS3Exception.

```
            val s3 = AmazonS3Client(
                BasicAWSCredentials(ACCESS_KEY_ID, SECRET_ACCESS_KEY),
                Region.getRegion(Regions.AP_NORTHEAST_1)
            )

            s3.putObject(
                BUCKET_NAME,
                "foo",
                "bar"
            )

```

**Which AWS service(s) are affected?**

S3

**Expected behavior**
It should not throw the exception.

**Screenshots**

logcat 
```
2020-08-24 13:29:52.320 17018-17618/com.test.app E/AndroidRuntime: FATAL EXCEPTION: Thread-4
    Process: com.test.app, PID: 17018
    com.amazonaws.services.s3.model.AmazonS3Exception: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint. (Service: Amazon S3; Status Code: 301; Error Code: PermanentRedirect; Request ID: 86BE90889BB53390), S3 Extended Request ID: /pP+kFOYsjNLQMq+t5X5B826GSV7huNe/9UIs0uBd48eSyNV4rDVMeIKLiXfEayELp1srqXpUIc=
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:731)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:405)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4913)
        at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1960)
        at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:5627)
        at com.test.app.upload.S3Uploader$upload$1.run(S3Uploader.kt:56)
        at java.lang.Thread.run(Thread.java:919)
```

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.18.0
 - Device: Pixel 3
 - Android Version: Android 10
 - Specific to simulators: No

**Additional context**

I tried to set ENDPOINT explicitly with the code below, but it does not resolve the issue.

```
        val ENDPOINT = "https://s3.ap-northeast-1.amazonaws.com"
        s3.setEndpoint(ENDPOINT)
```

**Comment by jpignata** [comment]
Thanks @kenmasumitsu. Can you confirm the bucket is definitely in `ap-northeast-1`? That would be the error I'd expect if the bucket was actually created in another region.

**Comment by kenmasumitsu** [comment]
I confirmed these parameters many times. 
When I ran similar codes in Python. It worked fine. So that, the bucket is in "ap-northeast-1".

```
import boto3

region_name = "ap-northeast-1"
aws_access_key_id = ...
aws_secret_access_key = ...
bucket_name = ...

s3 = boto3.resource(
    "s3",
    region_name=region_name,
    aws_access_key_id=aws_access_key_id,
    aws_secret_access_key=aws_secret_access_key,
)

obj = s3.Object(bucket_name, "foo")
obj.put(Body="bar".encode())
```

**Comment by kenmasumitsu** [comment]
Sorry, you are right. The region is wrong.

I found Python library (boto3) automatically corrected the region.

**Comment by jpignata** [comment]
No reason to apologize! Good for us to know, and that actually strikes me as reasonable behavior for an SDK: if you get a 301 redirect, follow it. Thanks.
