### ISSUE TITLE
Using old Android reference for ContextCompat

### ISSUE THREAD

**Issue by sgrosz** [aws-amplify/aws-sdk-android#2094]
The `com.amazonaws:aws-android-sdk-mobile-client` library references old class for ContextCompat but should either be removed or updated to AndroidX to avoid unnecessary error.

https://github.com/aws-amplify/aws-sdk-android/blob/a1313211d3e29454d105c71585952cd11754eac8/aws-android-sdk-mobile-client/src/main/java/com/amazonaws/mobile/client/AWSMobileClient.java#L771

**Comment by TrekSoft** [comment]
Hey, yes this has been fixed in the latest release.

**Comment by sgrosz** [comment]
From what I can see in the source code for 2.18.0 that exact line of code is still there and will throw an exception since you're now using AndroidX. I'm using 2.18.0 and this shows up in my logs so would be nice if you removed that line of code or updated to `Class.forName("androidx.core.content.ContextCompat")` instead.

This is the exception that's being thrown and logged:
```
Could not check if ACCESS_NETWORK_STATE permission is available.
    java.lang.ClassNotFoundException: android.support.v4.content.ContextCompat
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at java.lang.Class.forName(Class.java:379)
        at com.amazonaws.mobile.client.AWSMobileClient.isNetworkAvailable(AWSMobileClient.java:771)
        at com.amazonaws.mobile.client.AWSMobileClient.getUserStateDetails(AWSMobileClient.java:983)
        at com.amazonaws.mobile.client.AWSMobileClient.waitForSignIn(AWSMobileClient.java:923)
        at com.amazonaws.mobile.client.AWSMobileClient.getCredentials(AWSMobileClient.java:364)
        at com.amazonaws.mobileconnectors.iot.AWSIotMqttManager$1.run(AWSIotMqttManager.java:984)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.ContextCompat" on path: DexPathList[[zip file "..."],nativeLibraryDirectories=[..., ..., /system/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:454) 
        at java.lang.Class.forName(Class.java:379) 
        at com.amazonaws.mobile.client.AWSMobileClient.isNetworkAvailable(AWSMobileClient.java:771) 
        at com.amazonaws.mobile.client.AWSMobileClient.getUserStateDetails(AWSMobileClient.java:983) 
        at com.amazonaws.mobile.client.AWSMobileClient.waitForSignIn(AWSMobileClient.java:923) 
        at com.amazonaws.mobile.client.AWSMobileClient.getCredentials(AWSMobileClient.java:364) 
        at com.amazonaws.mobileconnectors.iot.AWSIotMqttManager$1.run(AWSIotMqttManager.java:984) 
        at java.lang.Thread.run(Thread.java:919) 
```

**Comment by TrekSoft** [comment]
Ah, I'm sorry, I see the fix hasn't been released yet: https://github.com/aws-amplify/aws-sdk-android/commit/deebe8936c7839066a46106c004a85deb5387af3

Will update this ticket when it's out - should hopefully be by end of week.

**Comment by richardmcclellan** [comment]
2.19.0 has been released, and contains a fix for this issue: https://github.com/aws-amplify/aws-sdk-android/releases/tag/release_v2.19.0
