### ISSUE TITLE
NPE on IdentityProvider.getDisplayName()

### ISSUE THREAD

**Issue by tomblenz** [aws-amplify/aws-sdk-android#2155]
**Describe the bug**
We have a few hundred occurrences of this crash report, at least a dozen every week.  We don't know the exact cause and are unable to reproduce. 
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String com.amazonaws.mobile.auth.core.IdentityProvider.getDisplayName()' on a null object reference
       at com.amazonaws.mobile.auth.core.IdentityManager$6$1.onError(IdentityManager.java:726)
       at com.amazonaws.mobile.auth.core.signin.SignInManager$SignInProviderResultAdapter$3.run(SignInManager.java:199)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6923)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
```

Basically at some point in time, IdentityManager's `currentIdentityProvider` field is set to null prior to `SignInProviderResultAdapter.onError(currentIdentityProvider)` being called.  This then calls a log message which causes the NP dereference:
```
public void onError(final IdentityProvider provider, final Exception ex) {
    Log.e(LOG_TAG,
        String.format("SignInProviderResultAdapter.onError(): %s provider error. %s",
                      provider.getDisplayName(), ex.getMessage()), ex);  // CRASH
    handler.onError(provider, new ProviderAuthException(provider, ex));
}
```

It appears that it may be a race condition as the only place that `currentIdentityProvider` is nulled out is in `IdentityManager.signOut()`.  So our best guess is that something has signed the user out while another request (which ultimately fails) is still in motion.

This is all in AWS SDK code so we don't have any control over it or ability to insert NPE guards or extra logging unfortunately.

**To Reproduce**
Unknown

**Which AWS service(s) are affected?**
Cognito 

**Expected behavior**
I would expect `provider` to never be null in the above callback and no crashes to occur.

**Screenshots**
N/A

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: we've seen this for 2.16.12 and 2.6.30
 - Device: Hundreds of device models.
 - Android Version: 6, 7, 8, 9, 10
 - Specific to simulators: No

**Additional context**
We integrate Cognito user pools, facebook and google logins.  The only clue we have is that the number of crashes once spiked into the hundreds when the facebook dev app was briefly disabled, but we can't confirm that all crashes are cognito+facebook related.

Our dependencies:
```
def aws_version = '2.16.12'
implementation("com.amazonaws:aws-android-sdk-auth-core:$aws_version@aar") 
implementation("com.amazonaws:aws-android-sdk-auth-google:$aws_version@aar") {
    transitive = true
}
implementation("com.amazonaws:aws-android-sdk-auth-facebook:$aws_version@aar")
implementation("com.amazonaws:aws-android-sdk-auth-userpools:$aws_version@aar")
implementation("com.amazonaws:aws-android-sdk-cognitoidentityprovider:$aws_version")
implementation("com.amazonaws:aws-android-sdk-apigateway-core:$aws_version") {
    exclude group: 'com.google.code.gson'
}
```

Let me know if I can provide any further information, I apologise for not having much around cause/reproduction.

**Comment by tomblenz** [comment]
Just following up to say this is still a regular occurrence for our users.
