### ISSUE TITLE
ResourceNotFoundException AWS IoT connection

### ISSUE THREAD

**Issue by armandr** [aws-amplify/aws-sdk-android#2253]
**Describe the bug**

calling createKeysAndCertificate or any other iot calls results in a 404 error.

 

**To Reproduce**
A code sample or steps:

The credentials provider is from Cognito auth and the app is able to communicate with other AWS service (ddb, s3, etc).

Following the same process as we do in iOS.  The iOS side does not result in error and works fine, so the issue should not be related to IAM roles, policies, etc as they are the same.

```
` val region: Region = Region.getRegion(Regions.US_EAST_1)

                        val cred = StaticCredentialsProvider(credProvider?.credentials)
                        val iot = AWSIotClient(cred) 
                        iot.setRegion(region)
                        iot.endpoint = "xxxxxxxxxxxxxxx.iot.us-east-1.amazonaws.com"

                       var certReq = CreateKeysAndCertificateRequest().withSetAsActive(true)
                       val keysAndCert = iot.createKeysAndCertificate(certReq)
`

```

**Which AWS service(s) are affected?**

**Expected behavior**
return cert and keys

**Screenshots**

    --------- beginning of crash
2020-11-22 10:02:30.136 20970-21036/com.example.unuapp E/AndroidRuntime: FATAL EXCEPTION: Thread-7
    Process: com.example.unuapp, PID: 20970
    com.amazonaws.services.iot.model.ResourceNotFoundException: Not Found (Service: AWSIot; Status Code: 404; Error Code: ResourceNotFoundException; Request ID: 0bcd0c57-2851-72aa-3675-a93b92ab88be)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:742)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:420)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:229)
        at com.amazonaws.services.iot.AWSIotClient.invoke(AWSIotClient.java:11748)
        at com.amazonaws.services.iot.AWSIotClient.createKeysAndCertificate(AWSIotClient.java:1750)
        at com.example.unuapp.MainActivity$onCreate$3$onResult$1.run(MainActivity.kt:144)
        at java.lang.Thread.run(Thread.java:923)
2020-11-22 10:02:30.203 20970-21036/com.example.unuapp I/Process: Sending signal. PID: 20970 SIG: 9

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: [e.g. 2.6.25] 2.19.2.  I have also tried this on previous builds going back to 2.15.0.
 - Device: [e.g. Pixel XL, Simulator] Pixel 3a, real Phones as well
 - Android Version: [e.g. Nougat 7.1.2] Androidx
 - Specific to simulators: [e.g. Yes/No]
No

**Additional context**

Possibly related to #2251 and #2246

**Comment by armandr** [comment]
works with AWSIotClient(AWSMobileClient.getInstance()).  Even though the rest of the services work by passing a Cognito credentials provider.
