### ISSUE TITLE
AWSIotMqttManager: an Exception in reconnectToSession causes reconnect loop without backoff

### ISSUE THREAD

**Issue by wijnanb** [aws-amplify/aws-sdk-android#2273]
When an Exception is thrown in AWSIotMqttManager.reconnectToSession(), this cause 2 issues:

1. In handleConnectionFailure() a new reconnect is scheduled, without checking that a reconnect is already scheduled. This will cause fast reconnect loop without taking the exponential backoff policy into account
2. HandlerThread not being quit. The reconnect loop will create thousands of threads that are not quit.

Solution:

1. Do not schedule a new reconnect when there is already one scheduled.
2. Use a try/catch/finally block where ht.quit() is called within finally.

This excerpt of a log demonstrates it:
```
11-26 18:49:01.744 12238 13537 I AWSIotMqttManager: schedule Reconnect attempt 51 of -1 in 64 seconds.
11-26 18:49:01.752 12238 13537 D AWSIotMqttManager: mqtt reconnecting attempt 52
11-26 18:49:02.320 12238 13546 I AWSIotMqttManager: attempting to reconnect to mqtt broker
11-26 18:49:02.484 12238 13546 E AWSIotMqttManager: Failed to get credentials. AmazonClientException: 
11-26 18:49:02.484 12238 13546 E AWSIotMqttManager: com.amazonaws.services.cognitoidentity.model.NotAuthorizedException: Unauthenticated access is not supported for this identity pool. (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: NotAuthorizedException; Request ID: 6dd95667-6b9a-4854-a9ae-16f085ce2e4c)
...
11-26 18:49:02.484 12238 13546 E AWSIotMqttManager: 	at com.amazonaws.mobileconnectors.iot.AWSIotMqttManager.reconnectToSession(AWSIotMqttManager.java:1174)
11-26 18:49:02.485 12238 13546 I AWSIotMqttManager: schedule Reconnect attempt 52 of -1 in 64 seconds.
11-26 18:49:02.493 12238 13546 D AWSIotMqttManager: mqtt reconnecting attempt 53
11-26 18:49:02.498 12238 13546 E AWSIotMqttManager: Exception during reconnect, exception: 
11-26 18:49:02.498 12238 13546 E AWSIotMqttManager: Connect already in progress (32110)
11-26 18:49:02.498 12238 13546 E AWSIotMqttManager: 	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.connect(MqttAsyncClient.java:602)
11-26 18:49:02.498 12238 13546 E AWSIotMqttManager: 	at com.amazonaws.mobileconnectors.iot.AWSIotMqttManager.reconnectToSession(AWSIotMqttManager.java:1187)
11-26 18:49:02.498 12238 13546 I AWSIotMqttManager: schedule Reconnect attempt 53 of -1 in 64 seconds.
11-26 18:49:02.696 12238 13557 W AWSIotMqttManager: Reconnect failed 
11-26 18:49:02.696 12238 13557 W AWSIotMqttManager: MqttException (0) - java.io.IOException: Already connected
11-26 18:49:02.696 12238 13557 I AWSIotMqttManager: schedule Reconnect attempt 53 of -1 in 64 seconds.
11-26 18:50:05.789 12238 13549 I AWSIotMqttManager: attempting to reconnect to mqtt broker
11-26 18:50:06.185 12238 13549 E AWSIotMqttManager: com.amazonaws.services.cognitoidentity.model.NotAuthorizedException: Unauthenticated access is not supported for this identity pool. (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: NotAuthorizedException; Request ID: 99bca64b-95d8-493f-a87a-865b46db7ed9)
...
11-26 18:50:06.185 12238 13549 E AWSIotMqttManager: 	at com.amazonaws.mobileconnectors.iot.AWSIotMqttManager.reconnectToSession(AWSIotMqttManager.java:1174)
11-26 18:50:06.185 12238 13549 I AWSIotMqttManager: schedule Reconnect attempt 53 of -1 in 64 seconds.
11-26 18:50:06.194 12238 13549 D AWSIotMqttManager: mqtt reconnecting attempt 54
11-26 18:50:06.541 12238 13558 I AWSIotMqttManager: attempting to reconnect to mqtt broker
11-26 18:50:06.565 12238 13559 I AWSIotMqttManager: attempting to reconnect to mqtt broker
```

 - AWS Android SDK Version: 2.16.8
 - Device: Pearl
 - Android Version: 9
 - Specific to simulators: No

The reconnect loop is demonstrated here:

```
11-26 18:58:08.908 12238 14773 I AWSIotMqttManager: schedule Reconnect attempt 822 of -1 in 64 seconds.
11-26 18:58:08.916 12238 14773 I AWSIotMqttManager: schedule Reconnect attempt 823 of -1 in 64 seconds.
11-26 18:58:08.973 12238 15126 I AWSIotMqttManager: attempting to reconnect to mqtt broker
11-26 18:58:08.983 12238 15127 I AWSIotMqttManager: attempting to reconnect to mqtt broker
11-26 18:58:09.041 12238 14774 I AWSIotMqttManager: schedule Reconnect attempt 823 of -1 in 64 seconds.
11-26 18:58:09.051 12238 14774 I AWSIotMqttManager: schedule Reconnect attempt 824 of -1 in 64 seconds.
11-26 18:58:09.083 12238 15128 I AWSIotMqttManager: attempting to reconnect to mqtt broker
11-26 18:58:09.101 12238 15129 I AWSIotMqttManager: attempting to reconnect to mqtt broker
11-26 18:58:09.160 12238 14775 I AWSIotMqttManager: schedule Reconnect attempt 824 of -1 in 64 seconds.
11-26 18:58:09.170 12238 14775 I AWSIotMqttManager: schedule Reconnect attempt 825 of -1 in 64 seconds.
11-26 18:58:09.285 12238 14776 I AWSIotMqttManager: schedule Reconnect attempt 825 of -1 in 64 seconds.
11-26 18:58:09.297 12238 14776 I AWSIotMqttManager: schedule Reconnect attempt 826 of -1 in 64 seconds.
11-26 18:58:09.438 12238 14779 I AWSIotMqttManager: schedule Reconnect attempt 826 of -1 in 64 seconds.
11-26 18:58:09.444 12238 14779 I AWSIotMqttManager: schedule Reconnect attempt 827 of -1 in 64 seconds.
11-26 18:58:09.552 12238 15906 I AWSIotMqttManager: schedule Reconnect attempt 827 of -1 in 64 seconds.
11-26 18:58:09.556 12238 14780 I AWSIotMqttManager: schedule Reconnect attempt 827 of -1 in 64 seconds.
11-26 18:58:09.672 12238 14782 I AWSIotMqttManager: schedule Reconnect attempt 828 of -1 in 64 seconds.
11-26 18:58:09.693 12238 14782 I AWSIotMqttManager: schedule Reconnect attempt 829 of -1 in 64 seconds.
11-26 18:58:09.753 12238 15135 I AWSIotMqttManager: attempting to reconnect to mqtt broker
11-26 18:58:09.794 12238 14783 I AWSIotMqttManager: schedule Reconnect attempt 829 of -1 in 64 seconds.
11-26 18:58:09.801 12238 14783 I AWSIotMqttManager: schedule Reconnect attempt 830 of -1 in 64 seconds.
11-26 18:58:09.918 12238 14785 I AWSIotMqttManager: schedule Reconnect attempt 830 of -1 in 64 seconds.
11-26 18:58:09.926 12238 14785 I AWSIotMqttManager: schedule Reconnect attempt 831 of -1 in 64 seconds.
11-26 18:58:10.042 12238 14786 I AWSIotMqttManager: schedule Reconnect attempt 831 of -1 in 64 seconds.
11-26 18:58:10.049 12238 14786 I AWSIotMqttManager: schedule Reconnect attempt 832 of -1 in 64 seconds.
11-26 18:58:10.156 12238 14789 I AWSIotMqttManager: schedule Reconnect attempt 832 of -1 in 64 seconds.
11-26 18:58:10.163 12238 14789 I AWSIotMqttManager: schedule Reconnect attempt 833 of -1 in 64 seconds.
11-26 18:58:10.270 12238 14790 I AWSIotMqttManager: schedule Reconnect attempt 833 of -1 in 64 seconds.
11-26 18:58:10.276 12238 14790 I AWSIotMqttManager: schedule Reconnect attempt 834 of -1 in 64 seconds.
11-26 18:58:10.384 12238 14792 I AWSIotMqttManager: schedule Reconnect attempt 834 of -1 in 64 seconds.
11-26 18:58:10.390 12238 14792 I AWSIotMqttManager: schedule Reconnect attempt 835 of -1 in 64 seconds.
11-26 18:58:10.443 12238 15927 I AWSIotMqttManager: schedule Reconnect attempt 835 of -1 in 64 seconds.
11-26 18:58:10.506 12238 14793 I AWSIotMqttManager: schedule Reconnect attempt 835 of -1 in 64 seconds.
11-26 18:58:10.633 12238 14794 I AWSIotMqttManager: schedule Reconnect attempt 836 of -1 in 64 seconds.
11-26 18:58:10.646 12238 14794 I AWSIotMqttManager: schedule Reconnect attempt 837 of -1 in 64 seconds.
11-26 18:58:10.750 12238 14795 I AWSIotMqttManager: schedule Reconnect attempt 837 of -1 in 64 seconds.
```

**Comment by sktimalsina** [comment]
Closing issue due to inactivity in related PR. 
Please +1 or reopen this issue with relevant information if you are still facing the issue.
