### ISSUE TITLE
MqttException (0) - java.net.SocketTimeoutException: Connect timed out error over proxy

### ISSUE THREAD

**Issue by rajishere** [aws-amplify/aws-sdk-android#2281]
Hi Team,

Seeing below timeout error when trying to connect using `connectWithProxy(KeyStore keyStore, final String proxyHost, final int proxyPort, final AWSIotMqttClientStatusCallback statusCallback)` in `AWSIotMqttManager` to connect to IOT end point `<iot address>-ats.iot.<region>.amazonaws.com:8883.` over proxy (firewall)

```
2020-12-09 18:49:22.483 16603-16603/com.seven11.lvt E/IOT: Connection error.
    MqttException (0) - java.net.SocketTimeoutException: Connect timed out
        at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:738)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.net.SocketTimeoutException: Connect timed out
        at java.net.SocksSocketImpl.readSocksReply(SocksSocketImpl.java:126)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:467)
        at java.net.Socket.connect(Socket.java:631)
        at com.amazonaws.mobileconnectors.iot.AWSIotProxiedSSLSocket.connect(AWSIotProxiedSSLSocket.java:61)
        at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:74)
        at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:132)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:724)
        at java.lang.Thread.run(Thread.java:764) 
```

Not seeing issue when connecting over a public network with `connect` method

Is there a way to identify why connect to endpoint is timing out (in 30 seconds)

**Comment by rjuliano** [comment]
30 seconds is the default timeout applied by the underlying mqtt library (paho). As far as root cause, one thing to try would be to attempt to verify reachability of that address from the machine where you are running your code.
