### ISSUE TITLE
App is crashed when try to upload the files.

### ISSUE THREAD

**Issue by marimuthugovi** [aws-amplify/aws-sdk-android#2339]
SDK Versions
```
implementation 'com.amazonaws:aws-android-sdk-core:2.13.1'
implementation 'com.amazonaws:aws-android-sdk-s3:2.13.1'
```

```
Fatal Exception: h.a
at com.innothink.innomaint.feature.attachment.fragment.AttachmentUploadFragment$uploadFileToS3$1.onStateChanged(AttachmentUploadFragment.java:290)
at com.amazonaws.mobileconnectors.s3.transferutility.TransferStatusUpdater$1.run(TransferStatusUpdater.java:6)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:201)
at android.app.ActivityThread.main(ActivityThread.java:6820)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:922)
```

**Comment by richardmcclellan** [comment]
Hi @marimuthugovi, it looks like the crash is occurring in your `AttachmentUploadFragment` class, not the Android SDK.   Can you provide a code sample where that includes the line where this crash is occurring?
