### ISSUE TITLE
HUAWEI ANE-LX3 videos failed to upload to bucket

### ISSUE THREAD

**Issue by shiv71** [aws-amplify/aws-sdk-android#2351]
**Describe the bug**
On HUAWEI ANE-LX3 videos are failing to upload while photos uploaded to S3 Bucket.

**To Reproduce**
Run the TransferUtility video upload on the latest SDK on HUAWEI ANE-LX3.

**Which AWS service(s) are affected?**
TransferUtility

**Expected behavior**
videos should be uploaded to the S3 bucket.

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: [2.20]
 - Device: [HUAWEI ANE-LX3]
 - Android Version: [9]

**Additional context**
The same device was working with video uploads with SDK version 2.7. Since we don't have the physical device with us as it's with some user of our App. So we're not able to troubleshoot the issue. Could someone shed any light on this issue?

Also if we roll back to the previous SDK 2.7 then the app crashes. Below is the crash log
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.buddynation.DroneNation/com.buddynation.dronenation.view.post.CreatePostAct}: android.database.sqlite.SQLiteException: Can't downgrade database from version 6 to 5
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3162)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3305)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1993)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7285)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```

So, I want to know how I can roll back the SDK to the old version 2.7 which was working earlier on HUAWEI ANE-LX3? Our app is already live and if I upload a new build with SDK version 2.7 and if it starts crashing it will lead to a bad consumer experience for us. So please suggest a solution for this.

**Comment by raphkim** [comment]
I would recommend against rolling back to 2.7 in favor of sticking with newer versions of the SDK. Would you be able to let us know how exactly the app is failing to upload by providing code snippets and stack trace?

Meanwhile, if you really need to use the older version of the SDK and would like to circumvent the failure to downgrade, then please try clearing app's data (specifically `awss3transfertable.db`) and try again.

**Comment by raphkim** [comment]
There has been a change in `TransferUtility` to make large file uploads to be more reliable. Please try updating the SDK to v2.22.7 for improved experience.
