### ISSUE TITLE
Getting Error "Unable to store object contents to disk: /20210214-2100.json (Read-only file system)" when downloading objects from S3 bucket to internal storage

### ISSUE THREAD

**Issue by prashanthravir** [aws-amplify/aws-sdk-android#2372]
I'm getting an error while trying to download all objects in my Amazon S3 bucket I uploaded the file with a particular key and trying to download the same path,

I'm getting the below error,

````2021-02-27 13:02:59.121 26052-26052/com.example.myproject E/MyAmplifyApp: Download Failure
    StorageException{message=Something went wrong with your AWS S3 Storage download file operation, cause=com.amazonaws.AmazonClientException: Unable to store object contents to disk: /20210214-2100.json (Read-only file system), recoverySuggestion=See attached exception for more information and suggestions}
        at com.amplifyframework.storage.s3.operation.AWSS3StorageDownloadFileOperation$DownloadTransferListener.onError(AWSS3StorageDownloadFileOperation.java:195)
        at com.amazonaws.mobileconnectors.s3.transferutility.TransferStatusUpdater$4.run(TransferStatusUpdater.java:306)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: com.amazonaws.AmazonClientException: Unable to store object contents to disk: /20210214-2100.json (Read-only file system)
        at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.saveToFile(DownloadTask.java:200)
        at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.call(DownloadTask.java:111)
        at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.call(DownloadTask.java:42)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.io.FileNotFoundException: /20210214-2100.json (Read-only file system)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:308)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:238)
        at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.saveToFile(DownloadTask.java:188)
        at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.call(DownloadTask.java:111) 
        at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.call(DownloadTask.java:42) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
2021-02-27 13:02:59.123 26052-26052/com.example.seki E/MyAmplifyApp: Download Failure
    StorageException{message=Storage download operation was interrupted., cause=null, recoverySuggestion=Please verify that you have a stable internet connection.}
        at com.amplifyframework.storage.s3.operation.AWSS3StorageDownloadFileOperation$DownloadTransferListener.onStateChanged(AWSS3StorageDownloadFileOperation.java:176)
        at com.amazonaws.mobileconnectors.s3.transferutility.TransferStatusUpdater$2.run(TransferStatusUpdater.java:224)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)```


Here is my download code,

   ```Amplify.Storage.downloadFile(
                "Project/events/00006/20210214-2100.json",
                exampleFile,
                { result ->
                    val r  = result
                    Log.i("MyAmplifyApp", "Successfully downloaded: ${
                    result.file.name}" + r.file.toString())
                },
                { error -> Log.e("MyAmplifyApp", "Download Failure", error) }
        )```

the key I use for upload is same except the file I upload is different I am just changing the file name alone in the download as I am trying to download the file that is generated in same path

**Comment by prashanthravir** [comment]
hi I think this question should be raised under aws-amplify/amplify-android GitHub repo as I am using Amplify framework, hence closing this and raising it there.
