### ISSUE TITLE
AWS IoT device multiple reconnect: I/O error during system call, Connection reset by peer

### ISSUE THREAD

**Issue by beersheba** [aws-amplify/aws-sdk-android#2416]
**Describe the bug**
MQTT client is constantly dropping the connection. 
In about 4 sec it's being reconnected, then it repeats in 20-30 min.
What may be the reason for that?

```
2021-04-04 09:17:54.358 [MQTT Rec: 104958] INFO onStatusChanged with exception
org.eclipse.paho.client.mqttv3.MqttException: Connection lost
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:181)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: javax.net.ssl.SSLException: Read error: ssl=0xdb1776d8: I/O error during system call, Connection reset by peer
	at org.conscrypt.NativeCrypto.SSL_read(Native Method)
	at org.conscrypt.NativeSsl.read(NativeSsl.java:409)
	at org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:548)
	at org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:519)
	at java.io.DataInputStream.readByte(DataInputStream.java:75)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:133)
	... 7 common frames omitted
2021-04-04 09:17:58.665 [MQTT Call: 104958] INFO  mqttCallback onStatusChanged; status: Connected
...
2021-04-04 09:37:58.677 [MQTT Rec: 104958] INFO  onStatusChanged with exception
org.eclipse.paho.client.mqttv3.MqttException: Connection lost
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:181)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: javax.net.ssl.SSLException: Read error: ssl=0xd2180e88: I/O error during system call, Connection reset by peer
	at org.conscrypt.NativeCrypto.SSL_read(Native Method)
	at org.conscrypt.NativeSsl.read(NativeSsl.java:409)
	at org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:548)
	at org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:519)
	at java.io.DataInputStream.readByte(DataInputStream.java:75)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:133)
	... 7 common frames omitted
2021-04-04 09:38:02.932 [MQTT Call: 104958] INFO  mqttCallback onStatusChanged; status: Connected
```

**To Reproduce**
A code sample or steps:
```
        mMqttManager = new AWSIotMqttManager(thingName, thingUrl);
        mMqttManager.setMaxAutoReconnectAttempts(-1);
        mqttCallback = new AWSIotMqttClientStatusCallback() {
            @Override
            public void onStatusChanged(final AWSIotMqttClientStatus status,
                                        final Throwable throwable) {
                Logger.i(TAG_LOCAL, "mqttCallback onStatusChanged; status: " + status);
                if (throwable != null) {
                    Logger.i(TAG_LOCAL, "onStatusChanged with exception", throwable);
                }

                if (status == AWSIotMqttClientStatus.Connecting) {
                    Logger.i(TAG, "Connecting...");
                    connected = false;
                } else if (status == AWSIotMqttClientStatus.Connected) {
                    Logger.i(TAG, "Connected");
                    connected = true;
                    if (!mInitialized) {
                        subscribe(String.format(CONFIGURATION_SUBSCRIBE_URL, thingName), CONFIGURATION_CALLBACK, new SubscriptionStatusCallback() {
                            @Override
                            public void onSuccess() {
                                refreshConfiguration(onServerDoneListener, onRemoteEventListener, onCredentialsListener);
                            }
                        }, null);
                        subscribe(String.format(DELTA_SUBSCRIBE_URL, thingName), DELTA_CALLBACK, null);
                    }
                    onRemoteEventListener.onConnected();
                } else if (status == AWSIotMqttClientStatus.Reconnecting) {
                    Logger.i(TAG, "Reconnecting");
                    connected = false;
                    onRemoteEventListener.onReconnect();
                } else if (status == AWSIotMqttClientStatus.ConnectionLost) {
                    Logger.i(TAG, "Disconnected");
                    connected = false;
                }
            }
        };
        KeyStore clientKeyStore = AWSIotKeystoreHelper.getIotKeystore(CERTIFICATE_ID,
                keystorePath, KEYSTORE_NAME, KEYSTORE_PASSWORD);
        mMqttManager.connectUsingALPN(clientKeyStore, mqttCallback);
```

**Which AWS service(s) are affected?**
AWS IoT

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.15.+@aar
 - Device: Lp PT7003_AC
 - Android Version: Android 5.1
 - Specific to simulators: No

**Additional context**
Doesn't reproduced by many of the rest IoT devices we have.

**Comment by eeatonaws** [comment]
Thank you for reporting this issue. The error `javax.net.ssl.SSLException: Read error: ssl=0xdb1776d8: I/O error during system call, Connection reset by peer` can be caused by the device losing network connection. Please check if the device is connected to the Internet. Also, I’m unable to reproduce the issue with the latest version of the AWS SDK for Android. Please try updating to the latest version of the AWS SDK for Android.

**Comment by eeatonaws** [comment]
Closing due to inactivity. Please create a new issue if the issue persists.
