### ISSUE TITLE
NoSuchFieldError in AmazonS3Client 

### ISSUE THREAD

**Issue by guillaume-tgl** [aws-amplify/aws-sdk-android#2420]
**Describe the bug**

Some of my users are expecting a crash with the following stack trace:
```
Fatal Exception: java.lang.NoSuchFieldError: No field NODE of type Li/b/a/a; in class Ljavax/xml/xpath/XPathConstants; or its superclasses (declaration of 'javax.xml.xpath.XPathConstants' appears in /apex/com.android.art/javalib/core-libart.jar)
       at com.amazonaws.util.XpathUtils.asNode(XpathUtils.java:312)
       at com.amazonaws.util.XpathUtils.evaluateAsString(XpathUtils.java:293)
       at com.amazonaws.util.XpathUtils.asString(XpathUtils.java:121)
       at com.amazonaws.services.s3.internal.S3ErrorResponseHandler.handle(S3ErrorResponseHandler.java:74)
       at com.amazonaws.services.s3.internal.S3ErrorResponseHandler.handle(S3ErrorResponseHandler.java:46)
       at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:711)
       at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:420)
       at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:229)
       at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4913)
       at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1960)
```

**To Reproduce**
I haven't been able to reproduce yet

**Which AWS service(s) are affected?**
S3

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.19.3
 - Device: All
 - Android Version: All
 - Specific to simulators: No

**Comment by eeatonaws** [comment]
Hi @guillaume-tgl. Thanks for reporting this issue. Could you please share your code snippets?

**Comment by guillaume-tgl** [comment]
We don't seem to have this error anymore, let's close.
