### ISSUE TITLE
open app again KinesisVideoAndroidClientFactory#createKinesisVideoClient crash the application.

### ISSUE THREAD

**Issue by GhRyuJin** [aws-amplify/aws-sdk-android#2421]
There is an Exception and app crashes after re-launch the app after first sign.

Full details and steps for reproducing the issue is below. It is reproducible on multiple device types, recent tested device is Letv X501.

Follow the https://github.com/awslabs/aws-sdk-android-samples/blob/master/AmazonKinesisVideoDemoApp/README.md to set up the Cognito.

Sign in the app and close it.

open the app again. Exception pops up and app crashes.

Stacktrace in the Console:

04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art: JNI DETECTED ERROR IN APPLICATION: JNI GetObjectClass called with pending exception java.lang.RuntimeException: Certificate integration is not implemented
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:     at com.amazonaws.kinesisvideo.producer.AuthInfo com.amazonaws.kinesisvideo.auth.DefaultAuthCallbacks.getDeviceCertificate() (DefaultAuthCallbacks.java:84)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:     at com.amazonaws.kinesisvideo.producer.AuthInfo com.amazonaws.kinesisvideo.internal.producer.jni.NativeKinesisVideoProducerJni.getDeviceCertificate() (NativeKinesisVideoProducerJni.java:604)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:     at long com.amazonaws.kinesisvideo.internal.producer.jni.NativeKinesisVideoProducerJni.createKinesisVideoClient(com.amazonaws.kinesisvideo.producer.DeviceInfo) (NativeKinesisVideoProducerJni.java:-2)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:     at void com.amazonaws.kinesisvideo.internal.producer.jni.NativeKinesisVideoProducerJni.create(com.amazonaws.kinesisvideo.producer.DeviceInfo, java.lang.String) (NativeKinesisVideoProducerJni.java:251)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:     at void com.amazonaws.kinesisvideo.internal.producer.jni.NativeKinesisVideoProducerJni.createSync(com.amazonaws.kinesisvideo.producer.DeviceInfo, java.lang.String) (NativeKinesisVideoProducerJni.java:263)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:     at void com.amazonaws.kinesisvideo.internal.producer.jni.NativeKinesisVideoProducerJni.createSync(com.amazonaws.kinesisvideo.producer.DeviceInfo) (NativeKinesisVideoProducerJni.java:229)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:     at com.amazonaws.kinesisvideo.internal.producer.KinesisVideoProducer com.amazonaws.kinesisvideo.internal.client.NativeKinesisVideoClient.initializeNewKinesisVideoProducer(com.amazonaws.kinesisvideo.producer.DeviceInfo) (NativeKinesisVideoClient.java:219)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:     at void com.amazonaws.kinesisvideo.internal.client.NativeKinesisVideoClient.initialize(com.amazonaws.kinesisvideo.producer.DeviceInfo) (NativeKinesisVideoClient.java:136)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:     at com.amazonaws.kinesisvideo.client.KinesisVideoClient com.amazonaws.mobileconnectors.kinesisvideo.client.KinesisVideoAndroidClientFactory.createKinesisVideoClient(android.content.Context, com.amazonaws.kinesisvideo.client.KinesisVideoClientConfiguration, com.amazonaws.kinesisvideo.producer.DeviceInfo, com.amazonaws.kinesisvideo.common.logging.Log, java.util.concurrent.ScheduledExecutorService) (KinesisVideoAndroidClientFactory.java:139)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:     at com.amazonaws.kinesisvideo.client.KinesisVideoClient com.amazonaws.mobileconnectors.kinesisvideo.client.KinesisVideoAndroidClientFactory.createKinesisVideoClient(android.content.Context, com.amazonaws.regions.Regions, com.amazonaws.auth.AWSCredentialsProvider) (KinesisVideoAndroidClientFactory.java:114)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:     at android.view.View com.amazonaws.kinesisvideo.demoapp.fragment.StreamConfigurationFragment.onCreateView(android.view.LayoutInflater, android.view.ViewGroup, android.os.Bundle) (StreamConfigurationFragment.java:70)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:     at void android.support.v4.app.Fragment.performCreateView(android.view.LayoutInflater, android.view.ViewGroup, android.os.Bundle) (Fragment.java:2439)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:     at void android.support.v4.app.FragmentManagerImpl.moveToState(android.support.v4.app.Fragment, int, int, int, boolean) (FragmentManager.java:1460)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:     at void android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(android.support.v4.app.Fragment) (FragmentManager.java:1784)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:     at void android.support.v4.app.FragmentManagerImpl.moveToState(int, boolean) (FragmentManager.java:1852)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:     at void android.support.v4.app.BackStackRecord.executeOps() (BackStackRecord.java:802)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:     at void android.support.v4.app.FragmentManagerImpl.executeOps(java.util.ArrayList, java.util.ArrayList, int, int) (FragmentManager.java:2625)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:     at void android.support.v4.app.FragmentManagerImpl.executeOpsTogether(java.util.ArrayList, java.util.ArrayList, int, int) (FragmentManager.java:2411)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:     at void android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(java.util.ArrayList, java.util.ArrayList) (FragmentManager.java:2366)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:     at boolean android.support.v4.app.FragmentManagerImpl.execPendingActions() (FragmentManager.java:2273)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:     at void android.support.v4.app.FragmentManagerImpl.dispatchStateChange(int) (FragmentManager.java:3273)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:     at void android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated() (FragmentManager.java:3229)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:     at void android.support.v4.app.FragmentController.dispatchActivityCreated() (FragmentController.java:201)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:     at void android.support.v4.app.FragmentActivity.onStart() (FragmentActivity.java:620)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:     at void android.support.v7.app.AppCompatActivity.onStart() (AppCompatActivity.java:178)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:     at void android.app.Instrumentation.callActivityOnStart(android.app.Activity) (Instrumentation.java:1245)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:     at void android.app.Activity.performStart() (Activity.java:6332)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2642)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2750)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:     at void android.app.ActivityThread.-wrap13(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:-1)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1595)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:111)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:     at void android.os.Looper.loop() (Looper.java:207)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:5975)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:789)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:679)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:     in call to GetObjectClass
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:     from long com.amazonaws.kinesisvideo.internal.producer.jni.NativeKinesisVideoProducerJni.createKinesisVideoClient(com.amazonaws.kinesisvideo.producer.DeviceInfo)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art: "main" prio=5 tid=1 Runnable
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:   | group="main" sCount=0 dsCount=0 obj=0x76385570 self=0x7fac447400
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:   | sysTid=14392 nice=0 cgrp=default sched=0/0 handle=0x7fb17352c0
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:   | state=R schedstat=( 372569230 72567381 309 ) utm=31 stm=6 core=0 HZ=100
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:   | stack=0x7fcf271000-0x7fcf273000 stackSize=8MB
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:   | held mutexes= "mutator lock"(shared held)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:   native: #00 pc 0000000000489708  /system/lib64/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiPKcPNS_9ArtMethodEPv+236)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:   native: #01 pc 0000000000458ac4  /system/lib64/libart.so (_ZNK3art6Thread4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+220)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:   native: #02 pc 000000000030eba4  /system/lib64/libart.so (_ZN3art9JavaVMExt8JniAbortEPKcS2_+1268)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:   native: #03 pc 000000000030f44c  /system/lib64/libart.so (_ZN3art9JavaVMExt9JniAbortVEPKcS2_St9__va_list+116)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:   native: #04 pc 0000000000141fbc  /system/lib64/libart.so (_ZN3art11ScopedCheck6AbortFEPKcz+144)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:   native: #05 pc 0000000000148e6c  /system/lib64/libart.so (_ZN3art11ScopedCheck5CheckERNS_18ScopedObjectAccessEbPKcPNS_12JniValueTypeE.constprop.116+6088)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:   native: #06 pc 0000000000151fa4  /system/lib64/libart.so (_ZN3art8CheckJNI14GetObjectClassEP7_JNIEnvP8_jobject+464)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:   native: #07 pc 0000000000028c34  /data/app/com.amazonaws.kinesisvideo.demoapp-1/lib/arm64/libKinesisVideoProducerJNI.so (_ZN25KinesisVideoClientWrapper11getAuthInfoEP10_jmethodIDPPhPjPm+188)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:   native: #08 pc 000000000000f0c8  /data/app/com.amazonaws.kinesisvideo.demoapp-1/lib/arm64/libKinesisVideoProducerJNI.so (getAuthInfo+204)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:   native: #09 pc 0000000000010ba8  /data/app/com.amazonaws.kinesisvideo.demoapp-1/lib/arm64/libKinesisVideoProducerJNI.so (executeAuthClientState+24)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:   native: #10 pc 00000000000117c4  /data/app/com.amazonaws.kinesisvideo.demoapp-1/lib/arm64/libKinesisVideoProducerJNI.so (stepStateMachine+364)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:   native: #11 pc 000000000000f6a8  /data/app/com.amazonaws.kinesisvideo.demoapp-1/lib/arm64/libKinesisVideoProducerJNI.so (createKinesisVideoClient+884)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:   native: #12 pc 0000000000022ff0  /data/app/com.amazonaws.kinesisvideo.demoapp-1/lib/arm64/libKinesisVideoProducerJNI.so (_ZN25KinesisVideoClientWrapperC1EP7_JNIEnvP8_jobjectS3_+132)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:   native: #13 pc 000000000002958c  /data/app/com.amazonaws.kinesisvideo.demoapp-1/lib/arm64/libKinesisVideoProducerJNI.so (Java_com_amazonaws_kinesisvideo_internal_producer_jni_NativeKinesisVideoProducerJni_createKinesisVideoClient+216)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:   native: #14 pc 0000000000955498  /data/app/com.amazonaws.kinesisvideo.demoapp-1/oat/arm64/base.odex (long com.amazonaws.kinesisvideo.internal.producer.jni.NativeKinesisVideoProducerJni.createKinesisVideoClient(com.amazonaws.kinesisvideo.producer.DeviceInfo)+156)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:   native: #15 pc 000000000095a6d0  /data/app/com.amazonaws.kinesisvideo.demoapp-1/oat/arm64/base.odex (void com.amazonaws.kinesisvideo.internal.producer.jni.NativeKinesisVideoProducerJni.create(com.amazonaws.kinesisvideo.producer.DeviceInfo, java.lang.String)+404)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:   native: #16 pc 000000000095aed4  /data/app/com.amazonaws.kinesisvideo.demoapp-1/oat/arm64/base.odex (void com.amazonaws.kinesisvideo.internal.producer.jni.NativeKinesisVideoProducerJni.createSync(com.amazonaws.kinesisvideo.producer.DeviceInfo, java.lang.String)+72)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:   native: #17 pc 000000000095ae38  /data/app/com.amazonaws.kinesisvideo.demoapp-1/oat/arm64/base.odex (void com.amazonaws.kinesisvideo.internal.producer.jni.NativeKinesisVideoProducerJni.createSync(com.amazonaws.kinesisvideo.producer.DeviceInfo)+92)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:   native: #18 pc 0000000000d30408  /data/app/com.amazonaws.kinesisvideo.demoapp-1/oat/arm64/base.odex (com.amazonaws.kinesisvideo.internal.producer.KinesisVideoProducer com.amazonaws.kinesisvideo.internal.client.NativeKinesisVideoClient.initializeNewKinesisVideoProducer(com.amazonaws.kinesisvideo.producer.DeviceInfo)+220)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:   native: #19 pc 0000000000d3028c  /data/app/com.amazonaws.kinesisvideo.demoapp-1/oat/arm64/base.odex (void com.amazonaws.kinesisvideo.internal.client.NativeKinesisVideoClient.initialize(com.amazonaws.kinesisvideo.producer.DeviceInfo)+64)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:   native: #20 pc 00000000005214e8  /data/app/com.amazonaws.kinesisvideo.demoapp-1/oat/arm64/base.odex (com.amazonaws.kinesisvideo.client.KinesisVideoClient com.amazonaws.mobileconnectors.kinesisvideo.client.KinesisVideoAndroidClientFactory.createKinesisVideoClient(android.content.Context, com.amazonaws.kinesisvideo.client.KinesisVideoClientConfiguration, com.amazonaws.kinesisvideo.producer.DeviceInfo, com.amazonaws.kinesisvideo.common.logging.Log, java.util.concurrent.ScheduledExecutorService)+316)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:   native: #21 pc 00000000005218ac  /data/app/com.amazonaws.kinesisvideo.demoapp-1/oat/arm64/base.odex (com.amazonaws.kinesisvideo.client.KinesisVideoClient com.amazonaws.mobileconnectors.kinesisvideo.client.KinesisVideoAndroidClientFactory.createKinesisVideoClient(android.content.Context, com.amazonaws.regions.Regions, com.amazonaws.auth.AWSCredentialsProvider)+848)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:   native: #22 pc 0000000000dc3bf8  /data/app/com.amazonaws.kinesisvideo.demoapp-1/oat/arm64/base.odex (android.view.View com.amazonaws.kinesisvideo.demoapp.fragment.StreamConfigurationFragment.onCreateView(android.view.LayoutInflater, android.view.ViewGroup, android.os.Bundle)+812)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:   native: #23 pc 00000000007e0028  /data/app/com.amazonaws.kinesisvideo.demoapp-1/oat/arm64/base.odex (void android.support.v4.app.Fragment.performCreateView(android.view.LayoutInflater, android.view.ViewGroup, android.os.Bundle)+364)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:   native: #24 pc 00000000007fd650  /data/app/com.amazonaws.kinesisvideo.demoapp-1/oat/arm64/base.odex (void android.support.v4.app.FragmentManagerImpl.moveToState(android.support.v4.app.Fragment, int, int, int, boolean)+6980)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:   native: #25 pc 00000000007fafe4  /data/app/com.amazonaws.kinesisvideo.demoapp-1/oat/arm64/base.odex (void android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(android.support.v4.app.Fragment)+520)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:   native: #26 pc 00000000007fb70c  /data/app/com.amazonaws.kinesisvideo.demoapp-1/oat/arm64/base.odex (void android.support.v4.app.FragmentManagerImpl.moveToState(int, boolean)+576)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:   native: #27 pc 00000000007d444c  /data/app/com.amazonaws.kinesisvideo.demoapp-1/oat/arm64/base.odex (void android.support.v4.app.BackStackRecord.executeOps()+2032)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:   native: #28 pc 00000000007ea684  /data/app/com.amazonaws.kinesisvideo.demoapp-1/oat/arm64/base.odex (void android.support.v4.app.FragmentManagerImpl.executeOps(java.util.ArrayList, java.util.ArrayList, int, int)+568)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:   native: #29 pc 00000000007eac44  /data/app/com.amazonaws.kinesisvideo.demoapp-1/oat/arm64/base.odex (void android.support.v4.app.FragmentManagerImpl.executeOpsTogether(java.util.ArrayList, java.util.ArrayList, int, int)+1304)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:   native: #30 pc 00000000007eddd4  /data/app/com.amazonaws.kinesisvideo.demoapp-1/oat/arm64/base.odex (void android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(java.util.ArrayList, java.util.ArrayList)+1112)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:   native: #31 pc 00000000007f7cdc  /data/app/com.amazonaws.kinesisvideo.demoapp-1/oat/arm64/base.odex (boolean android.support.v4.app.FragmentManagerImpl.execPendingActions()+304)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:   native: #32 pc 00000000007e9b68  /data/app/com.amazonaws.kinesisvideo.demoapp-1/oat/arm64/base.odex (void android.support.v4.app.FragmentManagerImpl.dispatchStateChange(int)+188)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:   native: #33 pc 00000000007f1914  /data/app/com.amazonaws.kinesisvideo.demoapp-1/oat/arm64/base.odex (void android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated()+136)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:   native: #34 pc 00000000001e9520  /data/app/com.amazonaws.kinesisvideo.demoapp-1/oat/arm64/base.odex (void android.support.v4.app.FragmentController.dispatchActivityCreated()+100)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:   native: #35 pc 0000000000ca59b4  /data/app/com.amazonaws.kinesisvideo.demoapp-1/oat/arm64/base.odex (void android.support.v4.app.FragmentActivity.onStart()+216)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:   native: #36 pc 0000000000d7dbf0  /data/app/com.amazonaws.kinesisvideo.demoapp-1/oat/arm64/base.odex (void android.support.v7.app.AppCompatActivity.onStart()+68)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:   native: #37 pc 0000000000c4f6d4  /data/dalvik-cache/arm64/system@framework@boot.oat (???)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:     at com.amazonaws.kinesisvideo.internal.producer.jni.NativeKinesisVideoProducerJni.createKinesisVideoClient(Native method)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:     at com.amazonaws.kinesisvideo.internal.producer.jni.NativeKinesisVideoProducerJni.create(NativeKinesisVideoProducerJni.java:251)
04-08 15:02:37.541 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:   - locked <0x06544297> (a java.lang.Object)
04-08 15:02:37.542 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:     at com.amazonaws.kinesisvideo.internal.producer.jni.NativeKinesisVideoProducerJni.createSync(NativeKinesisVideoProducerJni.java:263)
04-08 15:02:37.542 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:     at com.amazonaws.kinesisvideo.internal.producer.jni.NativeKinesisVideoProducerJni.createSync(NativeKinesisVideoProducerJni.java:229)
04-08 15:02:37.542 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:     at com.amazonaws.kinesisvideo.internal.client.NativeKinesisVideoClient.initializeNewKinesisVideoProducer(NativeKinesisVideoClient.java:219)
04-08 15:02:37.542 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:     at com.amazonaws.kinesisvideo.internal.client.NativeKinesisVideoClient.initialize(NativeKinesisVideoClient.java:136)
04-08 15:02:37.542 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:     at com.amazonaws.mobileconnectors.kinesisvideo.client.KinesisVideoAndroidClientFactory.createKinesisVideoClient(KinesisVideoAndroidClientFactory.java:139)
04-08 15:02:37.542 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:     at com.amazonaws.mobileconnectors.kinesisvideo.client.KinesisVideoAndroidClientFactory.createKinesisVideoClient(KinesisVideoAndroidClientFactory.java:114)
04-08 15:02:37.542 14392-14392/com.amazonaws.kinesisvideo.demoapp E/art:     at com.amazonaws.kinesisvideo.demoapp.fragment.StreamConfigurationFragment.onCreateView(StreamConfigurationFragment.java:70)

**Comment by richardmcclellan** [comment]
@hassanctech any thoughts on this one?

**Comment by hassanctech** [comment]
@GhRyuJin What version of Android is this device running?

**Comment by disa6302** [comment]
It does look like we do not support device certificate for Java at the moment. Tagging this as an enhancement work item.

**Comment by GhRyuJin** [comment]
@hassanctech Android 11 、Android 7 and Android 8
