### ISSUE TITLE
NullPointerException in KinesisRecorder.submitAllRecords()

### ISSUE THREAD

**Issue by hayohayo** [aws-amplify/aws-sdk-android#249]
I am investigating a crash caused by `NullPointerException` coming from `KinesisRecorder.submitAllRecords()`. SDK version is 2.3.3, we are using core and Kinesis libraries, devices: from 4.x to 6.x (maybe 7.x too).

Here's the stack trace:
```
java.lang.NullPointerException: file == null
at java.io.FileOutputStream.<init>(FileOutputStream.java:85)
at com.amazonaws.mobileconnectors.kinesis.kinesisrecorder.FileManager.newOutputStream(FileManager.java:115)
at com.amazonaws.mobileconnectors.kinesis.kinesisrecorder.FileRecordStore.tryInitializeWriter(FileRecordStore.java:119)
at com.amazonaws.mobileconnectors.kinesis.kinesisrecorder.FileRecordStore.put(FileRecordStore.java:78)
at com.amazonaws.mobileconnectors.kinesis.kinesisrecorder.AbstractKinesisRecorder.saveRecord(AbstractKinesisRecorder.java:97)
at com.amazonaws.mobileconnectors.kinesis.kinesisrecorder.KinesisRecorder.saveRecord(KinesisRecorder.java:236)
at com.amazonaws.mobileconnectors.kinesis.kinesisrecorder.AbstractKinesisRecorder.submitAllRecords(AbstractKinesisRecorder.java:153)
```
It's inconsistent, but some projects also have a call to `KinesisRecorder.submitAllRecords()` in a different thread.
```
libcore.io.Posix.getaddrinfo(Native Method)
libcore.io.ForwardingOs.getaddrinfo(ForwardingOs.java:61)
java.net.InetAddress.lookupHostByName(InetAddress.java:412)
java.net.InetAddress.getAllByNameImpl(InetAddress.java:236)
java.net.InetAddress.getAllByName(InetAddress.java:214)
com.android.okhttp.internal.Dns$1.getAllByName(Dns.java:28)
com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:216)
com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:122)
com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:292)
com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255)
com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206)
com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:89)
com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:197)
com.android.okhttp.internal.http.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:254)
com.amazonaws.http.UrlHttpClient.writeContentToConnection(UrlHttpClient.java:128)
com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:65)
com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:356)
com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:199)
com.amazonaws.services.kinesis.AmazonKinesisClient.invoke(AmazonKinesisClient.java:2775)
com.amazonaws.services.kinesis.AmazonKinesisClient.putRecords(AmazonKinesisClient.java:1451)
com.amazonaws.mobileconnectors.kinesis.kinesisrecorder.KinesisStreamRecordSender.sendBatch(KinesisStreamRecordSender.java:71)
com.amazonaws.mobileconnectors.kinesis.kinesisrecorder.AbstractKinesisRecorder.submitAllRecords(AbstractKinesisRecorder.java:138)
...
```
I was unable to reproduce this issue, so I don't know if updating to 2.3.8 would fix the problem. However, I've been able to crash application with the following code in SDK 2.3.3 and 2.3.8:
```
// Initialization
kinesis = new KinesisRecorder(context.getDir("somedir", 0), region, cognito);

// Later
for (int i = 0; i < 10; i++) {
    new Thread(String.format("writer-%d", i)) {
        @Override
        public void run() {
            for (; ; ) {
                byte[] bytes = new byte[1024];
                kinesis.saveRecord(bytes, STREAM_NAME);

                try {
                    mKinesis.submitAllRecords();
                } catch (AmazonClientException e) {
                    // Whatever
                }
                try {
                    Thread.sleep(100L);
                } catch (InterruptedException e) {
                    throw propagate(e);
                }
                kinesis.submitAllRecords();
            }
        }
    }.start();
}
```
This is under assumption that `KinesisRecorder` does not properly synchronize calls. I don't know if it is the same problem. This code crashes when device is offline. Stack trace is missing though...

**Comment by minbi** [comment]
Thank you for reporting this. We will update this thread when we have identified the problem.

**Comment by xuaninbox** [comment]
```
Fatal Exception: java.lang.NullPointerException
       at java.io.FileOutputStream.<init>(FileOutputStream.java:210)
       at com.amazonaws.mobileconnectors.kinesis.kinesisrecorder.FileManager.newOutputStream(FileManager.java:115)
       at com.amazonaws.mobileconnectors.kinesis.kinesisrecorder.FileRecordStore.tryInitializeWriter(FileRecordStore.java:121)
       at com.amazonaws.mobileconnectors.kinesis.kinesisrecorder.FileRecordStore.put(FileRecordStore.java:80)
       at com.amazonaws.mobileconnectors.kinesis.kinesisrecorder.AbstractKinesisRecorder.saveRecord(AbstractKinesisRecorder.java:100)
       at com.amazonaws.mobileconnectors.kinesis.kinesisrecorder.KinesisFirehoseRecorder.saveRecord(KinesisFirehoseRecorder.java:199)
```

Same issue in 2.6.18

**Comment by kvasukib** [comment]
Hi @xuaninbox, Thank you for reporting to us. Sorry for the inconvenience caused. Can you post a code snippet and verbose logs if possible?

**Comment by xuaninbox** [comment]
```
    val recorder = KinesisFirehoseRecorder(this.cacheDir, Regions.US_EAST_1,  CredentialsProvider())
    event["t_user_id"] = FirebaseAuth.getInstance().currentUser?.uid
    event["date"] = (System.currentTimeMillis() / 1000).toInt()
    recorder.saveRecord(Gson().toJson(event).toByteArray(), "${index}_${type}_prod")
    DoAsync {
        try {
            recorder.submitAllRecords()
        } catch (t: Throwable) {
        }
    }.execute()
```

u can find me on chime if u want xuazh

**Comment by muellerfr** [comment]
This issue has been closed because it has not had recent activity. Please open a new issue if you still need help.
