### ISSUE TITLE
GetToken() return java.lang.Exception: getTokens does not support retrieving tokens for federated sign-in

### ISSUE THREAD

**Issue by atomicalsoftwares** [aws-amplify/aws-sdk-android#2586]
**Describe the bug**
Using Developer Provided Identity IDs in conjunction with AWS Amplify fails as getToken() does not support retrieving tokens for federated sign-in.

**To Reproduce**

1. Initialize AWSMobileClient
2. Initialize Amplify
3. Attempt to make a call through AWS Amplify

**Which AWS service(s) are affected?**

**Expected behavior**
Developer provided identity IDs are given a JWT token, why can't AWSMobileHub access it from the custom developer provider?

**Environment Information (please complete the following information):**
Not specific to any device or versions

**Additional context**

I've enabled Cognito user pools and imported the pool to the app.
User state changes to sign in, but whenever I attempt to do an Amplify request, it does the same error.

```
D/AWSMobileClient: Using the SignInProviderConfig from `awsconfiguration.json`.
D/AWSMobileClient: Inspecting user state details
D/AWSMobileClient: _federatedSignIn: Putting provider and token in store
D/AWSMobileClient: Inspecting user state details
D/AWSMobileClient: hasFederatedToken: false provider: cognito-identity.amazonaws.com
D/AWSMobileClient: Inspecting user state details
```

```
Caused by: ApiAuthException{message=getTokens does not support retrieving tokens for federated sign-in, cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}
        at com.amplifyframework.api.aws.sigv4.DefaultCognitoUserPoolsAuthProvider.fetchToken(DefaultCognitoUserPoolsAuthProvider.java:98)
        at com.amplifyframework.api.aws.sigv4.DefaultCognitoUserPoolsAuthProvider.getLatestAuthToken(DefaultCognitoUserPoolsAuthProvider.java:104)
        at com.amplifyframework.api.aws.auth.AuthRuleRequestDecorator.getAuthToken(AuthRuleRequestDecorator.java:228)
        at com.amplifyframework.api.aws.auth.AuthRuleRequestDecorator.getIdentityValue(AuthRuleRequestDecorator.java:154)
        at com.amplifyframework.api.aws.auth.AuthRuleRequestDecorator.decorate(AuthRuleRequestDecorator.java:123)
        at com.amplifyframework.api.aws.AWSApiPlugin.buildSubscriptionOperation(AWSApiPlugin.java:628)
        at com.amplifyframework.api.aws.AWSApiPlugin.subscribe(AWSApiPlugin.java:308)
        at com.amplifyframework.api.aws.AWSApiPlugin.subscribe(AWSApiPlugin.java:288) 
        at com.amplifyframework.api.ApiCategory.subscribe(ApiCategory.java:91) 
        at com.amplifyframework.datastore.appsync.AppSyncClient.subscription(AppSyncClient.java:333) 
        at com.amplifyframework.datastore.appsync.AppSyncClient.onDelete(AppSyncClient.java:291) 
        at com.amplifyframework.datastore.syncengine.-$$Lambda$LfTnks97TCLFw65BOtt1XzQCv3w.subscribe(Unknown Source:7) 
        at com.amplifyframework.datastore.syncengine.SubscriptionProcessor.lambda$subscriptionObservable$6$SubscriptionProcessor(SubscriptionProcessor.java:182) 
        at com.amplifyframework.datastore.syncengine.-$$Lambda$SubscriptionProcessor$w6tohapLGUGmW4mOmsvNOno7GVE.subscribe(Unknown Source:11) 
        at io.reactivex.rxjava3.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40) 
        at io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13099) 
        at io.reactivex.rxjava3.internal.operators.observable.ObservableDoOnEach.subscribeActual(ObservableDoOnEach.java:42) 
        at io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13099) 
        at io.reactivex.rxjava3.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96) 
        at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614) 
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65) 
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
```

Code:

```
AWSMobileClient.getInstance().federatedSignIn("cognito-identity.amazonaws.com", credentialsProvider.getToken(),
								FederatedSignInOptions.builder().cognitoIdentityId(developerProvider.getIdentityId()).build(), new Callback<UserStateDetails>() {
									@Override
									public void onResult(UserStateDetails result) {
										Log.e("SignInState", result.getUserState().toString());
										try {
											Amplify.addPlugin(new AWSDataStorePlugin());
											Amplify.addPlugin(new AWSApiPlugin());
											Amplify.addPlugin(new AWSCognitoAuthPlugin(AWSMobileClient.getInstance(), merchant.getId()));
											Amplify.configure(mActivity);
											callProviderReady(); //This makes a Query in Amplify
											
										} catch (Exception e) {
											e.printStackTrace();
										}
									}

									@Override
									public void onError(Exception e) {
										e.printStackTrace();
									}
								});
```

SignInState: SIGNED_IN

**Comment by div5yesh** [comment]
With a federatedSignIn a user is directly federated into an Identity Pool by exchanging IdP's tokens for AWS Credentials. `getTokens` fetches Cognito User Pool tokens which in case of federation is not possible since the user does not exists in User Pool.

**Comment by div5yesh** [comment]
Amplify internally initializes AWSMobileClient. 

Use the Amplify escape hatch to directly access mobile client instance instead: https://docs.amplify.aws/lib-v1/auth/escapehatch/q/platform/android/
