### ISSUE TITLE
No field timeOffset of type I in class Lcom/amazonaws/services/iot/AWSIotClient

### ISSUE THREAD

**Issue by yyj424** [aws-amplify/aws-sdk-android#2620]
**Error**
No field timeOffset of type I in class Lcom/amazonaws/services/iot/AWSIotClient;

**Question**
https://docs.amplify.aws/sdk/pubsub/getting-started/q/platform/android/#aws-iot
I'm connecting Arduino and Android apps with the link.

But in the course of the attachpolicy,(mIotAndroidClient.attachPolicy(attachPolicyReq);)

java.lang.NoSuchFieldError: No field timeOffset of type I in class Lcom/amazonaws/services/iot/AWSIotClient; or its superclasses (declaration of 'com.amazonaws.services.iot.AWSIotClient' appears in /data/app/{package name}==/base.apk)

This error occurs. How can I solve this?
Please help me.

**my code**

```
CognitoCachingCredentialsProvider credentialsProvider = new CognitoCachingCredentialsProvider(
                    getApplicationContext(),
                    "ap-northeast-2:***",
                    Regions.AP_NORTHEAST_2
            );

AttachPolicyRequest attachPolicyReq = new AttachPolicyRequest();
            attachPolicyReq.setPolicyName("***"); 
            attachPolicyReq.setTarget(credentialsProvider.getIdentityId());
            AWSIotClient mIotAndroidClient = new AWSIotClient(credentialsProvider);
            mIotAndroidClient.setEndpoint("***");
            mIotAndroidClient.setRegion(Region.getRegion("ap-northeast-2")); 
            mIotAndroidClient.attachPolicy(attachPolicyReq);
```

**Environment**
compileSdkVersion 30
buildToolsVersion "30.0.3"

**Device** 
Galaxy S8 - Android 9(API 28)

**Comment by rjuliano** [comment]
Do you happen to have a stack trace we can look at?

**Comment by yyj424** [comment]
@rjuliano 
Thank you for your reply.
Is this what you want right?

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.hanium.greenduks, PID: 5976
    java.lang.NoSuchFieldError: No field timeOffset of type I in class Lcom/amazonaws/services/iot/AWSIotClient; or its superclasses (declaration of 'com.amazonaws.services.iot.AWSIotClient' appears in /data/app/{package name}==/base.apk)
        at com.amazonaws.services.iot.AWSIotClient.invoke(AWSIotClient.java:9850)
        at com.amazonaws.services.iot.AWSIotClient.attachPolicy(AWSIotClient.java:656)
        at com.hanium.greenduks.testActivity$MqttTask.onPostExecute(testActivity.java:111)
        at com.hanium.greenduks.testActivity$MqttTask.onPostExecute(testActivity.java:83)
        at android.os.AsyncTask.finish(AsyncTask.java:695)
        at android.os.AsyncTask.access$600(AsyncTask.java:180)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by rjuliano** [comment]
What version of the SDK are you using? I just executed your code in one of my sample apps with the latest version of the SDK and didn't see the error. One thing you may want to try is to add a dependency to the core library

```
implementation ("com.amazonaws:aws-android-sdk-core:2.30.0@aar") { transitive = true }
```

**Comment by yyj424** [comment]
@rjuliano 
I added your code and changed the version of aws-android-sdk-iot & aws-android-sdk-mobile-client to 2.30.0
it works!!!!
Thank you for helping me.
Have a nice day😄
