### ISSUE TITLE
MqttException (0) - java.io.IOException: WebSocket Response header: Incorrect upgrade.

### ISSUE THREAD

**Issue by chayandashora** [aws-amplify/aws-sdk-android#2674]
**Describe the bug**
Whenever the local date-time of android device is changed to any past date-time, then the MQTT connection becomes offline instantly and it does not recover at any point until the date and time is matched with current date-time of the time zone. 

**To Reproduce**
1. Connect device (MQTT Client) to MQTT server
2. Go to Android Settings > System > Date & Time and disable the **Use network provided time** toggle.
3. Select the **Date** option and change the date to 2-3 days back.
4. Check the MQTT Client connection

```
Logs: 

W AWSIotMqttManager: onFailure: connection failed.
W AWSIotMqttManager: MqttException (0) - java.io.IOException: WebSocket Response header: Incorrect upgrade.
W AWSIotMqttManager: 	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
W AWSIotMqttManager: 	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:738)
W AWSIotMqttManager: 	at java.lang.Thread.run(Thread.java:919)
W AWSIotMqttManager: Caused by: java.io.IOException: WebSocket Response header: Incorrect upgrade.
W AWSIotMqttManager: 	at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketHandshake.receiveHandshakeResponse(WebSocketHandshake.java:162)
W AWSIotMqttManager: 	at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketHandshake.execute(WebSocketHandshake.java:80)
W AWSIotMqttManager: 	at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketSecureNetworkModule.start(WebSocketSecureNetworkModule.java:65)
W AWSIotMqttManager: 	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:724)
W AWSIotMqttManager: 	... 1 more
```

**Which AWS service(s) are affected?**
com.amazonaws:aws-android-sdk-iot
com.amazonaws:aws-android-sdk-mobile-client

**Expected behavior**
Connection should remain established

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: [e.g. 2.19.4]
 - Device: Android 10 custom device
 - Android Version: Android 10
 - Specific to simulators: No

**Additional context**

**Comment by eeatonaws** [comment]
Closing this issue due to inactivity. Please create a new issue with the requested information if the issue persists.

**Comment by mayank1jain** [comment]
I also facing this issue. Below are the details

1. Does the issue occur with the latest version of the AWS SDK for Android?
AWS SDK for Android - 2.58.0
2. Which version of the connect method in AWSIotMqttManager are you using?
```
  val mqttManager = AWSIotMqttManager.from(
            Region.getRegion(Regions.US_WEST_2),
            AWSIotMqttManager.ClientId.fromString("D203005846"),
            AWSIotMqttManager.Endpoint.fromString("secure-broker.eloview.com")
        )
```
3. How are you checking the MQTT client connection (step 4 to reproduce)? Are you just using the onStatusChanged callback in AWSIotMqttManager.connect(...)?
Yes we are using onStatusChanged.

Logs
```
--------- beginning of system
--------- beginning of main
---------------------------- PROCESS STARTED (2711) for package com.example.provisioningtest ----------------------------
2023-03-06 17:45:49.586  2711-2797  AWSIotMqttManager       com.example.provisioningtest         D  MQTT broker: secure-broker.eloview.com:443
2023-03-06 17:45:50.640  2711-2797  AWSIotMqttManager       com.example.provisioningtest         D  ready to do mqtt connect
2023-03-06 17:45:50.640  2711-2797  AWSIotMqttManager       com.example.provisioningtest         I  metrics collection is enabled, username: ?SDK=Android&Version=2.22.6
2023-03-06 17:45:50.640  2711-2797  AWSIotMqttManager       com.example.provisioningtest         I  resetting reconnect attempt and retry time
2023-03-06 17:45:50.640  2711-2797  AWSIotMqttManager       com.example.provisioningtest         D  Setting up Callback for MqttClient
2023-03-06 17:45:52.567  2711-2805  AWSIotMqttManager       com.example.provisioningtest         I  onSuccess: mqtt connection is successful.
---------------------------- PROCESS ENDED (2711) for package com.example.provisioningtest ----------------------------
---------------------------- PROCESS STARTED (2835) for package com.example.provisioningtest ----------------------------
2023-03-06 17:46:13.732  2835-2962  AWSIotMqttManager       com.example.provisioningtest         D  MQTT broker: secure-broker.eloview.com:443
2023-03-06 17:46:13.924  2835-2962  AWSIotMqttManager       com.example.provisioningtest         D  ready to do mqtt connect
2023-03-06 17:46:13.925  2835-2962  AWSIotMqttManager       com.example.provisioningtest         I  metrics collection is enabled, username: ?SDK=Android&Version=2.22.6
2023-03-06 17:46:13.925  2835-2962  AWSIotMqttManager       com.example.provisioningtest         I  resetting reconnect attempt and retry time
2023-03-06 17:46:13.925  2835-2962  AWSIotMqttManager       com.example.provisioningtest         D  Setting up Callback for MqttClient
2023-03-06 17:46:17.087  2835-2969  AWSIotMqttManager       com.example.provisioningtest         I  onSuccess: mqtt connection is successful.
---------------------------- PROCESS ENDED (2835) for package com.example.provisioningtest ----------------------------
---------------------------- PROCESS STARTED (3101) for package com.example.provisioningtest ----------------------------



---------------------------- AFTER TIME Change ----------------------------
---------------------------- AFTER TIME Change ----------------------------

2023-03-06 22:25:33.531  3101-3175  AWSIotMqttManager       com.example.provisioningtest         D  MQTT broker: secure-broker.eloview.com:443
2023-03-06 22:25:35.744  3101-3175  AWSIotMqttManager       com.example.provisioningtest         D  ready to do mqtt connect
2023-03-06 22:25:35.744  3101-3175  AWSIotMqttManager       com.example.provisioningtest         I  metrics collection is enabled, username: ?SDK=Android&Version=2.22.6
2023-03-06 22:25:35.744  3101-3175  AWSIotMqttManager       com.example.provisioningtest         I  resetting reconnect attempt and retry time
2023-03-06 22:25:35.744  3101-3175  AWSIotMqttManager       com.example.provisioningtest         D  Setting up Callback for MqttClient
2023-03-06 22:25:43.253  3101-3185  AWSIotMqttManager       com.example.provisioningtest         W  onFailure: connection failed.
                                                                                                    MqttException (0) - java.io.IOException: WebSocket Response header: Incorrect upgrade.
                                                                                                    	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
                                                                                                    	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:738)
                                                                                                    	at java.lang.Thread.run(Thread.java:764)
                                                                                                    Caused by: java.io.IOException: WebSocket Response header: Incorrect upgrade.
                                                                                                    	at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketHandshake.receiveHandshakeResponse(WebSocketHandshake.java:162)
                                                                                                    	at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketHandshake.execute(WebSocketHandshake.java:80)
                                                                                                    	at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketSecureNetworkModule.start(WebSocketSecureNetworkModule.java:65)
                                                                                                    	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:724)
                                                                                                    	at java.lang.Thread.run(Thread.java:764) 
```

Video 
Uploading mqtt.mp4…

**Comment by eeatonaws** [comment]
@mayank1jain thank you for the additional information. Could you please also provide a code snippet for how you are calling the connect method of the AWSIotMqttManager?

**Comment by mayank1jain** [comment]
```
private fun connectMQTT() {
        try {
            mqttManager = AWSIotMqttManager.from(
                Region.getRegion(Regions.US_WEST_2),
                AWSIotMqttManager.ClientId.fromString("D203005846"),
                AWSIotMqttManager.Endpoint.fromString("secure-broker.eloview.com")
            )

            mqttManager!!.isAutoReconnect = true
            MQTTAgentUtil.setMqttManager(mqttManager)
            val lwt = AWSIotMqttLastWillAndTestament(
                TOPIC_WILL,
                WILL_MESSAGE,
                AWSIotMqttQos.QOS1
            )
            mqttManager!!.mqttLastWillAndTestament = lwt
            mqttManager!!.connect(AWSMobileClient.getInstance()) { status, _ ->
                Log.d(LOG_TAG, "Status = $status")
            }
        } catch (e: Exception) {
            Log.e(LOG_TAG, "connectMQTT error - " + e.message)
        }
    }
```

**Comment by eeatonaws** [comment]
When the device time is out of sync by more than a certain threshold (a few minutes or so), the request to connect to AWS IoT will fail since the signed URL used to connect to AWS IoT will have a time that doesn’t match the time AWS has. You can account for device clock skew by setting the time offset before connecting to AWS IoT (calling `AWSIotMqttManager.connect(…)`):
```
SDKGlobalConfiguration.setGlobalTimeOffset(offsetInSeconds);
```
where `offsetInSeconds` is the difference in seconds between the device time and the actual time, and can be negative if the device time is behind the actual time.

**Comment by eeatonaws** [comment]
Closing due to inactivity. Please create a new issue or reopen this issue if you have additional questions.

**Comment by ZubairAkber** [comment]
@eeatonaws as mentioned by @tylerjroach i am facing this issue while moving to version 2 of amplify from version 1, this issue is not replicating on version 1 of amplify

**Comment by databridge-consult** [comment]
Hi all, 

I was also faced with an issue. 

Here are my dependencies: 
implementation("com.amazonaws:aws-android-sdk-iot:2.73.0")
implementation("com.amazonaws:aws-android-sdk-mobile-client:2.73.0")

My code:
var mqttManager = from(Region.getRegion(Regions.AP_SOUTHEAST_2), mqttClientId, endpoint)

mqttManager.connect(Constants.IOT_AWS_CA_CERT,
                Constants.IOT_AWS_CERT_PEM,
                Constants.IOT_AWS_KEY,
                "dev-authorizer",
                mqttCallback)
