### ISSUE TITLE
Cronet Network Engine Support

### ISSUE THREAD

**Issue by SemihGk** [aws-amplify/aws-sdk-android#2710]
**Which AWS Services is the feature request for?**
Kinesis

**Is your feature request related to a problem? Please describe.**
We need to use Cronet network engine on android platform. However, Kinesis SDK does not seem to be compatible with Cronet Engine. Basically, I do get this error => 

```
W/System.err: com.amazonaws.AmazonClientException: Unable to execute HTTP request: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
W/System.err:     at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:456)
W/System.err:     at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:229)
W/System.err:     at com.amazonaws.services.kinesis.AmazonKinesisClient.invoke(AmazonKinesisClient.java:3344)
W/System.err:     at com.amazonaws.services.kinesis.AmazonKinesisClient.putRecord(AmazonKinesisClient.java:1576)
W/System.err:     at tv.youi.clientapp.analytics.kinesis.Kinesis.putRecords(Kinesis.java:47)
W/System.err: Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
W/System.err:     at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562)
W/System.err:     at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1403)
 W/System.err:     at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:592)
W/System.err:     at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:378)
W/System.err:     at com.amazonaws.util.json.GsonFactory$GsonReader.beginObject(GsonFactory.java:65)
W/System.err:     at com.amazonaws.services.kinesis.model.transform.PutRecordResultJsonUnmarshaller.unmarshall(PutRecordResultJsonUnmarshaller.java:33)
W/System.err:     at com.amazonaws.services.kinesis.model.transform.PutRecordResultJsonUnmarshaller.unmarshall(PutRecordResultJsonUnmarshaller.java:26)
W/System.err:     at com.amazonaws.http.JsonResponseHandler.handle(JsonResponseHandler.java:126)
W/System.err:     at com.amazonaws.http.JsonResponseHandler.handle(JsonResponseHandler.java:47)
W/System.err:     at com.amazonaws.http.AmazonHttpClient.handleResponse(AmazonHttpClient.java:661)
W/System.err:     at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:398)
W/System.err: 	... 4 more
```

When I review the request, it looks like Cronet overrides Accept-Encoding header internally. Basically, the SDK adds Accept-Encoding: identity at [here](https://github.com/aws-amplify/aws-sdk-android/blob/c9a940229d9ee43e31b8fc8fe068943798549264/aws-android-sdk-core/src/main/java/com/amazonaws/http/HttpRequestFactory.java#L114) and this header is ignored by [Cronet](https://chromium.googlesource.com/chromium/src/+/lkgr/components/cronet/android/java/src/org/chromium/net/impl/UrlRequestBuilderImpl.java?autodive=0%2F%2F#117) 

and when I check the request header, Cronet makes the header as 
<html>
<body>

Content-Encoding | gzip
-- | --
X-Amz-Target | Kinesis_20131202.PutRecord
Content-Type | application/x-amz-json-1.1
Accept-Encoding | gzip, deflate

</body>
</html>

Then, eventually fails with the exception I posted above.

**Describe the solution you'd like**
I would like to get an alternative way of sending the requests with Cronet. 

**Describe alternatives you've considered**
I tried to enable gzip through SDK configuration

```
ClientConfiguration clientConfiguration = new ClientConfiguration();
clientConfiguration.setEnableGzip(true);
AmazonKinesisClient client = new AmazonKinesisClient(awsCredentials, clientConfiguration);
```

but no luck. I still get the same exception with Cronet. Plus, I do not see backend returns the response headers with Content-Encoding as gzip even though the Accept-Encoding: gzip was sent after enabling the gzip through configuration. Is that possible I miss something with gzip? Is there any example with gzip configuration?

**Additional context**
You may also test the issue by following the llink below.
[Cronet Android Engine Selection](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/components/cronet/README.md#using-the-java_net_httpurlconnection-api)

**Comment by sktimalsina** [comment]
@hassanctech please take a look at this issue.
