### ISSUE TITLE
[IOT] MQTT can not connect to AWS server on android 12

### ISSUE THREAD

**Issue by hoangnam9194** [aws-amplify/aws-sdk-android#2741]
Hi,

**Describe the bug**
I have an android app that was tested on mobile phones using Android 8/9/10/11/12, and Android 8/9/10/11 phones are working normally, but I can’t receive notifications on android 12.

The exception I am getting (Only Android 12)! "MqttException (0) - javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found."

**To Reproduce**
1. create AWSIotMqttManager(String mqttClientId, String endpoint).
2. custom CognitoCredentialsProvider to refresh when token expired.
3. try to connect AWSIotMqttManager.

**Which AWS service(s) are affected?**
```
    MqttException (0) - javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:738)
        at java.lang.Thread.run(Thread.java:920)
     Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:363)
        at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1134)
        at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1089)
        at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
        at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
        at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
        at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:858)
        at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:731)
        at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:241)
        at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:220)
        at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:159)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:724)
        at java.lang.Thread.run(Thread.java:920) 
     Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:656)
        at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:615)
        at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:505)
        at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:425)
        at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:353)
        at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
        at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:90)
        at com.android.org.conscrypt.ConscryptEngineSocket$2.checkServerTrusted(ConscryptEngineSocket.java:163)
        at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:255)
        at com.android.org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1638)
        at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
        at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:569)
        at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
        at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079)
        at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876) 
        at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747) 
        at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712) 
        at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:858) 
        at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:731) 
        at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:241) 
        at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:220) 
        at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:159) 
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:724) 
        at java.lang.Thread.run(Thread.java:920) 
     Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:656) 
        at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:615) 
        at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:505) 
        at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:425) 
        at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:353) 
        at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94) 
        at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:90) 
        at com.android.org.conscrypt.ConscryptEngineSocket$2.checkServerTrusted(ConscryptEngineSocket.java:163) 
        at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:255) 
        at com.android.org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1638) 
        at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method) 
        at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:569) 
        at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095) 
        at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079) 
        at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876) 
        at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747) 
        at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712) 
        at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:858) 
        at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:731) 
        at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:241) 
        at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:220) 
        at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:159) 
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:724) 
        at java.lang.Thread.run(Thread.java:920) 
```

**Expected behavior**
MQTT can connect to AWS server

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: [2.36.0]
 - Device: Pixel 4, Simulator
 - Android Version: 12

**Additional context**
so, what's i need to update so that it can work for android 12?
thank you.

**Comment by duyenlv** [comment]
I encountered the same error while running on Android 12, Android 10/11 works normally.
** Environment**:
- AWS Android SDK Version: [2.36.0]
- Device: Pixel 4a≥
- Android Version: 12

```
2021-12-13 11:40:59.188 28504-28588/com.sample.android.dev W/System.err: com.amazonaws.AmazonClientException: Unable to execute HTTP request: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
2021-12-13 11:40:59.189 28504-28588/com.sample.android.dev W/System.err:     at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:456)
2021-12-13 11:40:59.189 28504-28588/com.sample.android.dev W/System.err:     at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:229)
2021-12-13 11:40:59.189 28504-28588/com.sample.android.dev W/System.err:     at com.amazonaws.services.iotdata.AWSIotDataClient.invoke(AWSIotDataClient.java:887)
2021-12-13 11:40:59.189 28504-28588/com.sample.android.dev W/System.err:     at com.amazonaws.services.iotdata.AWSIotDataClient.getThingShadow(AWSIotDataClient.java:570)
2021-12-13 11:40:59.189 28504-28588/com.sample.android.dev W/System.err:     at com.lib.core.service.iot.IotService.getShadow$lambda-10(IotService.kt:296)
2021-12-13 11:40:59.189 28504-28588/com.sample.android.dev W/System.err:     at com.lib.core.service.iot.IotService.$r8$lambda$qAuQprwsptbbNGxWXTGint8GoTM(Unknown Source:0)
2021-12-13 11:40:59.190 28504-28588/com.sample.android.dev W/System.err:     at com.lib.core.service.iot.IotService$$ExternalSyntheticLambda3.apply(Unknown Source:6)
2021-12-13 11:40:59.190 28504-28588/com.sample.android.dev W/System.err:     at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:57)
2021-12-13 11:40:59.190 28504-28588/com.sample.android.dev W/System.err:     at io.reactivex.internal.operators.observable.ObservableScalarXMap$ScalarDisposable.run(ObservableScalarXMap.java:248)
2021-12-13 11:40:59.190 28504-28588/com.sample.android.dev W/System.err:     at io.reactivex.internal.operators.observable.ObservableJust.subscribeActual(ObservableJust.java:35)
2021-12-13 11:40:59.190 28504-28588/com.sample.android.dev W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:12267)
2021-12-13 11:40:59.190 28504-28588/com.sample.android.dev W/System.err:     at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
2021-12-13 11:40:59.190 28504-28588/com.sample.android.dev W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:12267)
2021-12-13 11:40:59.190 28504-28588/com.sample.android.dev W/System.err:     at io.reactivex.internal.operators.observable.ObservableObserveOn.subscribeActual(ObservableObserveOn.java:45)
2021-12-13 11:40:59.190 28504-28588/com.sample.android.dev W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:12267)
2021-12-13 11:40:59.190 28504-28588/com.sample.android.dev W/System.err:     at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
2021-12-13 11:40:59.190 28504-28588/com.sample.android.dev W/System.err:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
2021-12-13 11:40:59.190 28504-28588/com.sample.android.dev W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
2021-12-13 11:40:59.190 28504-28588/com.sample.android.dev W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
2021-12-13 11:40:59.191 28504-28588/com.sample.android.dev W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2021-12-13 11:40:59.191 28504-28588/com.sample.android.dev W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
2021-12-13 11:40:59.191 28504-28588/com.sample.android.dev W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2021-12-13 11:40:59.191 28504-28588/com.sample.android.dev W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2021-12-13 11:40:59.191 28504-28588/com.sample.android.dev W/System.err:     at java.lang.Thread.run(Thread.java:920)
2021-12-13 11:40:59.192 28504-28588/com.sample.android.dev W/System.err: Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
2021-12-13 11:40:59.192 28504-28588/com.sample.android.dev W/System.err:     at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:363)
2021-12-13 11:40:59.192 28504-28588/com.sample.android.dev W/System.err:     at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1134)
2021-12-13 11:40:59.192 28504-28588/com.sample.android.dev W/System.err:     at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1089)
2021-12-13 11:40:59.192 28504-28588/com.sample.android.dev W/System.err:     at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
2021-12-13 11:40:59.192 28504-28588/com.sample.android.dev W/System.err:     at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
2021-12-13 11:40:59.192 28504-28588/com.sample.android.dev W/System.err:     at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
2021-12-13 11:40:59.192 28504-28588/com.sample.android.dev W/System.err:     at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:858)
2021-12-13 11:40:59.192 28504-28588/com.sample.android.dev W/System.err:     at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:731)
2021-12-13 11:40:59.192 28504-28588/com.sample.android.dev W/System.err:     at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:241)
2021-12-13 11:40:59.192 28504-28588/com.sample.android.dev W/System.err:     at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:220)
2021-12-13 11:40:59.193 28504-28588/com.sample.android.dev W/System.err:     at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:196)
2021-12-13 11:40:59.193 28504-28588/com.sample.android.dev W/System.err:     at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
2021-12-13 11:40:59.193 28504-28588/com.sample.android.dev W/System.err:     at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
2021-12-13 11:40:59.193 28504-28588/com.sample.android.dev W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
2021-12-13 11:40:59.193 28504-28588/com.sample.android.dev W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
2021-12-13 11:40:59.193 28504-28588/com.sample.android.dev W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
2021-12-13 11:40:59.193 28504-28588/com.sample.android.dev W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
2021-12-13 11:40:59.193 28504-28588/com.sample.android.dev W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
2021-12-13 11:40:59.193 28504-28588/com.sample.android.dev W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
2021-12-13 11:40:59.193 28504-28588/com.sample.android.dev W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
2021-12-13 11:40:59.194 28504-28588/com.sample.android.dev W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseMessage(HttpURLConnectionImpl.java:538)
2021-12-13 11:40:59.194 28504-28588/com.sample.android.dev W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseMessage(DelegatingHttpsURLConnection.java:110)
2021-12-13 11:40:59.194 28504-28588/com.sample.android.dev W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseMessage(HttpsURLConnectionImpl.java:30)
2021-12-13 11:40:59.194 28504-28588/com.sample.android.dev W/System.err:     at com.amazonaws.http.UrlHttpClient.createHttpResponse(UrlHttpClient.java:92)
2021-12-13 11:40:59.194 28504-28588/com.sample.android.dev W/System.err:     at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:85)
2021-12-13 11:40:59.194 28504-28588/com.sample.android.dev W/System.err:     at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:386)
2021-12-13 11:40:59.194 28504-28588/com.sample.android.dev W/System.err: 	... 23 more
2021-12-13 11:40:59.195 28504-28588/com.sample.android.dev W/System.err: Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
2021-12-13 11:40:59.195 28504-28588/com.sample.android.dev W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:656)
2021-12-13 11:40:59.195 28504-28588/com.sample.android.dev W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:615)
2021-12-13 11:40:59.195 28504-28588/com.sample.android.dev W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:505)
2021-12-13 11:40:59.195 28504-28588/com.sample.android.dev W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:425)
2021-12-13 11:40:59.195 28504-28588/com.sample.android.dev W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:353)
2021-12-13 11:40:59.196 28504-28588/com.sample.android.dev W/System.err:     at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
2021-12-13 11:40:59.196 28504-28588/com.sample.android.dev W/System.err:     at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:90)
2021-12-13 11:40:59.196 28504-28588/com.sample.android.dev W/System.err:     at com.android.org.conscrypt.ConscryptEngineSocket$2.checkServerTrusted(ConscryptEngineSocket.java:163)
2021-12-13 11:40:59.196 28504-28588/com.sample.android.dev W/System.err:     at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:255)
2021-12-13 11:40:59.196 28504-28588/com.sample.android.dev W/System.err:     at com.android.org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1638)
2021-12-13 11:40:59.196 28504-28588/com.sample.android.dev W/System.err:     at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
2021-12-13 11:40:59.196 28504-28588/com.sample.android.dev W/System.err:     at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:569)
2021-12-13 11:40:59.196 28504-28588/com.sample.android.dev W/System.err:     at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
2021-12-13 11:40:59.196 28504-28588/com.sample.android.dev W/System.err:     at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079)
2021-12-13 11:40:59.196 28504-28588/com.sample.android.dev W/System.err: 	... 46 more
2021-12-13 11:40:59.197 28504-28588/com.sample.android.dev W/System.err: Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
2021-12-13 11:40:59.197 28504-28588/com.sample.android.dev W/System.err: 	... 60 more
```

**Comment by AndreiAntonenka** [comment]
> Hi,
> 
> **Describe the bug** I have an android app that was tested on mobile phones using Android 8/9/10/11/12, and Android 8/9/10/11 phones are working normally, but I can’t receive notifications on android 12.
> 
> The exception I am getting (Only Android 12)! "MqttException (0) - javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found."
> 
> **To Reproduce**
> 
> 1. create AWSIotMqttManager(String mqttClientId, String endpoint).
> 2. custom CognitoCredentialsProvider to refresh when token expired.
> 3. try to connect AWSIotMqttManager.
> 
> **Which AWS service(s) are affected?**
> 
> ```
>     MqttException (0) - javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
>         at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
>         at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:738)
>         at java.lang.Thread.run(Thread.java:920)
>      Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
>         at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:363)
>         at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1134)
>         at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1089)
>         at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
>         at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
>         at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
>         at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:858)
>         at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:731)
>         at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:241)
>         at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:220)
>         at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:159)
>         at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:724)
>         at java.lang.Thread.run(Thread.java:920) 
>      Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
>         at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:656)
>         at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:615)
>         at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:505)
>         at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:425)
>         at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:353)
>         at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
>         at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:90)
>         at com.android.org.conscrypt.ConscryptEngineSocket$2.checkServerTrusted(ConscryptEngineSocket.java:163)
>         at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:255)
>         at com.android.org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1638)
>         at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
>         at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:569)
>         at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
>         at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079)
>         at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876) 
>         at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747) 
>         at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712) 
>         at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:858) 
>         at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:731) 
>         at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:241) 
>         at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:220) 
>         at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:159) 
>         at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:724) 
>         at java.lang.Thread.run(Thread.java:920) 
>      Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
>         at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:656) 
>         at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:615) 
>         at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:505) 
>         at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:425) 
>         at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:353) 
>         at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94) 
>         at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:90) 
>         at com.android.org.conscrypt.ConscryptEngineSocket$2.checkServerTrusted(ConscryptEngineSocket.java:163) 
>         at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:255) 
>         at com.android.org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1638) 
>         at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method) 
>         at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:569) 
>         at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095) 
>         at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079) 
>         at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876) 
>         at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747) 
>         at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712) 
>         at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:858) 
>         at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:731) 
>         at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:241) 
>         at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:220) 
>         at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:159) 
>         at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:724) 
>         at java.lang.Thread.run(Thread.java:920) 
> ```
> 
> **Expected behavior** MQTT can connect to AWS server
> 
> **Environment Information (please complete the following information):**
> 
> * AWS Android SDK Version: [2.36.0]
> * Device: Pixel 4, Simulator
> * Android Version: 12
> 
> **Additional context** so, what's i need to update so that it can work for android 12? thank you.

Hi, Faced with the same issue. Any progress?

**Comment by goranopacic** [comment]
According to https://docs.aws.amazon.com/iot/latest/developerguide/iot-connect-devices.html old accountEndpointPrefix of type iot:Data should not be used. It is described as legacy 'Verisign' endpoint and it obviously doesn't work with Android 12. 

Call: aws iot describe-endpoint --endpoint-type iot:Data-ATS

and you will get new accountEndpointPrefix ending with -ats (or you can just add -ats to your current accountEndpointPrefix) and try again. It works fine for me now.

**Comment by hoangnam9194** [comment]
hi @goranopacic , i checked and saw that we've already used endpoint with endpointType  == iot:Data-ATS (format: xxxxxxxxxxxxxx-ats.iot.us-east-1.amazonaws.com). is it correct?

**Comment by gpanshu** [comment]
If this continues to remain a problem then please reopen this issue. Closing due to inactivity and pending customer response.

**Comment by hoangnam9194** [comment]
I updated to latest version ([2.42.0](https://github.com/aws-amplify/aws-sdk-android/releases/tag/release_v2.41.0)), but still was in this trouble.

**Comment by hoangnam9194** [comment]
@gpanshu I updated to latest version ([2.42.0](https://github.com/aws-amplify/aws-sdk-android/releases/tag/release_v2.41.0)), but still was in this trouble.
Can you re-open this issue?

**Comment by sktimalsina** [comment]
@hoangnam9194 I sorry that you are still facing the issue. 
I tried combinations of Pixel 4a, 4 and 5 emulator on API 30 and 31 and Galaxy S21 physical device. But was unable to reproduce the issue. 
Could you please provide some additional info to help me dissect the issue faster.
1. Code snippet of code block that is causing to throw the error with sensitive information redacted. I am particularly interested in flavor of `connect` API from MQTTManager that you are using and publish, subscribe calls.
2. CustomCredentialsProvider if possible.

**Comment by sktimalsina** [comment]
Closing this due to inactivity. Please feel free to reopen if the issue still persists with the requested and any additional info you think will be relevant.
