### ISSUE TITLE
Incompatible with Pollfish SDK

### ISSUE THREAD

**Issue by esathamzaj** [aws-amplify/aws-sdk-android#2745]
**Describe the bug**
I use android-sdk-pollfish and when I make a release build I get this error message.

Process: xxxxxxxxxxxx PID: 14924
java.lang.RuntimeException: Unable to create application xxxxxxxxxxxx.XXXApplication: java.lang.RuntimeException: Failed to read awsconfiguration.json please check that it is correctly formed.
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6717)
    at android.app.ActivityThread.access$1300(ActivityThread.java:237)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:223)
    at android.app.ActivityThread.main(ActivityThread.java:7656)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
 Caused by: java.lang.RuntimeException: Failed to read awsconfiguration.json please check that it is correctly formed.
    at com.amazonaws.mobile.config.AWSConfiguration.<init>(AWSConfiguration.java:13)
    at xxxxxxxxxxxx.onCreate(xxxxxxxxxxxx.kt:31)
    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6712)
    at android.app.ActivityThread.access$1300(ActivityThread.java:237) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913) 
    at android.os.Handler.dispatchMessage(Handler.java:106) 
    at android.os.Looper.loop(Looper.java:223) 
    at android.app.ActivityThread.main(ActivityThread.java:7656) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
 Caused by: org.json.JSONException: End of input at character 0 of
    at org.json.JSONTokener.syntaxError(JSONTokener.java:460)
    at org.json.JSONTokener.nextValue(JSONTokener.java:101)
    at org.json.JSONObject.<init>(JSONObject.java:165)
    at org.json.JSONObject.<init>(JSONObject.java:182)
    at com.amazonaws.mobile.config.AWSConfiguration.<init>(AWSConfiguration.java:12)
    xxxxxxxxxxxx.onCreate(xxxxxxxxxxxx.kt:31) 
    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192) 
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6712) 
    at android.app.ActivityThread.access$1300(ActivityThread.java:237) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913) 
    at android.os.Handler.dispatchMessage(Handler.java:106) 
    at android.os.Looper.loop(Looper.java:223) 
    at android.app.ActivityThread.main(ActivityThread.java:7656) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
2021-12-09 15:27:06.759 14924-14960/? V/FA: Connecting to remote service

Maybe there is a conflict between dependencies but I don't know why it works on debug builds. I also added the proguard rules as specified.

FYI: Disabling proguard fixes this issue.

**To Reproduce**
A code sample or steps:
```
Your code
```

**Which AWS service(s) are affected?**

 implementation('com.amazonaws:aws-android-sdk-mobile-client:2.18.0@aar') { transitive = true }
 implementation('com.amazonaws:aws-android-sdk-auth-userpools:2.18.0@aar') { transitive = true }
 implementation 'com.amazonaws:aws-android-sdk-s3:2.18.0'
    
    
**Expected behavior**

**Screenshots**

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: [e.g. 2.6.25]
 - Device: [e.g. Pixel XL, Simulator]
 - Android Version: [e.g. Nougat 7.1.2]
 - Specific to simulators: [e.g. Yes/No]

**Additional context**

**Comment by div5yesh** [comment]
There seems to an issue with your `awsconfiguration.json` config. Can you please share the config file with **sensitive information removed**?
