### ISSUE TITLE
TransferUtility can't read awsconfiguration.json region attribute

### ISSUE THREAD

**Issue by taouichaimaa** [aws-amplify/aws-sdk-android#2784]
**Describe the bug**
I'm trying to upload a file into my s3 bucket using transferUtility , I've added the 
```
"S3TransferUtility": {
        "Default": {
            "Bucket": "bucket-deployment",
            "Region": "us-region"
        }
    }
```

 section to my awsconfiguration.json but I keep getting: 

  ```
  java.lang.IllegalArgumentException: Failed to read S3TransferUtility please check your setup or awsconfiguration.json file
        at com.amazonaws.mobileconnectors.s3.transferutility.TransferUtility$Builder.build(TransferUtility.java:292)
```
 this is the code i use for uploading: 
```
fun setAmazonS3Client() {
        s3 = AmazonS3Client(AWSMobileClient.getInstance().awsCredentials, Region.getRegion(Regions.US_REGION))

    }
    fun setTransferUtility() {
        transferUtility = TransferUtility.builder()
            .context(requireContext())
            .awsConfiguration(AWSMobileClient.getInstance().configuration)
            .s3Client(s3)
            .build()

    }
 fun upload(transferUtility: TransferUtility,fileKey:String,filename:File) {
 val observer: TransferObserver = transferUtility.upload(
     "bucket-deployment",
            fileKey,
          filename,
            CannedAccessControlList.PublicRead
        )
        observer.setTransferListener(object : TransferListener {
            override fun onStateChanged(id: Int, state: TransferState) {
                if (state == TransferState.COMPLETED) {
                    Log.i("state changed", state.toString() + "")
                } else if (state == TransferState.FAILED) {
                    Log.e("state changed", state.toString() + "")
                }
            }

            override fun onProgressChanged(id: Int, bytesCurrent: Long, bytesTotal: Long) {
                val percentDonef = bytesCurrent.toFloat() / bytesTotal.toFloat() * 100
                val percentDone = percentDonef.toInt()

                Log.d(
                    "TransferProg", "ID:$id bytesCurrent: " + bytesCurrent
                        .toString() + " bytesTotal: " + bytesTotal.toString() + " " + percentDone.toString() + "%"
                )
            }
            override fun onError(id: Int, ex: Exception) {
                Log.e("state changed", ex.toString() + "")
            }
        })
    }

```

**To Reproduce**
A code sample or steps:
```
view above
```

**Which AWS service(s) are affected?**

**Expected behavior**
read from awsConfiguration.json

**Screenshots**

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: [ 2.38.0]
 - Device: [physical device
 - Android Version: [11]
 - Specific to simulators: [No]

**Additional context**

**Comment by eeatonaws** [comment]
Hi @taouichaimaa, `US_REGION` is not one of the regions defined in `Regions`. Please use one of the regions in Regions.java, located [here](https://github.com/aws-amplify/aws-sdk-android/blob/8de48797ae2e5c157169a94746c768da7de61056/aws-android-sdk-core/src/main/java/com/amazonaws/regions/Regions.java).

**Comment by taouichaimaa** [comment]
Hi, in reality I have us-east-1 in my config file , I just put that for security sake.

**Comment by sagar-docterz** [comment]
Process: com.thepediatricnetwork.receptionapp.stage, PID: 19010
                                                                                                    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=123, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:3892 flg=0x1 }} to activity {com.thepediatricnetwork.receptionapp.stage/com.thepediatricnetwork.receptionapp.activities.AddRecordsActivity}: java.lang.IllegalArgumentException: Failed to read S3TransferUtility please check your setup or awsconfiguration.json file
                                                                                                    	at android.app.ActivityThread.deliverResults(ActivityThread.java:5590)
                                                                                                    	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5631)
                                                                                                    	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:246)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8653)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
                                                                                                    Caused by: java.lang.IllegalArgumentException: Failed to read S3TransferUtility please check your setup or awsconfiguration.json file
                                                                                                    	at com.amazonaws.mobileconnectors.s3.transferutility.TransferUtility$Builder.build(TransferUtility.java:292)
                                                                                                    	at com.thepediatricnetwork.receptionapp.utils.AWSUtils.uploadFileToS3(AWSUtils.kt:32)
                                                                                                    	at com.thepediatricnetwork.receptionapp.activities.AddRecordsActivity.uploadFile(AddRecordsActivity.kt:524)
                                                                                                    	at com.thepediatricnetwork.receptionapp.activities.AddRecordsActivity.onActivityResult(AddRecordsActivity.kt:401)
                                                                                                    	at android.app.Activity.dispatchActivityResult(Activity.java:8550)
                                                                                                    	at android.app.ActivityThread.deliverResults(ActivityThread.java:5583)
                                                                                                    	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5631) 
                                                                                                    	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loop(Looper.java:246) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8653) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
