### ISSUE TITLE
TransferNetworkLossHandler throws ConcurrentModificationException

### ISSUE THREAD

**Issue by sktimalsina** [aws-amplify/aws-sdk-android#2802]
**Describe the bug**
Here is a summary of the problem :
1. Android app with support to upload metrics and images to S3
1. At app startup, we scan our local storage for files to upload and start transfer for each file
1. As each transfer completes our app deletes the file to keep local storage clear
 
The problem occurs when there is a network outage or no wifi connection on device.  As the app is creating transfer requests the app crashes with following trace:
 
```
2022-02-09 18:38:58.613 17329-17360/com.amazon.jackjack E/AndroidRuntime: FATAL EXCEPTION: Thread-239
    Process: com.amazon.jackjack, PID: 17329
    java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextEntry(HashMap.java:787)
        at java.util.HashMap$ValueIterator.next(HashMap.java:819)
        at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:960)
        at com.amazonaws.mobileconnectors.s3.transferutility.TransferNetworkLossHandler.pauseAllTransfersDueToNetworkInterruption(TransferNetworkLossHandler.java:212)
        at com.amazonaws.mobileconnectors.s3.transferutility.TransferNetworkLossHandler.access$100(TransferNetworkLossHandler.java:37)
        at com.amazonaws.mobileconnectors.s3.transferutility.TransferNetworkLossHandler$1.run(TransferNetworkLossHandler.java:125)
        at java.lang.Thread.run(Thread.java:818)
```
 
 
It looks like a problem inside TransferNetworkLossHandler.pauseAllTransfersDueToNetworkInterruption :
 
    private synchronized void pauseAllTransfersDueToNetworkInterruption() {
        for (final TransferRecord transferRecord : updater.getTransfers().values()) {
            final AmazonS3 s3 = S3ClientReference.get([transferRecord.id](http://transferrecord.id/));
            if (s3 != null && 
                transferRecord != null && 
                transferRecord.pauseIfRequiredForNetworkInterruption(s3, updater, connManager)) {
                updater.updateState([transferRecord.id](http://transferrecord.id/), TransferState.WAITING_FOR_NETWORK);
            }
        }
    }
 
The for loop iterator [updater.getTransfers().values()] must fail if the transfer list is updated during the conversion in TransferStatusUpdater.getTransfers :
 
    synchronized Map<Integer, TransferRecord> getTransfers() {
        return Collections.unmodifiableMap(transfers);
    }
 
During the time it crashes, there are transfers being created from the metrics or POD directories so it does seem like a timing issue.  I don’t see how we can protect against this problem though as it happens in other threads so we can’t catch the exception.

**To Reproduce**
A code sample or steps:
```
Your code
```

**Which AWS service(s) are affected?**
Storage

**Expected behavior**
No exception

**Screenshots**

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.16.x
 - Device: [e.g. Pixel XL, Simulator]
 - Android Version: [e.g. Nougat 7.1.2]
 - Specific to simulators: [e.g. Yes/No]

**Additional context**

**Comment by sktimalsina** [comment]
Closing this as it is no longer relevant as per notes.
