### ISSUE TITLE
Getting error while fetching and uploading files on s3 bucket: wrapped.errorStream must not be null

### ISSUE THREAD

**Issue by jaypratapsingh** [aws-amplify/aws-sdk-android#2807]
While fetching or uploading files on AWS S3 Bucket getting below error:

```
2022-02-23 12:44:34.434 9205-9365/com.app W/System.err: java.lang.NullPointerException: wrapped.errorStream must not be null
2022-02-23 12:44:34.434 9205-9365/com.app W/System.err:     at com.android.tools.appinspection.network.httpurl.TrackedHttpURLConnection.getErrorStream(TrackedHttpURLConnection.kt:155)
2022-02-23 12:44:34.434 9205-9365/com.app W/System.err:     at com.android.tools.appinspection.network.httpurl.HttpsURLConnectionWrapper.getErrorStream(HttpsURLConnectionWrapper.kt:130)
2022-02-23 12:44:34.434 9205-9365/com.app W/System.err:     at com.amazonaws.http.UrlHttpClient.createHttpResponse(UrlHttpClient.java:94)
2022-02-23 12:44:34.434 9205-9365/com.app W/System.err:     at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:85)
2022-02-23 12:44:34.434 9205-9365/com.app W/System.err:     at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:386)
2022-02-23 12:44:34.434 9205-9365/com.app W/System.err:     at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:229)
2022-02-23 12:44:34.434 9205-9365/com.app W/System.err:     at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4829)
2022-02-23 12:44:34.434 9205-9365/com.app W/System.err:     at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4777)
2022-02-23 12:44:34.434 9205-9365/com.app W/System.err:     at com.amazonaws.services.s3.AmazonS3Client.listObjectsV2(AmazonS3Client.java:916)
```

using gradle plugin: com.amazonaws:aws-android-sdk-s3:2.39.0 and also tried version 2.41.0 also but nothing working.

**Comment by jaypratapsingh** [comment]
@lakinduboteju Nope I am not using any network inspector even I am also facing same issue on mobile device.

**Comment by lakinduboteju** [comment]
@jaypratapsingh, In you stack trace of the Exception, it shows a presence of `com.android.tools.appinspection.network`, which is the Network Inspector tool. That's why I suspected that you are running it when your app runs. Thanks for the reply.

**Comment by sktimalsina** [comment]
@jaypratapsingh Do you see this issue outside android studios? (ex command shell logcat or crashalytics etc). This might be related to issue in Android Studio's implementation where the migrated Kotlin code (HttpsURLConnectionWrapper) seems to be culprit (see [Google Issue](https://issuetracker.google.com/issues/219572925))

**Comment by jaypratapsingh** [comment]
@lakinduboteju Yes, I am not using network inspector but I am using the Background Task Inspector to check the worker is executed or not. So I think when I open App Inspection to check the Background Task Inspector the Network task inspector is also there, might be that run automatically and create the issue. But when I run the same app on mobile the issue also replicate. I am attaching screenshot of my mobile device you check there.

![Screenshot_2022-02-22-19-01-07-166_com doobert app](https://user-images.githubusercontent.com/11877215/155440697-c4f79f17-86ae-418d-bd54-5f61f82ad79a.jpg)

@sktimalsina Nope issue doesn't report on crashlytics. I suspect is this issue related to work manager because when I upload the file on button click file upload without any errors but when I schedule the file upload for 5 mins then it creates the error. And after that when I go to download or fetching files from bucket then again the error produce.

**Comment by girishacme** [comment]
Any update on this?
I am also facing the same issue without using any AppInspection.

Failed to upload: 28 due to wrapped.errorStream must not be null
exception: java.lang.NullPointerException: wrapped.errorStream must not be null

**Comment by sdhuka** [comment]
@girishacme Could you please provide a detailed repro steps for this issue? We can look into fixing this after figuring out the root cause.

**Comment by girishacme** [comment]
@sdhuka I am simply uploading my assets data (images / videos etc.) on S3.
For example, I am uploading 20 assets, sometimes all gets uploaded successfully, sometimes when few gets uploaded, others are in progress, I get this error suddenly.
Do let me know, if you need anything else.

**Comment by girishacme** [comment]
@sdhuka Any update on this?

**Comment by sdhuka** [comment]
@girishacme I am not able to repro. Could you please share more details?

1) Android OS Version?
2) AWS Android SDK Version?
3) Any sample app/code demonstrating the issue?

**Comment by sdhuka** [comment]
Closing due to inactivity, please open a new issue if issue persists in the latest SDK.
