### ISSUE TITLE
Connect to cognito-identity.us-east-1.amazonaws.com:443

### ISSUE THREAD

**Issue by zstartw** [aws-amplify/aws-sdk-android#2811]
I created the server token and identity id with reference to this official webpage,[Developer authenticated identities][1] but the following error is reported, please help me find out the problem
 

 

    Caused by: org.apache.http.conn.HttpHostConnectException: Connect to cognito-identity.us-east-1.amazonaws.com:443 [cognito-identity.us-east-1.amazonaws.com/127.0.0.1] failed: Connection refused: connect
        	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
        	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
        	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        	at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76)
        	at com.amazonaws.http.conn.$Proxy2.connect(Unknown Source)
        	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
        	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
        	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
        	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1343)
        	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1154)
        	... 13 more

  [1]: https://docs.aws.amazon.com/cognito/latest/developerguide/developer-authenticated-identities.html

**Comment by zstartw** [comment]
Now it has work fine. This problem does not arise anymore
