### ISSUE TITLE
NotificationClientBase.java , Fatal Exception: java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by kcj30906** [aws-amplify/aws-sdk-android#2813]
**Describe the bug**
NotificationClientBase.java line 572 crash 
Fatal Exception: java.lang.IllegalArgumentException
Wrong number of arguments; expected 2, got 1

**To Reproduce**
1. Go to 'Start'

**Screenshots**
![스크린샷 2021-10-26 오후 1 25 34](https://user-images.githubusercontent.com/3112531/138808842-fd6f11cd-2702-47ff-984d-3c2ed6e6c94b.png)

**Expected behavior**
This crash event occurred within the first 3 seconds of starting a user session.

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - OS: [e.g. Android11, Android10, Android9, Android8, Android7, Android6, Android5]

**Additional context**

- Lib version
  com.amazonaws:aws-android-sdk-pinpoint:2.25.0
  com.amazonaws:aws-android-sdk-mobile-client:2.25.0@aar

 - Log trace 
`Fatal Exception: java.lang.IllegalArgumentException: Wrong number of arguments; expected 2, got 1
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
       at com.amazonaws.mobileconnectors.pinpoint.targeting.notification.NotificationClientBase.createNotification(NotificationClientBase.java:572)
       at com.amazonaws.mobileconnectors.pinpoint.targeting.notification.NotificationClientBase.access$100(NotificationClientBase.java:59)
       at com.amazonaws.mobileconnectors.pinpoint.targeting.notification.NotificationClientBase$1.run(NotificationClientBase.java:732)
       at java.lang.Thread.run(Thread.java:923)`

**Comment by sdhuka** [comment]
@kcj30906 I am not able to repro the issue on Android 11. 

Could you please provide more details on how to repro this issue?
