### ISSUE TITLE
cognitoidentityprovider: RuntimeException with IllegalArgumentException: Invalid userPoolId format

### ISSUE THREAD

**Issue by Eric-Cen** [aws-amplify/aws-sdk-android#2822]
**Describe the bug**

```
private val userPool: CognitoUserPool = CognitoUserPool(context, COGNITO_POOL_ID,
            COGNITO_CLIENT_ID, COGNITO_CLIENT_SECRET, Regions.US_EAST_1)
```
In Android project, the code above runs fine with implementation 'com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.32.0' in build.gradle.

However, if I try to update the library version 2.33.0 or even the latest 2.41.1, it crashes the app:

Error:
    java.lang.RuntimeException: Unable to start activity ComponentInfo{}: java.lang.IllegalArgumentException: Invalid userPoolId format.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7664)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.IllegalArgumentException: Invalid userPoolId format.
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUserPool.<init>(CognitoUserPool.java:280)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUserPool.<init>(CognitoUserPool.java:255)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUserPool.<init>(CognitoUserPool.java:221)

**To Reproduce**
A code sample or steps:
```
private val userPool: CognitoUserPool = CognitoUserPool(context, COGNITO_POOL_ID,
            COGNITO_CLIENT_ID, COGNITO_CLIENT_SECRET, Regions.US_EAST_1)
```

implementation 'com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.41.1' in build.gradle.

**Which AWS service(s) are affected?**
Cognito, com.amazonaws:aws-android-sdk-cognitoidentityprovider

**Expected behavior**
No crash, successfully retrieve the CognitoUserPool object from AWS service

**Screenshots**

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.41.1
 - Device: Pixel 3 XL(API 30), Emulator Pixel 2 (API 21)
 - Android Version: 11
 - Specific to simulators: No

**Additional context**

**Comment by eeatonaws** [comment]
Hi @Eric-Cen. Version 2.33.0 of the AWS SDK for Android introduced additional checks for the format of the user pool ID: 1) the length is less than or equal to 55 and 2) matches the regex "^[\\w-]+_[0-9a-zA-Z]+$". An IllegalArgumentException is thrown if one or both of these requirements are not met. Please check that your user pool ID satisfies these requirements.

**Comment by eeatonaws** [comment]
Closing due to inactivity. Please comment or reopen this issue if you have additional questions.

**Comment by Eric-Cen** [comment]
This regex check doesn't match with the document from https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-name.html.

Is there a way to bypass this regex check?  This is preventing us from using the latest aws-android-sdk-cognitoidentityprovider library with the existing user pool.

**Comment by div5yesh** [comment]
UserPoolId is different from user pool name. User Pool Name is a friendly readable format string as mentioned in the link you posted above. UserPoolId is of the form `<region>_<poolId>` (eg: us-east-1_xxXX00XX).
