### ISSUE TITLE
[IoT Core] Getting Error while using device advisor test endpoint to connect to IoT

### ISSUE THREAD

**Issue by whlanita** [aws-amplify/aws-sdk-android#2832]
**Describe the bug**
I tried to connect to IoT with device advisor test endpoint, but failed.
I got "Cannot parse region from endpoint" from the log, but the endpoint is from device advisor.
The log are below:
03-11 17:56:12.394 E/AndroidRuntime( 8985): Caused by: java.lang.IllegalArgumentException: Cannot parse region from endpoint.
03-11 17:56:12.394 E/AndroidRuntime( 8985):     at com.amazonaws.mobileconnectors.iot.AwsIotEndpointUtility.getRegionFromIotEndpoint(AwsIotEndpointUtility.java:53)
03-11 17:56:12.394 E/AndroidRuntime( 8985):     at com.amazonaws.mobileconnectors.iot.AWSIotMqttManager.<init>(AWSIotMqttManager.java:660)

**To Reproduce**
Connect to IoT with device advisor test endpoint

**Which AWS service(s) are affected?**
IoT & device advisor

**Expected behavior**
The device can connect to IoT.

**Screenshots**
no

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.15.2
 - Device: IFP
 - Android Version: 11
 - Specific to simulators: No

**Additional context**

**Comment by sdhuka** [comment]
@whlanita Could you please update the SDK version to the latest('2.42.0') and retry? 2.15.2 is very old version and since then we have refactored the code to region for an endpoint.

**Comment by sktimalsina** [comment]
Closing this issue due to inactivity. Please reopen if needed.
