### ISSUE TITLE
Timeout Problem for AWSMobileClient.getInstance().signUp function

### ISSUE THREAD

**Issue by hasbisevinc** [aws-amplify/aws-sdk-android#2852]
**Describe the bug**
AWSMobileClient.getInstance().signUp function sometimes throws a timeout error with an "Unable to execute HTTP request: timeout" message. Why do we get sometimes this error?

full error message:
`
E : com.amazonaws.AmazonClientException: Unable to execute HTTP request: timeout
E : at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:441)
E : at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
E : at com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.invoke(AmazonCognitoIdentityProviderClient.java:6261)
E : at com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.signUp(AmazonCognitoIdentityProviderClient.java:5290)
E : at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUserPool.signUpInternal(CognitoUserPool.java:472)
E : at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUserPool.signUp(CognitoUserPool.java:418)
E : at com.amazonaws.mobile.client.AWSMobileClient$13.run(AWSMobileClient.java:1847)
E : at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
E : at java.lang.Thread.run(Thread.java:919)
E : Caused by: java.net.SocketTimeoutException: timeout
E : at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:214)
E : at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:263)
E : at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
E : at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:307)
E : at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:301)
E : at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:197)
E : at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:188)
E : at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:129)
E : at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:770)
E : at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:642)
E : at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
E : at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
E : at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseMessage(HttpURLConnectionImpl.java:538)
E : at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseMessage(DelegatingHttpsURLConnection.java:110)
E : at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseMessage(HttpsURLConnectionImpl.java:30)
E : at com.amazonaws.http.UrlHttpClient.createHttpResponse(UrlHttpClient.java:92)
E : at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:85)
E : at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:371)
E : ... 8 more
E : Caused by: java.net.SocketException: socket is closed
E : at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:554)
E : at com.android.okhttp.okio.Okio$2.read(Okio.java:138)
E : at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:213)
E : ... 23 more
`

**To Reproduce**
- The bug cannot be reproduced at all times. It happens randomly
- call AWSMobileClient.getInstance().signUp(..) function with new a new email and password

**Which AWS service(s) are affected?**
AWSMobileClient

**Expected behavior**
Sign up function should perform the signing up process without a timeout

**Comment by gpanshu** [comment]
Hi @hasbisevinc could you provide a little more detail on how we may be able to reproduce this? I have tried consecutive signups on the same email and different emails and did not see this. I tried on the emulator and also Samsung S20 5G. Can you please advise which phone, OS you are seeing it. Also if you can mention which version of the library you are using. Have you tried using the Amplify Android library instead?

**Comment by sktimalsina** [comment]
Closing this due to inactivity. If you are still facing the issue, please feel free to reopen with the additional info requested.
