### ISSUE TITLE
AWS S3 Android SDK - TransferUtility.java - Fatal Exception: java.lang.IllegalStateException

### ISSUE THREAD

**Issue by yifeifiona** [aws-amplify/aws-sdk-android#2866]
**Describe the bug**
Calling `transferUtility.getTransfersWithType(TransferType.UPLOAD)` results in `Fatal Exception: java.lang.IllegalStateException`.
Stack trace: 
```
Fatal Exception: java.lang.IllegalStateException: Couldn't read row 998, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
       at android.database.CursorWindow.nativeGetLong(CursorWindow.java)
       at android.database.CursorWindow.getLong(CursorWindow.java:511)
       at android.database.CursorWindow.getInt(CursorWindow.java:578)
       at android.database.AbstractWindowedCursor.getInt(AbstractWindowedCursor.java:69)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferUtility.getTransfersWithType(TransferUtility.java:673)
```

Is there a way to `cleanup/ reset` the TransferUtility internal SQLite state to fix the issue? 

**To Reproduce**
A code sample or steps:
```
fun archiveAddAllNewToQueue(path: String?) {
        synchronized(lock) {
              ...
              val existingTransfers = transferUtility.getTransfersWithType(TransferType.UPLOAD)  // Triggers the Exceptoin
              ...
        }
}
```

**Which AWS service(s) are affected?**
s3 file upload with TransferUtility

**Expected behavior**
Calling `transferUtility.getTransfersWithType(...)` does not trigger IllegalStateException and crashes the app

**Screenshots**

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: [e.g. 2.6.25] - `com.amazonaws:aws-android-sdk-s3:2.34.0`
 - Device: [e.g. Pixel XL, Simulator] - AOSP Device
 - Android Version: [e.g. Nougat 7.1.2]  - Android 6 
 - Specific to simulators: [e.g. Yes/No] -  No

**Additional context**

I found this similar issue (not the same) from the past, which has been fixed by paginating the cursor: https://github.com/aws-amplify/aws-sdk-android/issues/288 
The fix is supposed to be released in TransferUtility 2.6.16, but the fix does not resolve my issue.

**Comment by eeatonaws** [comment]
Closing due to inactivity. Please reopen this issue or create a new issue with the requested information.
