### ISSUE TITLE
Crash due to InternalCallback: Duplicate call to execute code. 

### ISSUE THREAD

**Issue by abhishek-mobile** [aws-amplify/aws-sdk-android#2963]
**Describe the bug**
When ever I am trying to run below code I am getting crash. till now we have total 3.2k crashes recorded. 

**To Reproduce**
* Init AWS SDK before login as per document https://docs.amplify.aws/sdk/auth/getting-started/q/platform/android/#install-dependencies.

```
  AWSMobileClient.getInstance().initialize(
                APIApplicationContext.appContext,
                object : Callback<UserStateDetails> {
                    override fun onResult(userStateDetails: UserStateDetails) {
                        Log.i("INIT", "onResult: " + userStateDetails.userState)
                        if (userStateDetails != null && userStateDetails.userState == UserState.SIGNED_IN) {
                            AWSMobileClient.getInstance().signOut()
                        }
                        loginAction(request)
                        CognitoManager.isInitialize = true
                    }
                    override fun onError(e: java.lang.Exception) {
                        Log.e("INIT", "Initialization error.", e)
                    }
                }
            )
```

**Which AWS service(s) are affected?**
AWS Authentication 
**Expected behavior**
App should not crash 

**Screenshots**
<img width="1329" alt="Screenshot 2022-08-02 at 12 25 47 AM" src="https://user-images.githubusercontent.com/110421612/182223026-16f30a0d-5662-45c6-930b-831410712305.png">

**Environment Information (please complete the following information):**
- implementation 'com.amazonaws:aws-android-sdk-mobile-client:2.49.0'
- implementation 'com.amazonaws:aws-android-sdk-auth-userpools:2.49.0'
- implementation 'com.amazonaws:aws-android-sdk-auth-ui:2.49.0'

**Additional context**
Error log

```
2022-08-01 23:57:18.689 7264-7264/com.orbit.driverapp E/InternalCallback: Duplicate call to execute code.
    java.lang.RuntimeException: Internal error, duplicate call
        at com.amazonaws.mobile.client.internal.InternalCallback.async(InternalCallback.java:93)
        at com.amazonaws.mobile.client.AWSMobileClient.signIn(AWSMobileClient.java:1196)
        at com.amazonaws.mobile.client.AWSMobileClient.signIn(AWSMobileClient.java:1185)
        at com.orbit.driver_application_api.crud_operation.master.login.DriverLoginAPI.loginAction(DriverLoginAPI.kt:81)
        at com.orbit.driver_application_api.crud_operation.master.login.DriverLoginAPI.call(DriverLoginAPI.kt:67)
        at com.orbit.driverapp.activity.welcome.welcomefragment.WelcomeFragment.loginForBackgroundSync(WelcomeFragment.kt:652)
        at com.orbit.driverapp.activity.welcome.welcomefragment.WelcomeFragment.onResume(WelcomeFragment.kt:401)
        at androidx.fragment.app.Fragment.performResume(Fragment.java:3039)
        at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:607)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:306)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
        at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:3086)
        at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:273)
        at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:458)
        at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:447)
        at androidx.appcompat.app.AppCompatActivity.onPostResume(AppCompatActivity.java:240)
        at android.app.Activity.performResume(Activity.java:7964)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4195)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4237)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2022-08-01 23:57:18.730 7264-7264/com.orbit.driverapp E/OSSDK_Demo: onError: DeviceManager:HoneywellOSService not connected
2022-08-01 23:57:18.735 7264-7264/com.orbit.driverapp E/com.orbit.driverapp.activity.welcome.welcomefragment.WelcomeFragment: entering enableUserInteraction()
2022-08-01 23:57:20.455 7264-7872/com.orbit.driverapp E/AndroidRuntime: FATAL EXCEPTION: Thread-32
    Process: com.orbit.driverapp, PID: 7264
    java.lang.NullPointerException: Attempt to invoke interface method 'void com.amazonaws.mobile.client.Callback.onError(java.lang.Exception)' on a null object reference
        at com.amazonaws.mobile.client.internal.InternalCallback.call(InternalCallback.java:77)
        at com.amazonaws.mobile.client.internal.InternalCallback.access$000(InternalCallback.java:34)
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:103)
        at java.lang.Thread.run(Thread.java:919)

```

**Comment by eeatonaws** [comment]
Thank you for reporting this issue. Where is the code block you shared (for initializing AWSMobileClient and signing in) being run, is it in the `onCreate` of your app's `MainActivity`? From the logs, the issue is occurring when `AWSMobileClient.signIn(...)` is called. Could you share the contents of the `loginAction(request)` function from your code snippet?

**Comment by eeatonaws** [comment]
Closing due to inactivity. Please create a new issue or reopen this issue with the requested information if the issue persists.
