### ISSUE TITLE
AuthException{message=Sign-in with web UI failed, cause=java.lang.Exception: showSignIn called without HostedUI options in awsconfiguration.json, recoverySuggestion=See attached exception for more details}

### ISSUE THREAD

**Issue by YawarOsman** [aws-amplify/aws-sdk-android#2990]
**Describe the bug**
I am trying to LogIn with Google to my app in `Flutter` but it show this error:
```
E/amplify:flutter:auth_cognito(10680): AuthException
E/amplify:flutter:auth_cognito(10680): AuthException{message=Sign-in with web UI failed, cause=java.lang.Exception: showSignIn called without HostedUI options in awsconfiguration.json, recoverySuggestion=See attached exception for more details}
E/amplify:flutter:auth_cognito(10680): 	at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin$23.onError(AWSCognitoAuthPlugin.java:1275)
E/amplify:flutter:auth_cognito(10680): 	at com.amazonaws.mobile.client.internal.InternalCallback.call(InternalCallback.java:77)
E/amplify:flutter:auth_cognito(10680): 	at com.amazonaws.mobile.client.internal.InternalCallback.onError(InternalCallback.java:67)
E/amplify:flutter:auth_cognito(10680): 	at com.amazonaws.mobile.client.AWSMobileClient$25.run(AWSMobileClient.java:3274)
E/amplify:flutter:auth_cognito(10680): 	at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
E/amplify:flutter:auth_cognito(10680): 	at java.lang.Thread.run(Thread.java:923)
E/amplify:flutter:auth_cognito(10680): Caused by: java.lang.Exception: showSignIn called without HostedUI options in awsconfiguration.json
E/amplify:flutter:auth_cognito(10680): 	... 3 more
I/flutter (10680): Sign-in with web UI failed
```

**To Reproduce**
A code sample:
```
  try {
      final result = await Amplify.Auth.signInWithWebUI(provider: AuthProvider.google);
      print('Result: $result');
       } on AmplifyException catch (e) {
           print('${e.message}');
       }
```

**Expected behavior**
I expect to see google login page but this error is showed up.

I have used AWS Amplify LogIn with email and password before and it works without any error, i don't know what is wrong now.

**Environment Information (please complete the following information):**
 - Device: [Android Emultor]
 - Android Version: [android 11.0 x86]
 - Specific to simulators: [Yes]

**pubspec.yaml**
```
  amplify_flutter: ^0.6.5
  amplify_auth_cognito: ^0.6.5
  amplify_analytics_pinpoint: ^0.6.5
  amplify_api: ^0.6.5
  amplify_datastore: ^0.6.5
  amplify_storage_s3: ^0.6.5
```

**Comment by sktimalsina** [comment]
Have you setup your auth configuration to use hosted UI using aws cli as outlined here:
https://docs.amplify.aws/lib/auth/signin_web_ui/q/platform/flutter/#configure-auth-category
