### ISSUE TITLE
 java.lang.OutOfMemoryError：org.eclipse.paho.client.mqttv3.internal.CommsReceiver.start(CommsReceiver.java:77)

### ISSUE THREAD

**Issue by WooYu** [aws-amplify/aws-sdk-android#3025]
**Describe the bug**
App crash

**To Reproduce**
A code sample or steps:
```
 public synchronized void connectMqtt(MqttConnectParam connectParam) {
        if (null == connectParam) {
            LogFileUtils.e(TAG, "connectMqtt()-> connectParam is null!");
            return;
        }
        mMqttConnectParams = connectParam;
        String dataEndpoint = SpUtil.getInstance().getStringValue(ENDPOINT_STRING_KEY);
        String iotConnectStatus = getAWSIotMqttManagerConnectStatus();

        if (!subscribedTopicList.isEmpty()) {
            subscribedTopicList.clear();
        }
        try {
            String userInfoId = DiagnosisApplication.userInfo.getId();
            String newClientId = "chat-" + userInfoId + Math.round((Math.random() * 1000000) + 1);
            LogFileUtils.d(TAG, "connectMqtt()-> newClientId = " + newClientId + " , lastConnectStatus = " + iotConnectStatus);
            mAWSIotMqttManager = new AWSIotMqttManager(newClientId, dataEndpoint);
            mAWSIotMqttManager.setKeepAlive(10);
            mAWSIotMqttManager.setAutoReconnect(true);
            mAWSIotMqttManager.setOfflinePublishQueueEnabled(false);

            BasicSessionCredentials credentials = new BasicSessionCredentials(
                    connectParam.getAwsAccessKeyId(), connectParam.getAwsSecretAccessKey(),
                    connectParam.getSessionToken());
            AWSCredentialsProvider provider = new AWSCredentialsProvider() {
                @Override
                public AWSCredentials getCredentials() {
                    return credentials;
                }

                @Override
                public void refresh() {

                }
            };

            SimpleDateFormat format = new SimpleDateFormat("HH:mm:ss");
            format.setTimeZone(TimeZone.getTimeZone("UTC"));
            LogFileUtils.i(AppConstBean.TAG_MQTT, "时区时间：" + format.format(System.currentTimeMillis()) + " currentTimeMillis:" + System.currentTimeMillis());
            mAWSIotMqttManager.connect(provider, (status, throwable) -> {
                LogFileUtils.e(AppConstBean.TAG_MQTT, "onStatusChanged clientId = " + newClientId + " , status = " + status.name());
                if (null != throwable) {
                    LogFileUtils.e(AppConstBean.TAG_MQTT, throwable.toString());
                }

                if (TextUtils.equals(status.name(), "Connected")) {
                    subscribeTopic();
                }else if (TextUtils.equals(status.name(), "Reconnecting") && null != throwable) {
                    LogFileUtils.e(AppConstBean.TAG_MQTT, "connectMqtt onStatusChanged() you need to obtain the iot connection information again!");
                    boolean isNetworkIsConnected = NetBroadcastReceiver.getInstance().isNetworkIsConnected();
                    if (!isNetworkIsConnected) {
                        return;
                    }
                    //解决https://jira.autel.com/browse/REM-6950 MqttException (0) - java.io.IOException: WebSocket Response header: Incorrect upgrade.
                    onHandleIotConnectExcept();
                }
            });

        } catch (Throwable e) {
            LogFileUtils.e(TAG, "connectMqtt Throwable:" + e);
            e.printStackTrace();
        }
    }
```

**Which AWS service(s) are affected?**
Android 4.4

**Expected behavior**
09-16 16:13:46.225  6777  3515 E AndroidRuntime: FATAL EXCEPTION: MQTT Con: chat-1552575548608749570999222
09-16 16:13:46.225  6777  3515 E AndroidRuntime: Process: com.autel.rd, PID: 6777
09-16 16:13:46.225  6777  3515 E AndroidRuntime: java.lang.OutOfMemoryError: pthread_create (stack size 16384 bytes) failed: Try again
09-16 16:13:46.225  6777  3515 E AndroidRuntime: 	at java.lang.VMThread.create(Native Method)
09-16 16:13:46.225  6777  3515 E AndroidRuntime: 	at java.lang.Thread.start(Thread.java:1029)
09-16 16:13:46.225  6777  3515 E AndroidRuntime: 	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.start(CommsReceiver.java:77)
09-16 16:13:46.225  6777  3515 E AndroidRuntime: 	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:726)
09-16 16:13:46.225  6777  3515 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:841)

**Screenshots**

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: [e.g. 2.6.25]  
    aws_version                  : "2.44.0",
    implementation "com.amazonaws:aws-android-sdk-iot:${lib_version.aws_version}"
    implementation "com.amazonaws:aws-android-sdk-mobile-client:${lib_version.aws_version}" 

 - Device: [e.g. Pixel XL, Simulator]
 Pad

 - Android Version: [e.g. Nougat 7.1.2]
 Android 4.4 32位设备

 - Specific to simulators: [e.g. Yes/No]
 No

**Additional context**

**Comment by eeatonaws** [comment]
@WooYu thank you for reporting this issue. The OutOfMemoryError could be due to creating many new MQTT connections (repeatedly calling the `connectMqtt(…)` method you provided) which also re-creates the underlying Paho MQTT client each time. Please check that you are not re-creating the AWSIotMqttManager or calling `AWSIotMqttManager.connect(…)` multiple times.

**Comment by eeatonaws** [comment]
Closing due to inactivity. Please create a new issue or reopen this issue if the issue persists.
