### ISSUE TITLE
Subscription Exception after being connected

### ISSUE THREAD

**Issue by fxsweety** [aws-amplify/aws-sdk-android#3030]
**Describe the bug**
We are noticing a lot of this exception from the logs gathered from customer
We are using custom authorization to conect to MQTT
com.amazonaws.AmazonClientException: Client error when subscribing.
Caused by: Client is not connected (32104)
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(SourceFile:31)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.sendNoWait(SourceFile:205)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.subscribeBase(SourceFile:1088)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.subscribe(SourceFile:1061)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.subscribe(SourceFile:1027)
	at com.amazonaws.mobileconnectors.iot.AWSIotMqttManager.subscribeToTopic(SourceFile:1495)
	... 15 more

**To Reproduce**
A code sample or steps:
We don't a way to reproduce this issue
But this happens after we received Connected
Logs flow of events:
Connecting
Connected
Subscription Exception
EOFException

> Connection lost (32109) - java.io.EOFException 	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(SourceFile:197) 	at java.lang.Thread.run(Thread.java:923) Caused by: java.io.EOFException 	at java.io.DataInputStream.readByte(DataInputStream.java:270) 	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(SourceFile:92) 	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(SourceFile:137) 	... 1 more

Reconnecting
Connected
Subscription Exception
 java.io.EOFException
....

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: "com.amazonaws:aws-android-sdk-iot:2.22.2"

**Comment by eeatonaws** [comment]
@fxsweety thank you for reporting this issue. Could you please provide a code sample showing how you use the AWSIotMqttManager to connect and subscribe? This will help us in reproducing the issue.

**Comment by eeatonaws** [comment]
Closing due to inactivity. Please create a new issue or reopen this issue with the requested information if the issue persists.

**Comment by ShubhAppentus** [comment]
hi @fxsweety did you found any solution for this issue. currently i am facing the same issue, after i connected to aws iot, the logs showing reconnecting and connected again and again within few minutes, its not stable after i connected successfully. can you please halp me out thorugh this issue.
