### ISSUE TITLE
Amplify.Auth.fetchAuthSession() returns empty token even after successful login

### ISSUE THREAD

**Issue by ten-skv** [aws-amplify/aws-sdk-android#3075]
**Describe the bug**
Amplify.Auth.fetchAuthSession()  returns empty token even after successful login.
We are using both "Amplify.Auth.signInWithSocialWebUI" (some users using sso)  and "Amplify.Auth.signInWithSocialWebUI" (some users using our user/password).

**To Reproduce**
Try to use 2 different users. 
1. Login with first user.
2. You will be successfully signed in and get session token.
3. Logout from that user (Because we are using both "signInWithSocialWebUI" and regular "signin" configuration, logout will invoke web signout, this is a known bug in Amplify).
4. Login with different user(try to use a user with multifactor authentication enabled)
5.  You will be successfully signed in and get session token.
6. Logout and try to login.
7. you will be able to successfully sign-in, but session token will be empty. (Please find the stack trace below)

W/AWSMobileClient: signalTokensNotAvailable
W/AWSMobileClient: Tokens are invalid, please sign-in again.
    java.lang.Exception: No cached session.
        at com.amazonaws.mobile.client.AWSMobileClient$11$1.signalTokensNotAvailable(AWSMobileClient.java:1858)
        at com.amazonaws.mobile.client.AWSMobileClient$11$1.getAuthenticationDetails(AWSMobileClient.java:1838)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getSession(CognitoUser.java:1032)
        at com.amazonaws.mobile.client.AWSMobileClient$11.run(AWSMobileClient.java:1819)
        at com.amazonaws.mobile.client.internal.InternalCallback.await(InternalCallback.java:115)
        at com.amazonaws.mobile.client.AWSMobileClient.getTokens(AWSMobileClient.java:1785)
        at com.amazonaws.mobile.client.AWSMobileClient.getUserStateDetails(AWSMobileClient.java:1042)
        at com.amazonaws.mobile.client.AWSMobileClient$5.run(AWSMobileClient.java:843)
        at com.amazonaws.mobile.client.AWSMobileClient$5.run(AWSMobileClient.java:840)
        at com.amazonaws.mobile.client.internal.ReturningRunnable$1.run(ReturningRunnable.java:44)
        at java.lang.Thread.run(Thread.java:764)
I/LoginViewModel$getCognitoAuthSession: AWSCognitoAuthSession{isSignedIn=true, awsCredentials=AuthSessionResult{value=null, error=AmplifyException {message=Your session has expired., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE}, userSub='AuthSessionResult{value=null, error=AmplifyException {message=Your session has expired., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE}', identityId='AuthSessionResult{value=null, error=AmplifyException {message=Your session has expired., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE}', userPoolTokens='AuthSessionResult{value=null, error=AmplifyException {message=Your session has expired., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE}'}

Amplify configuration:
```
{
  "UserAgent": "aws-amplify-cli/2.0",
  "Version": "1.0",
  "auth": {
    "plugins": {
      "awsCognitoAuthPlugin": {
        "UserAgent": "aws-amplify-cli/0.1.0",
        "Version": "0.1.0",
        "IdentityManager": {
          "Default": {}
        },
        "CognitoUserPool": {
          "Default": {
            "PoolId": "us-east-2_xxxxxxxxxx",
            "AppClientId": "xxxxxxp90rhg4hxxxxxxxxx",
            "Region": "us-east-2"
          }
        },
        "Auth": {
          "Default": {
            "OAuth": {
              "WebDomain": "xxxxxxx.auth.us-east-1.amazoncognito.com",
              "AppClientId": "xxxxxxxxxrhg4h9xxxxxxxx",
              "SignInRedirectURI": "xxxxx://signin",
              "SignOutRedirectURI": "xxxxx://signout",
              "responseType": "code",
              "Scopes": [
                "phone",
                "email",
                "openid",
                "profile",
                "aws.cognito.signin.user.admin"
              ]
            },
            "authenticationFlowType": "USER_SRP_AUTH"
          }
        }
      }
    }
  }
}
```

**Which AWS service(s) are affected?**

**Expected behavior**
After successful signin, Amplify.Auth.fetchAuthSession() should return non empty/non expired token.

**Environment Information (please complete the following information):**
 - Amplify Version: 
 - Device: Any device. I was able to reproduce in Xioami.
 - Android Version: Any Android

**Comment by eeatonaws** [comment]
Transferring this issue to Amplify Android.
