### ISSUE TITLE
Error in Logcat "Failed to parse HostedUI settings from store"

### ISSUE THREAD

**Issue by UrielFrankel** [aws-amplify/aws-sdk-android#3188]
I get an error in the logcat when I start the Android app:
```
Failed to parse HostedUI settings from store
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object referenceat org.json.JSONTokener.nextCleanInternal(JSONTokener.java:121)
  at org.json.JSONTokener.nextValue(JSONTokener.java:98)
  at org.json.JSONObject.<init>(JSONObject.java:168)
  at org.json.JSONObject.<init>(JSONObject.java:185)
  at com.amazonaws.mobile.client.AWSMobileClient.getHostedUIJSON(AWSMobileClient.java:712)
  at com.amazonaws.mobile.client.AWSMobileClient$2.run(AWSMobileClient.java:617)
  at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
  at java.lang.Thread.run(Thread.java:1012)
```
Can I ignore it?

BTW I made the json a year and a half ago on an old Amplify version - 1.35.4

**Which AWS Services are you utilizing?**
Storage

**Provide code snippets (if applicable)**
```
 private fun initAmplify() {
        // https://docs.amplify.aws/lib/storage/getting-started/q/platform/android/#initialize-amplify-storage
        try {
            // Add these lines to add the AWSCognitoAuthPlugin and AWSS3StoragePlugin plugins
            Amplify.addPlugin(AWSCognitoAuthPlugin())
            Amplify.addPlugin(AWSS3StoragePlugin())
            Amplify.configure(applicationContext)
            val plugin = Amplify.Storage.getPlugin("awsS3StoragePlugin") as AWSS3StoragePlugin
            val client = plugin.escapeHatch
            client.setS3ClientOptions(S3ClientOptions.builder().setAccelerateModeEnabled(true).build())
        } catch (error: AmplifyException) {
            Log.e(TAG, "Could not initialize Amplify", error)
        }
    }
```

**Environment(please complete the following information):**
 - SDK Version:1.37.13

**Device Information (please complete the following information):**
 - Device: Galaxy A71 and emulator
 - Android Version: 33
 - Specific to simulators: no

**Comment by tylerjroach** [comment]
Are you using `signInWithWebUI` or `signInWIthSocialWebUI`? If so, then the sdk is failing to read the "Oauth" block of your configuration json. We would need to see your configuration being passed to diagnose.

If you are using SRP sign in and seeing this warning, you could ignore because it would only cause failures on Hosted UI (Web) sign ins.

**Comment by tylerjroach** [comment]
@UrielFrankel Have you been able to resolve this issue?

**Comment by UrielFrankel** [comment]
Yes, I upgraded Amplify version and removed the UI from the gradle and the error is gone

**Comment by tylerjroach** [comment]
@JannesNebendahl, If you are not using web (hosted ui) sign ins, remove the "Oauth" block from your awsconfiguration.json and amplifyconfiguration.json if you have one.

If you are try to use web sign in, please open up a new ticket with your json configuration details and we can help you diagnose what is missing or improperly formatted.

**Comment by JannesNebendahl** [comment]
I'm using a custom sign in, as described here: https://docs.amplify.aws/lib/auth/signin_with_custom_flow/q/platform/flutter/

I just have a amplifyconfiguration.json file, but without an "Oauth" block inside. 

The part where I start to wonder is that a awsconfiguration.json file is mentioned in the error log, but I can't find this file and never recognized it before as well.

My error log looks like this:
```
I/amplify:flutter:auth_cognito(22656): Added Auth plugin
I/amplify:flutter:api(22656): Added API plugin
D/AWSMobileClient(22656): Using the SignInProviderConfig from `awsconfiguration.json`.
W/AWSMobileClient(22656): Failed to parse HostedUI settings from store
W/AWSMobileClient(22656): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
W/AWSMobileClient(22656): 	at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:121)
W/AWSMobileClient(22656): 	at org.json.JSONTokener.nextValue(JSONTokener.java:98)
W/AWSMobileClient(22656): 	at org.json.JSONObject.<init>(JSONObject.java:165)
W/AWSMobileClient(22656): 	at org.json.JSONObject.<init>(JSONObject.java:182)
W/AWSMobileClient(22656): 	at com.amazonaws.mobile.client.AWSMobileClient.getHostedUIJSON(AWSMobileClient.java:712)
W/AWSMobileClient(22656): 	at com.amazonaws.mobile.client.AWSMobileClient$2.run(AWSMobileClient.java:617)
W/AWSMobileClient(22656): 	at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
W/AWSMobileClient(22656): 	at java.lang.Thread.run(Thread.java:923)
```

This is my amplifyconfiguration.json file (I replaced all credentials by _XXX_):
```
const amplifyconfig = ''' {
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "SmartGarden": {
                    "endpointType": "GraphQL",
                    "endpoint": "https://XXX.appsync-api.eu-central-1.amazonaws.com/graphql",
                    "region": "eu-central-1",
                    "authorizationType": "API_KEY",
                    "apiKey": "XXX"
                }
            }
        }
    },
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "AppSync": {
                    "Default": {
                        "ApiUrl": "https://XXX.appsync-api.eu-central-1.amazonaws.com/graphql",
                        "Region": "eu-central-1",
                        "AuthMode": "API_KEY",
                        "ApiKey": "XXX",
                        "ClientDatabasePrefix": "SmartGarden_API_KEY"
                    },
                    "SmartGarden_AWS_IAM": {
                        "ApiUrl": "https://XXX.appsync-api.eu-central-1.amazonaws.com/graphql",
                        "Region": "eu-central-1",
                        "AuthMode": "AWS_IAM",
                        "ClientDatabasePrefix": "SmartGarden_AWS_IAM"
                    }
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "eu-central-1:XXX",
                            "Region": "eu-central-1"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "eu-central-1_XXX",
                        "AppClientId": "XXX",
                        "Region": "eu-central-1"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH",
                        "mfaConfiguration": "OFF",
                        "mfaTypes": [
                            "SMS"
                        ],
                        "passwordProtectionSettings": {
                            "passwordPolicyMinLength": 8,
                            "passwordPolicyCharacters": []
                        },
                        "signupAttributes": [
                            "EMAIL"
                        ],
                        "socialProviders": [],
                        "usernameAttributes": [
                            "EMAIL"
                        ],
                        "verificationMechanisms": [
                            "EMAIL"
                        ]
                    }
                }
            }
        }
    }
}''';
```

**Comment by tylerjroach** [comment]
@JannesNebendahl While this may look alarming as a `Warn` log in your Logcat, you can safely ignore this message. After further inspection of the block that prints this log, it will display this, not only if hosted ui is configured incorrectly, but if it is not configured at all.

Since you are not using hosted UI, you can ignore.

**Comment by tylerjroach** [comment]
@JannesNebendahl I do not believe there would be correlation between the two. Please open up a ticket in the Amplify repo for the issue you are experiencing.
