### ISSUE TITLE
Moving from Amplify to TransferUtility causes a crash in the first time.

### ISSUE THREAD

**Issue by UrielFrankel** [aws-amplify/aws-sdk-android#3232]
**Describe the bug**
Use Amplify 2.5.0 in the app, and then move to use aws-android-sdk-s3 2.65.0. The app crashes.
This is the StackTrace:

`FATAL EXCEPTION: DefaultDispatcher-worker-3
                                                                                                    Process: riverside.fm, PID: 13864
                                                                                                    android.database.sqlite.SQLiteException: table awstransfer already exists (code 1 SQLITE_ERROR[1]): , while compiling: create table awstransfer(_id integer primary key autoincrement, main_upload_id integer, type text not null, state text not null, bucket_name text not null, key text not null, version_id text, bytes_total bigint, bytes_current bigint, speed bigint, is_requester_pays integer, is_encrypted integer, file text not null, file_offset bigint, is_multipart int, part_num int not null, is_last_part integer, multipart_id text, etag text, range_start bigint, range_last bigint, header_content_type text, header_content_language text, header_content_disposition text, header_content_encoding text, header_cache_control text, header_expire text);
                                                                                                    	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                                                    	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1521)
                                                                                                    	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:957)
                                                                                                    	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
                                                                                                    	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:63)
                                                                                                    	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:34)
                                                                                                    	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:2628)
                                                                                                    	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:2550)
                                                                                                    	at com.amazonaws.mobileconnectors.s3.transferutility.TransferTable.onCreate(TransferTable.java:250)
                                                                                                    	at com.amazonaws.mobileconnectors.s3.transferutility.TransferDatabaseHelper.onCreate(TransferDatabaseHelper.java:45)
                                                                                                    	at com.amazonaws.mobileconnectors.s3.transferutility.TransferDatabaseHelper.onDowngrade(TransferDatabaseHelper.java:56)
                                                                                                    	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:512)
                                                                                                    	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:413)
                                                                                                    	at com.amazonaws.mobileconnectors.s3.transferutility.TransferDBBase.<init>(TransferDBBase.java:58)
                                                                                                    	at com.amazonaws.mobileconnectors.s3.transferutility.TransferDBUtil.<init>(TransferDBUtil.java:67)
                                                                                                    	at com.amazonaws.mobileconnectors.s3.transferutility.TransferUtility.<init>(TransferUtility.java:330)
                                                                                                    	at com.amazonaws.mobileconnectors.s3.transferutility.TransferUtility.<init>(TransferUtility.java:108)
                                                                                                    	at com.amazonaws.mobileconnectors.s3.transferutility.TransferUtility$Builder.build(TransferUtility.java:304)
                                                                                                    	at riverside.fm.managers.S3Manager$transferUtility$2.invoke(S3Manager.kt:21)
                                                                                                    	at riverside.fm.managers.S3Manager$transferUtility$2.invoke(S3Manager.kt:19)
                                                                                                    	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
                                                                                                    	at riverside.fm.managers.S3Manager.getTransferUtility(S3Manager.kt:19)
                                                                                                    	at riverside.fm.utils.Logger$Companion.uploadLogFileToServer(Logger.kt:80)
                                                                                                    	at riverside.fm.android.UploadService.cleanup(UploadService.kt:150)
                                                                                                    	at riverside.fm.android.UploadService.access$cleanup(UploadService.kt:49)
                                                                                                    	at riverside.fm.android.UploadService$onStartCommand$1.invokeSuspend(UploadService.kt:85)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
                                                                                                    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@bde3ac6, Dispatchers.IO]`

**Environment Information (please complete the following information):**
 - Amplify 2.5.0
 - AWS Android SDK Version: 2.65.0

**Comment by eeatonaws** [comment]
Amplify does not currently support using multiple buckets. However, when using Amplify Android v2, you can use the [escape hatch](https://docs.amplify.aws/lib/storage/escapehatch/q/platform/android/) to access the Kotlin SDK, which allows you to specify a bucket name for an operation. For example, to [list objects](https://sdk.amazonaws.com/kotlin/api/latest/s3/aws.sdk.kotlin.services.s3/list-objects-v2.html) in a given bucket:
```
val plugin = Amplify.Storage.getPlugin("awsS3StoragePlugin") as AWSS3StoragePlugin
plugin.escapehatch.listObjectsV2 {
    this.bucket = s3BucketName
    this.prefix = path
}
```

**Comment by sdhuka** [comment]
Closing this duplicate, issue for mulitple bucket support is tracked [here](https://github.com/aws-amplify/amplify-android/issues/1607).

**Comment by ruthwikkk** [comment]
> I need to use 2 different buckets in the same app. Amplify does not support this. So I have to start using the AWS Android SDK. My solution is to delete the database by myself. because the code `context.deleteDatabase(DATABASE_NAME);` at TransferDatabaseHelper.java not working.

I'm also facing the same issue
How you managed to do this ?
Will this create any other side effects ? @UrielFrankel
