### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException. Throwable.getCause()

### ISSUE THREAD

**Issue by Egorman7** [aws-amplify/aws-sdk-android#3273]
**Describe the bug**
Updated AWS sdk in my project from 2.14.2 to 2.65.0. During testing all run smooth as expected.
But after releasing the app a lot of crash reporst coming to Firebase Crashlytics.

**To Reproduce**
Not able to reproduce locally on the devices, but issue appears on some percent of app users.
Here is a logs that I have in crashytics. Nothing related to my code.
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Throwable java.lang.Throwable.getCause()' on a null object reference
       at com.amazonaws.mobileconnectors.pinpoint.internal.event.EventRecorder.isClientExceptionRetryable(EventRecorder.java:559)
       at com.amazonaws.mobileconnectors.pinpoint.internal.event.EventRecorder.submitEventsAndEndpoint(EventRecorder.java:469)
       at com.amazonaws.mobileconnectors.pinpoint.internal.event.EventRecorder.submitEventsAndEndpoint(EventRecorder.java:407)
       at com.amazonaws.mobileconnectors.pinpoint.internal.event.EventRecorder.processEvents(EventRecorder.java:360)
       at com.amazonaws.mobileconnectors.pinpoint.internal.event.EventRecorder$1.run(EventRecorder.java:256)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)
```

**Which AWS service(s) are affected?**
Suppose that Pinpoint Service

**Expected behavior**
App runs without crashes

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.65.0
 - Device: A lot of devices
 - Android Version: Pie 9.0+
 - Specific to simulators: No

**Comment by eeatonaws** [comment]
A fix has been released in version 2.68.0 of the AWS SDK for Android.
