### ISSUE TITLE
Unable to connect after updating to Amplify V2

### ISSUE THREAD

**Issue by ZubairAkber** [aws-amplify/aws-sdk-android#3286]
**Describe the bug**
I just update to Amplify V2 from V1 and update the MQTT library to latest but after doing that all successfully i am unable to connect to MQTT, getting an exception while connecting to MQTT

Reconnect failed 
                                         MqttException (0) - java.io.IOException: WebSocket Response header: Incorrect upgrade.
                                         	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
                                         	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:738)
                                         	at java.lang.Thread.run(Thread.java:923)
                                         Caused by: java.io.IOException: WebSocket Response header: Incorrect upgrade.
                                         	at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketHandshake.receiveHandshakeResponse(WebSocketHandshake.java:162)
                                         	at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketHandshake.execute(WebSocketHandshake.java:80)
                                         	at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketSecureNetworkModule.start(WebSocketSecureNetworkModule.java:65)
                                         	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:724)
                                         	at java.lang.Thread.run(Thread.java:923) 

**To Reproduce**
Simply update to latest Amplify library from V1, means to V2 

Your code
I use the MyCredentialProvider provided in https://github.com/aws-amplify/amplify-android/issues/2400 bug while connecting to MQTT in connect call

**Which AWS service(s) are affected?**

**Expected behavior**

**Screenshots**
![image](https://github.com/aws-amplify/aws-sdk-android/assets/15378288/577da043-a7b4-410c-9fd8-b9bcd92072c4)

**Environment Information (please complete the following information):**
   
   Following are the libraries in which i am facing the issue
   
        // Amplify dependencies
        implementation 'com.amplifyframework:core:2.7.1'
        implementation 'com.amplifyframework:aws-api:2.7.1'
        implementation 'com.amplifyframework:aws-datastore:2.7.1'
        implementation 'com.amplifyframework:aws-auth-cognito:2.7.1'
        implementation 'com.amplifyframework:aws-storage-s3:2.7.1'
    
        // AWS MQTT dependencies
        implementation 'com.amazonaws:aws-android-sdk-iot:2.65.0'
        implementation 'com.amazonaws:aws-android-sdk-mobile-client:2.65.0'
    
        // Support for Java 8 features
        coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.5'

Previously used libraries in which every thing works well

       // Amplify dependencies
        implementation 'com.amplifyframework:core:1.38.1'
        implementation 'com.amplifyframework:aws-api:1.38.1'
        implementation 'com.amplifyframework:aws-datastore:1.38.1'
        implementation 'com.amplifyframework:aws-auth-cognito:1.38.1'
        implementation 'com.amplifyframework:aws-storage-s3:1.38.1'
    
        // AWS MQTT dependencies
        implementation 'com.amazonaws:aws-android-sdk-iot:2.65.0'
        implementation 'com.amazonaws:aws-android-sdk-mobile-client:2.65.0'
    
        // Support for Java 8 features
        coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.5'

**Comment by eeatonaws** [comment]
Closing this issue since it has been resolved in issue [2400](https://github.com/aws-amplify/amplify-android/issues/2400). Please follow issue [2400](https://github.com/aws-amplify/amplify-android/issues/2400) for any further updates.
