### ISSUE TITLE
Cognito - NotAuthorizedException forcing users to Sign-In

### ISSUE THREAD

**Issue by sunilRWC** [aws-amplify/aws-sdk-android#347]
* What service are you using?
Cognito

* In what version of SDK are you facing the problem?
I have seen the issue with version 2.3.9 and 2.6.2.

* Is the issue limited to Simulators / Actual Devices?
Actual Device.

* Can your problem be resolved if you bump to a higher version of SDK?
No.

* Is this problem related to specific Android/OS version?
Seen on Both Android and iOS.

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

1.	After launching the application for the first time, the user logs in from the Sign-In activity. (Note: uses Cognito for authentication)
2.	After a successful login, the user runs the app throughout the day without any issues.
3.	Close/minimize the application for the night.
4.	Launch the application the next day which results in application going to the Sign-In page.

Stacktrace after launching the app the next day:
```
09-19 10:24:12.176 31543-31625/ D/CognitoCachingCredentialsProvider: Loading credentials from SharedPreferences
09-19 10:24:12.177 31543-31625/D/CognitoCachingCredentialsProvider: No valid credentials found in SharedPreferences
09-19 10:24:15.831 31543-31646/D/CognitoCachingCredentialsProvider: Loading credentials from SharedPreferences
09-19 10:24:15.831 31543-31646/D/CognitoCachingCredentialsProvider: No valid credentials found in SharedPreferences
09-19 10:24:16.817 31543-31646/E/CognitoCachingCredentialsProvider: Failure to get credentials
    com.amazonaws.services.cognitoidentity.model.NotAuthorizedException: Unauthenticated access is not supported for this identity pool. (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: NotAuthorizedException; Request ID: 38584547-9d46-11e7-852c-7b9b46e911e1)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:720)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:394)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:200)
        at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:558)
        at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getId(AmazonCognitoIdentityClient.java:444)
        at com.amazonaws.auth.AWSAbstractCognitoIdentityProvider.getIdentityId(AWSAbstractCognitoIdentityProvider.java:172)
        at com.amazonaws.auth.AWSEnhancedCognitoIdentityProvider.refresh(AWSEnhancedCognitoIdentityProvider.java:76)
        at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:601)
        at com.amazonaws.auth.CognitoCredentialsProvider.getCredentials(CognitoCredentialsProvider.java:388)
        at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:442)
        at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:76)
        at com.amazonaws.mobileconnectors.iot.AWSIotMqttManager$1.run(AWSIotMqttManager.java:669)
        at java.lang.Thread.run(Thread.java:761)
09-19 10:24:16.817 31543-31646/D/CognitoCachingCredentialsProvider: Identity id is changed
09-19 10:24:16.817 31543-31646/D/CognitoCachingCredentialsProvider: Saving identity id to SharedPreferences
09-19 10:24:16.822 31543-31646/D/CognitoCachingCredentialsProvider: Clearing credentials from SharedPreferences
09-19 10:24:16.824 31543-31543/E/NetworkUtil: requestFailure(): AmazonServiceException - errorMessageDisplay - Unauthenticated access is not supported for this identity pool.
09-19 10:24:16.833 31543-31543/D/DeviceProvider: Mqtt manager disconnected
09-19 10:24:16.880 31543-31648/D/CognitoCachingCredentialsProvider: Loading credentials from SharedPreferences
09-19 10:24:16.880 31543-31648/D/CognitoCachingCredentialsProvider: No valid credentials found in SharedPreferences
09-19 10:24:16.882 31543-31646/E/AndroidRuntime: FATAL EXCEPTION: Thread-9
   Process:, PID: 31543
   com.amazonaws.services.cognitoidentity.model.NotAuthorizedException: Unauthenticated access is not supported for this identity pool. (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: NotAuthorizedException; Request ID: 3866eb8e-9d46-11e7-88ea-278be8950570)
       at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:720)
       at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:394)
       at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:200)
       at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:558)
       at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getId(AmazonCognitoIdentityClient.java:444)
       at com.amazonaws.auth.AWSAbstractCognitoIdentityProvider.getIdentityId(AWSAbstractCognitoIdentityProvider.java:172)
       at com.amazonaws.auth.AWSEnhancedCognitoIdentityProvider.refresh(AWSEnhancedCognitoIdentityProvider.java:76)
       at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:601)
       at com.amazonaws.auth.CognitoCredentialsProvider.getCredentials(CognitoCredentialsProvider.java:388)
       at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:456)
       at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:76)
       at com.amazonaws.mobileconnectors.iot.AWSIotMqttManager$1.run(AWSIotMqttManager.java:669)
       at java.lang.Thread.run(Thread.java:761)
09-19 10:24:17.046 31543-31648/E/CognitoCachingCredentialsProvider: Failure to get credentials
    com.amazonaws.services.cognitoidentity.model.NotAuthorizedException: Unauthenticated access is not supported for this identity pool. (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: NotAuthorizedException; Request ID: 386fc4d9-9d46-11e7-a72f-59c0b4272704)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:720)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:394)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:200)
        at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:558)
        at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getId(AmazonCognitoIdentityClient.java:444)
        at com.amazonaws.auth.AWSAbstractCognitoIdentityProvider.getIdentityId(AWSAbstractCognitoIdentityProvider.java:172)
        at com.amazonaws.auth.AWSEnhancedCognitoIdentityProvider.refresh(AWSEnhancedCognitoIdentityProvider.java:76)
        at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:601)
        at com.amazonaws.auth.CognitoCredentialsProvider.getCredentials(CognitoCredentialsProvider.java:388)
        at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:442)
        at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:76)
        at com.amazonaws.mobileconnectors.apigateway.ApiClientHandler.buildRequest(ApiClientHandler.java:185)
        at com.amazonaws.mobileconnectors.apigateway.ApiClientHandler.createHttpRequest(ApiClientHandler.java:116)
        at com.amazonaws.mobileconnectors.apigateway.ApiClientHandler.invoke(ApiClientHandler.java:94)
        at java.lang.reflect.Proxy.invoke(Proxy.java:813)
        at $Proxy1.v1LocationsGet(Unknown Source)
        at com.rwc.networklibrary.providers.location.LocationProvider$2.run(LocationProvider.java:86)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
        at com.rwc.networklibrary.util.NetworkUtil$1$1.run(NetworkUtil.java:37)
09-19 10:24:17.046 31543-31648/D/CognitoCachingCredentialsProvider: Identity id is changed
09-19 10:24:17.046 31543-31648/D/CognitoCachingCredentialsProvider: Saving identity id to SharedPreferences
09-19 10:24:17.046 31543-31648/D/CognitoCachingCredentialsProvider: Clearing credentials from SharedPreferences
09-19 10:24:17.106 31543-31647/D/CognitoCachingCredentialsProvider: Clearing credentials from SharedPreferences
09-19 10:24:17.106 31543-31648/W/System.err: com.amazonaws.mobileconnectors.apigateway.ApiClientException: Unauthenticated access is not supported for this identity pool. (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: NotAuthorizedException; Request ID: 38885651-9d46-11e7-8223-035e47f21c10) (Service: null; Status Code: 0; Error Code: null; Request ID: null)
09-19 10:24:17.108 31543-31543/D/CognitoCachingCredentialsProvider: Clearing credentials from SharedPreferences
09-19 10:24:17.109 31543-31543/D/CognitoCachingCredentialsProvider: Identity id is changed
09-19 10:24:17.109 31543-31543/D/CognitoCachingCredentialsProvider: Saving identity id to SharedPreferences
09-19 10:24:17.110 31543-31543/D/CognitoCachingCredentialsProvider: Clearing credentials from SharedPreferences
09-19 10:24:17.112 31543-31647/D/CognitoCachingCredentialsProvider: Clearing credentials from SharedPreferences
09-19 10:24:17.113 31543-31647/D/CognitoCachingCredentialsProvider: Identity id is changed
09-19 10:24:17.113 31543-31647/D/CognitoCachingCredentialsProvider: Saving identity id to SharedPreferences
09-19 10:24:17.113 31543-31647/D/CognitoCachingCredentialsProvider: Clearing credentials from SharedPreferences
09-19 10:24:17.114 31543-31647/D/CognitoCachingCredentialsProvider: Clearing credentials from SharedPreferences
09-19 10:24:17.114 31543-31647/D/CognitoCachingCredentialsProvider: Clearing credentials from SharedPreferences
```

**Comment by vlekakis** [comment]
From the stack trace seems clear that the identity pool is not configured for Unauthenticated access. 

So have you tried to enable it:
http://docs.aws.amazon.com/cognito/latest/developerguide/identity-pools.html

**Comment by kvasukib** [comment]
Hi @sunilRWC, Are you still facing the issue?

**Comment by minbi** [comment]
Hi @sunilRWC @aneeshjoshi ,

We have launched a new `AWSMobileClient` in v2.8.+ , which will manage the Cognito Identity federation. It will provide callbacks like `SIGNED_OUT_FEDERATED_TOKENS_INVALID` to allow developers to show a sign-in screen or otherwise refresh the token.

A full details available in the [Release notes](https://github.com/aws-amplify/aws-sdk-android/releases/tag/release_v2.8.0) and [Documentation](https://aws-amplify.github.io/docs/android/authentication)

**Comment by minbi** [comment]
Hi,

We are closing this issue because there has been no activity. Please feel free to open a new issue if the problem persists. We ask this because closed issues are not actively monitored.

Thanks
