### ISSUE TITLE
Pinpoint requires undocumented IAM Role Policy to publish events

### ISSUE THREAD

**Issue by SamazonWelch** [aws-amplify/aws-sdk-android#561]
**Describe the bug**
Publishing events on Android requires more than just 
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "mobiletargeting:UpdateEndpoint",
            "Resource": [
                "[omitted]apps/*/endpoints/*",
            ]
        }
    ]
}
```
It requires
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "mobiletargeting:UpdateEndpoint",
            "Resource": [
                "[omitted]:apps/*/endpoints/*",
                "[omitted]:apps/*/events/*"
            ]
        }
    ]
}
```

**To Reproduce**
1. Try submitting a pinpoint event.
2. Check the logs and see errors:

```
D/PinpointSessionManager: [onRegisteredStart] submitting events and starting session...
E/EventRecorder: AmazonServiceException occured during send of put event 
    com.amazonaws.AmazonServiceException: User: [omitted]:assumed-role/CustomerMetricsRole/CognitoIdentityCredentials is not authorized to perform: mobiletargeting:UpdateEndpoint on resource: [omitted]/events/legacy (Service: AmazonPinpoint; Status Code: 403; Error Code: AccessDeniedException; Request ID: [omitted])
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:730)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:405)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
        at com.amazonaws.services.pinpoint.AmazonPinpointClient.invoke(AmazonPinpointClient.java:3885)
        at com.amazonaws.services.pinpoint.AmazonPinpointClient.putEvents(AmazonPinpointClient.java:2973)
        at com.amazonaws.mobileconnectors.pinpoint.internal.event.EventRecorder.submitEventsAndEndpoint(EventRecorder.java:357)
        at com.amazonaws.mobileconnectors.pinpoint.internal.event.EventRecorder.submitEventsAndEndpoint(EventRecorder.java:335)
        at com.amazonaws.mobileconnectors.pinpoint.internal.event.EventRecorder.processEvents(EventRecorder.java:306)
        at com.amazonaws.mobileconnectors.pinpoint.internal.event.EventRecorder$1.run(EventRecorder.java:231)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

**Which AWS service(s) are affected?**
Pinpoint Analytics

**Expected behavior**
The documented IAM roles are all that are required.  "*/endpoints/*" should suffice.
https://docs.aws.amazon.com/pinpoint/latest/developerguide/permissions-actions.html

**Environment(please complete the following information):**
 - SDK Version: [2.7.6], [2.6.5]

**Device Information (please complete the following information):**
 Every device I've tried

**Comment by kvasukib** [comment]
@SamazonWelch As discussed offline, this was a miss in the documentation which the team is working on to update. Hence closing the issue.

**Comment by kaldown** [comment]
2 years passed since. Any update?
