### ISSUE TITLE
Download stops when changing from mobile data to wifi

### ISSUE THREAD

**Issue by vicpinm** [aws-amplify/aws-sdk-android#566]
**Describe the bug**
I have noticed that when I download a file with mobile data, if while the file is downloading, I enable wifi on the device, the current download stops with the following exception: 

    AmazonClientException: Unable to store object contents to disk: Read error: ssl=0x79731e92c0: I/O 
    error during system call, Software caused connection abort
    .../System.err:     at         
    com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.saveToFile(DownloadTask.java:157)
    .../System.err:     at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.call(DownloadTask.java:104)
    .../System.err:     at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.call(DownloadTask.java:41)
    .../System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    .../System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
    .../System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
    .../System.err:     at java.lang.Thread.run(Thread.java:764)
    .../System.err: Caused by: javax.net.ssl.SSLException: Read error: ssl=0x79731e92c0: I/O error during system call, Software caused connection abort

I have also noticed that this does not happen when I upload a file. It only occurs with downloads.

**To Reproduce**
1. Start a download with wifi disabled and mobile data enabled
2. During the download, enable wifi
3. When wifi enables, the download is stopped with an exception.

**Which AWS service(s) are affected?**
S3

**Expected behavior**
The download should continue without stopping

**Environment(please complete the following information):**
 - SDK Version: 2.7.7

**Device Information: Any

**Comment by kvasukib** [comment]
@vicpinm Sorry for the inconvenience caused. We made a change in 2.7.0 where TransferService has to be started explicitly in the app. Are you starting this service from your app?

**Comment by muellerfr** [comment]
This issue has been automatically closed because of inactivity. Please open a new issue if are still encountering problems.
