### ISSUE TITLE
com.amazonaws.AmazonClientException: Unable to execute HTTP request: Read timed out

### ISSUE THREAD

**Issue by zhouxuemeng1988** [aws-amplify/aws-sdk-android#567]
*I only initialized aws related services after requesting our own server, so the user's network should be good.
*aws lot mqtt
*sdk version: 2.6.28
**Device Information (please complete the following information):**
 - TIME=1505475948000
FINGERPRINT=DPT/public_talent_3751V500/public_talent_3751V500:4.4.2/BOE/20170915.194347:eng/dev-keys
HARDWARE=hi3751
UNKNOWN=unknown
RADIO=unknown
BOARD=bigfish
versionCode=75
PRODUCT=public_talent_3751V500
versionName=3.1.4
DISPLAY=BOE_iGallery32_V_dfjh1.01
USER=leidongdong
HOST=leidongdong
DEVICE=public_talent_3751V500
TAGS=dev-keys
MODEL=5V10-C-CWQX
BOOTLOADER=unknown
CPU_ABI=armeabi-v7a
CPU_ABI2=armeabi
IS_DEBUGGABLE=true
devicesId=2208caebb5b77853
ID=BOE
SERIAL=unknown
MANUFACTURER=Talent
BRAND=DPT
TYPE=eng

**Additional context**
```java
com.amazonaws.AmazonClientException: Unable to execute HTTP request: Read timed out
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:441)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
	at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:566)
	at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getCredentialsForIdentity(AmazonCognitoIdentityClient.java:389)
	at com.amazonaws.auth.CognitoCredentialsProvider.populateCredentialsWithCognito(CognitoCredentialsProvider.java:782)
	at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:694)
	at com.amazonaws.auth.CognitoCredentialsProvider.getCredentials(CognitoCredentialsProvider.java:465)
	at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:485)
	at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:77)
	at com.amazonaws.mobileconnectors.iot.AWSIotMqttManager$1.run(AWSIotMqttManager.java:708)
	at java.lang.Thread.run(Thread.java:841)
Caused by: java.net.SocketTimeoutException: Read timed out
	at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
	at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:690)
	at java.io.InputStream.read(InputStream.java:162)
	at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:142)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:227)
	at com.android.okhttp.internal.Util.readAsciiLine(Util.java:316)
	at com.android.okhttp.internal.http.RawHeaders.fromBytes(RawHeaders.java:308)
	at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:135)
	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:644)
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:347)
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseMessage(HttpURLConnectionImpl.java:499)
	at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseMessage(HttpsURLConnectionImpl.java:140)
	at com.amazonaws.http.UrlHttpClient.createHttpResponse(UrlHttpClient.java:92)
	at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:85)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:371)
	... 10 more
java.net.SocketTimeoutException: Read timed out
	at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
	at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:690)
	at java.io.InputStream.read(InputStream.java:162)
	at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:142)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:227)
	at com.android.okhttp.internal.Util.readAsciiLine(Util.java:316)
	at com.android.okhttp.internal.http.RawHeaders.fromBytes(RawHeaders.java:308)
	at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:135)
	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:644)
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:347)
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseMessage(HttpURLConnectionImpl.java:499)
	at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseMessage(HttpsURLConnectionImpl.java:140)
	at com.amazonaws.http.UrlHttpClient.createHttpResponse(UrlHttpClient.java:92)
	at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:85)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:371)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
	at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:566)
	at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getCredentialsForIdentity(AmazonCognitoIdentityClient.java:389)
	at com.amazonaws.auth.CognitoCredentialsProvider.populateCredentialsWithCognito(CognitoCredentialsProvider.java:782)
	at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:694)
	at com.amazonaws.auth.CognitoCredentialsProvider.getCredentials(CognitoCredentialsProvider.java:465)
	at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:485)
	at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:77)
	at com.amazonaws.mobileconnectors.iot.AWSIotMqttManager$1.run(AWSIotMqttManager.java:708)
	at java.lang.Thread.run(Thread.java:841)
```

**Comment by zhouxuemeng1988** [comment]
It case app crash.  I tried to catch this exception, but I couldn't capture it.

**Comment by kvasukib** [comment]
@zhouxuemeng1988 Sorry for the delayed response. This issue happens when the network connectivity is poor/lost. You can grab this exception by looking into the callback that you attach to the connect method. The callback will be invoked with `ConnectionLost` status and the throwable object will have the exception that is thrown by the SDK.

**Comment by tajchert** [comment]
@kvasukib how I can attach listener for that callback?
I create DynamoDbMapper:
`DynamoDBMapper.builder().dynamoDBClient(ddbClient).build()`
and then for example scan for all objects:
`resultScan = mapper.scan(MyObject.class, new DynamoDBScanExpression());`
And this line throws `AmazonClientException` that I cannot catch as it is on the other thread so it crashes my app.

My stacktrace:

`com.amazonaws.AmazonClientException: Unable to execute HTTP request: Unable to resolve host "cognito-identity.eu-central-1.amazonaws.com": No address associated with hostname
at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:441)
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:566)
at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getId(AmazonCognitoIdentityClient.java:448)
at com.amazonaws.auth.AWSAbstractCognitoIdentityProvider.getIdentityId(AWSAbstractCognitoIdentityProvider.java:172)
at com.amazonaws.auth.AWSEnhancedCognitoIdentityProvider.refresh(AWSEnhancedCognitoIdentityProvider.java:76)
at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:678)
at com.amazonaws.auth.CognitoCredentialsProvider.getCredentials(CognitoCredentialsProvider.java:465)
at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:485)
at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:77)
at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:5200)
at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.scan(AmazonDynamoDBClient.java:2481)
at com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBMapper.scan(DynamoDBMapper.java:2264)
at com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBMapper.scan(DynamoDBMapper.java:2228)`

**Comment by tajchert** [comment]
@kvasukib 
Probably my mistake. Due to some earlier work (2 years old project, earlier with 2.6.6) I had:

    ```
implementation 'com.amazonaws:aws-android-sdk-core:2.8.0'
    implementation 'com.amazonaws:aws-android-sdk-ddb:2.8.0'
    implementation('com.amazonaws:aws-android-sdk-ddb-mapper:2.8.0') {
        exclude module: 'commons-io'
    }
```
Sadly I don't remember the reason behind exluding commons-io. But with it not excluded it works fine - error is catched correctly.
So it seems to be working fine, sorry for creating a bit of chaos. I will report if app will crash but seems so far fine.

**Comment by kvasukib** [comment]
@tajchert Thank you for the confirmation. Regardless, the SDK should be catching the exception and throwing it back to the application when the network call is made on the background thread. We will look into it. Can you post a sample code snippet right from where you create the credentials provider till the scan call is made? (Exclude the AWS configuration/sensitive information).

**Comment by zhouxuemeng1988** [comment]
@kvasukib  I have already handled this throwable callback,but it still crash my app.

`try {

            credentialsProvider = new CognitoCachingCredentialsProvider(
                    WXEnvironment.getApplication().getApplicationContext(),
                    cognito_pool_id,
                    Regions.fromName(region)
            );
            mqttManager = new AWSIotMqttManager(clientId, end_point);
            mqttManager.connect(credentialsProvider, new AWSIotMqttClientStatusCallback() {
                @Override
                public void onStatusChanged(final AWSIotMqttClientStatus status,
                                            final Throwable throwable) {
                    checkConnectionTime = System.currentTimeMillis();
                    statusCallBack = "Disconnected";
                    if (status == AWSIotMqttClientStatus.Connecting) {
                        Log.e(LOG_TAG, "Connecting...");
                        statusCallBack = "Connecting";
                    } else if (status == AWSIotMqttClientStatus.Connected) {
                        Log.e(LOG_TAG, "Connected");
                        checkConnectionTime = System.currentTimeMillis();
                        statusCallBack = "Connected";
                    } else if (status == AWSIotMqttClientStatus.Reconnecting) {
                        if (throwable != null) {
                            Log.e(LOG_TAG, "Connection error.", throwable);
                        }
                        statusCallBack = "Reconnecting";
                        Log.e(LOG_TAG, "Reconnecting");
                    } else if (status == AWSIotMqttClientStatus.ConnectionLost) {
                        if (throwable != null) {
                            Log.e(LOG_TAG, "Connection error.", throwable);
                            throwable.printStackTrace();
                        }
                        statusCallBack = "ConnectionLost";
                        Log.e(LOG_TAG, "Connection lost");
                    } else {
                        Log.e(LOG_TAG, "Disconnected");
                    }

                    if (stateLisenter != null) {
                        stateLisenter.onStateChange(statusCallBack);
                    }
                }
            });
        } catch (AmazonClientException e) {
            Log.e(LOG_TAG, "Connection AmazonClientException111.", e);
        } catch (Exception e) {
            Log.e(LOG_TAG, "Connection error1111.", e);
        }`

**Comment by kvasukib** [comment]
@zhouxuemeng1988 I have changed your code to look for the exception from the callback.

```java
try {
            credentialsProvider = new CognitoCachingCredentialsProvider(
                    WXEnvironment.getApplication().getApplicationContext(),
                    cognito_pool_id,
                    Regions.fromName(region)
            );
            mqttManager = new AWSIotMqttManager(clientId, end_point);
            mqttManager.connect(credentialsProvider, new AWSIotMqttClientStatusCallback() {
                @Override
                public void onStatusChanged(final AWSIotMqttClientStatus status,
                                            final Throwable throwable) {
      
                  if (throwable != null) {
                            Log.d("", throwable.getMessage());

                            if (throwable instanceof AmazonClientException) {

                            } else if (throwable instanceof MqttException) {

                            } else if (throwable instanceof Exception) {

                            }
                    }

                    checkConnectionTime = System.currentTimeMillis();
                    statusCallBack = "Disconnected";
                    if (status == AWSIotMqttClientStatus.Connecting) {
                        Log.e(LOG_TAG, "Connecting...");
                        statusCallBack = "Connecting";
                    } else if (status == AWSIotMqttClientStatus.Connected) {
                        Log.e(LOG_TAG, "Connected");
                        checkConnectionTime = System.currentTimeMillis();
                        statusCallBack = "Connected";
                    } else if (status == AWSIotMqttClientStatus.Reconnecting) {
                        if (throwable != null) {
                            Log.e(LOG_TAG, "Connection error.", throwable);
                        }
                        statusCallBack = "Reconnecting";
                        Log.e(LOG_TAG, "Reconnecting");
                    } else if (status == AWSIotMqttClientStatus.ConnectionLost) {
                        if (throwable != null) {
                            Log.e(LOG_TAG, "Connection error.", throwable);
                            throwable.printStackTrace();
                        }
                        statusCallBack = "ConnectionLost";
                        Log.e(LOG_TAG, "Connection lost");
                    } else {
                        Log.e(LOG_TAG, "Disconnected");
                    }

                    if (stateLisenter != null) {
                        stateLisenter.onStateChange(statusCallBack);
                    }
                }
            });
        } catch (AmazonClientException e) {
            Log.e(LOG_TAG, "Connection AmazonClientException111.", e);
        } catch (Exception e) {
            Log.e(LOG_TAG, "Connection error1111.", e);
        }
```

**Comment by zhouxuemeng1988** [comment]
@kvasukib  Thanks for your response, but I think doing this just prints the error log and doesn't solve the real crash.

**Comment by kvasukib** [comment]
@zhouxuemeng1988 The issue you're getting is because of a slow/stale connection. You can set `autoReconnect` to true in the `AWSIotMqttManager` where the SDK would be reconnecting when there is connection loss. Or you could check for the exception in the callback and issue a connect again.

**Comment by zhouxuemeng1988** [comment]
@kvasukib I did not set the relevant default values. I looked at the AWSlotMqttManager source and found one of the following default values: autoReconnect=true, needResubscribe=trueminReconnectRetryTime=4, maxReconnectRetryTime=64, maxAutoReconnectAttempts=10. The automatic reconnection has been set by default.

**Comment by kvasukib** [comment]
@zhouxuemeng1988 Can we setup a call to discuss the issue further? You can email me at karthba at amazon dot com.

**Comment by muellerfr** [comment]
@zhouxuemeng1988, we have not heard from you. Please reach out to @kvasukib via email so we can setup a call to diagnose the issue.

**Comment by aslamhossin** [comment]
**I am facing the same issue is there any solution?**  
**com.amazonaws.AmazonClientException**: Unable to execute **HTTP** request: Unable to resolve host "**cognito-idp.ap-southeast-1.amazonaws.com**": No address associated with **hostname**

**Comment by vinuthagowda375** [comment]
12/17/2019 17:28:13 : SEVERE : Unable to fetch message text from input message.
com.fiorano.edbc.framework.service.exception.ServiceExecutionException: Unable to fetch message text from input message.
	at com.fiorano.esb.service.S3UploaderMessageListener.handleMessage(S3UploaderMessageListener.java:231)
	at com.fiorano.edbc.framework.service.jms.AbstractMessageListener.onMessage(AbstractMessageListener.java:46)
	at fiorano.jms.runtime.ptp.FioranoQueueReceiver.invokeCallback(FioranoQueueReceiver.java:988)
	at fiorano.jms.runtime.ptp.FioranoQueueDispatchJob.execute(FioranoQueueDispatchJob.java:125)
	at fiorano.jms.runtime.ptp.FioranoQueueSession.run_Consumers(FioranoQueueSession.java:1150)
	at fiorano.jms.runtime.ptp.FioranoQueueSession$PTPSessionThread.run(FioranoQueueSession.java:4028)
caused by
com.amazonaws.SdkClientException: Unable to execute HTTP request: hdfc-fiorano-test.s3.ap-south-1.amazonaws.com
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1038)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:742)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:716)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4191)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4138)
	at com.amazonaws.services.s3.AmazonS3Client.initiateMultipartUpload(AmazonS3Client.java:3025)
	at com.fiorano.esb.service.UploadHandler.init(UploadHandler.java:87)
	at com.fiorano.esb.service.UploadHandler.push(UploadHandler.java:171)
	at com.fiorano.esb.service.S3UploaderMessageListener.handleMessage(S3UploaderMessageListener.java:208)
	at com.fiorano.edbc.framework.service.jms.AbstractMessageListener.onMessage(AbstractMessageListener.java:46)
	at fiorano.jms.runtime.ptp.FioranoQueueReceiver.invokeCallback(FioranoQueueReceiver.java:988)
	at fiorano.jms.runtime.ptp.FioranoQueueDispatchJob.execute(FioranoQueueDispatchJob.java:125)
	at fiorano.jms.runtime.ptp.FioranoQueueSession.run_Consumers(FioranoQueueSession.java:1150)
	at fiorano.jms.runtime.ptp.FioranoQueueSession$PTPSessionThread.run(FioranoQueueSession.java:4028)
caused by
java.net.UnknownHostException: hdfc-fiorano-test.s3.ap-south-1.amazonaws.com
	at java.net.InetAddress.getAllByName0(Unknown Source)
	at java.net.InetAddress.getAllByName(Unknown Source)
	at java.net.InetAddress.getAllByName(Unknown Source)
	at com.amazonaws.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:27)
	at com.amazonaws.http.DelegatingDnsResolver.resolve(DelegatingDnsResolver.java:38)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:111)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76)
	at com.amazonaws.http.conn.$Proxy12.connect(Unknown Source)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1181)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1030)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:742)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:716)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4191)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4138)
	at com.amazonaws.services.s3.AmazonS3Client.initiateMultipartUpload(AmazonS3Client.java:3025)
	at com.fiorano.esb.service.UploadHandler.init(UploadHandler.java:87)
	at com.fiorano.esb.service.UploadHandler.push(UploadHandler.java:171)
	at com.fiorano.esb.service.S3UploaderMessageListener.handleMessage(S3UploaderMessageListener.java:208)
	at com.fiorano.edbc.framework.service.jms.AbstractMessageListener.onMessage(AbstractMessageListener.java:46)
	at fiorano.jms.runtime.ptp.FioranoQueueReceiver.invokeCallback(FioranoQueueReceiver.java:988)
	at fiorano.jms.runtime.ptp.FioranoQueueDispatchJob.execute(FioranoQueueDispatchJob.java:125)
	at fiorano.jms.runtime.ptp.FioranoQueueSession.run_Consumers(FioranoQueueSession.java:1150)
	at fiorano.jms.runtime.ptp.FioranoQueueSession$PTPSessionThread.run(FioranoQueueSession.java:4028)

**Comment by vinuthagowda375** [comment]
[S3upload (2).txt](https://github.com/aws-amplify/aws-sdk-android/files/3983021/S3upload.2.txt)

**Comment by h-hub** [comment]
I'm having the same issue. Any update?

**Comment by deriklpw** [comment]
I'm having the same issue. What is wrong?
com.amazonaws.AmazonClientException: Unable to execute HTTP request: Unable to resolve host "cognito-idp.us-east-1.amazonaws.com": No address associated with hostname

**Comment by mohammadkashifkhan** [comment]
I am facing the same issue. No Idea, why it's happening. The Internet connection seems to be working fine. 
Error: 
Unable to execute HTTP request: Unacceptable certificate: CN=Amazon, OU=Server CA 1B, O=Amazon, C=US

**Comment by Gilboot** [comment]
Same issue. Whats the update

**Comment by buntupana** [comment]
A lot of my user are reporting this problem with S3 service with stable network connections (wifi)
