### ISSUE TITLE
Stream is not displaying correctly on Kinesis Console

### ISSUE THREAD

**Issue by muellerfr** [aws-amplify/aws-sdk-android#581]
Issue originally opened by @marujeyakumar at https://github.com/awslabs/aws-sdk-android-samples/issues/269

**State your question**

Hi,
I am running the Kinesis Video demo app on a One Plus 6T device. I'm only able to get a few seconds (if not any seconds) of video content displaying on the Kinesis console. When I check the application logs, I see the following exception repeatedly. Anything I can do to fix this? Is this a problem with the application or the Kinesis Console I am sending the video data to? Thanks in advance! 

```bash
E/AndroidCameraMediaSource: error updating sink with frame
    com.amazonaws.kinesisvideo.producer.ProducerException: Failed to put a frame into the stream. StatusCode: 0x3200000d
        at com.amazonaws.kinesisvideo.internal.producer.jni.NativeKinesisVideoProducerJni.putKinesisVideoFrame(Native Method)
        at com.amazonaws.kinesisvideo.internal.producer.jni.NativeKinesisVideoProducerJni.putFrame(NativeKinesisVideoProducerJni.java:495)
        at com.amazonaws.kinesisvideo.internal.producer.jni.NativeKinesisVideoProducerStream.putFrame(NativeKinesisVideoProducerStream.java:292)
        at com.amazonaws.kinesisvideo.internal.mediasource.ProducerStreamSink.onFrame(ProducerStreamSink.java:52)
        at com.amazonaws.mobileconnectors.kinesisvideo.mediasource.android.AndroidCameraMediaSource$2.onFrameAvailable(AndroidCameraMediaSource.java:266)
        at com.amazonaws.mobileconnectors.kinesisvideo.encoding.EncoderWrapper.sendEncodedFrameToProducerSDK(EncoderWrapper.java:198)
        at com.amazonaws.mobileconnectors.kinesisvideo.encoding.EncoderWrapper.processEncodedData(EncoderWrapper.java:164)
        at com.amazonaws.mobileconnectors.kinesisvideo.encoding.EncoderWrapper.processEncoderOutputBuffer(EncoderWrapper.java:145)
        at com.amazonaws.mobileconnectors.kinesisvideo.encoding.EncoderWrapper.getDataFromEncoder(EncoderWrapper.java:121)
        at com.amazonaws.mobileconnectors.kinesisvideo.encoding.EncoderWrapper.encodeFrame(EncoderWrapper.java:94)
        at com.amazonaws.mobileconnectors.kinesisvideo.camera.CameraFramesSource$1.onImageAvailable(CameraFramesSource.java:68)
        at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:800)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Which AWS Services are you utilizing?**
Kinesis Video Streams

**Provide code snippets (if applicable)**

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.25]

**Device Information (please complete the following information):**
 - Device: [e.g. Pixel XL, Simulator]
 - Android Version: [e.g. Nougat 7.1.2]
 - Specific to simulators:

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by MushMal** [comment]
@muellerfr thanks for reaching out. Some Android devices use encoders which output the elementary stream in a non-Annex-B format. Here is an article that covers some of the aspects: https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/troubleshooting.html#troubleshooting-producer-android-invalid-annexb

KVS producer error code reference: https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/producer-sdk-errors.html

**Comment by muellerfr** [comment]
This issue has been closed because of inactivity. Please open a new issue if are still encountering problems.
