### ISSUE TITLE
Upload fails with S3 acceleration enabled

### ISSUE THREAD

**Issue by baole** [aws-amplify/aws-sdk-android#591]
**State your question**
I try to upload files to S3 from our Android app. It works perfectly with S3 acceleration off. However, It fails to upload when S3 acceleration on. 

S3 acceleration is already turned on on AWS.

**Which AWS Services are you utilizing?**
S3

**Provide code snippets (if applicable)**
The follow function is used to test with and without acceleration. 

```
   public void test(Boolean useAcceleration, File afile) {
        String accessKeyId = pref.getAwsAccessKeyId();
        String secretKey = pref.getAwsSecretKey();
        String sessionToken = pref.getAwsSessionToken();
        String bucket = "my_bucket";


        AmazonS3Client s3Client = new AmazonS3Client(new BasicSessionCredentials(accessKeyId, secretKey, sessionToken));
        s3Client.setRegion(Region.getRegion(Regions.US_EAST_1));
        s3Client.setS3ClientOptions(S3ClientOptions.builder()
                .setPathStyleAccess(true)
                .setAccelerateModeEnabled(useAcceleration)
                .build());

        PutObjectRequest por = new PutObjectRequest(bucket, "test.txt", afile);
        por.setCannedAcl(CannedAccessControlList.BucketOwnerFullControl);

        s3Client.putObject(por);
    }

```

It works fine when `useAcceleration=false` and throws following error when `useAcceleration=true`

```
com.amazonaws.AmazonClientException: Unable to execute HTTP request: Unable to resolve host "s3-accelerate.amazonaws.com": No address associated with hostname
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:441)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
    at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4659)
    at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1752)
```

AWS S3 SDK somehow doesn't resolve the endpoint correctly because this article (https://docs.aws.amazon.com/AmazonS3/latest/dev/transfer-acceleration.html) states that the endpoint should include the bucket name.

Next step, I rewrite the request to change the endpoint as follow
```
void intercept(AmazonS3Client sS3Client, String bucket) {

        sS3Client.addRequestHandler(new RequestHandler2() {
            @Override
            public void beforeRequest(Request<?> request) {
                String endpoint = request.getEndpoint().toString();
                Logging.d("S3: endpoint %s", endpoint);
                request.setEndpoint(URI.create("https://" + bucket + ".s3-accelerate.amazonaws.com"));
                Logging.d("S3: endpoint new %s", request.getEndpoint());
            }

            @Override
            public void afterResponse(Request<?> request, com.amazonaws.Response<?> response) {

            }

            @Override
            public void afterError(Request<?> request, com.amazonaws.Response<?> response, Exception e) {
                e.printStackTrace();
            }
        });

    }
```

The new endpoint now includes the bucket name. However, I now get another error:

```
com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 55E733B2585A4811), S3 Extended Request ID: xXMFmnUajjU78WsiOCwfBAl0RY/e5xSgPaUFsX3ZZ5WIAPJp/sjQ2/o31A3AnxxG/N6er4ZCK6I=
    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:730)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:405)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
    at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4659)
    at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1752)

```

**Environment(please complete the following information):**
 - SDK Version: 2.8.4

**Device Information (please complete the following information):**
 - Device: Pixel, Samung Duos
 - Android Version: Android 9, Android 7

**Comment by ederaldooc** [comment]
I'm facing same problem here, there is a ETA to fix this issue ?

**Comment by muellerfr** [comment]
Hello @baole and @ederaldooc,

Thanks for reporting this issue, and sorry for the problems. We'll take a look and report back.

**Comment by kvasukib** [comment]
@baole Sorry for the delayed response. Can you try enabling acceleration but without path style access set to true?

```java
s3Client.setS3ClientOptions(S3ClientOptions.builder()
                .setAccelerateModeEnabled(useAcceleration)
                .build());
```

**Comment by baole** [comment]
It works @kvasukib  @muellerfr. Thank you.

**Comment by kvasukib** [comment]
Thank you @baole.
