### ISSUE TITLE
not taking awsconfiguration.json file,SDK initialization failing 

### ISSUE THREAD

**Issue by warlock-jay** [aws-amplify/aws-sdk-android#626]
**State your question**
not taking awsconfiguration.json file even it's present in specified location
**Which AWS Services are you utilizing?**
My application is user has to sign-in and sign up using my cognitopool and federated identities,have give services s3 bucket and iot
**Provide code snippets (if applicable)**
this is the code i used in Main activity

```
        AWSMobileClient.getInstance().initialize(getApplicationContext(),awsConfig, new Callback<UserStateDetails>() {

                    @Override
                    public void onResult(UserStateDetails userStateDetails) {
                        Log.i("INIT", "onResult: " + userStateDetails.getUserState());
                    }

                    @Override
                    public void onError(Exception e) {
                        Log.e("INIT", "Initialization error.", e);
                    }
                }
        );
```

 i got this error when running apk
```
2018-12-24 13:42:34.928 18293-18293/? I/userState: Code started
2018-12-24 13:42:34.935 18293-18293/? D/AndroidRuntime: Shutting down VM
2018-12-24 13:42:34.940 18293-18340/? D/AWSMobileClient: Using the SignInProviderConfig from `awsconfiguration.json`.
2018-12-24 13:42:34.940 18293-18293/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.aura.app8, PID: 18293
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.aura.app8/com.example.aura.app8.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUserPool.getUser(java.lang.String)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2900)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2979)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1634)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6673)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUserPool.getUser(java.lang.String)' on a null object reference
        at com.example.aura.app8.Cognito.userLogin(Cognito.java:95)
        at com.example.aura.app8.MainActivity.onCreate(MainActivity.java:52)
        at android.app.Activity.performCreate(Activity.java:6984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1235)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2853)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2979) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1634) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6673) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769) 
2018-12-24 13:42:34.940 18293-18340/? D/AWSMobileClient: CognitoUserPool not found in `awsconfiguration.json`
2018-12-24 13:42:34.940 18293-18340/? D/AWSMobileClient: FacebookSignIn not found in `awsconfiguration.json`
2018-12-24 13:42:34.940 18293-18340/? D/AWSMobileClient: GoogleSignIn not found in `awsconfiguration.json`
2018-12-24 13:42:34.942 18293-18340/? E/INIT: Initialization error.
    java.lang.NullPointerException: Attempt to invoke virtual method 'org.json.JSONObject com.amazonaws.mobile.config.AWSConfiguration.optJsonObject(java.lang.String)' on a null object reference
        at com.amazonaws.mobile.client.AWSMobileClient$2.run(AWSMobileClient.java:396)
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
        at java.lang.Thread.run(Thread.java:764)
2018-12-24 13:42:34.945 2927-4443/? W/ActivityManager:   Force finishing activity com.example.aura.app8/.MainActivity
```

 my awsconfiguration file looks like this
```
{
   "CredentialsProvider": {
    "CognitoIdentity": {
      "Default": {
        "PoolId": "******************",
        "Region": "**********"
      }
    }
  },
  "IdentityManager": {
    "Default": {}
  },
  "CognitoUserPool": {
    "Default": {
      "PoolId": "***************************",
      "AppClientId": "*************************",
      "AppClientSecret": "****************",
      "Region": "*******"
    }
  }
}
```

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.25]
these lines i have added to gradle

def androidLibraryVersion='28.0.0'
    def aws_version = "2.8.+"
    implementation('com.amazonaws:aws-android-sdk-mobile-client:2.8.+@aar') { transitive = true }
    implementation('com.amazonaws:aws-android-sdk-auth-userpools:2.8.+@aar') { transitive = true }
    implementation('com.amazonaws:aws-android-sdk-auth-ui:2.8.+@aar') { transitive = true }
    implementation 'com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.8.+'
    implementation ('com.amazonaws:aws-android-sdk-cognitoauth:2.8.+@aar') { transitive = true}
    implementation "com.android.support:customtabs:${androidLibraryVersion}"
    implementation "com.amazonaws:aws-android-sdk-s3:2.8+"
    implementation ("com.amazonaws:aws-android-sdk-mobile-client:2.8+") { transitive = true }
    implementation "com.amazonaws:aws-android-sdk-iot:2.8+"
    implementation "com.amazonaws:aws-android-sdk-mobile-client:2.8+"
    implementation "com.amazonaws:aws-android-sdk-core:2.8+"

**Device Information (please complete the following information):**
 - Device: [e.g. Pixel XL, Simulator]
i am using my own phone moto-g6
 - Android Version: [e.g. Nougat 7.1.2]
Android oreo
 - Specific to simulators:

I stuck with setting up this thing ,it's not takinig the configuration file

/home/jay/AndroidStudioProjects/App12/app/src/main/res/raw/awsconfiguration.json

Do i have to give any permissions?

Give details about initialization of SDK(mobile client)?
What i read online or forums all are deprecated

**Comment by minbi** [comment]
Hi @warlock-jay ,

Can you check whether the `AWSConfiguration` object you are passing in is null? The exception appears to happen the first time that value is being accessed. [Approximate line](https://github.com/aws-amplify/aws-sdk-android/blob/master/aws-android-sdk-mobile-client/src/main/java/com/amazonaws/mobile/client/AWSMobileClient.java#L397)

**Comment by minbi** [comment]
Since you are using the default location and not customizing it's usage you may use:

```
AWSMobileClient.getInstance().initialize(getApplicationContext(), new Callback<UserStateDetails>() {...}
```

This will create the AWSConfiguration object for you.

Otherwise you may construct it:

```
awsConfig = new AWSConfiguration(getApplicationContext());
```

**Comment by warlock-jay** [comment]
HI @minbi 
Thank you,Initialization is working.
Do you have any code snippets on sign-in using cognito userpool and federated identities?

**Comment by minbi** [comment]
Our [documentation](https://aws-amplify.github.io/docs/android/authentication) should help get you started.
