### ISSUE TITLE
Best practice to handle hanging of calls to AWS services

### ISSUE THREAD

**Issue by nchorniy** [aws-amplify/aws-sdk-android#637]
**Question**
What is the best practice to avoid hanging of AWS service calls (such as dynamodb save operation) if credentials token becomes invalid?

**AWS Services we are utilizing**:
- DynamoDB
- S3
- AppSync

**Problem description and code snippets**
This call blocked the thread forever in `AWSMobileClient.waitForSignIn()` method.

```kotlin
dynamoDBMapper.save(entity)
```
dynamoDBMapper of class `DynamoDBMapper`.

Before making this call to dynamoDB service, the code also checked whether the user was signed by calling `AWSMobileClient.isSignedIn()` and it returned `true` (the `UserState` was `SIGNED_OUT_USER_POOLS_TOKENS_INVALID`).

It seems that workaround here would be to register a user state change listener `AWSMobileClient.getInstance().addUserStateListener` and on `SIGNED_OUT_USER_POOLS_TOKENS_INVALID` state (per https://github.com/aws-amplify/docs/blob/master/android/authentication.md#cognito-user-pool-tokens) make sure that no calls to the `AWSMobileClient.getCredentials()` (or any other AWS operations will be called, except login attempts).

But this is not clear from the documentation which says
> If you want to cancel the re-login process, for instance if your application is shared among multiple users of the device or a user clicks "cancel" on the re-login attempt, you can call releaseSignInWait() to terminate the call and then call a signOut()

From the other side, it seems to be at least strange, that call to some operations will block the thread forever. 
In case `AWSMobileClient` threw an appropriate exception, the app would have a chance to handle it, but in current state thread will be just blocked forever.

```
signalTokensNotAvailable
Tokens are invalid, please sign-in again.
	at com.amazonaws.mobile.client.AWSMobileClient$6$1.getAuthenticationDetails(AWSMobileClient.java:1017)
java.lang.Exception: No cached session.
	at com.amazonaws.mobile.client.AWSMobileClient$6$1.signalTokensNotAvailable(AWSMobileClient.java:1037)
	at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getSession(CognitoUser.java:749)
	at com.amazonaws.mobile.client.AWSMobileClient.getUserStateDetails(AWSMobileClient.java:655)
	at com.amazonaws.mobile.client.AWSMobileClient$6.run(AWSMobileClient.java:999)
	at com.amazonaws.mobile.client.internal.InternalCallback.await(InternalCallback.java:115)
	at com.amazonaws.mobile.client.AWSMobileClient.waitForSignIn(AWSMobileClient.java:570)
	at com.amazonaws.mobile.client.AWSMobileClient.getTokens(AWSMobileClient.java:973)
	at com.amazonaws.mobile.client.AWSMobileClient.getCredentials(AWSMobileClient.java:256)
	at com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBMapper.save(DynamoDBMapper.java:1132)
	at com.ehawk.model.dynamo.DynamoParoleLoader.saveEvent(DynamoParoleLoader.kt:173)
	at com.ehawk.ehawktracker.workers.SaveCheckInEventWorker.performAuthenticatedWork(SaveCheckInEventWorker.kt:52)
	at com.ehawk.common.workers.BaseAuthenticatedWorker$doWork$1.invokeSuspend(BaseAuthenticatedWorker.kt:41)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:5200)
	at com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBMapper.save(DynamoDBMapper.java:909)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.updateItem(AmazonDynamoDBClient.java:2848)
	at com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBMapper$SaveObjectHandler.doUpdateItem(DynamoDBMapper.java:1402)
	at com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBMapper$2.executeLowLevelRequest(DynamoDBMapper.java:1101)
	at com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBMapper$SaveObjectHandler.execute(DynamoDBMapper.java:1285)
	at com.ehawk.model.dynamo.DynamoParoleLoader.addCheckIn(DynamoParoleLoader.kt:169)
	at com.ehawk.ehawktracker.ParoleManager.addCheckIn(ParoleManager.kt:341)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.kt:116)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:76)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:53)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:35)
	at androidx.work.Worker$1.run(Worker.java:84)
waitForSignIn: userState:SIGNED_OUT_USER_POOLS_TOKENS_INVALID
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at com.ehawk.common.workers.BaseAuthenticatedWorker.doWork(BaseAuthenticatedWorker.kt:30)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
```

**Environment:**
 - SDK Version: 2.9.1

**Device Information:**
 - Device: Pixel 1
 - Android Version: 9

**Comment by nchorniy** [comment]
@minbi That makes sense. That's actually a normal behaviour. I think this should be outlined in documentation in the first place: like `Don't forget to register UserStateListener every time you use AWSMobileClient and perform a sign out upon detecting the "tokens invalid" state, because otherwise, your running operations may block the threads they are running inside`.

Another possible solution is to avoid blocking of the threads in case if tokens become invalid (and throwing some Exception), but that would be a breaking change.

**Comment by minbi** [comment]
We are tracking this documentation issue here https://github.com/aws-amplify/docs/issues/414
