### ISSUE TITLE
S3 TransferUtility : Timeout  error in slow network when media is uploaded 

### ISSUE THREAD

**Issue by sysquare** [aws-amplify/aws-sdk-android#638]
**Describe the bug**
Not able to upload a 125 MB video on slow network. Refer screenshots

**To Reproduce**
1. Go to upload section of s3 transfer utility sample app
2. Click on upload media
3. Upload a file. Mine was 125 MB
4. See error enslosed. It is because of slow network and where and upload speed was less than equal to 2 Mbps

**Which AWS service(s) are affected?**
Transfer Utility from android phone

**Expected behavior**
It should upload even in slow network. Its

**Screenshots**
![screenshot_20190108-195542](https://user-images.githubusercontent.com/24691073/50891579-969fa800-1422-11e9-9870-f96136bdd9c9.png)
[error_log_aws_demo.txt](https://github.com/aws-amplify/aws-sdk-android/files/2740283/error_log_aws_demo.txt)

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.25]

**Device Information (please complete the following information):**
 - Device: [Samsung S7, Moto G5s Plus]
 - Android Version: [8.1.0]
 - Specific to simulators:

**Additional context**
Nothing.

**Comment by sysquare** [comment]
I did not tried "RESUME", but how does it matter as I have not "PAUSED" anything ?

**Comment by sysquare** [comment]
I tried 2-3 files again, but this time it did not failed. It fails on poor network and its hard to reproduce.
Will try again

**Comment by sysquare** [comment]
Also, I am getting below errors in firebase when app is in background :


Fatal Exception: java.lang.RuntimeException: Unable to create application com.buddynation.DroneNation.Applications: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.buddynation.DroneNation/com.amazonaws.mobileconnectors.s3.transferutility.TransferService }: app is in background uid UidRecord{423b448 u0a314 RCVR idle procs:1 seq(0,0,0)}
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6061)
       at android.app.ActivityThread.-wrap1(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6940)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)



Caused by java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.buddynation.DroneNation/com.amazonaws.mobileconnectors.s3.transferutility.TransferService }: app is in background uid UidRecord{423b448 u0a314 RCVR idle procs:1 seq(0,0,0)}
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1538)
       at android.app.ContextImpl.startService(ContextImpl.java:1484)
       at android.content.ContextWrapper.startService(ContextWrapper.java:663)
       at com.buddynation.DroneNation.Applications.onCreate(Applications.java:139)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1125)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6058)
       at android.app.ActivityThread.-wrap1(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6940)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by kvasukib** [comment]
@sysquare It is expected to get the exception when you start the service when the app is in background. We are actively working on a solution to move the service to foreground state when the device is running Oreo and above. I will update this thread when the fix for this foreground promotion feature is released.

The functionality that `TransferService` provides is: Detecting the network connectivity and pausing transfers when its offline and resuming when its online. As a workaround (until the fix for foreground promotion is released), you could write a foreground service that does the same functionality as `TransferService` to avoid the crash.

**Comment by kvasukib** [comment]
@sysquare The next SDK release will be containing the changes for transitioning the service to foreground state when the device is running Oreo and above. Thank you for the patience.

**Comment by sysquare** [comment]
any rough idea, when can we expect next SDK ?

**Comment by palpatim** [comment]
Hi @sysquare,

We are working on this feature now but don't have a firm release date. We'll update this thread when we have more information.

**Comment by kvasukib** [comment]
@sysquare The foreground feature is released in `2.11.0` version of the SDK. Please read our [CHANGELOG](https://github.com/aws-amplify/aws-sdk-android/blob/master/CHANGELOG.md#release-2110) and [Documentation](https://aws-amplify.github.io/docs/android/storage#supporting-transferservice-on-oreo-and-above) for detailed information on the change. We advise you to perform testing and understand the behavior before upgrading the SDK.
