### ISSUE TITLE
AWS Rekognition Android Sample code

### ISSUE THREAD

**Issue by VirRajpurohit** [aws-amplify/aws-sdk-android#639]
I am not able to find the sample code for the face compare feature provided by AWS Rekognition in Android.

**AWS Rekognition**

**Comment by kvasukib** [comment]
@VirRajpurohit Thank you for reporting to us.

```java
public void compareFaces() {
        Float similarityThreshold = 70F;
        String sourceImage = "source.jpg";
        String targetImage = "target.jpg";
        ByteBuffer sourceImageBytes = null;
        ByteBuffer targetImageBytes = null;

        AmazonRekognition rekognitionClient = new AmazonRekognitionClient(new BasicAWSCredentials("", ""));


        //Load source and target images and create input parameters
        try (InputStream inputStream = new FileInputStream(new File(sourceImage))) {
            sourceImageBytes = ByteBuffer.wrap(IOUtils.toByteArray(inputStream));
        }
        catch(Exception e)
        {
            System.out.println("Failed to load source image " + sourceImage);
            System.exit(1);
        }
        try (InputStream inputStream = new FileInputStream(new File(targetImage))) {
            targetImageBytes = ByteBuffer.wrap(IOUtils.toByteArray(inputStream));
        }
        catch(Exception e)
        {
            System.out.println("Failed to load target images: " + targetImage);
            System.exit(1);
        }

        Image source = new Image()
                .withBytes(sourceImageBytes);
        Image target = new Image()
                .withBytes(targetImageBytes);

        CompareFacesRequest request = new CompareFacesRequest()
                .withSourceImage(source)
                .withTargetImage(target)
                .withSimilarityThreshold(similarityThreshold);

        // Call operation
        CompareFacesResult compareFacesResult = rekognitionClient.compareFaces(request);


        // Display results
        List <CompareFacesMatch> faceDetails = compareFacesResult.getFaceMatches();
        for (CompareFacesMatch match: faceDetails){
            ComparedFace face= match.getFace();
            BoundingBox position = face.getBoundingBox();
            System.out.println("Face at " + position.getLeft().toString()
                    + " " + position.getTop()
                    + " matches with " + face.getConfidence().toString()
                    + "% confidence.");

        }
        List<ComparedFace> uncompared = compareFacesResult.getUnmatchedFaces();

        System.out.println("There was " + uncompared.size()
                + " face(s) that did not match");
        System.out.println("Source image rotation: " + compareFacesResult.getSourceImageOrientationCorrection());
        System.out.println("target image rotation: " + compareFacesResult.getTargetImageOrientationCorrection());
    }
```

Be sure to use `import com.amazonaws.services.rekognition.model.Image;` for the `Image` class referenced in the code and not the Image from `android.media`.

**Comment by VirRajpurohit** [comment]
Ok, so this certainly requires AWS api keys and another authentication things. Where all this needs to be kept in code?

**Comment by desokroshan** [comment]
@VirRajpurohit You can pass the AWS access key id and secret access key while instantiating that Rekognition client in the snippet above : 
```java
AmazonRekognition rekognitionClient = new AmazonRekognitionClient(new BasicAWSCredentials(<Access_key_id>, "secret_access_key"));
```
It is however recommended to use temporary credentials from a credentials provider for production apps as follows : 

```
AmazonRekognition rekognitionClient = new AmazonRekognitionClient(AWSMobileClient.getInstance());
```

You can read more using and initializing AWsMobileClient in the [documentation here](https://aws-amplify.github.io/docs/android/authentication).

**Comment by VirRajpurohit** [comment]
@desokroshan 
so,
`AmazonRekognition rekognitionClient = new AmazonRekognitionClient(AWSMobileClient.getInstance());
`This is we can take as a testing purpose

when we want to go live with the app
 `AmazonRekognition rekognitionClient = new AmazonRekognitionClient(new BasicAWSCredentials(<Access_key_id>, "secret_access_key"));`
This is recommended.
Is it so?

Also,
withoput key must be having some limitations in compare to provoding keys in the clientBuilder?

**Comment by desokroshan** [comment]
Its the other way round actually. Providing key is not recommended for security reasons. Hard coding keys into the app code makes it available to anyone with access to your app's apk file(which is everyone once the app is live on play store).
Hope it help!

**Comment by VirRajpurohit** [comment]
@desokroshan 
Understand!

My actual question rolls around the curiosity about the authentication procedure. 

One must have AWS account to proceed with the AWS Rekognition integration. so where does this account credentials are being used?

Downloading the SDK and integrating the code @kvasukib provided is all about this?

**Comment by desokroshan** [comment]
To be able to use AWS Rekognition you need to configure Cognito Identity pool. You would  then have to create awsconfiguration.json file with Cognito identity pool Id and region, place it res/raw folder of your application. This information will be used by AWSMobile client during its initialization to configure Cognito Identity.
I would suggest going through the [documentation](https://aws-amplify.github.io/docs/android/authentication) and trying out some [sample apps](https://github.com/awslabs/aws-sdk-android-samples) before getting started.

**Comment by VirRajpurohit** [comment]
After going through samples and documentation it is being difficult to integrate Face Rekognition.

[SDK](https://github.com/aws-amplify/aws-sdk-android/tree/master/aws-android-sdk-rekognition) and [samples](https://github.com/awslabs/aws-sdk-android-samples) do not include steps and code for AWS Rekognition service integration in Android.

**Comment by ketanspryox** [comment]
Hi i am working with aws reKognition  in android  i want to scan image and check whether it is  s3 bucket is there any who can help me with that

**Comment by haorans1994** [comment]
Hey there, I have a question...when I run this code:
                        //Load source and target images and create input parameters
                        try (InputStream inputStream = new FileInputStream(new File(sourceImage))) {
                            sourceImageBytes = ByteBuffer.wrap(IOUtils.toByteArray(inputStream));
                        }
                        catch(Exception e)
                        {

                        }
                        try (InputStream inputStream = new FileInputStream(new File(targetImage))) {
                            targetImageBytes = ByteBuffer.wrap(IOUtils.toByteArray(inputStream));
                        }
                        catch(Exception e)
                        {

                        }

                        Image source = new Image()
                                .withBytes(sourceImageBytes);
                        Image target = new Image()
                                .withBytes(targetImageBytes);

                        CompareFacesRequest request = new CompareFacesRequest()
                                .withSourceImage(source)
                                .withTargetImage(target)
                                .withSimilarityThreshold(similarityThreshold);

                        // Call operation
                        CompareFacesResult compareFacesResult = rekognitionClient.compareFaces(request);

                        List<ComparedFace> uncompared = compareFacesResult.getUnmatchedFaces();


                        final StringBuilder stringBuilder = new StringBuilder();

                        // Display results
                        List<CompareFacesMatch> faceDetails = compareFacesResult.getFaceMatches();
                        for (CompareFacesMatch match: faceDetails){
                            ComparedFace face= match.getFace();
                            BoundingBox position = face.getBoundingBox();
                            stringBuilder.append("Face at " + position.getLeft().toString()
                                    + " " + position.getTop()
                                    + " matches with " + face.getConfidence().toString()
                                    + "% confidence.");

                        }
it will give me the error that:Requested image should either contain bytes or s3 object.
I'm pretty sure I was using import com.amazonaws.services.rekognition.model.Image;
and I have put my jpg file in the same path as this MainActivity. I was processing the image based on your advice, but why did the service consider it as non-contain bytes?
Cheers

**Comment by haorans1994** [comment]
Hi 
I was developing a demo in Android, So I use your code, and did some changes:

public class MainActivity extends AppCompatActivity {

    ImageView imageView;

    Float similarityThreshold = 70F;
    ByteBuffer sourceImageBytes = null;
    ByteBuffer targetImageBytes = null;
    AmazonRekognition rekognitionClient = new AmazonRekognitionClient(new BasicAWSCredentials(
            "xxxxxxxxx",
            "xxxxxxxxxxxxxxxxxxxxxxxxxxxx")
            );

    @RequiresApi(api = Build.VERSION_CODES.KITKAT)



    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);


        Button btnCamera = (Button) findViewById(R.id.BtnCamera);
        imageView = (ImageView)findViewById(R.id.imageView);
        

        btnCamera.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent intent = new Intent(MediaStore.ACTION_IMAGE_CAPTURE);
                startActivityForResult(intent,0);

//                TextView resultTextView = (TextView) findViewById(R.id.resultTextView);
//                resultTextView.setText(("good job"));
            }
        });

    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        Bitmap bitmap = (Bitmap)data.getExtras().get("data");
        int bytes = bitmap.getByteCount();

        ByteBuffer buffer = ByteBuffer.allocate(bytes); //Create a new buffer
        bitmap.copyPixelsToBuffer(buffer); //Move the byte data to the buffer

        sourceImageBytes = buffer;
        targetImageBytes = buffer;
        Image source = new Image()
                .withBytes(sourceImageBytes);
        Image target = new Image()
                .withBytes(targetImageBytes);

        final CompareFacesRequest request = new CompareFacesRequest()
                .withSourceImage(source)
                .withTargetImage(target)
                .withSimilarityThreshold(similarityThreshold);

        // Call operation

        AsyncTask.execute(new Runnable() {
            @Override
            public void run() {
                CompareFacesResult compareFacesResult = rekognitionClient.compareFaces(request);
            }
        });
    }
}

So I use a button to use camera, and have the bitmap of it. Then I transfer it to byte buffer.
When I run the program on android, I click the button, click ok to store the bitmp of the picture, I would get error on “CompareFacesResult compareFacesResult = rekognitionClient.compareFaces(request);”
The information is:
2019-11-03 15:46:11.952 8834-9553/com.example.takepicture E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: com.example.takepicture, PID: 8834
    com.amazonaws.AmazonServiceException: 2 validation errors detected: Value 'java.nio.HeapByteBuffer[pos=0 lim=0 cap=0]' at 'sourceImage.bytes' failed to satisfy constraint: Member must have length greater than or equal to 1; Value 'java.nio.HeapByteBuffer[pos=0 lim=0 cap=0]' at 'targetImage.bytes' failed to satisfy constraint: Member must have length greater than or equal to 1 (Service: AmazonRekognition; Status Code: 400; Error Code: ValidationException; Request ID: db230cc3-7e42-499c-a02b-4635f6e0077a)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:730)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:405)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
        at com.amazonaws.services.rekognition.AmazonRekognitionClient.invoke(AmazonRekognitionClient.java:3006)
        at com.amazonaws.services.rekognition.AmazonRekognitionClient.compareFaces(AmazonRekognitionClient.java:399)
        at com.example.takepicture.MainActivity$2.run(MainActivity.java:101)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

Seems the service consider the Buffer I send was empty.
Could you help me solve the problem if you have time?
Thank you very much.

**Comment by maven08** [comment]
Hi, @kvasukib 

I am working on AWS rekognition in android followed the same steps as mentioned by you but getting the below error.


    2023-01-27 18:52:47.162  7049-7049  GraphicsEnvironment     com.example.myapplication            V  ANGLE Developer option for 'com.example.myapplication' set to: 'default'
    2023-01-27 18:52:47.163  7049-7049  GraphicsEnvironment     com.example.myapplication            V  ANGLE GameManagerService for com.example.myapplication: false
    2023-01-27 18:52:47.163  7049-7049  GraphicsEnvironment     com.example.myapplication            V  Neither updatable production driver nor prerelease driver is supported.
    2023-01-27 18:52:47.181  7049-7049  NetworkSecurityConfig   com.example.myapplication            D  No Network Security Config specified, using platform default
    2023-01-27 18:52:47.185  7049-7049  NetworkSecurityConfig   com.example.myapplication            D  No Network Security Config specified, using platform default
    2023-01-27 18:52:47.260  7049-7086  libEGL                  com.example.myapplication            D  loaded /vendor/lib64/egl/libEGL_emulation.so
    2023-01-27 18:52:47.261  7049-7086  libEGL                  com.example.myapplication            D  loaded /vendor/lib64/egl/libGLESv1_CM_emulation.so
    2023-01-27 18:52:47.265  7049-7086  libEGL                  com.example.myapplication            D  loaded /vendor/lib64/egl/libGLESv2_emulation.so
    2023-01-27 18:52:47.556  7049-7049  AppCompatDelegate       com.example.myapplication            D  Checking for metadata for AppLocalesMetadataHolderService : Service not found
    2023-01-27 18:52:47.718  7049-7049  e.myapplicatio          com.example.myapplication            W  Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (unsupported, reflection, allowed)
    2023-01-27 18:52:47.718  7049-7049  e.myapplicatio          com.example.myapplication            W  Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (unsupported, reflection, allowed)
    2023-01-27 18:52:48.941  7049-7084  HostConnection          com.example.myapplication            D  createUnique: call
    2023-01-27 18:52:48.958  7049-7084  HostConnection          com.example.myapplication            D  HostConnection::get() New Host Connection established 0x767888ae8b90, tid 7084
    2023-01-27 18:52:48.980  7049-7084  HostConnection          com.example.myapplication            D  HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0 
    2023-01-27 18:52:48.986  7049-7084  OpenGLRenderer          com.example.myapplication            W  Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
    2023-01-27 18:52:48.987  7049-7084  OpenGLRenderer          com.example.myapplication            W  Failed to initialize 101010-2 format, error = EGL_SUCCESS
    2023-01-27 18:52:48.988  7049-7084  EGL_emulation           com.example.myapplication            D  eglCreateContext: 0x767888ae9190: maj 3 min 0 rcv 3
    2023-01-27 18:52:48.990  7049-7084  EGL_emulation           com.example.myapplication            D  eglMakeCurrent: 0x767888ae9190: ver 3 0 (tinfo 0x767aad2e3080) (first time)
    2023-01-27 18:52:49.001  7049-7087  e.myapplicatio          com.example.myapplication            I  Waiting for a blocking GC ClassLinker
    2023-01-27 18:52:49.004  7049-7084  Gralloc4                com.example.myapplication            I  mapper 4.x is not supported
    2023-01-27 18:52:49.009  7049-7084  HostConnection          com.example.myapplication            D  createUnique: call
    2023-01-27 18:52:49.010  7049-7084  HostConnection          com.example.myapplication            D  HostConnection::get() New Host Connection established 0x767888ae8e90, tid 7084
    2023-01-27 18:52:49.013  7049-7084  goldfish-address-space  com.example.myapplication            D  allocate: Ask for block of size 0x100
    2023-01-27 18:52:49.015  7049-7084  goldfish-address-space  com.example.myapplication            D  allocate: ioctl allocate returned offset 0x3f3ffe000 size 0x2000
    2023-01-27 18:52:49.018  7049-7084  Gralloc4                com.example.myapplication            W  allocator 4.x is not supported
    2023-01-27 18:52:49.036  7049-7059  e.myapplicatio          com.example.myapplication            I  Background young concurrent copying GC freed 351(65KB) AllocSpace objects, 5(7956KB) LOS objects, 17% free, 33MB/41MB, paused 1.254ms,128us total 106.898ms
    2023-01-27 18:52:49.036  7049-7087  e.myapplicatio          com.example.myapplication            I  WaitForGcToComplete blocked ClassLinker on Background for 34.926ms
    2023-01-27 18:52:49.040  7049-7084  HostConnection          com.example.myapplication            D  HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0 
    2023-01-27 18:52:49.256  7049-7049  Choreographer           com.example.myapplication            I  Skipped 31 frames!  The application may be doing too much work on its main thread.
    2023-01-27 18:52:50.139  7049-7059  e.myapplicatio          com.example.myapplication            I  Background concurrent copying GC freed 108(35KB) AllocSpace objects, 2(28MB) LOS objects, 21% free, 89MB/113MB, paused 484us,65us total 100.643ms
    2023-01-27 18:52:50.396  7049-7087  e.myapplicatio          com.example.myapplication            I  Waiting for a blocking GC Alloc
    2023-01-27 18:52:50.409  7049-7059  e.myapplicatio          com.example.myapplication            I  Background concurrent copying GC freed 14(31KB) AllocSpace objects, 3(25MB) LOS objects, 13% free, 147MB/171MB, paused 425us,65us total 115.410ms
    2023-01-27 18:52:50.409  7049-7087  e.myapplicatio          com.example.myapplication            I  WaitForGcToComplete blocked Alloc on Background for 13.249ms
    2023-01-27 18:52:50.409  7049-7087  e.myapplicatio          com.example.myapplication            I  Starting a blocking GC Alloc
    2023-01-27 18:52:50.465  7049-7087  e.myapplicatio          com.example.myapplication            I  Waiting for a blocking GC Alloc
    2023-01-27 18:52:50.473  7049-7059  e.myapplicatio          com.example.myapplication            I  Background young concurrent copying GC freed 1(29KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 185MB/185MB, paused 9.887ms,65us total 62.444ms
    2023-01-27 18:52:50.473  7049-7087  e.myapplicatio          com.example.myapplication            I  WaitForGcToComplete blocked Alloc on Background for 7.677ms
    2023-01-27 18:52:50.473  7049-7087  e.myapplicatio          com.example.myapplication            I  Starting a blocking GC Alloc
    2023-01-27 18:52:50.473  7049-7087  e.myapplicatio          com.example.myapplication            I  Forcing collection of SoftReferences for 18MB allocation
    2023-01-27 18:52:50.474  7049-7087  e.myapplicatio          com.example.myapplication            I  Starting a blocking GC Alloc
    2023-01-27 18:52:50.499  7049-7087  e.myapplicatio          com.example.myapplication            I  Alloc concurrent copying GC freed 1261(76KB) AllocSpace objects, 3(54MB) LOS objects, 15% free, 131MB/155MB, paused 572us,68us total 25.185ms
    2023-01-27 18:52:50.500  7049-7059  e.myapplicatio          com.example.myapplication            I  WaitForGcToComplete blocked Background on Alloc for 25.299ms
    2023-01-27 18:52:50.546  7049-7059  e.myapplicatio          com.example.myapplication            I  Background young concurrent copying GC freed 0(31KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 187MB/187MB, paused 12.952ms,94us total 33.277ms
    2023-01-27 18:52:50.741  7049-7087  AWS4Signer              com.example.myapplication            D  AWS4 Canonical Request: '"POST
                                                                                                        /
                                                                                                        
                                                                                                        host:rekognition.us-east-1.amazonaws.com
                                                                                                        x-amz-date:20230127T132250Z
                                                                                                        x-amz-target:RekognitionService.CompareFaces
                                                                                                        
                                                                                                        host;x-amz-date;x-amz-target
                                                                                                        b5eface55aae79114772856743e417ee361e9c1541c4e2cfb553a5ca218dcffe"
    2023-01-27 18:52:50.743  7049-7087  AWS4Signer              com.example.myapplication            D  AWS4 String to Sign: '"AWS4-HMAC-SHA256
                                                                                                        20230127T132250Z
                                                                                                        20230127/us-east-1/rekognition/aws4_request
                                                                                                        1abc4baff1b385231d803be1c94630bdd36ae6476f8878628c920ccd3a8e0f5d"
    2023-01-27 18:52:59.455  7049-7087  AWS4Signer              com.example.myapplication            D  AWS4 Canonical Request: '"POST
                                                                                                        /
                                                                                                        
                                                                                                        host:rekognition.us-east-1.amazonaws.com
                                                                                                        x-amz-date:20230127T132259Z
                                                                                                        x-amz-target:RekognitionService.CompareFaces
                                                                                                        
                                                                                                        host;x-amz-date;x-amz-target
                                                                                                        b5eface55aae79114772856743e417ee361e9c1541c4e2cfb553a5ca218dcffe"
    2023-01-27 18:52:59.457  7049-7087  AWS4Signer              com.example.myapplication            D  AWS4 String to Sign: '"AWS4-HMAC-SHA256
                                                                                                        20230127T132259Z
                                                                                                        20230127/us-east-1/rekognition/aws4_request
                                                                                                        fec2793c27b1afb7f27bb6b149d11000abf8445230b63895de40153c7fbdf9ea"
    2023-01-27 18:53:04.466  7049-7087  AWS4Signer              com.example.myapplication            D  AWS4 Canonical Request: '"POST
                                                                                                        /
                                                                                                        
                                                                                                        host:rekognition.us-east-1.amazonaws.com
                                                                                                        x-amz-date:20230127T132304Z
                                                                                                        x-amz-target:RekognitionService.CompareFaces
                                                                                                        
                                                                                                        host;x-amz-date;x-amz-target
                                                                                                        b5eface55aae79114772856743e417ee361e9c1541c4e2cfb553a5ca218dcffe"
    2023-01-27 18:53:04.467  7049-7087  AWS4Signer              com.example.myapplication            D  AWS4 String to Sign: '"AWS4-HMAC-SHA256
                                                                                                        20230127T132304Z
                                                                                                        20230127/us-east-1/rekognition/aws4_request
                                                                                                        9c18b9d012b7240c53375561836c6db8fe1aa9f82fd257cec13817bda570a88c"
    2023-01-27 18:53:09.194  7049-7087  AWS4Signer              com.example.myapplication            D  AWS4 Canonical Request: '"POST
                                                                                                        /
                                                                                                        
                                                                                                        host:rekognition.us-east-1.amazonaws.com
                                                                                                        x-amz-date:20230127T132309Z
                                                                                                        x-amz-target:RekognitionService.CompareFaces
                                                                                                        
                                                                                                        host;x-amz-date;x-amz-target
                                                                                                        b5eface55aae79114772856743e417ee361e9c1541c4e2cfb553a5ca218dcffe"
    2023-01-27 18:53:09.195  7049-7087  AWS4Signer              com.example.myapplication            D  AWS4 String to Sign: '"AWS4-HMAC-SHA256
                                                                                                        20230127T132309Z
                                                                                                        20230127/us-east-1/rekognition/aws4_request
                                                                                                        5972e5262dc5b3404edf643176cf189c5de7b6e51b4085205cca14afbd395d36"
    2023-01-27 18:53:58.119  7049-7087  sada :::                com.example.myapplication            E  Unable to execute HTTP request: Connection reset
