### ISSUE TITLE
KinesisVideo Pause/resume streaming error

### ISSUE THREAD

**Issue by sixbladeknife** [aws-amplify/aws-sdk-android#648]
Hello,
we are experiencing some errors in logcat while pressing a button on our fragment that toggles the streaming on KinesisVideo.
the button works well when we first press the play/resume button, the mMediaSourceState of the AndroidCameraSource goes from INITIALIZED state to STARTED and the streaming starts correctly.

Then, on a second press of the play/resume button, the mMediaSourceState goes to STOPPED but we have logged the following errors:

```
2019-01-15 10:20:32.587 1100-1100/com.example.qwerty I/RequestQueue: Repeating capture request cancelled.
2019-01-15 10:20:32.588 1100-1100/com.example.qwerty D/CameraAdapter: releasing camera
2019-01-15 10:20:32.617 1100-1657/com.example.qwerty D/gralloc: gralloc_lock_ycbcr success. format : 11, usage: 30, ycbcr.y: 0xc987b000, .cb: 0xc988dc01, .cr: 0xc988dc00, .ystride: 320 , .cstride: 320, .chroma_step: 2
2019-01-15 10:20:32.653 1100-1113/com.example.qwerty W/MessageQueue: Handler (android.graphics.SurfaceTexture$1) {b286561} sending message to a Handler on a dead thread
    java.lang.IllegalStateException: Handler (android.graphics.SurfaceTexture$1) {b286561} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
        at android.os.Handler.enqueueMessage(Handler.java:643)
        at android.os.Handler.sendMessageAtTime(Handler.java:612)
        at android.os.Handler.sendMessageDelayed(Handler.java:582)
        at android.os.Handler.sendEmptyMessageDelayed(Handler.java:546)
        at android.os.Handler.sendEmptyMessage(Handler.java:531)
        at android.graphics.SurfaceTexture.postEventFromNative(SurfaceTexture.java:376)
2019-01-15 10:20:32.658 1100-1114/com.example.qwerty E/BufferQueueProducer: [SurfaceTexture-1-1100-1] dequeueBuffer: BufferQueue has been abandoned
2019-01-15 10:20:32.674 1100-1528/com.example.qwerty E/BufferQueueProducer: [SurfaceTexture-1-1100-1] queueBuffer: BufferQueue has been abandoned
2019-01-15 10:20:32.779 1100-1656/com.example.qwerty E/BufferQueueProducer: [SurfaceTexture-1-1100-1] cancelBuffer: BufferQueue has been abandoned
2019-01-15 10:20:32.780 1100-1656/com.example.qwerty E/BufferQueueProducer: [SurfaceTexture-1-1100-1] cancelBuffer: BufferQueue has been abandoned
2019-01-15 10:20:32.781 1100-1656/com.example.qwerty E/BufferQueueProducer: [SurfaceTexture-1-1100-1] cancelBuffer: BufferQueue has been abandoned
2019-01-15 10:20:32.782 1100-1656/com.example.qwerty E/BufferQueueProducer: [SurfaceTexture-1-1100-1] cancelBuffer: BufferQueue has been abandoned
2019-01-15 10:20:32.783 1100-1656/com.example.qwerty E/BufferQueueProducer: [SurfaceTexture-1-1100-1] cancelBuffer: BufferQueue has been abandoned
2019-01-15 10:20:32.783 1100-1656/com.example.qwerty E/BufferQueueProducer: [SurfaceTexture-1-1100-1] cancelBuffer: BufferQueue has been abandoned
2019-01-15 10:20:32.784 1100-1656/com.example.qwerty E/BufferQueueProducer: [SurfaceTexture-1-1100-1] cancelBuffer: BufferQueue has been abandoned
2019-01-15 10:20:32.785 1100-1656/com.example.qwerty E/BufferQueueProducer: [SurfaceTexture-1-1100-1] cancelBuffer: BufferQueue has been abandoned
2019-01-15 10:20:32.792 1100-1656/com.example.qwerty E/BufferQueueProducer: [SurfaceTexture-1-1100-1] connect: BufferQueue has been abandoned
2019-01-15 10:20:32.792 1100-1656/com.example.qwerty E/BufferQueueProducer: [SurfaceTexture-1-1100-1] setMaxDequeuedBufferCount: BufferQueue has been abandoned
2019-01-15 10:20:33.188 1100-1100/com.example.qwerty D/CameraAdapter: stopping background thread
2019-01-15 10:20:33.188 1100-1100/com.example.qwerty D/CameraAdapter: stopped background thread
2019-01-15 10:20:33.188 1100-1100/com.example.qwerty I/CameraFramesSource: released everything

```
on a third press of the Play/Resume button we get this error:

```
2019-01-15 10:21:38.178 1100-1813/com.example.qwerty W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
2019-01-15 10:21:38.179 1100-1813/com.example.qwerty W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
2019-01-15 10:21:38.180 1100-1813/com.example.qwerty W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
2019-01-15 10:21:38.181 1100-1813/com.example.qwerty W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
2019-01-15 10:21:38.182 1100-1813/com.example.qwerty W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
2019-01-15 10:21:38.182 1100-1813/com.example.qwerty W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
2019-01-15 10:21:38.184 1100-1813/com.example.qwerty W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
2019-01-15 10:21:38.185 1100-1813/com.example.qwerty W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
2019-01-15 10:21:38.186 1100-1813/com.example.qwerty W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
2019-01-15 10:21:38.186 1100-1813/com.example.qwerty W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
2019-01-15 10:21:38.187 1100-1813/com.example.qwerty W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
2019-01-15 10:21:38.187 1100-1813/com.example.qwerty W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
2019-01-15 10:21:38.188 1100-1813/com.example.qwerty W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
2019-01-15 10:21:38.188 1100-1813/com.example.qwerty W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
2019-01-15 10:21:38.189 1100-1813/com.example.qwerty W/VideoCapabilities: Unrecognized profile 2130706434 for video/avc
2019-01-15 10:21:38.189 1100-1813/com.example.qwerty W/VideoCapabilities: Unrecognized profile 2130706434 for video/avc
2019-01-15 10:21:38.190 1100-1813/com.example.qwerty W/VideoCapabilities: Unrecognized profile 2130706434 for video/avc
2019-01-15 10:21:38.190 1100-1813/com.example.qwerty W/VideoCapabilities: Unrecognized profile 2130706434 for video/avc
2019-01-15 10:21:38.191 1100-1813/com.example.qwerty W/VideoCapabilities: Unrecognized profile 2130706434 for video/avc
2019-01-15 10:21:38.191 1100-1813/com.example.qwerty W/VideoCapabilities: Unrecognized profile 2130706434 for video/avc
2019-01-15 10:21:38.192 1100-1813/com.example.qwerty W/VideoCapabilities: Unrecognized profile 2130706434 for video/avc
2019-01-15 10:21:38.192 1100-1813/com.example.qwerty W/VideoCapabilities: Unrecognized profile 2130706434 for video/avc
2019-01-15 10:21:38.193 1100-1813/com.example.qwerty W/VideoCapabilities: Unrecognized profile 2130706434 for video/avc
2019-01-15 10:21:38.213 1100-1813/com.example.qwerty D/EncoderFactory: Supported color formats: [2135033992, 19, 21, 2130706449, 16, 2130747392, 2130708361, 2130706450]
2019-01-15 10:21:38.213 1100-1815/com.example.qwerty I/ACodec: [OMX.Exynos.AVC.Encoder] Now Loaded->Idle
2019-01-15 10:21:38.220 1100-1813/com.example.qwerty E/CameraFramesSource: starting camera frames source second time | threadId=1553
2019-01-15 10:21:38.229 1100-1815/com.example.qwerty I/ACodec: [OMX.Exynos.AVC.Encoder] Now Idle->Executing
2019-01-15 10:21:38.230 1100-1813/com.example.qwerty E/CameraFramesSource: encoder loop exception | threadId=1553
    java.lang.RuntimeException: starting camera frames source second time
        at com.amazonaws.mobileconnectors.kinesisvideo.camera.CameraFramesSource.prepareCameraAndPreview(CameraFramesSource.java:168)
        at com.amazonaws.mobileconnectors.kinesisvideo.camera.CameraFramesSource.startCapturing(CameraFramesSource.java:145)
        at com.amazonaws.mobileconnectors.kinesisvideo.camera.CameraFramesSource.access$300(CameraFramesSource.java:41)
        at com.amazonaws.mobileconnectors.kinesisvideo.camera.CameraFramesSource$CameraFramesSourceRunnableWrapper.run(CameraFramesSource.java:114)
        at java.lang.Thread.run(Thread.java:762)
2019-01-15 10:21:38.231 1100-1815/com.example.qwerty I/ACodec: [OMX.Exynos.AVC.Encoder] Now Executing
2019-01-15 10:21:46.644 1100-1800/com.example.qwerty D/TextualHelperFragment: All message received
2019-01-15 10:21:46.764 1100-1803/com.example.qwerty I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2019-01-15 10:21:46.765 1100-1803/com.example.qwerty I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
```
The SurfaceView stands still and no streaming occurs.

we are using a Samsung Galaxy tab A 2016 (Android 7.0), using the latest (2.10.1) SDK.

I can provide with complete logs, if needed.

sixbladeknife

**Comment by MushMal** [comment]
@sixbladeknife thanks for contacting. Could you please set filtering in the logcat to the current application only, run the scenario by starting the camera, letting it stream for a couple of seconds, stopping the camera, wait for a second, start again and wait for a couple of seconds and capture the logs. Please attach the logs here or send them directly to "kinesis-video-support@amazon.com"
