### ISSUE TITLE
BadRequestException thrown when updating endpoint due to limit being exceeded

### ISSUE THREAD

**Issue by nthieu90** [aws-amplify/aws-sdk-android#663]
When I call updateEndpointProfile and get an error:
    
`com.amazonaws.services.pinpoint.model.BadRequestException: Exceeded maximum endpoint per user count 10 (Service: AmazonPinpoint; Status Code: 400; Error Code: BadRequestException; Request ID: 6af05861-1b15-11e9-87cd-8bdea723c33a)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:730)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:405)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
        at com.amazonaws.services.pinpoint.AmazonPinpointClient.invoke(AmazonPinpointClient.java:4037)
        at com.amazonaws.services.pinpoint.AmazonPinpointClient.updateEndpoint(AmazonPinpointClient.java:3731)
        at com.amazonaws.mobileconnectors.pinpoint.targeting.TargetingClient$1.run(TargetingClient.java:198)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)`

Version 2.11.0
How to fix it? 
Thanks

**Comment by kvasukib** [comment]
@nthieu90 Thank you for reporting to us. This is the limit enforced by Amazon Pinpoint Service. Here is the documentation for the limits: [Limits](https://docs.aws.amazon.com/pinpoint/latest/developerguide/limits.html#limits-endpoint). 
Endpoints with the same user ID: 10 unique endpoints per user ID.

**Comment by nthieu90** [comment]
Hi @kvasukib  
if I update endpoint by new userId, that will remove endpoint from current userId?
How to remove endpoints not available from a user? In case, user uninstall and reinstall the app that will create new endpoint_id and assign to the same user until got the limit exception.
Thanks

**Comment by kvasukib** [comment]
@nthieu90 Thank you for the quick reply. You can use the `get-user-endpoints` API of Pinpoint to query for the endpoints associated with a user-id. The equivalent method in the SDK would be: [getUserEndpoints](https://github.com/aws-amplify/aws-sdk-android/blob/master/aws-android-sdk-pinpoint/src/main/java/com/amazonaws/services/pinpoint/AmazonPinpointClient.java#L2854)

**Comment by nthieu90** [comment]
Which value I can check if endpoint still available or not to delete?

**Comment by kvasukib** [comment]
@nthieu90 Sorry for the delayed reply. You can retrieve the endpoint information through [GetEndpoint](https://github.com/aws-amplify/aws-sdk-android/blob/master/aws-android-sdk-kinesis/src/main/java/com/amazonaws/mobileconnectors/kinesis/kinesisrecorder/FileRecordStore.java#L43) and delete an endpoint using [DeleteEndpoint](https://github.com/aws-amplify/aws-sdk-android/blob/7a2955cd387dfdcd292f7f5eede4b6b32c8a2f84/aws-android-sdk-pinpoint/src/main/java/com/amazonaws/services/pinpoint/AmazonPinpointClient.java#L1004).

**Comment by nthieu90** [comment]
Thanks

**Comment by itViratSingh** [comment]
I am getting Endpoint response null when i try to get Endpoint list using getUserEndpoints
