### ISSUE TITLE
SignInUI : E/WindowManager: android.view.WindowLeaked: Activity com.amazonaws.mobile.auth.ui.SignInActivity has leaked window 

### ISSUE THREAD

**Issue by BillBunting** [aws-amplify/aws-sdk-android#664]
**Describe the bug**
Exception upon sign up completion. User creates new account, user enters validation code, then the app will throw this exception. Is this a bug or integration issue? New users are unable to complete sign-up (a workaround is to restart the app)

SignInUI signinUI = (SignInUI) AWSMobileClient.getInstance().getClient(AuthenticatorActivity.this, SignInUI.class);
                signinUI.login(AuthenticatorActivity.this, MainActivity.class).authUIConfiguration(config).execute();

```
2019-01-18 10:58:39.635 5108-5108/com.buntingsoftware.modlist E/WindowManager: android.view.WindowLeaked: Activity com.amazonaws.mobile.auth.ui.SignInActivity has leaked window DecorView@b177146[SignInActivity] that was originally added here
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:511)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:346)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
        at android.app.Dialog.show(Dialog.java:329)
        at android.app.AlertDialog$Builder.show(AlertDialog.java:1125)
        at com.amazonaws.mobile.auth.core.internal.util.ViewHelper.showDialog(ViewHelper.java:46)
        at com.amazonaws.mobile.auth.userpools.CognitoUserPoolsSignInProvider$2.onSuccess(CognitoUserPoolsSignInProvider.java:248)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser$1$1.run(CognitoUser.java:282)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**To Reproduce**
1. Open app that has a SignIn UI embedded in an activity
2. Sign up as a new user and enter the validation code
3. Observe sign-in closes and exception is thrown.
4. Keyboard is never dismissed.

**Which AWS service(s) are affected?**
AWSMobileClient SignInUI

**Expected behavior**
Sign-in Window should dismiss 

**Environment(please complete the following information):**
 - SDK Version: 2.10.0 and 2.11.0

**Device Information (please complete the following information):**
 - Device: Pixel 2 API 28 (Android Pie) Simulator
 - Android Version: API 28, Android 9)
 - Specific to simulators: No

**Additional context**
Maybe related to issue #565 
https://github.com/aws-amplify/aws-sdk-android/issues/565

**Comment by BillBunting** [comment]
@minbi I will update the app to use AWSMobileClient.getInstance().showSignIn(...)  I just completed a major upgrade on the iOS version of the app to swap to using AWSMobileClient.getInstance().showSignIn(...) and will start the same process on the Android version. Both apps, were initially from MobileHub templates and have been upgraded and refactored several time to keep up.  I hope this will resolve the issue. Thank you.

**Comment by BillBunting** [comment]
I moved the call AWSMobileClient.getInstance().showSignIn from its own Activity into the apps MainActivity to workaround the issue.
