### ISSUE TITLE
Getting list of object keys in s3 bucket 

### ISSUE THREAD

**Issue by warlock-jay** [aws-amplify/aws-sdk-android#674]
**State your question**
Hi ,
I am using S3 bucket service in Android ,I can download files by putting object key hard coded but first i want to get list of object keys present in bucket then i want to download .How to do that?
**Which AWS Services are you utilizing?**
Cognito,S3,Iot
**Environment(please complete the following information):**
 - SDK Version: 2.9

**Device Information (please complete the following information):**
 - Device: Moto g6
 - Android Version: oreo 

I am using transferutility service to download files,it's working fine.I am not getting list of objets by that. 
I want get list of object present in specific folder in s3bucket,code snippets will be helpful

**Comment by warlock-jay** [comment]
I tried this code

`            AmazonS3Client s3client1 = new AmazonS3Client(AWSMobileClient.getInstance());
            s3client1.setRegion(Region.getRegion("eu-west-1"));

            ObjectListing transferRecordMaps;
            String sub_id = AWSMobileClient.getInstance().getTokens().getIdToken().getClaim("sub");
            Log.i("usersub", "usersub is" + sub_id);
            transferRecordMaps = s3client1.listObjects("aurabucket1");
            Log.i("objectlist", "objects are" + transferRecordMaps);`

this is the error i got 

2019-01-25 15:18:59.998 25650-25650/com.example.aura.app15 I/usersub: usersub ise30e7c1a-28cf-421e-b29c-3e77bf26ebc2
2019-01-25 15:19:00.000 25650-25650/com.example.aura.app15 D/AWSMobileClient: Inspecting user state details
2019-01-25 15:19:00.004 25650-25650/com.example.aura.app15 D/AWSMobileClient: hasFederatedToken: true provider: cognito-idp.eu-west-1.amazonaws.com/eu-west-1_*******
2019-01-25 15:19:00.004 25650-25650/com.example.aura.app15 D/AWSMobileClient: waitForSignIn: userState:SIGNED_IN
2019-01-25 15:19:00.004 25650-25650/com.example.aura.app15 D/AWSMobileClient: getCredentials: Validated user is signed-in
2019-01-25 15:19:00.015 2921-4363/? D/WificondControl: Scan result ready event
2019-01-25 15:19:00.027 25650-25650/com.example.aura.app15 W/System.err: android.os.NetworkOnMainThreadException
2019-01-25 15:19:00.028 25650-25650/com.example.aura.app15 W/System.err:     at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1457)
2019-01-25 15:19:00.028 25650-25650/com.example.aura.app15 W/System.err:     at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:102)
2019-01-25 15:19:00.028 25650-25650/com.example.aura.app15 W/System.err:     at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:90)
2019-01-25 15:19:00.028 25650-25650/com.example.aura.app15 W/System.err:     at java.net.InetAddress.getAllByName(InetAddress.java:787)
2019-01-25 15:19:00.028 25650-25650/com.example.aura.app15 W/System.err:     at com.android.okhttp.Dns$1.lookup(Dns.java:39)
2019-01-25 15:19:00.028 25650-25650/com.example.aura.app15 W/System.err:     at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:175)
2019-01-25 15:19:00.028 25650-25650/com.example.aura.app15 W/System.err:     at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:141)
2019-01-25 15:19:00.029 25650-25650/com.example.aura.app15 W/System.err:     at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:83)
2019-01-25 15:19:00.029 25650-25650/com.example.aura.app15 W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:174)
2019-01-25 15:19:00.029 25650-25650/com.example.aura.app15 W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
2019-01-25 15:19:00.029 25650-25650/com.example.aura.app15 W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
2019-01-25 15:19:00.029 25650-25650/com.example.aura.app15 W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
2019-01-25 15:19:00.029 25650-25650/com.example.aura.app15 W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
2019-01-25 15:19:00.029 25650-25650/com.example.aura.app15 W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
2019-01-25 15:19:00.029 26914-27068/? D/AkaSDKLogger: RestWrapper: capture analytics: true
2019-01-25 15:19:00.029 25650-25650/com.example.aura.app15 W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
2019-01-25 15:19:00.030 25650-25650/com.example.aura.app15 W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseMessage(HttpURLConnectionImpl.java:534)
2019-01-25 15:19:00.030 25650-25650/com.example.aura.app15 W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseMessage(DelegatingHttpsURLConnection.java:109)
2019-01-25 15:19:00.030 25650-25650/com.example.aura.app15 W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseMessage(Unknown Source:0)
2019-01-25 15:19:00.030 25650-25650/com.example.aura.app15 W/System.err:     at com.amazonaws.http.UrlHttpClient.createHttpResponse(UrlHttpClient.java:92)
2019-01-25 15:19:00.030 25650-25650/com.example.aura.app15 W/System.err:     at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:85)
2019-01-25 15:19:00.030 25650-25650/com.example.aura.app15 W/System.err:     at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:371)
2019-01-25 15:19:00.030 25650-25650/com.example.aura.app15 W/System.err:     at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
2019-01-25 15:19:00.030 25650-25650/com.example.aura.app15 W/System.err:     at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4659)
2019-01-25 15:19:00.031 25650-25650/com.example.aura.app15 W/System.err:     at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4607)
2019-01-25 15:19:00.031 25650-25650/com.example.aura.app15 W/System.err:     at com.amazonaws.services.s3.AmazonS3Client.listObjects(AmazonS3Client.java:673)
2019-01-25 15:19:00.031 25650-25650/com.example.aura.app15 W/System.err:     at com.amazonaws.services.s3.AmazonS3Client.listObjects(AmazonS3Client.java:621)
2019-01-25 15:19:00.031 25650-25650/com.example.aura.app15 W/System.err:     at com.example.aura.app15.DeviceActivity.listingkeys(DeviceActivity.java:69)
2019-01-25 15:19:00.031 25650-25650/com.example.aura.app15 W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-01-25 15:19:00.031 25650-25650/com.example.aura.app15 W/System.err:     at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:385)
2019-01-25 15:19:00.031 25650-25650/com.example.aura.app15 W/System.err:     at android.view.View.performClick(View.java:6259)
2019-01-25 15:19:00.031 25650-25650/com.example.aura.app15 W/System.err:     at android.view.View$PerformClick.run(View.java:24732)
2019-01-25 15:19:00.031 25650-25650/com.example.aura.app15 W/System.err:     at android.os.Handler.handleCallback(Handler.java:789)
2019-01-25 15:19:00.032 25650-25650/com.example.aura.app15 W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
2019-01-25 15:19:00.032 25650-25650/com.example.aura.app15 W/System.err:     at android.os.Looper.loop(Looper.java:164)
2019-01-25 15:19:00.032 25650-25650/com.example.aura.app15 W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6673)
2019-01-25 15:19:00.032 25650-25650/com.example.aura.app15 W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-01-25 15:19:00.032 25650-25650/com.example.aura.app15 W/System.err:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
2019-01-25 15:19:00.032 25650-25650/com.example.aura.app15 W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)
2019-01-25 15:19:00.032 19815-29044/? D/EventNotificationJob: Running EventNotificationJob, isDetail=true

**Comment by kvasukib** [comment]
@warlock-jay Thank you for reporting to us. You cannot make a network call from a main thread in Android. You need to wrap the call to `listObjects` in a background thread.

```java
new Thread(new Runnable() {
    public void run() {
        transferRecordMaps = s3client1.listObjects("aurabucket1");
    }
}).start();
```

**Comment by warlock-jay** [comment]
Hi @kvasukib 
Thanks, It's working when i put on separate thread .
but how do we know which api has to put on separate thread?

**Comment by kvasukib** [comment]
@warlock-jay Good question! If the method is synchronous (makes a network call on the same thread you are calling from and blocks), you need to wrap it with a background thread. 

In the AWS SDK for Android, the methods in a class Amazon<ServiceName>Client are synchronous unless stated otherwise in the Javadoc. Synchronous methods take in an input and return an output when succeeds and throws exception when it fails. Asynchronous methods take in an input and a callback and return (void) immediately. The results (success and failure) will be communicated via the callback. The Javadoc of each method can be consulted to know which are synchronous or asynchronous.

For most low-level clients, Amazon<ServiceName>Client has the methods that are synchronous and Amazon<ServiceName>AsyncClient has the methods that are asynchronous. 

For the high-level clients, you can consult the Javadoc and method signature for finding if a method is synchronous or asynchronous.

**Comment by warlock-jay** [comment]
Thanks @kvasukib for clarifying about methods,i will read documentation again .
