### ISSUE TITLE
Fatal Issue caused by SocketTimeoutException

### ISSUE THREAD

**Issue by DeMoss15** [aws-amplify/aws-sdk-android#681]
*SDK version: 2.11.0*
*AppSync version: 2.7.6*

Device was connected to internet via proxy. Proxy was lost and than we caught application crash
with next stack trace:

```
Fatal Exception: io.b.c.f: com.a.a.c.d: Failed to execute http call
       at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
       at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.onError(ObservableCreate.java:74)
       at com.menklab.chat.repository.remote.aws.NewUserDialogsObservable$subscribe$1.onFailure(NewUserDialogsObservable.kt:29)
       at com.apollographql.apollo.internal.RealAppSyncSubscriptionCall$1$1.onFailure(RealAppSyncSubscriptionCall.java:124)
       at com.apollographql.apollo.GraphQLCall$Callback.onNetworkError(GraphQLCall.java:135)
       at com.apollographql.apollo.internal.RealAppSyncCall$1.onFailure(RealAppSyncCall.java:292)
       at com.apollographql.apollo.internal.interceptor.ApolloCacheInterceptor$1$1.onFailure(ApolloCacheInterceptor.java:108)
       at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onFailure(ApolloParseInterceptor.java:94)
       at com.apollographql.apollo.internal.interceptor.AppSyncSubscriptionInterceptor$1.onFailure(AppSyncSubscriptionInterceptor.java:134)
       at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$1$1.onFailure(ApolloServerInterceptor.java:105)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:215)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
```

```
Caused by com.a.a.c.d: Failed to execute http call
       at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$1$1.onFailure(ApolloServerInterceptor.java:105)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:215)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
```

```
Caused by java.net.SocketTimeoutException: failed to connect to /192.168.21.49 (port 8888) from /192.168.21.41 (port 46930) after 10000ms
       at libcore.io.IoBridge.connectErrno(IoBridge.java:185)
       at libcore.io.IoBridge.connect(IoBridge.java:130)
       at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:129)
       at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:356)
       at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
       at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
       at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:357)
       at java.net.Socket.connect(Socket.java:626)
       at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.java:73)
       at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:246)
       at okhttp3.internal.connection.RealConnection.connectTunnel(RealConnection.java:218)
       at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:160)
       at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
       at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
       at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at com.amazonaws.mobileconnectors.appsync.sigv4.AppSyncSigV4SignerInterceptor.intercept(AppSyncSigV4SignerInterceptor.java:181)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at com.amazonaws.mobileconnectors.appsync.retry.RetryInterceptor.intercept(RetryInterceptor.java:50)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:144)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:200)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
```

NewUsedDialogsObservable mentioned in first part looks:
```
import com.amazonaws.mobileconnectors.appsync.AWSAppSyncClient
import com.amazonaws.mobileconnectors.appsync.AppSyncSubscriptionCall
import com.apollographql.apollo.api.Response
import com.apollographql.apollo.exception.ApolloException
import com.menklab.NewUserDialogSubscription
import com.menklab.chat.repository.remote.exception.OnNewDialogException
import com.menklab.fragment.ChatConversation
import io.reactivex.ObservableEmitter
import io.reactivex.ObservableOnSubscribe
import io.reactivex.disposables.Disposables

class NewUserDialogsObservable(private val subscription: NewUserDialogSubscription,
                               private val awsAppSyncClient: AWSAppSyncClient) : ObservableOnSubscribe<ChatConversation> {
    override fun subscribe(emitter: ObservableEmitter<ChatConversation>) {
        val subscription = awsAppSyncClient.subscribe(subscription)

        subscription.execute(object : AppSyncSubscriptionCall.Callback<NewUserDialogSubscription.Data> {
            override fun onResponse(response: Response<NewUserDialogSubscription.Data>) {
                response.data()?.let {
                    it.newUserConversation()?.fragments()?.chatConversation()?.run {
                        emitter.onNext(this)
                    } ?: emitter.onError(OnNewDialogException("NewUserDialogSubscription: message is null"))
                } ?: emitter.onError(OnNewDialogException("NewUserDialogSubscription: response data is null"))
            }

            override fun onFailure(e: ApolloException) {
                emitter.onError(e) // here is line 29 ==========================================
            }

            override fun onCompleted() {}
        })

        emitter.setDisposable(Disposables.fromAction { subscription.cancel() })

    }
}
```
in *onError(e)*, parameter *e* - can be any Throwable, 
ApolloException < Exception < Throwable

**Comment by cbommas** [comment]
@DeMoss15 

From the stacktrace, it looks like the crash is happening here

     io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)

The call to subscribe is failing with a socket timeout and it is triggering the onError method of your callback, and the `emitter.onError` appears to be crashing the app. This would be in the app code and I am happy to troubleshoot this with you, but I am not aware of how RxJava works or how to properly handle errors in RxJava.

**Comment by DeMoss15** [comment]
I've just caught that we didn't check emitter is it disposed. 
Thank you for your answer and sorry for this issue...

**Comment by cbommas** [comment]
@DeMoss15  No worries. Glad that the problem is resolved.
