### ISSUE TITLE
sometimes kinesisvideo throws illegalstateexception

### ISSUE THREAD

**Issue by anshulsharma789** [aws-amplify/aws-sdk-android#694]
```
java.lang.IllegalStateException
	at com.amazonaws.kinesisvideo.common.preconditions.Preconditions.checkState(Preconditions.java:126)
	at com.amazonaws.kinesisvideo.producer.jni.NativeKinesisVideoProducerJni.putFrame(NativeKinesisVideoProducerJni.java:452)
	at com.amazonaws.kinesisvideo.producer.jni.NativeKinesisVideoProducerStream.putFrame(NativeKinesisVideoProducerStream.java:276)
	at com.amazonaws.kinesisvideo.mediasource.ProducerStreamSink.onFrame(ProducerStreamSink.java:52)
	at com.amazonaws.mobileconnectors.kinesisvideo.mediasource.android.AndroidCameraMediaSource$2.onFrameAvailable(AndroidCameraMediaSource.java:198)
	at com.amazonaws.mobileconnectors.kinesisvideo.encoding.EncoderWrapper.sendEncodedFrameToProducerSDK(EncoderWrapper.java:198)
	at com.amazonaws.mobileconnectors.kinesisvideo.encoding.EncoderWrapper.processEncodedData(EncoderWrapper.java:164)
	at com.amazonaws.mobileconnectors.kinesisvideo.encoding.EncoderWrapper.processEncoderOutputBuffer(EncoderWrapper.java:145)
	at com.amazonaws.mobileconnectors.kinesisvideo.encoding.EncoderWrapper.getDataFromEncoder(EncoderWrapper.java:121)
	at com.amazonaws.mobileconnectors.kinesisvideo.encoding.EncoderWrapper.encodeFrame(EncoderWrapper.java:94)
	at com.amazonaws.mobileconnectors.kinesisvideo.camera.CameraFramesSource$1.onImageAvailable(CameraFramesSource.java:68)
	at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:812)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6940)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)


```

**Comment by kvasukib** [comment]
@anshulsharma789 Thank you for reporting to us. Sorry for the inconvenience caused. Can you fill the necessary information in the issue template when creating the issue?

What is the SDK version?
What is the Android API Level?
A description of the issue?
A sample code snippet?

**Comment by MushMal** [comment]
@anshulsharma789 it seems that the creation/initialization of the stream had failed earlier. Could you please send the logcat logs to kinesis-video-support@amazon.com or include those here.

**Comment by SanthoshMKunthe** [comment]
Fatal Exception: java.lang.IllegalStateException
at com.amazonaws.kinesisvideo.common.preconditions.Preconditions.checkState(Preconditions.java:126)
at com.amazonaws.kinesisvideo.internal.producer.jni.NativeKinesisVideoProducerJni.putFrame(NativeKinesisVideoProducerJni.java:491)
at com.amazonaws.kinesisvideo.internal.producer.jni.NativeKinesisVideoProducerStream.putFrame(NativeKinesisVideoProducerStream.java:292)
at com.amazonaws.kinesisvideo.internal.mediasource.ProducerStreamSink.onFrame(ProducerStreamSink.java:52)
at com.amazonaws.mobileconnectors.kinesisvideo.mediasource.android.AndroidCameraMediaSource$2.onFrameAvailable(AndroidCameraMediaSource.java:266)
at com.amazonaws.mobileconnectors.kinesisvideo.encoding.EncoderWrapper.sendEncodedFrameToProducerSDK(EncoderWrapper.java:198)
at com.amazonaws.mobileconnectors.kinesisvideo.encoding.EncoderWrapper.processEncodedData(EncoderWrapper.java:164)
at com.amazonaws.mobileconnectors.kinesisvideo.encoding.EncoderWrapper.processEncoderOutputBuffer(EncoderWrapper.java:145)
at com.amazonaws.mobileconnectors.kinesisvideo.encoding.EncoderWrapper.getDataFromEncoder(EncoderWrapper.java:121)
at com.amazonaws.mobileconnectors.kinesisvideo.encoding.EncoderWrapper.encodeFrame(EncoderWrapper.java:94)
at com.amazonaws.mobileconnectors.kinesisvideo.camera.CameraFramesSource$1.onImageAvailable(CameraFramesSource.java:68)
at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:800)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:201)
at android.app.ActivityThread.main(ActivityThread.java:6823)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)


The issue is raised when the streaming is started and stopped multiple times under low internet speed. . . The issue is seen to happen RANDOMLY. . .

**Comment by MushMal** [comment]
@SanthoshMKunthe this issue went stale was closed months ago.

At any rate, the small snippet of log doesn't really contain the root cause. You might need to look at your overall log and ensure you have debug log in order to see what's going on.

My hunch is that the initialization of the stream had failed after the retries due to networking errors but the application goes ahead with pumping frames.

**Comment by mattfiocca** [comment]
I am seeing this consistently when stopping the stream, using the code from the example project. It's happening 100% of the time. Stream start is good to go, but when stop is called I see these exceptions every time. Connection strength is strong. 

Also, is there a way we can catch these Exceptions? I have everything wrapped in try/catch but am still seeing app crashes due to these exceptions.

Logcat:
```
V/KinesisVideoAndroidClient: Pausing Kinesis Video client
I/AndroidCameraMediaSource: encoding stopping
D/platform-utils: Java_com_amazonaws_kinesisvideo_internal_producer_jni_NativeKinesisVideoProducerJni_stopKinesisVideoStream(): Stopping Kinesis Video stream.
    stopKinesisVideoStream(): Stopping Kinesis Video Stream 00000000c992b460.
D/KinesisVideoAndroidClient: Data availability notification. Upload handle: 0, Size: 0, Duration 0 
    Stream a4a85d5de9684a37a430b1bc59bfc35c-1619741134023 is closed
V/KinesisVideoAndroidClient: Releasing Kinesis Video client
D/KinesisVideoAndroidClient: Stream a4a85d5de9684a37a430b1bc59bfc35c-1619741134023 is closed
D/KinesisVideoAndroidClient: Stopping the kinesis video producer stream
D/platform-utils: Java_com_amazonaws_kinesisvideo_internal_producer_jni_NativeKinesisVideoProducerJni_stopKinesisVideoStream(): Stopping Kinesis Video stream.
    stopKinesisVideoStream(): Stopping Kinesis Video Stream 00000000c992b460.
D/KinesisVideoAndroidClient: getStreamData fill 0 bytes for stream a4a85d5de9684a37a430b1bc59bfc35c-1619741134023 with uploadHandle 0
    no data for stream a4a85d5de9684a37a430b1bc59bfc35c-1619741134023 with uploadHandle 0, waiting
D/platform-utils: Java_com_amazonaws_kinesisvideo_internal_producer_jni_NativeKinesisVideoProducerJni_stopKinesisVideoStreams(): Stopping Kinesis Video streams.
D/EncoderWrapper: time between frames: 11ms
D/platform-utils: stopKinesisVideoStreams(): Stopping Kinesis Video Streams.
    stopKinesisVideoStream(): Stopping Kinesis Video Stream 00000000c992b460.
D/FrameUtility: frame timestamp: 1619741144196, index: 170, duration: 2, keyFrame: false, flags: 0
I/AndroidCameraMediaSource: updating sink with frame
D/platform-utils: Java_com_amazonaws_kinesisvideo_internal_producer_jni_NativeKinesisVideoProducerJni_freeKinesisVideoClient(): Freeing Kinesis Video client.
    freeKinesisVideoClient(): Freeing Kinesis Video Client
    commonHeapDebugCheckAllocator(): Heap is initialized
    commonHeapDebugCheckAllocator(): Heap limit: 				402653184
D/KinesisVideoAndroidClient: PutFrame index: 170, pts: 16197411441960000, dts: 16197411441960000, duration: 20000, keyFrame: false, flags: 0
D/platform-utils: commonHeapDebugCheckAllocator(): Heap size: 				0
D/platform-utils: commonHeapDebugCheckAllocator(): Number of allocations: 				0
    aivHeapDebugCheckAllocator(): Allocated blocks pointer: 				0x0
    aivHeapDebugCheckAllocator(): *******************************************
    aivHeapDebugCheckAllocator(): *******************************************
    aivHeapDebugCheckAllocator(): Free blocks pointer: 				0xb0d00000
    aivHeapDebugCheckAllocator(): *******************************************
    aivHeapDebugCheckAllocator(): Block:	0xb0d00000		size:	402653159
    aivHeapDebugCheckAllocator(): *******************************************
    heapRelease(): Freeing native heap.
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.incidentclear.driver, PID: 22190
    java.lang.IllegalStateException
        at com.amazonaws.kinesisvideo.common.preconditions.Preconditions.checkState(Preconditions.java:126)
        at com.amazonaws.kinesisvideo.internal.producer.jni.NativeKinesisVideoProducerJni.putFrame(NativeKinesisVideoProducerJni.java:491)
        at com.amazonaws.kinesisvideo.internal.producer.jni.NativeKinesisVideoProducerStream.putFrame(NativeKinesisVideoProducerStream.java:292)
        at com.amazonaws.kinesisvideo.internal.mediasource.ProducerStreamSink.onFrame(ProducerStreamSink.java:52)
        at com.amazonaws.mobileconnectors.kinesisvideo.mediasource.android.AndroidCameraMediaSource$2.onFrameAvailable(AndroidCameraMediaSource.java:266)
        at com.amazonaws.mobileconnectors.kinesisvideo.encoding.EncoderWrapper.sendEncodedFrameToProducerSDK(EncoderWrapper.java:198)
        at com.amazonaws.mobileconnectors.kinesisvideo.encoding.EncoderWrapper.processEncodedData(EncoderWrapper.java:164)
        at com.amazonaws.mobileconnectors.kinesisvideo.encoding.EncoderWrapper.processEncoderOutputBuffer(EncoderWrapper.java:145)
        at com.amazonaws.mobileconnectors.kinesisvideo.encoding.EncoderWrapper.getDataFromEncoder(EncoderWrapper.java:121)
        at com.amazonaws.mobileconnectors.kinesisvideo.encoding.EncoderWrapper.encodeFrame(EncoderWrapper.java:94)
        at com.amazonaws.mobileconnectors.kinesisvideo.camera.CameraFramesSource$1.onImageAvailable(CameraFramesSource.java:68)
        at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:800)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7179)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```

code:
```java

// STARTUP
mSurfaceTexture = new SurfaceTexture(1);
mSurfaceTexture.setDefaultBufferSize(mCanvasSize.getWidth(),mCanvasSize.getHeight());

try {

	mKinesisVideoClient = KinesisVideoAndroidClientFactory.createKinesisVideoClient(
			IncidentClearApplication.getContext(),
			REGION,
			IoTManager.getAWSCredentialsProvider());

	mCameraMediaSource = (AndroidCameraMediaSource) mKinesisVideoClient.createMediaSource(
			mRequest.getKVSStreamName(),
			getConfiguration(lens)
	);

	mCameraMediaSource.setPreviewSurfaces(new Surface(mSurfaceTexture));
	mCameraMediaSource.start();

	bStreaming = true;

} catch (Exception e) {
	e.printStackTrace();
}

// some time later when wanting to stop streaming:

bStreaming = false;

try {

	if ( mCameraMediaSource != null ) {
		mCameraMediaSource.stop();
	}

	if ( mKinesisVideoClient != null ) {
		mKinesisVideoClient.stopAllMediaSources();
	}

        KinesisVideoAndroidClientFactory.freeKinesisVideoClient();

} catch (Exception e) {
	e.printStackTrace();
}
```

**Comment by amedfa** [comment]
@mattfiocca did you find any solution?
I have the same issue as what you described
I was trying to release the surface too just in case, 
```java

try {

	if ( mCameraMediaSource != null ) {
		mCameraMediaSource.stop();
	}

	if ( mKinesisVideoClient != null ) {
		mKinesisVideoClient.stopAllMediaSources();
	}

        KinesisVideoAndroidClientFactory.freeKinesisVideoClient();

         // NEW ---- 
         if (!mSurfaceTexture.isReleased()) {
              mSurfaceTexture.release();
          }

} catch (Exception e) {
	e.printStackTrace();
}
```
