### ISSUE TITLE
Issue in getting started

### ISSUE THREAD

**Issue by ZYHZ100** [aws-amplify/aws-sdk-android#703]
**State your question**
In the second time, I run the same code and there is a bug but in the first time, it ran successfully.
Can anyone help me?
Thank you very much!

These are bugs:

```
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.zhouyuhong.step, PID: 5343
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.zhouyuhong.step/com.example.zhouyuhong.step.MainActivity}: java.lang.RuntimeException: Please check the AppSync configuration in awsconfiguration.json.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.RuntimeException: Please check the AppSync configuration in awsconfiguration.json.
        at com.amazonaws.mobileconnectors.appsync.AWSAppSyncClient$Builder.build(AWSAppSyncClient.java:495)
        at com.example.zhouyuhong.step.MainActivity.onCreate(MainActivity.java:118)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.amazonaws.mobileconnectors.appsync.AWSAppSyncClient$AuthMode.toString()' on a null object reference
        at com.amazonaws.mobileconnectors.appsync.AWSAppSyncClient$Builder.build(AWSAppSyncClient.java:492)
        at com.example.zhouyuhong.step.MainActivity.onCreate(MainActivity.java:118) 
        at android.app.Activity.performCreate(Activity.java:7136) 
        at android.app.Activity.performCreate(Activity.java:7127) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
I/Process: Sending signal. PID: 5343 SIG: 9
Application terminated.
```

**Which AWS Services are you utilizing?**
I followed the get start guide.

**Provide code snippets (if applicable)**

```java
    public void onCreate(Bundle savedInstanceState) {

        super.onCreate(savedInstanceState);

        setContentView(R.layout.activity_main);

        mAWSAppSyncClient = AWSAppSyncClient.builder()
                .context(getApplicationContext())
                .awsConfiguration(new AWSConfiguration(getApplicationContext()))
                .build();

        this.setTitle("STEPS");

        PreferenceManager.getDefaultSharedPreferences(this)
                .edit()
                .clear()
                .apply();
```

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.25]

```
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.esri.arcgisruntime:arcgis-android:100.2.1'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    implementation 'com.google.android.gms:play-services-location:11.8.0'
    implementation 'com.google.android.gms:play-services-maps:11.8.0'
    implementation 'com.google.code.gson:gson:2.8.2'
    implementation 'com.android.support:design:28.0.0'

    //Base SDK
    implementation 'com.amazonaws:aws-android-sdk-core:2.12.+'
    //AppSync SDK
    implementation 'com.amazonaws:aws-android-sdk-appsync:2.7.+'
    implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.0'
    implementation 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.1'

    implementation 'com.amazonaws:aws-android-sdk-ddb:2.12.+'
    implementation 'com.amazonaws:aws-android-sdk-s3:2.12.+'
    implementation ('com.amazonaws:aws-android-sdk-mobile-client:2.12.+@aar') { transitive = true }
    implementation ('com.amazonaws:aws-android-sdk-auth-userpools:2.12.+@aar') { transitive = true }
    
}
```

**Device Information (please complete the following information):**
 - Device: [e.g. Pixel XL, Simulator]
 - Android Version: [e.g. Nougat 7.1.2]
 - Specific to simulators:

Emulator Nexus_5X_API_28 Android 9, API 28

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by ZYHZ100** [comment]
Must AppSync be needed to implement amplify framework?
Actually, I want to have functions of signing in and up and upload data to AWS.

**Comment by ZYHZ100** [comment]
> @ZYHZ100 Sorry for the inconvenience caused. Do you need to integrate your app with a GraphQL API provided by AppSync? If so, you need to integrate with AWS AppSync. Otherwise, you don't need to integrate with AppSync.
> 
> What are the use-cases of your app?

Thank you. Maybe I don't need to integrate with AppSync. Actually, as a new user, I don't much understand functions of GraphQL API and AppSync. And if I just want to use Amazon Cognito User pool and Amazon S3, do I have to use amplify framework?

**Comment by kvasukib** [comment]
@ZYHZ100 Thank you for the quick response. In that case all you need is to integrate with 

Amazon Cognito User pool (Setup authentication) -> https://aws-amplify.github.io/docs/android/authentication

Amazon S3 (store data) -> https://aws-amplify.github.io/docs/android/storage

You can follow these two guides to setup authentication and storage.

**Comment by mhrjnamar** [comment]
Hi i am getting the same error but i need to use AppSync how to solve this problem @kvasukib can you help?
