### ISSUE TITLE
ConcurrentModificationException in pauseAllTransfersDueToNetworkInterruption with SDK 2.11.1

### ISSUE THREAD

**Issue by hfcheng** [aws-amplify/aws-sdk-android#777]
**Describe the bug**
We are encountering rare ConcurrentModificationException in pauseAllTransfersDueToNetworkInterruption added in SDK version 2.11.1.

```
java.util.HashMap$HashIterator.nextEntry
java.util.HashMap$ValueIterator.next
java.util.Collections$UnmodifiableCollection$1.next
com.amazonaws.mobileconnectors.s3.transferutility.TransferNetworkLossHandler.pauseAllTransfersDueToNetworkInterruption
com.amazonaws.mobileconnectors.s3.transferutility.TransferNetworkLossHandler.access$100
com.amazonaws.mobileconnectors.s3.transferutility.TransferNetworkLossHandler$1.run
java.lang.Thread.run (Thread.java:761)
```

**To Reproduce**
It looks like the issue is happening when the network is getting interrupted but the app is submitting a new upload request at the exact same time.

**Which AWS service(s) are affected?**
Amazon S3

**Expected behavior**
The exception should not happen

**Screenshots**
N/A

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.11.1
 - Device: Actual devices
 - Android Version: All Android versions
 - Specific to simulators: No

**Additional context**

**Comment by kvasukib** [comment]
@hfcheng Sorry for the inconvenience caused. What is the frequency of occurrence of this issue? I can see that the methods that access the transfer map created by `TransferStatusUpdater` are synchronized and we only have one `TransferStatusUpdater`.

Is there a chance your app is trying to operate on the same transfer id when the `TransferNetworkLossHandler` is operating on it (in this case pausing)?

**Comment by hfcheng** [comment]
@kvasukib Appreciated for the hint. We realized we forgot to remove the codes we implemented for early versions of SDK, which did similar processing like the current TransferNetworkLossHandler is doing (listening to connectivity change events but we were pausing those transfers instead). It becomes redundant after SDK 2.11.x and conflicting with the existing SDK code.

Although we have not done a complete verification by putting the updated version in the field, we are pretty sure this should be the root cause. The issue can be closed as far as we can see. Thanks again for the help.

**Comment by kvasukib** [comment]
Thank you @hfcheng for the information. Please feel free to re-open when you find a different root-cause or need help in migration.

**Comment by hfcheng** [comment]
@kvasukib Sorry to inform you that we misjudged the situation. After having more tests we realized this issue is still happening and what we did just reduced the number of occurrences.

We are back in investigation mode and trying to locate the exact timing/pattern to reproduce this error.

**Comment by hfcheng** [comment]
It looks like the issue occurs if a previous transfer happens to complete at the same time when the device is getting disconnected from the network.

**Comment by hfcheng** [comment]
We were able to reproduce this issue by adding a lot of upload requests in the queue (so it takes more times to change the states for all transfers). Then submit a new upload request using `TransferUtility#upload()` when the connectivity change event comes in.

We are temporarily implementing a workaround here by checking the network status before submitting a new upload, and delay the submit for few hundreds of milliseconds if network is not connected. We known this is not a good solution but it is working fairly well as far as now.

**Comment by kvasukib** [comment]
@hfcheng Do you have this issue occurring in production where the app is submitting concurrent upload requests while the network connectivity is changing? or is this issue happening during testing?

**Comment by hfcheng** [comment]
@kvasukib We firstly spotted the issue from Crashlytics in production environment. At the point of time it affected only a very small amount of users. Since we weren't able to reproduce the issue in our common test environment/procedure, we tried to test it under some extreme conditions with the steps as described above plus a custom Wi-Fi access point to disconnect the device rapidly.

After we implemented the workaround as mentioned (delay submitting uploads), the occurrence is further reduced to 1/10 but it is still happening based on the crash reports from real users.

**Comment by mbk820** [comment]
@kvasukib Hi, we are having the same issues facing by some users,
we only download assets from s3, not uploading anything.
it happened after when I fixed another aws s3 crash by putting this code

 ```
try {
            AWSConfiguration config = new AWSConfiguration(context);

            transferUtility = TransferUtility.builder()
                    .context(context)
                    .awsConfiguration(config)
                    .s3Client(new AmazonS3Client(new CognitoCachingCredentialsProvider(context, config)))
                    .build();

        } catch (Exception exception) {
            Crashlytics.logException(exception);
            Log.d("S3", "Amazon transferUtility Error: ", exception);
        }

```

instead of a normal way of initialization

please help.

**Comment by kvasukib** [comment]
@mbk820 Can you post the exception stack-trace and logs from the device where this error is occurring?

Also, do you have any information about the number of concurrent operations are being executed on the device?

**Comment by mbk820** [comment]
@kvasukib 
`Fatal Exception: java.util.ConcurrentModificationException
       at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
       at java.util.HashMap$ValueIterator.next(HashMap.java:1470)
       at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1084)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferNetworkLossHandler.pauseAllTransfersDueToNetworkInterruption(TransferNetworkLossHandler.java:212)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferNetworkLossHandler.access$100(TransferNetworkLossHandler.java:37)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferNetworkLossHandler$1.run(TransferNetworkLossHandler.java:125)
       at java.lang.Thread.run(Thread.java:764)`

**Comment by kvasukib** [comment]
We release the fix in `2.13.7` version of the SDK. Please refer to the [CHANGELOG](https://github.com/aws-amplify/aws-sdk-android/blob/master/CHANGELOG.md#change-log---aws-sdk-for-android) for more details.

**Comment by mbk820** [comment]
Ok, @kvasukib let me update the version and see if new version eliminates crashes from the application. Thanks.

**Comment by desokroshan** [comment]
Closing due to inactivity. Please open a new issue if the exception persists.
