### ISSUE TITLE
SQLiteDatabaseLockedException while submiting events

### ISSUE THREAD

**Issue by SergeiVasilenko** [aws-amplify/aws-sdk-android#778]
**Describe the bug**
```
Fatal Exception: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5 SQLITE_BUSY[5])
      at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:946)
       at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
       at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
       at android.database.sqlite.SQLiteDatabase.delete(SQLiteDatabase.java:2049)
       at com.amazonaws.mobileconnectors.pinpoint.internal.event.PinpointDBBase.delete(PinpointDBBase.java:219)
       at com.amazonaws.mobileconnectors.pinpoint.internal.event.PinpointDBUtil.deleteEvent(PinpointDBUtil.java:112)
       at com.amazonaws.mobileconnectors.pinpoint.internal.event.EventRecorder.processEvents(EventRecorder.java:322)
       at com.amazonaws.mobileconnectors.pinpoint.internal.event.EventRecorder$1.run(EventRecorder.java:240)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)
```

**Which AWS service(s) are affected?**
com.amazonaws:aws-android-sdk-pinpoint:2.12.2

**Expected behavior**
No crash

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.12.2
 - Device: SM-G960F
 - Android Version: 9
 - Specific to simulators: No

**Additional context**
An app are sending a lot of events for performance analytics.

**Comment by kvasukib** [comment]
@SergeiVasilenko Sorry for the inconvenience caused. Are you creating multiple `PinpointManager` instances?

PinpointManager -> AnalyticsClient -> EventRecorder -> PinpointDBUtil -> PinpointDBBase -> PinpointDBHelper. 

My suspicion is that creating multiple `PinpointDBHelper` instances could cause this crash and creating multiple PinpointManager instances will create multiple `PinpointDBHelper` objects.

Can you confirm that from your app? Also can you post a sample code of how you are constructing the `PinpointManager` object and recording and submitting events?

**Comment by SergeiVasilenko** [comment]
I found that each time I tap on Home button and after return in app` PinpointManager` recreates. I think it was case of creating multiple `PinpointDBHelper` objects. So now I create PinpointManager once at all life of app. I'll look at behaviour.

**Comment by kvasukib** [comment]
@SergeiVasilenko Thank you for the quick response. One recommended way to do it is to create the `PinpointManager` object in the `Application` class upon startup and your app can refer to the same `PinpointManager` object.

From the SDK standpoint, we could make the `PinpointDBUtil` a singleton object so irrespective of the number of `PinpointManager` objects, there will be one `PinpointDBHelper` object.
