### ISSUE TITLE
Upload Fails with error Log tag "RepeatableFileInputStream" exceeds limit of 23 characters

### ISSUE THREAD

**Issue by samyakjain** [aws-amplify/aws-sdk-android#787]
**Describe the bug**
Getting error while uploading any file from Android 7.1.1

**Which AWS service(s) are affected?** - S3

**Expected behavior**

**Logs**
019-03-14 13:44:37.645 18186-18517/? E/UploadTask: Error encountered during multi-part upload: 9 due to Log tag "RepeatableFileInputStream" exceeds limit of 23 characters
    
    java.lang.IllegalArgumentException: Log tag "RepeatableFileInputStream" exceeds limit of 23 characters
    
        at android.util.Log.isLoggable(Native Method)
        at com.amazonaws.logging.AndroidLog.a(AndroidLog.java:40)
        at com.amazonaws.services.s3.internal.RepeatableFileInputStream.mark(RepeatableFileInputStream.java:105)
        at com.amazonaws.internal.SdkFilterInputStream.mark(SdkFilterInputStream.java:97)
        at com.amazonaws.util.LengthCheckInputStream.mark(LengthCheckInputStream.java:107)
        at com.amazonaws.internal.SdkFilterInputStream.mark(SdkFilterInputStream.java:97)
        at com.amazonaws.http.AmazonHttpClient.b(AmazonHttpClient.java:306)
        at com.amazonaws.http.AmazonHttpClient.a(AmazonHttpClient.java:212)
        at com.amazonaws.services.s3.AmazonS3Client.a(AmazonS3Client.java:4659)
        at com.amazonaws.services.s3.AmazonS3Client.a(AmazonS3Client.java:1752)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.b(UploadTask.java:221)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:15099)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.8.4
 - Android Version: [e.g. Nougat 7.1.1]
 - Specific to simulators: No

**Additional context**

**Comment by rohandubal** [comment]
Hello @samyakjain 

Sorry that you are having issues using the SDK. This seems due to limitation imposed by Android. We would have to trim the classname under 23 characters. 

I will update this thread once we have a fix released.

Thanks,
Rohan

**Comment by rohandubal** [comment]
Hello @samyakjain 

We have fixed this issue with SDK release `2.13.1`. Please try it out and let us know if it works for you.

Best,
Rohan
