### ISSUE TITLE
Missing proguard rule for transfer util

### ISSUE THREAD

**Issue by freszu** [aws-amplify/aws-sdk-android#806]
**Describe the bug**
Recently we migrated from aws '2.6.30' to '2.12.2' since then the upload is failing on obfuscated version of our app(checked with 2.12.5 as well and problem still exists).

We resolved that by adding 
```
-keep class com.amazonaws.mobileconnectors.s3.transferutility.TransferNetworkConnectionType {*;}
```
to our proguard setup.
**To Reproduce**
Create obfuscated version of the app and try to upload anything using transfer utility
**Which AWS service(s) are affected?**

**Expected behavior**
Upload should be successful

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.12.2, 2.12.5 
- Any device

**Additional context**
Original stack trace:
```
 Critical error, Aws upload failure for uploads/xx.jpg
 java.lang.AssertionError: java.lang.NoSuchFieldException: ANY
2019-03-21 12:09:09.522 14389-14523/x.x E/w:     at com.google.gson.b.a.n$a.<init>(TypeAdapters.java:792)
     at com.google.gson.b.a.n$24.create(TypeAdapters.java:818)
     at com.google.gson.f.a(Gson.java:458)
     at com.google.gson.b.a.i.a(ReflectiveTypeAdapterFactory.java:117)
     at com.google.gson.b.a.i.a(ReflectiveTypeAdapterFactory.java:166)
     at com.google.gson.b.a.i.create(ReflectiveTypeAdapterFactory.java:102)
     at com.google.gson.f.a(Gson.java:458)
     at com.google.gson.f.a(Gson.java:696)
     at com.google.gson.f.a(Gson.java:683)
     at com.google.gson.f.b(Gson.java:638)
     at com.google.gson.f.b(Gson.java:618)
     at com.amazonaws.mobileconnectors.s3.transferutility.TransferDBUtil.b(TransferDBUtil.java:806)
     at com.amazonaws.mobileconnectors.s3.transferutility.TransferDBUtil.a(TransferDBUtil.java:139)
     at com.amazonaws.mobileconnectors.s3.transferutility.TransferUtility.a(TransferUtility.java:549)
     at com.amazonaws.mobileconnectors.s3.transferutility.TransferUtility.a(TransferUtility.java:572)
...
```

**Comment by freszu** [comment]
Also there any reason for which consumerProguardFiles are not provided with the library and developers needs to add them manually? 
(see consumerProguardFiles : 
https://developer.android.com/studio/projects/android-library#Considerations)

**Comment by minbi** [comment]
Hi @freszu ,

The S3 module is distributed as a JAR and not an AAR. We are considering transitioning, but evaluating if this would break any of our customers.

**Comment by raphkim** [comment]
Hi @freszu,

I wasn't able to reproduce the exact bug, but I think I have a potential fix for your issue. Would it be possible to test your app with this [code base](https://github.com/raphkim/aws-sdk-android/tree/gson-fix) to see if your issue is resolved?

If not, would you be able to provide us with more information regarding what proguard rules you used to obfuscate your code? For example, did you use any third-party library for obfuscation? 

Thank you.

**Comment by freszu** [comment]
Hi @raphkim sorry for coming with an answer so late. 

So i managed to make a local build with your changes and use generated jars instead. 
The mentioned enum was still removed upon obfuscation and i experienced the same error until i reapplied the rule mentioned in first post. It seems that R8/proguard thinks that this enum is never used and so it's removed upon obfuscation/something is renamed.
This is the updated stack trace:
```
java.lang.AssertionError: java.lang.NoSuchFieldException: ANY
    at com.google.gson.v.n.n$k0.<init>(TypeAdapters.java:792)
    at com.google.gson.v.n.n$w.create(TypeAdapters.java:818)
    at com.google.gson.f.a(Gson.java:458)
    at com.google.gson.v.n.i.a(ReflectiveTypeAdapterFactory.java:117)
    at com.google.gson.v.n.i.a(ReflectiveTypeAdapterFactory.java:166)
    at com.google.gson.v.n.i.create(ReflectiveTypeAdapterFactory.java:102)
    at com.google.gson.f.a(Gson.java:458)
    at com.google.gson.f.a(Gson.java:696)
    at com.google.gson.f.a(Gson.java:683)
    at com.google.gson.f.a(Gson.java:638)
    at com.google.gson.f.a(Gson.java:618)
    at com.amazonaws.mobileconnectors.s3.transferutility.TransferDBUtil.b(TransferDBUtil.java:806)
    at com.amazonaws.mobileconnectors.s3.transferutility.TransferDBUtil.a(TransferDBUtil.java:139)
    at com.amazonaws.mobileconnectors.s3.transferutility.TransferUtility.a(TransferUtility.java:571)
    at com.amazonaws.mobileconnectors.s3.transferutility.TransferUtility.a(TransferUtility.java:597)
```

About our setup we are not using anything extraordinary and recently made switch from proguard to r8 but the problem still occurs. We applied all the rules mentioned in the https://github.com/aws-amplify/aws-sdk-android/blob/master/Proguard.md + the one mentioned in first post to overcome the issue with missing enum. Release build is configured with ```minifyEnabled true```
 
Other people ran into the same problem in the past but issue was closed: https://github.com/aws-amplify/aws-sdk-android/issues/704
