### ISSUE TITLE
Android get SIGNED_OUT_USER_POOLS_TOKENS_INVALID after 1 hour

### ISSUE THREAD

**Issue by jiafei1986** [aws-amplify/aws-sdk-android#815]
**Describe the bug**
We are doing the login with the amplify sdk.   so far we found an issue that the sdk will return SIGNED_OUT_USER_POOLS_TOKENS_INVALID after 1 hour. and from the document, it suggests user to log in again which is not expected for the user.  it will also block the UI thread after that. the user cannot do anything after that.

**To Reproduce**
A code sample or steps:
```
AWSMobileClient.getInstance().getTokens().getIdToken().getTokenString();
Your code
```

**Which AWS service(s) are affected?**
We use the id token to pass to our backend

**Expected behavior**

SDK should get the new idToken and it should not hit this error.  
Another question is that i just checked aws code, it will send a HTTP call to refresh id and access token if these tokens expired. as we know android not allow to run network call on UI thread.  does it mean I need to set a callback everywhere when i use this id token as i don't know what time the token expire?.   because our backend API need the id token.   

**Screenshots**
2019-03-26 16:15:51.617 25199-25199/com.expampe W/AWSMobileClient: signalTokensNotAvailable
2019-03-26 16:15:51.620 25199-25199/com.expampe W/AWSMobileClient: Tokens are invalid, please sign-in again.
    java.lang.Exception: No cached session.
        at com.amazonaws.mobile.client.AWSMobileClient$7$2.signalTokensNotAvailable(AWSMobileClient.java:1538)
        at com.amazonaws.mobile.client.AWSMobileClient$7$2.onFailure(AWSMobileClient.java:1533)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getSession(CognitoUser.java:752)
        at com.amazonaws.mobile.client.AWSMobileClient$7.run(AWSMobileClient.java:1500)
        at com.amazonaws.mobile.client.internal.InternalCallback.await(InternalCallback.java:115)
        at com.amazonaws.mobile.client.AWSMobileClient.getTokens(AWSMobileClient.java:1434)
        at com.amazonaws.mobile.client.AWSMobileClient.getUserStateDetails(AWSMobileClient.java:929)
        at com.amazonaws.mobile.client.AWSMobileClient.waitForSignIn(AWSMobileClient.java:838)
        at com.amazonaws.mobile.client.AWSMobileClient$7.run(AWSMobileClient.java:1450)
        at com.amazonaws.mobile.client.internal.InternalCallback.await(InternalCallback.java:115)

2019-03-26 16:15:51.620 25199-25199/com.expampe D/AWSMobileClient: waitForSignIn: userState:SIGNED_OUT_USER_POOLS_TOKENS_INVALID
2019-03-26 16:15:51.621 25199-29008/com.expampe I/userState: need to login again
2019-03-26 16:15:51.639 25199-25199/com.expampe D/AWSMobileClient: Inspecting user state details
2019-03-26 16:15:51.689 25199-25199/com.expampe I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2019-03-26 16:15:51.689 25199-25199/com.expampe I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2019-03-26 16:15:51.691 25199-25199/com.expampe W/AWSMobileClient: signalTokensNotAvailable
2019-03-26 16:15:51.693 25199-25199/com.expampe W/AWSMobileClient: Tokens are invalid, please sign-in again.
    java.lang.Exception: No cached session.
        at com.amazonaws.mobile.client.AWSMobileClient$7$2.signalTokensNotAvailable(AWSMobileClient.java:1538)
        at com.amazonaws.mobile.client.AWSMobileClient$7$2.onFailure(AWSMobileClient.java:1533)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getSession(CognitoUser.java:752)
        at com.amazonaws.mobile.client.AWSMobileClient$7.run(AWSMobileClient.java:1500)
        at com.amazonaws.mobile.client.internal.InternalCallback.await(InternalCallback.java:115)
        at com.amazonaws.mobile.client.AWSMobileClient.getTokens(AWSMobileClient.java:1434)
        at com.amazonaws.mobile.client.AWSMobileClient.getUserStateDetails(AWSMobileClient.java:929)
        at com.amazonaws.mobile.client.AWSMobileClient.waitForSignIn(AWSMobileClient.java:850)
        at com.amazonaws.mobile.client.AWSMobileClient$7.run(AWSMobileClient.java:1450)
        at com.amazonaws.mobile.client.internal.InternalCallback.await(InternalCallback.java:115)

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: [e.g. 2.12.6]
 - Device: [e.g. Any device]
 - Android Version: [Any version]
 - Specific to simulators: [e.g. Yes]

**Additional context**
From our backend , they set the refresh token to 30 days.

**Comment by jiafei1986** [comment]
By the way,  we only use the SDK sign in API. the login UI is written by ourself.

**Comment by minbi** [comment]
Hi @jiafei1986 ,

I see that you are using the synchronous version of the method. Are you making the call from the main/UI thread? Can you try running it in a background thread? Or use the async version of the method.

```
AWSMobileClient.getInstance().getTokens(Callback)
```

**Comment by jiafei1986** [comment]
Hi @minbi 
    Yes, initially we found SDK provide us 2 methods,   we use the one without callback.  but we get issue as above,  so we change to the second one which is async one.   it seems ok now. 

But we have to pass this idToken to many APIs of our backend.   does it mean we need to wrap our business logic code inside the getTokens callback everywhere?

**Comment by minbi** [comment]
The `AWSMobileClient.addUserStateListener(UserStateListener)` is a way be notified the tokens have expired in a central location.

**Comment by jiafei1986** [comment]
@minbi  Thank you for your quick reply. Yes, we have implemented that token,   what I am trying to ask is what is the correct way to get the tokens?   For example,  we have 10 APIs need this idToken,  so we need to get token first and then pass them to our API.   as you mentioned above.  we should use AWSMobileClient.getInstance().getTokens(Callback), right?

**Comment by minbi** [comment]
>we should use AWSMobileClient.getInstance().getTokens(Callback), right?

Yes.

> as we know android not allow to run network call on UI thread. does it mean I need to set a callback everywhere when i use this id token as i don't know what time the token expire?. 

This should handled by the async variant recommended above. It will create the network request on a background thread.

**Comment by minbi** [comment]
Hi,

We are closing this issue because there has been no activity. Please feel free to open a new issue if the problem persists. We ask this because closed issues are not actively monitored.

Thanks
