### ISSUE TITLE
[S3] AccessDenied when trying to upload a file to S3 bucket

### ISSUE THREAD

**Issue by virtualprodigy** [aws-amplify/aws-sdk-android#898]
**State your question**
I am trying to upload images to an S3 bucket. I have been following the steps outlined in the [AWS Amplify Storage Documentation](https://aws-amplify.github.io/docs/android/storage). Whenever I start an upload to s3 using the TransferService S3 kicks back a 403 response. 

```
2019-04-15 13:11:49.593 32160-32552/com.virtualprodigy.app E/UploadTask: Error encountered during multi-part upload: 3 due to Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 83FEF0D4B123F81D)
    com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 83FEF0D4B123F81D), S3 Extended Request ID: umVQZQtmN45O+jzNZ782ooj8eqd8Xla8jWtArP0w/7s8VTwhfykMZRHZe8QY1ceQbGmal5Ag9Hs=
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:730)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:405)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4659)
        at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1752)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:221)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:99)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:55)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```
**Which AWS Services are you utilizing?**
Android Amplify SDK, S3, TransferService(Android)
**Provide code snippets (if applicable)**

```
 override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.create_recipe_activity)
        ( application as CookbookApplication).component.inject(this@CreateRecipeActivity)
        //init the transferservice        https://aws-amplify.github.io/docs/android/storage
        applicationContext.startService( Intent(this@CreateRecipeActivity, TransferService::class.java) )
    }

 
```
```
    private fun uploadPhoto(onResult : (Boolean) -> Unit) {

        val file = File(photoUri.path)

        val transferUtil: TransferUtility =
                TransferUtility.builder().context(this@CreateRecipeActivity)
                        .awsConfiguration(AWSMobileClient.getInstance().configuration)
                        .s3Client(AmazonS3Client(AWSMobileClient.getInstance()))
                        .build()

        val fileKey = AWSMobileClient.getInstance().username + "_recipe_image" + Date().toString()

        val transferObserver: TransferObserver =
                transferUtil.upload("<bucket-name-ommited>", fileKey, file)


         transferObserver.setTransferListener(object: TransferListener {
             override fun onStateChanged(id: Int, state: TransferState?) {
                 if( TransferState.COMPLETED == state){
                     onResult(true)
                 }
             }

             override fun onProgressChanged(id: Int, bytesCurrent: Long, bytesTotal: Long) {
                val percentageComplete = (bytesCurrent.div(bytesTotal) * 100.0 )
                 Log.d(TAG, "Uploading image | ID:" + id + " bytesCurrent: " + bytesCurrent
                        + " bytesTotal: " + bytesTotal + " " + percentageComplete.toInt() + "%");
             }

             override fun onError(id: Int, ex: java.lang.Exception?) {
                 Log.e(TAG, "Failed to upload the cooking image", ex)
                 onResult(false)
             }
         })


    }
```

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.25]
```
 //Base SDK
    implementation 'com.amazonaws:aws-android-sdk-core:2.8.+'
    //s3
    implementation 'com.amazonaws:aws-android-sdk-s3:2.8.+'
    //AppSync SDK
    implementation 'com.amazonaws:aws-android-sdk-appsync:2.6.+'
    implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.0'
    implementation 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.1'
    //For AWSMobileClient only:
    implementation 'com.amazonaws:aws-android-sdk-mobile-client:2.8.+'
    //For the drop-in UI also:
    implementation 'com.amazonaws:aws-android-sdk-auth-userpools:2.8.+'
    implementation 'com.amazonaws:aws-android-sdk-auth-ui:2.8.+'
    // Google SignIn
    implementation('com.amazonaws:aws-android-sdk-auth-google:2.8.+@aar') { transitive = true }
    implementation 'com.google.android.gms:play-services-auth:16.0.0'
    implementation 'com.google.firebase:firebase-auth:16.0.4'
    // Facebook SignIn
    implementation 'com.android.support:support-v4:28.+'
    implementation('com.amazonaws:aws-android-sdk-auth-facebook:2.8.+@aar') { transitive = true }
    // Mobile Client for initializing the SDK
    implementation('com.amazonaws:aws-android-sdk-mobile-client:2.8.+@aar') { transitive = true }
    // Sign in UI
    implementation 'com.android.support:appcompat-v7:28.+'
    implementation('com.amazonaws:aws-android-sdk-auth-ui:2.8.+@aar') { transitive = true }
    implementation 'com.squareup.retrofit2:retrofit:2.5.0'
    implementation 'com.google.code.gson:gson:2.8.5'
    implementation 'com.squareup.retrofit2:converter-gson:2.5.0'
    implementation 'io.reactivex.rxjava2:rxjava:2.2.4'
    implementation 'io.reactivex.rxjava2:rxandroid:2.1.0'
```

**Device Information (please complete the following information):**
 - Device: [e.g. Pixel XL, Simulator]
     **Pixel Android version 9** 
 - Android Version: [e.g. Nougat 7.1.2]
 - Specific to simulators:

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by kvasukib** [comment]
@virtualprodigy Thank you for reporting to us. I see that you are using `AWSMobileClient.getInstance()` as the `AWSCredentialsProvider` with `AmazonS3Client`. `AWSMobileClient.getInstance()` creates a `CognitoCachingCredentialsProvider` which uses AWSCredentials vended from Cognito Identity Pool to authenticate the requests to Amazon S3.

Can you check if you have the right IAM policies (`s3:putObject`) in this case attached to the IAM roles created by Cognito, on your S3 bucket?

**Comment by virtualprodigy** [comment]
@kvasukib You pointed me in the right direction! The issue on my end was that I did not include "public/" on the key name. Thank you so much for your help. If possible, I would love to see the required naming conventions added to the amplify documents or the code annotations, I'm sure other newbies like myself will find it extremely helpful. :D

**Comment by prateekpatil** [comment]
@kvasukib Which propertied need to be changed to make it private. After making the following changes in permission and saving the key as "private/fileName" 
![Screenshot from 2019-04-19 17-13-40](https://user-images.githubusercontent.com/1854401/56448728-a4d54e00-62c6-11e9-98ce-bada3b4846b2.png)

I am still getting the following error 
` com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 30F4BB02F1001877), S3 Extended Request ID: xWSbdWK99AMFVRxPbOfVBWYnWkduiIArEGBzs9aKCInZLNnGYxMtiqqn0g4UjgOWMI1tw7NPEDg=
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:730)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:405)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4908)
        at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1959)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:262)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:110)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:60)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)`

**Comment by taouichaimaa** [comment]
Having the same issue here but i'm using Amplify libraries. Any headway?
